### ISSUE TITLE
Replication over a Unix socket will not process users named 'cyrus'

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#1049]
From: [Paul Fisher](pnfisher@berkeley.edu)
Bugzilla-Id: 3106
Version: 2.3.x
Owner: [Ken Murchison](murch@andrew.cmu.edu)

**Comment by elliefm** [comment]
This is partially done -- CYRUS_USER is now a compile time setting (default: cyrus), and imapd.conf has a cyrus_user setting (default: null) to override this.

sync_server and backupd use the former, but not the latter.  Not sure what imapd does.

Guessing Paul isn't coming forth with a patch, so I'll take a look at this

**Comment by elliefm** [comment]
imapd doesn't accept connections on unix sockets, so I think there's no issue with replication over imap
