### ISSUE TITLE
external-lists for timsieved

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#1051]
From: [Dilyan Palauzov](dilyan.palauzov@aegee.org)
Bugzilla-Id: 3108
Version: 2.3.x
Owner: [Ken Murchison](murch@andrew.cmu.edu)

**Comment by dilyanpalauzov** [comment]
RFC 6134 Sieve Extension: Externally Stored Lists is now implemented, at least as far as the attached patch is concerned.

This case can be closed.
