### ISSUE TITLE
Existance and utility of sasl_<plugin_name>_<option> is not in imapd.conf man page

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#1056]
From: [Wes Craig](wes@umich.edu)
Bugzilla-Id: 3115
Version: 2.3.x
Owner: [Ken Murchison](murch@andrew.cmu.edu)

**Comment by elliefm** [comment]
These days the imapd.conf.5 man page contains the following generic thing:

> sasl_option: 0
>    Any SASL option can be set by preceding it with **sasl_**.  This file overrides the SASL configuration file.
