### ISSUE TITLE
Autoconf does not automatically enter thread-safe options for compiler

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#1074]
From: [Michael Bacon](baconm@email.unc.edu)
Bugzilla-Id: 3165
Version: 2.3.x
Owner: [Ken Murchison](murch@andrew.cmu.edu)

**Comment by rsto** [comment]
Fixed this for GCC by adding -pthread, just to make sure. We don't have any Solaris setup at hand and there's no further reports on this issue since 2009
