### ISSUE TITLE
Failed to compile with eglibc 2.10

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#1091]
From: [Vladimir V. Kamarzin](vvk@altlinux.org)
Bugzilla-Id: 3157
Version: 2.4.17
Owner: [Ken Murchison](murch@andrew.cmu.edu)

**Comment by elliefm** [comment]
> The patch is needed for 2.3.x / 2.4.x only, 2.5 does not have "makedepend" anymore.

Closing as no longer relevant based on this comment
