### ISSUE TITLE
faster tonum in sieve/sieve-lex.l

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#1096]
From: [Dilyan Palauzov](dilyan.palauzov@aegee.org)
Bugzilla-Id: 3160
Version: 2.3.x
Owner: [Ken Murchison](murch@andrew.cmu.edu)

**Comment by elliefm** [comment]
Maybe, but my care factor for micro optimisations on non critical code paths is pretty low.  This seems like it would take more cycles to evaluate its impact than it would ever reasonably save in prod...
