### ISSUE TITLE
compiling cyrus-imapd with db50

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#1115]
From: [Hajimu UMEMOTO](ume@mahoroba.org)
Bugzilla-Id: 3231
Version: 2.3.x
Owner: [Ken Murchison](murch@andrew.cmu.edu)

**Comment by obache** [comment]
master: f9ded67ef7968815a5b6757056da622ad2ac04a6
2.4: 37e9553373589c40c7244fb5016032f8b7c42c2b
2.3: ef1ca22164c8a8e1c9db44e8b1bc3a4751f2e185
