### ISSUE TITLE
cyr_expire silently quits if it hits a non-existant account

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#1134]
From: [Alan Robertson](alanjrobertson@gmail.com)
Bugzilla-Id: 3203
Version: 2.3.x
Owner: [Ken Murchison](murch@andrew.cmu.edu)

**Comment by rsto** [comment]
Can't reproduce, cyr_expire got heavily reworked on top of mboxlist API so that's most probably why.
