### ISSUE TITLE
Disable SNMP from cyrus-master commandline

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#1136]
From: [Anders Blomdell](anders.blomdell@control.lth.se)
Bugzilla-Id: 3205
Version: 2.3.x
Owner: [Ken Murchison](murch@andrew.cmu.edu)

**Comment by nicolan** [comment]
@elliefm Are you still looking at snmp support?

**Comment by elliefm** [comment]
This kind of sounds like a bug in the net-snmp library which may or may not exist anymore.

As far as I can tell from the code we currently have, "-P 0" is actually a valid value for that argument, so using it as a switch to disable SNMP functionality seems inappropriate.

Generally, I'd advise that if you're not using the SNMP functionality, recompile without it.
