### ISSUE TITLE
PATCH TLS doesn't check CRLs

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#1155]
From: stacy@millions.ca
Bugzilla-Id: 3229
Version: 2.3.x
Owner: [Ken Murchison](murch@andrew.cmu.edu)

**Comment by ajaysusarla** [comment]
@ksmurchison Do you think this bug is still relevant? If yes, how can I test this in Cyrus?

**Comment by ksmurchison** [comment]
I don't know for sure if its still relevant, but I expect that it might be.  I'm neither a TLS nor a security expert.  It might be worth doing a little OpenSSL research on certificate revocation lists.

I do know that the patch is flawed in that it should be adding the new option to lib/imapoptions and not the derived imapopts.[ch] files

**Comment by ajaysusarla** [comment]
@ksmurchison Thank you! I shall dig into this. Cheers!
