### ISSUE TITLE
Cyrus 2.4 does not conform to RFC5256

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#1178]
From: [Olivier ROLAND](cyrus-dev@edla.org)
Bugzilla-Id: 3265
Version: 2.4.0
Owner: [Bron Gondwana](brong@fastmail.fm)

**Comment by elliefm** [comment]
According to our docs, RFC 5256 is now supported?

**Comment by elliefm** [comment]
If it's not, someone can whinge about it
