### ISSUE TITLE
Development snapshot will have strange version information without git

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#1210]
From: [Leena Heino](Leena.Heino@uta.fi)
Bugzilla-Id: 3302
Version: 2.4.1
Owner: [Jeroen van Meeuwen (Kolab Systems)](vanmeeuwen@kolabsys.com)

**Comment by elliefm** [comment]
Pretty much all of this stuff (website, version defines, git versioning) has changed drastically since this bug was opened
