### ISSUE TITLE
Document process for telemetry logging

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#1282]
From: [Jeroen van Meeuwen (Kolab Systems)](vanmeeuwen@kolabsys.com)
Bugzilla-Id: 3414
Version: 2.5.x (next)
Owner: [Jeroen van Meeuwen (Kolab Systems)](vanmeeuwen@kolabsys.com)

**Comment by nicolan** [comment]
Done. http://cyrusimap.org/dev/imap/reference/faqs/o-telemetry.html
