### ISSUE TITLE
making backtraces, C print string arguments

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#1284]
From: [Rudy Gevaert](rudy.gevaert@ugent.be)
Bugzilla-Id: 3375
Version: 2.4.6
Owner: [Ken Murchison](murch@andrew.cmu.edu)

**Comment by rsto** [comment]
Fixed in https://github.com/cyrusimap/cyrus-imapd/commit/62e1af9c5540d317b56f6fbf08b30386446a765d
