### ISSUE TITLE
document /etc/services entries

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#1286]
From: [Bron Gondwana](brong@fastmail.fm)
Bugzilla-Id: 3422
Version: 2.5.x (next)
Owner: [Jeroen van Meeuwen (Kolab Systems)](vanmeeuwen@kolabsys.com)

**Comment by nicolan** [comment]
There is information on this in one of the install guides (possibly developer-only?).
It needs to be mentioned as a requirement in all the setup/install mechanisms.

**Comment by elliefm** [comment]
http://cyrusimap.org/imap/developer/basicserver.html#protocol-ports mentions it

**Comment by elliefm** [comment]
There's a bunch of extra stuff in that documentation which I'm not sure what it is or why it's there

**Comment by elliefm** [comment]
Looks like the port list originally came from `doc/legacy/install-configure.html`

**Comment by nicolan** [comment]
I'm reasonably sure @postilion updated this during the recent Docathon and pulled the information out into an asset snippet so we can refer to it consistently everywhere via an include. 

Assigning to @postilion to confirm/deny/work out what else needs to be done if anything.

**Comment by postilion** [comment]
This is documented in `docsrc/assets/services.rst` and is `.. include::`ed in `basicserver.rst`, `packager.rst`, `quickstart.rst` and `admin/ports/services.rst`.  If it should be included anywhere else, just do so or let me know.

**Comment by nicolan** [comment]
Declaring this done. Go team!
