### ISSUE TITLE
Document process for running cyrus components through a debugger like gdb

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#1330]
From: [Jeroen van Meeuwen (Kolab Systems)](vanmeeuwen@kolabsys.com)
Bugzilla-Id: 3413
Version: 2.5.x (next)
Owner: [Jeroen van Meeuwen (Kolab Systems)](vanmeeuwen@kolabsys.com)

**Comment by elliefm** [comment]
There's a "[gdb]" section of cassandane.ini which allows firing up service daemons in a debugger (technical note: "service daemons" are any programs which are based around master/service.c, and includes imapd, lmtpd, and a few others, but notably does not include the command line tools).   The cassandane.ini.example in the cassandane repo contains examples and instructions.

When I'm trying to debug something in a service daemon I find it most useful to throw together a Cassandane test that tries to reproduce it, enable one of the [gdb] options as appropriate and go from there.

For programs that aren't service daemons, you have two options:

* If they've been installed, just run them with gdb.  You might need to fiddle around with sudo depending on permissions.
* If they haven't been installed (and you're in the source/build tree), you need to run gdb from libtool in order for everything to fit together properly. e.g. `libtool --mode=execute gdb imap/cyr_virusscan` if you wanted to debug cyr_virusscan

**Comment by elliefm** [comment]
If you need to pass command line arguments to a tool you're debugging, you do this once you're in gdb with something like `set args [...]` before you `run`.  (I'm not going to go into gdb at length, it's got its own documentation, but that seems like a helpful starting point to someone who's new.)

**Comment by nicolan** [comment]
Fixed!
