### ISSUE TITLE
www.cyrusimap.org/docs/cyrus-imapd/2.3.16/install-murder.php contains an old link

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#1336]
From: [Michael Menge](michael.menge@zdv.uni-tuebingen.de)
Bugzilla-Id: 3421
Version: 2.3.16
Owner: [Ken Murchison](murch@andrew.cmu.edu)

**Comment by elliefm** [comment]
We're no longer generating those bad links in recent documentation

Could go back and manually edit that page to fix those bad links but, meh
