### ISSUE TITLE
ctl_mboxlist -m deletes but ignores delete_mode: delayed

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#1359]
From: [Simon Amor](simon@leaky.org)
Bugzilla-Id: 3455
Version: 2.4.8
Owner: [Ken Murchison](murch@andrew.cmu.edu)

**Comment by ksmurchison** [comment]
Fixed with https://github.com/cyrusimap/cyrus-imapd/commit/87e85e198a88440b677438734bd8d593b87f6357
