### ISSUE TITLE
Berkeley DB ERROR while upgrading from 2.3.16 to 2.4.10

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#1382]
From: [Yann Rouillard](yann@pleiades.fr.eu.org)
Bugzilla-Id: 3496
Version: 2.4.x (next)
Owner: [Bron Gondwana](brong@fastmail.fm)

**Comment by rsto** [comment]
Berkeley database support has been deprecated in 2015: https://github.com/cyrusimap/cyrus-imapd/commit/808c31614512a0458b9b6b1d30e2779597506da2
