### ISSUE TITLE
should not try to create notifications collection for non-existent users

### ISSUE THREAD

**Issue by ksmurchison** [cyrusimap/cyrus-imapd#14]
(08:25:42 PM) brong: kmurchison: lots of this in the log - IOERROR: failed to create gmail.com!user.foobar.#notifications (Permission denied)
(08:26:28 PM) brong: caused by someone putting /dav/calendars/user/foobar@gmail.com/ in their client - that user doesn't actually exist on our system
(08:26:34 PM) brong: obviously we shouldn't even be trying to create #notifications folders like this for users who don't exist

**Comment by ksmurchison** [comment]
Should be fixed with commit https://github.com/cyrusimap/cyrus-imapd/commit/cd93ca04b735afb379bee0db672904d9f3f6d649

Bron should review to see if he's satisfied with this approach.

**Comment by elliefm** [comment]
@brong ^

**Comment by elliefm** [comment]
@brong @ksmurchison can we close this?

**Comment by ksmurchison** [comment]
If Bron isn't complaining, I'm guessing its fixed

**Comment by elliefm** [comment]
that's good enough for me :)
