### ISSUE TITLE
Old replication logs are not reprocessed

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#1464]
From: [amuhametov](admin@anes.su)
Bugzilla-Id: 3633
Version: 2.4.x (next)
Owner: [Bron Gondwana](brong@fastmail.fm)

**Comment by elliefm** [comment]
This sounds more like a misunderstanding how sync logs work?  As I understand it, the failed log is left there for inspection, or for reprocessing manually with `sync_client -r -f ...`.  It's not a problem if newer log entries get processed first, nor if the same log is processed multiple times.

I suspect whatever caused this particular "Bad protocol" error has long been fixed...
