### ISSUE TITLE
seperate out idle imapds from active imapd

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#149]
From: [Larry Greenfield](leg+cyrus@andrew.cmu.edu)
Bugzilla-Id: 247
Version: 2.1.x
Owner: [Ken Murchison](murch@andrew.cmu.edu)

**Comment by elliefm** [comment]
grabbing assignments on snmp-related stuff for possible prometheus support

**Comment by elliefm** [comment]
@robn Hmm, is something along these lines useful to you?  We already have "cyrus_imap_active_connections" (which is the number of connected imap clients) and I think it would be fairly easy to add a gauge for the number of connections currently in IDLE state (and "number of clients actually doing something" would be derivable with `active - idle`)

[Reading between the lines, I think this request was originally talking about "number of connections that are not explicitly in IDLE state, but have been inactive for a while", but it looks like that'd require deep surgery to the cmdloop to implement, so I'd probably avoid that unless it was somehow gonna be really really useful.]

**Comment by brong** [comment]
We are moving away from SNMP anyway
