### ISSUE TITLE
Cyrus Jenkins instance maintenance

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#1496]
From: [Greg Banks](gnb@fastmail.fm)
Bugzilla-Id: 3620
Version: 2.5.x (next)
Owner: [Jeroen van Meeuwen (Kolab Systems)](vanmeeuwen@kolabsys.com)

**Comment by elliefm** [comment]
Don't think we need this anymore, though @FMQA might find this of historical interest
