### ISSUE TITLE
Add iSchedule support

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#1529]
From: [Ken Murchison](murch@andrew.cmu.edu)
Bugzilla-Id: 3658
Version: 2.5.x (next)
Owner: [Ken Murchison](murch@andrew.cmu.edu)

**Comment by ksmurchison** [comment]
This 95% complete.  With the iSchedule effort within CalConnect on hold, closing this issue.  Will open a new one if/when there is new work to be done
