### ISSUE TITLE
2.5.0 release blocker tracker ticket

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#1541]
From: [Jeroen van Meeuwen (Kolab Systems)](vanmeeuwen@kolabsys.com)
Bugzilla-Id: 3674
Version: 2.5.x (next)
Owner: [Jeroen van Meeuwen (Kolab Systems)](vanmeeuwen@kolabsys.com)

**Comment by elliefm** [comment]
2.5 has been out for yonks -- bit late for anything that was still blocking 2.5.0!
