### ISSUE TITLE
Cyrus process hangs causing a lock that spawns lots of other hanging processes.

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#1599]
From: matt.s@aptalaska.net
Bugzilla-Id: 3744
Version: 2.4.16
Owner: [Bron Gondwana](brong@fastmail.fm)

**Comment by rendxq** [comment]
I have the same problem. 
--------
My setup
Static hostname: mailserv
Icon name: computer-vm
Chassis: vm
Machine ID: cbb779ad0b103a10ec75c10c452e0f71
Boot ID: c31a27599dc84971902e6c70dca26c18
Virtualization: kvm
Operating System: CentOS Linux 7 (Core)
CPE OS Name: cpe:/o:centos:centos:7
Kernel: Linux 3.10.0-514.6.1.el7.x86_64
Architecture: x86-64
--------------------------------------------
name : Cyrus IMAPD
version : v2.4.17-Fedora-RPM-2.4.17-8.el7_1 d1df8aff 2012-12-01
vendor : Project Cyrus
support-url: http://www.cyrusimap.org
os : Linux
os-version : 3.10.0-514.6.1.el7.x86_64
environment: Built w/Cyrus SASL 2.1.26
Running w/Cyrus SASL 2.1.26
Built w/Berkeley DB 5.3.21: (May 11, 2012)
Running w/Berkeley DB 5.3.21: (May 11, 2012)
Built w/OpenSSL 1.0.1e-fips 11 Feb 2013
Running w/OpenSSL 1.0.1e-fips 11 Feb 2013
Built w/zlib 1.2.7
Running w/zlib 1.2.7
CMU Sieve 2.4
TCP Wrappers
NET-SNMP
mmap = shared
lock = fcntl
nonblock = fcntl
idle = idled

**Comment by elliefm** [comment]
Fixed in 2.4.19
