### ISSUE TITLE
mailbox annotations loss when moving mailbox

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#1660]
From: [GALAMBOS Daniel](galambos.dani@gmail.com)
Bugzilla-Id: 3883
Version: 2.4.16
Owner: [Bron Gondwana](brong@fastmail.fm)

**Comment by guimard** [comment]
Hi @elliefm,

is this bug still confirmed in current version ?

**Comment by guimard** [comment]
[Debian reference: 776139](https://bugs.debian.org/776139)

**Comment by elliefm** [comment]
I assume this was fixed long ago and the bugzilla entry never closed, and then it got imported when we moved to github...

Anyway, I've added a Cassadane test to try to reproduce it, based on the provided cyradm log: https://github.com/cyrusimap/cassandane/commit/6d727b906bde1823f59caa1f990a550cccdac5d7

And it passes for the current Cyrus master, 3.2 and 3.0 branches, which seems to confirm this was fixed long ago.  (I didn't bother testing 2.5 cause it's a little tricky to build these days.)

**Comment by guimard** [comment]
@elliefm, thanks !
