### ISSUE TITLE
Notifyd datagrams should not have hardcoded size limit

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#1674]
From: [S&eacute;bastien Michel](sebastien.michel@atos.net)
Bugzilla-Id: 3819
Version: 2.5.x (next)
Owner: [S&eacute;bastien Michel](sebastien.michel@atos.net)

**Comment by ksmurchison** [comment]
Potential fix.  @brong and @elliefm can you sanity check this for me?

[notify_datagram.diff.txt](https://github.com/cyrusimap/cyrus-imapd/files/1136658/notify_datagram.diff.txt)

**Comment by elliefm** [comment]
Looks sane to me

**Comment by ksmurchison** [comment]
Fixed with https://github.com/cyrusimap/cyrus-imapd/commit/ac07b589d96dc0b6a54ef28ef2e76c01d7980f8f
