### ISSUE TITLE
Incorrect calendar provisioning details

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#1675]
From: [Alfie John](alfiej@fastmail.fm)
Bugzilla-Id: 3821
Version: 2.4.17
Owner: [Jeroen van Meeuwen (Kolab Systems)](vanmeeuwen@kolabsys.com)

**Comment by nicolan** [comment]
Hey @brong, I think it does this now, yes?

**Comment by brong** [comment]
It's fixed on master, and 2.5 as well
