### ISSUE TITLE
SSL private key cannot be read if chmod is 640 and path contains a symlink

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#1710]
From: [bmn](b3364320@trbvm.com)
Bugzilla-Id: 3874
Version: 2.4.x (next)
Owner: [Bron Gondwana](brong@fastmail.fm)

**Comment by ajaysusarla** [comment]
I tried this with master and the current `libopenssl` 1.1 and doesn't seem to be an issue anymore. I've also added(66d08919747bc402ea860d9e14a3336d168c0ea8) error logs for certificate and key parsing, so we have some arsenal to tackle such issues in the future.
