### ISSUE TITLE
patch to address solaris compile errors and warnings

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#1717]
From: hsk@imb-jena.de
Bugzilla-Id: 3887
Version: 2.5.x (next)
Owner: [Ken Murchison](murch@andrew.cmu.edu)

**Comment by elliefm** [comment]
I think most/all of these fixes are already applied.  We got a bunch of patches for this sort of thing for a most of the earlier 2.5.x releases, but it's been a while
