### ISSUE TITLE
Compliance problem with RFC-4314

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#1723]
From: [Benoit Tellier](btellier@linagora.com)
Bugzilla-Id: 3895
Version: 2.4.17
Owner: [Bron Gondwana](brong@fastmail.fm)

**Comment by jgrisham** [comment]
It appears this bug may be (as of 2021) still causing problems with Microsoft Outlook (and potentially other clients) and the current version of imapd used by Fastmail.

Related?: https://github.com/cyrusimap/cyrus-imapd/issues/1375

**Comment by elliefm** [comment]
Looks like the permission check here is where this comes from:

https://github.com/cyrusimap/cyrus-imapd/blob/61f0d4754a975270b349fe536cefd9adbdb9a419/imap/index.c#L1264-L1271

We might be able to fix this by inverting the sense of the tests, removing the flags from the to-change set if the relevant permission isn't available, and then returning NO if the resulting set is empty

Fiddling around with cassadane to try and get a reproduction/regression test first though...
