### ISSUE TITLE
cyrus-imapd floods logs and enter loops

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#1726]
From: [Giuseppe Ghib&ograve;](ghibomgx@gmail.com)
Bugzilla-Id: 3901
Version: 2.4.17
Owner: [Bron Gondwana](brong@fastmail.fm)

**Comment by rsto** [comment]
This looks more like a configuration issue than a Cyrus bug: ptloader correctly identifies if Cyrus is configured to use afskrb but hasn't been built with AFSKRB. Since ptloader already dumps the reason for the abnormal abort in the syslogs, I don't think we can do any better.
