### ISSUE TITLE
reconstruct crashes

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#1742]
From: [Stephan](steffo76@gmx.de)
Bugzilla-Id: 3919
Version: 2.5.x (next)
Owner: [elliefm](ellie@fastmail.com)

**Comment by elliefm** [comment]
This is now on the cyrus-imapd-2.5 and master branches

I expect it won't fix whatever the underlying problem was, but reconstruct should at least report an error now when this case occurs, instead of segfaulting
