### ISSUE TITLE
Cyrus::IMAP::Admin missing case in listmailbox for support_referrals

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#1746]
From: [Wolfgang Breyha](wbreyha@gmx.net)
Bugzilla-Id: 3925
Version: 2.5.x (next)
Owner: [Bron Gondwana](brong@fastmail.fm)

**Comment by ksmurchison** [comment]
Fixed with https://github.com/cyrusimap/cyrus-imapd/commit/5b5acaea969363b581e802ce04b1cf29e083d61b
