### ISSUE TITLE
implement blobs for calendar and contacts

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#1760]
Using the same upload/download handling as mail, implement blobId support for calendars and contacts.

This might include refactoring the managed attachment support from Ken to work with JMAP as well.

**Comment by rsto** [comment]
Shelved. We need to get the spec define how to use blobs for these types, first.

**Comment by rsto** [comment]
A JMAP client on Cyrus can just use the blob file upload and add the attachment as a link. I don't see any reason why to align this with the WebDAV file repo. If anything, the blob service might get rewritten on top of the WebDAV handlers (or the other way round).

TL;DR: there is nothing special for calendars, just use the regular blob upload service
