### ISSUE TITLE
Incorporate Olly's faster snippet algorithm

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#1762]
Olly posted a patch against the snippet pull request which is faster and returns better matches, we should merge that and try it.

**Comment by rsto** [comment]
The conversation is at https://github.com/xapian/xapian/pull/117.

Our regression tests work fine with the proposed snippet algorithm after some tweaking. Can we run this in the experimental FM branch to see how it performs with real-world data?

**Comment by rsto** [comment]
This is as good as done. If https://github.com/xapian/xapian/pull/130 makes it into upstream, we'll be able to re-cut our xapian fork to only include the CJK word splitting patch.

**Comment by rsto** [comment]
And it's done.
