### ISSUE TITLE
Move SNMP out from master into a separate daemon

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#1765]
Greg explained this to me before he left FastMail.

Basically, every process should have its own file (like it already does with proc / lock / idle, etc) in which it stores stats in a simple format (possibly just binary, mmaped, write out numbers to locations - could be on tmpfs).

And then the snmp or other stats daemons just open the directory, read each file, increment counters.  This is blindingly fast in practice, and it means there's no messy threaded snmp junk sitting in the master process.  You'd just run the statsd as a separate daemon.

**Comment by elliefm** [comment]
First part of this (adding prometheus support) is in #2063

**Comment by elliefm** [comment]
add prometheus metrics for httpd: #2098

**Comment by elliefm** [comment]
I've switched snmp to off-by-default in configure (was: on if dependencies found), and marked it as deprecated in the `configure --help` output.  This will do for 3.2 -- it's not gone yet, but you can't turn it on without being told it'll go away in the future.

#2100 can keep hanging around for a little while, and land on master once 3.2 becomes its own branch.

**Comment by anatoli26** [comment]
@elliefm, is there any chance to close this issue? It's blocking the work on chroot and other security improvements.
