### ISSUE TITLE
make the 'quota' command support -u to process quota for a single user

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#1766]
Like many other tools (e.g. reconstruct), the quota command is often useful for a single user.  Right now you can only use prefixes, but it would be easy to add a flag '-u' and support users instead.

This is a great first-time task :)

**Comment by elliefm** [comment]
Functionality added in dd0848a

**Comment by elliefm** [comment]
And docs updated in e21ebe0
