### ISSUE TITLE
imported messages with junk Date headers messes up sorting for getMessageList

### ISSUE THREAD

**Issue by wolfsage** [cyrusimap/cyrus-imapd#1773]
If you call importMessages and pass in messages with junk Date header fields, when you retrieve those messages (and others) back from getMessageList with sort = 'date desc', the emails with junk headers show up first with a date of the UNIX epoch. If internaldate is going to be used for the sorting, perhaps that should come back for the Date field as well?

A test showing the issue can be found here: https://github.com/wolfsage/JMAP-TestSuite/commit/a1d6247f5d3e6d78e35aae89db2561e68a0dfe1e

**Comment by rsto** [comment]
Why would we even want to allow to import messages with junk Date header fields? Shouldn't we reject the message? @brong, thoughts?

**Comment by brong** [comment]
Rejecting messages is generally pretty fraught. Junk date headers exist
in the wild, for whatever reason, and the rest of the message still
contains useful content.


As for where they sort though, I don't particularly care - leaving that
undefined is perfectly alright by me.  So assuming they appear at a
particular spot in getMessageList is not reasonable.


Bron.





On Wed, 4 Jan 2017, at 20:06, Robert Stepanek wrote:

> Why would we even want to allow to import messages with junk Date
> header fields? Shouldn't we reject the message? @brong[1], thoughts?
> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[2], or mute the thread[3].
> 



--

  Bron Gondwana

  brong@fastmail.fm






Links:

  1. https://github.com/brong
  2. https://github.com/cyrusimap/cyrus-imapd/issues/1773#issuecomment-270324977

**Comment by rsto** [comment]
Fair enough. So everyone's is OK to close this as no-fix?

**Comment by wolfsage** [comment]
I think this may surprise new users constantly.

Imagine a UI that tries to show newest messages first.

These broken messages will *always* sort at the top, yet display a date of "1970".

That seems wrong to me.

**Comment by wolfsage** [comment]
brong, did be77394aefff13d6ace554c15f563d2ee785d283 fix this?

**Comment by wolfsage** [comment]
Hrm, nope, still seeing issues in our tests

**Comment by wolfsage** [comment]
I believe this is fixed now that internalDate is used for such things. Closing, thanks!
