### ISSUE TITLE
getMessages is generating an htmlBody from textBody if htmlBody is missing

### ISSUE THREAD

**Issue by wolfsage** [cyrusimap/cyrus-imapd#1774]
If a message has a text body but no html body, the text body is being filled in as the html body in the response.

I believe this is incorrect. The JMAP Spec (http://jmap.io/spec-mail.html#messages) says:

- textBody: String The plain text body part for the message. If there is only an HTML version of the body, a plain text version MUST be generated from this; the exact method of conversion in this case is not defined and is server-specific.
- htmlBody: String|null The HTML body part for the message if present.

**Comment by rsto** [comment]
Fixed in https://github.com/cyrusimap/cyrus-imapd/commit/85ebd01ca9dda3342a2ac022229eb71d93427d30 and tested in https://github.com/cyrusimap/cassandane/commit/c3a7f9271ecc577ea606a5af5fcf06102acb3b84
