### ISSUE TITLE
make cyr_info conf-lint complete

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#1775]
Make sure cyr_info conf-lint handles all the configuration options that we've added since 2.4 correctly 

e.g.:
* archivepartition-{name}:
* {name}_sync_host:

**Comment by elliefm** [comment]
6b7019a (xlist-) and 46d261f (archivepartition-, backuppartition-) partly take care of this

There's code in there to know about searchpartition-, but searchpartition- is not documented in lib/imapoptions

Still need to handle sync options when prefixed with a channel name

**Comment by elliefm** [comment]
I think this is done now, but please re-open if it still sooks about something that's valid!
