### ISSUE TITLE
Look into adding a 'from version' snippet into lib/imapoptions

### ISSUE THREAD

**Issue by nicolan** [cyrusimap/cyrus-imapd#1777]
Wouldn't it be neat if...

If each config option in lib/imapoptions knows which version it came to life. Then in the docs or in cyr_info lint an admin could check new/removed config options between specific versions. (And handy for writing release notes too!)

I'm sure we can do something sneaky with rst tags to make this easy and usable.

(lib/imapoptions is used to generate imapd.conf.rst)

**Comment by elliefm** [comment]
Little bit of overlap with #1775 here

**Comment by elliefm** [comment]
And a little bit of overlap with #2944

**Comment by elliefm** [comment]
wip here: https://github.com/elliefm/cyrus-imapd/tree/v31/1777-imapoptions-from-version

**Comment by elliefm** [comment]
Guts of the implementation (including annotating all the existing options!) is done.  cyr_info can take a version string and highlight options that are new or changed since that version.  Still gotta add the version info to the generated rst so it ends up in the man/html pages

**Comment by elliefm** [comment]
Thinking more, I'm not convinced the versions need to be in the man/html pages.

But we do need documentation about how to maintain lib/imapoptions, particular wrt updating the version when old options are incompatibly changed, or choosing the right version when new options are created.
