### ISSUE TITLE
write a tool to set specialuse for existing users

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#1783]
Create an upgrade tool to read the xlist-{foo} config variables and find every user folder with those names and set the SPECIAL-USE if it's not already set. 

There's a gap at the moment for people upgrading, where they lose the special-use for existing accounts even if they have autocreate for new accounts.

@nicolan - we'll want to document this in the upgrade guide

**Comment by elliefm** [comment]
Initial implementation here, thoughts?  https://github.com/cyrusimap/cyrus-imapd/compare/master...elliefm:v30/1783-specialuse-convert-tool

I suspect this might have been doable in perl too, but I'm less familiar with that API so started in C

**Comment by elliefm** [comment]
Done and merged: 969077c and 9cd1cb4
