### ISSUE TITLE
discover man pages automatically

### ISSUE THREAD

**Issue by elliefm** [cyrusimap/cyrus-imapd#1790]
Currently, documentation in man format is generated based on the big hardcoded `man_pages[]` array in `docsrc/conf.py`.  This array contains, for each man page to be generated:

* The path (relative to `docsrc/`) to the rst source file (without the .rst extension)
* The name of the man page (usually/always the same as the source filename)
* An array of the authors
* The section number

A lot of this is redundant: the name is the same as the source filename (or could be made so); the section number can be inferred from the path to the source file (8 => "systemcommands", 5 => "configs", 3 => "libraries", 1 => "usercommands").

The big hardcoded array adds maintenance overhead -- it needs to be kept in sync with the actual files.

It seems like it should be possible to build the man pages based entirely on the contents of the `docsrc/imap/reference/manpages/*` directories, inferring the name/section information from the filename/path.  The author information could probably be embedded into the source files (if it's not already).

**Comment by elliefm** [comment]
The hardcoded list is also duplicated in `docsrc/imap/reference/manpages/commands.rst`...

**Comment by nicolan** [comment]
Begun work 34e85c3f30fce5ff6

This interrogates the file structure for all the files and knows which directories are which man page section.

Does not 

- [ ] detect authors
- [ ] fix commands.rst which has everything hardcoded

**Comment by nicolan** [comment]
commands.rst has some file mentions that are explicitly hidden, not sure why. But we can't just use a :glob: match to include everything in the relevant directories until this is resolved.

**Comment by nicolan** [comment]
Pushed to 3.0

**Comment by elliefm** [comment]
commands.rst will be dealt with in #2007

**Comment by nicolan** [comment]
All of this is fixed! Closing.
