### ISSUE TITLE
place a copy of sieve vacation responses in the user's \Sent folder

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#1793]
Now that we can lookup folders by special-use, it seems reasonable to allow vacation responses to be copied into the Sent folder so that people know they were sent!

**Comment by elliefm** [comment]
It looks like this is already available using something like "vacation :fcc \\Sent" from the sieve script (not sure of the exact syntax, but @ksmurchison would know).

I've had a look into the possibility of adding an imapd.conf option to do this for all "vacation" actions, but it's not yet clear whether it would be better to do that from within the sieve engine (by quietly adding a fileinto action during bytecode evaluation if it wasn't already there), or from within lmtp_sieve after the message has been sent (in which case the user might get duplicate sent items if they are explicitly using the :fcc functionality in their script)

**Comment by ksmurchison** [comment]
The syntax currently implemenented in Cyrus Sieve is the following:

vacation VACATION-OPTS [ ":fcc" FILEINTO-OPTS <mailbox: string>] <reason: string>

where VACATION-OPTS is the expected:

[":days" number | ":seconds" number] [":subject" string] [":from" string]
 [":addresses" string-list] [":mime"] [":handle" string]

and FILEINTO-OPTS is:

[ ":create" ] [ ":flags" <list-of-flags: string-list> ] [ ":specialuse" <special-use-flag: string> ]

**Comment by elliefm** [comment]
Shall we just close this off, since the functionality is already there?  It's not exactly Cyrus automatically doing it, but the power exists within sieve.

**Comment by ksmurchison** [comment]
I'd say close it
