### ISSUE TITLE
message.date property should be internaldate, not header

### ISSUE THREAD

**Issue by rjbs** [cyrusimap/cyrus-imapd#1813]
The `date` property of a message is the date it entered the server, not its header.  (You can get the header with header.date, I assume.)  Right now you can sort by date and you'll get things sorted by internaldate, which might bear no resemblance to header date, but `message.date` shows the header date!

There's a tentative test for this for the JMAP Test Suite at https://github.com/pobox/JMAP-TestSuite/pull/3

**Comment by brong** [comment]
Fixed
