### ISSUE TITLE
cyr_virusscan issues in 3.0.0rc2

### ISSUE THREAD

**Issue by hagedose** [cyrusimap/cyrus-imapd#1825]
I noticed there is already an open issue for cyr_virusccan, but it's for 2.5. I installed clamav and built cyrus. When I run cyr_virusscan, there is the following error message:

```
$ cyr_virusscan user/a0620
Using ClamAV virus scanner
LibClamAV Error: Can't load /var/lib/clamav/daily.cvd: Can't allocate memory
fatal error: Can't allocate memory

```
The file exists:

```
$ ll /var/lib/clamav/daily.cvd
-rw-r--r-- 1 clamupdate clamupdate 36748381 Feb  7 13:01 /var/lib/clamav/daily.cvd

```
I ran strace. The relevant part appears to be this:

```
openat(AT_FDCWD, "/var/lib/clamav", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 3
brk(0)                                  = 0x768000
brk(0x789000)                           = 0x789000
getdents(3, /* 6 entries */, 32768)     = 176
getdents(3, /* 0 entries */, 32768)     = 0
access("/var/lib/clamav/daily.cld", R_OK) = -1 ENOENT (No such file or directory)
access("/var/lib/clamav/daily.cvd", R_OK) = 0
access("/var/lib/clamav/daily.cvd", R_OK) = 0
open("/var/lib/clamav/daily.cvd", O_RDONLY) = 4
fstat(4, {st_mode=S_IFREG|0644, st_size=36748381, ...}) = 0
mmap(NULL, 4096, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7f627d050000
lseek(4, 0, SEEK_SET)                   = 0
read(4, "ClamAV-VDB:07 Feb 2017 03-32 -05"..., 4096) = 4096
futex(0x7f627a5e8264, FUTEX_WAKE_PRIVATE, 2147483647) = 0
write(2, "LibClamAV Error: Can't load /var"..., 77LibClamAV Error: Can't load /var/lib/clamav/daily.cvd: Can't allocate memory
) = 77
close(4)                                = 0
```

The VM doesn't have a lot of memory, but it looks enough to me to open an 36 MB file:

```
$ free -m
              total        used        free      shared  buff/cache   available
Mem:            988         284         391           2         313         541
Swap:          2079          10        2069

```
clamscan works fine.

**Comment by elliefm** [comment]
I wonder if the file is internally compressed in some way, such that it's only 36MB on disk, but is maybe much larger when expanded into clamav's internal datatypes.

I'm curious what appears in syslog when you run it?  I think, from the strace, that it's failing very early -- possibly at the call to `cl_load()` at line 144 of `imap/cyr_virusscan.c` -- but if there's syslog output, that might narrow things down more precisely

**Comment by elliefm** [comment]
This is a shot in the dark, but I don't suppose this fixes things?  https://github.com/cyrusimap/cyrus-imapd/compare/master...elliefm:v30/1825-clamav-memory

**Comment by elliefm** [comment]
Hmm:

```
$ls -l /var/lib/clamav/total 142648
-rw-r--r-- 1 clamav clamav    103987 Feb  8 18:28 bytecode.cvd
-rw-r--r-- 1 clamav clamav  36809900 Feb  8 18:28 daily.cvd
-rw-r--r-- 1 clamav clamav 109143933 Feb  8 18:25 main.cvd
-rw------- 1 clamav clamav       104 Feb  8 18:28 mirrors.dat
```

I know the error says it couldn't load "daily.cvd" (36MB), but maybe it couldn't load that because it had already loaded "main.cvd" (109MB) ran out of memory while trying to also load daily.cvd?  The cyr_virusscan.c file looks like it loads all cvds in that directory, not just one.

I'm still trying to set up a test case to see if I can reproduce the issue myself (turns out installing clamav definitions takes quite a while), but at this stage it is looking like maybe it just needs more memory than you have spare

**Comment by elliefm** [comment]
Whoa actually:

```
=====> Instance[1501] Running: "/dev/shm/cyrus/main/sbin/cyr_virusscan" "-C" "/dev/shm/cass/0735221/conf/imapd.conf" "-r"
LibClamAV Error: Can't load /var/lib/clamav/daily.cvd: Can't allocate memory
fatal error: Can't allocate memory
Using ClamAV virus scanner
```

... just reproduced your issue exactly!

For reference:

```
$free -m
              total        used        free      shared  buff/cache   available
Mem:           3956         820        1336         404        1799        2463
Swap:          1292           0        1292
```

I wonder if my vm also doesn't have enough memory for it... and I wonder how much it actually needs

**Comment by elliefm** [comment]
Similar report (albeit with perl, not cyrus), unanswered since 2014: https://rt.cpan.org/Public/Bug/Display.html?id=96876

**Comment by elliefm** [comment]
I just bumped my vm up from 4GB of memory to 8GB and tried again, and now I get:

```
=====> Instance[1501] Running: "/dev/shm/cyrus/main/sbin/cyr_virusscan" "-C" "/dev/shm/cass/0743481/conf/imapd.conf" "-r"
fatal error: Internal error: assertion failed: imap/mboxevent.c: 705: filled_params(type, event)
Using ClamAV virus scanner
Loaded 5727234 virus signatures.

Mailbox Name                            	   Msg UID	Status	Virus Name
----------------------------------------	----------	------	--------------------------------------------------
user.cassandane                         	         1	UNREAD	Eicar-Test-Signature
```

So: turns out the memory requirements of libclamav as used by cyr_virusscan are _substantial_!  I wonder what clamscan does differently...

And also, there's a bug in there somewhere with that assertion failure, but that's not the problem you're hitting.

**Comment by hagedose** [comment]
That's strange. I upped my VM to 8GB memory as well, and it still doesn't work. I haven't yet applied the patch above. Should I try that?
gdb doesn't work, unfortunately:

```
(gdb) run
Starting program: /usr/sbin/cyr_virusscan user/a0620
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Using ClamAV virus scanner
LibClamAV Error: Can't load /var/lib/clamav/daily.cvd: Can't allocate memory
fatal error: Can't allocate memory
[Inferior 1 (process 1455) exited with code 0113]
(gdb) bt
No stack.
(gdb) thread apply all bt
(gdb)

```
Looks like there is nothing left at that point.

**Comment by elliefm** [comment]
I just tried again with a (freshly-booted, idle) VM with only 4GB and it worked (but with that assertion failure), just like it did for me with 8GB, which is interesting.

I'm about to try without my earlier patch, and see what difference that makes -- the patch is the right thing to do in general (according to clamav docs anyway), but I don't know if it will have any effect in this particular case.

**Comment by elliefm** [comment]
Just tried it without the patch, and got this, which is completely different from anything you're seeing:

```
=====> Instance[1501] Running: "/dev/shm/cyrus/main/sbin/cyr_virusscan" "-C" "/dev/shm/cass/2330371/conf/imapd.conf" "-r"
LibClamAV Error: Can't load /var/lib/clamav/daily.cld: Malformed database
fatal error: Malformed database
Using ClamAV virus scanner
```

And then I tried it again with the patch, and got the same behaviour I've seen a few times: virus scan loads and succeeds, but then an assertion fails in mboxevent.

So that's weird.  The patch seems to make a big difference for me.

I wonder if yours _would_ have reported the "Malformed database", except that it ran out of memory first?

**Comment by elliefm** [comment]
I've opened #1832 for the assertion failure, because it doesn't seem to be strictly related to cyr_virusscan at all, and it only shows up if you have debug: yes in imapd.conf.

**Comment by elliefm** [comment]
How much capacity do you have to (temporarily) up the VM's memory?  I'd be curious to see whether it works for you at 12GB, 16GB, ... but naturally that's very much constrained by what you have available. :)

I'm especially curious to see what the results are with increased memory, both with and without my patch.

How much work is your VM doing other than running cyrus?  Do you have a lot of tmpfs partitions mounted?

**Comment by hagedose** [comment]
Well, the machine that's hosting the VM only has 12 GB of memory, so I can't really give the VM much more than 8 GB. But with the path applied, it's working now?! And the process doesn't seem to require much memory, either. I will reduce the VM's memory back to 1 GB now and try again.
Could this be a timing issue?

**Comment by hagedose** [comment]
Now it works with 1 GB RAM as well! I hate threading ;-)

**Comment by hagedose** [comment]
On second thought, the original code never called cl_init(), did it? It looks like that's required before calling cl_engine_new():

http://caipirinha.homelinux.org/usr/share/doc/packages/clamav/html/node52.html

**Comment by elliefm** [comment]
Yeah, I saw that in the docs while trying to find out about its memory requirements, which is why I made the patch.  Wasn't sure if it would help with the memory issue, but it seemed like the right thing to do anyway :)

**Comment by elliefm** [comment]
I'm working on some Cassandane tests so we can keep verifying this thing in the future, so I'll leave this open while I do so.  (And: there might be a bug with the -r argument not working correctly, but I'm not sure if the problem is cyr_virusscan, or something my testing is doing wrong.  Investigation continues...)

**Comment by elliefm** [comment]
Have your tests included one where a message is actually infected?  If so, what happens?

I've been trying out various fixes for the assertion (#1832), and what I'm finding is if it doesn't fail from the assertion, then it consistently segfaults a bit later on.  The cause of the segfault is proving difficult to track down, but I'm starting to suspect cyr_virusscan (or perhaps even libclamav) is the actual cause.

**Comment by elliefm** [comment]
After much hair pulling on my part, @robn kindly observed that the segfault was because the global variable `int notify` in cyr_virusscan.c was conflicting with the function `void notify(...)` in notify.c... doh!

So that's now fixed as of 4a83247

**Comment by elliefm** [comment]
And we now have a cassandane test for it, so hopefully cyr_virusscan won't get so righteously broken again in the future: https://github.com/cyrusimap/cassandane/commit/af3d01cfc2387909094fb2dc0bb35a124e42153f

**Comment by hagedose** [comment]
Cool. I actually never triggered that because I hadn't enabled notifications - or so I thought. Strangely, when I do this on a system without 4a83247, it works fine but there is no notification. 

```
$ cyr_virusscan -n user/a0620/Viren
Using ClamAV virus scanner
Loaded 5787369 virus signatures.

Mailbox Name                            	   Msg UID	Status	Virus Name
----------------------------------------	----------	------	--------------------------------------------------
user.a0620.Viren                        	        12	  READ	Win.Worm.Sober-6
```

Do I need to configure something for notifications to work? 

One more thing: cyr_virusscan has no manage. Should I create a new issue for that?

**Comment by postilion** [comment]
@hagedose: Yes, please create a new issue for the missing cyr_virusscan man page, and I'll get to work on that.

Thanks for reporting!
-nic

**Comment by elliefm** [comment]
@hagedose, the segfault is triggered by requesting infected messages be expunged (-r option) -- even though the "notify" variable is for (email) notifications, it's the expunge code path where the conflict occurs.  If you don't ask it to expunge, the conflict wouldn't cause a problem. :)

**Comment by elliefm** [comment]
I haven't tested the email notifications in the slightest yet.  They look like they'll append straight into the affected user's mailbox (no SMTP round trip required) so they might or might not work out of the box.  Maybe they only get sent if messages were also expunged?  Maybe the mailbox needs certain ACL's for them to work? No idea! :)

**Comment by hagedose** [comment]
OK, the notifications are really just appended to the user's INBOX. FWIW, even with "-rn" my unpatched copy of cyr_virusscan works without segfault or assertion now:

```
# cyr_virusscan -rn user/a0620/Viren
Using ClamAV virus scanner
Loaded 5787369 virus signatures.

Mailbox Name                            	   Msg UID	Status	Virus Name
----------------------------------------	----------	------	--------------------------------------------------
user.a0620.Viren                        	        12	  READ	Win.Worm.Sober-6

```
Thanks for your help!
