### ISSUE TITLE
Bug-submission instructions need fixing

### ISSUE THREAD

**Issue by UnitedMarsupials** [cyrusimap/cyrus-imapd#1830]
The [Reporting Bugs](https://cyrusimap.org/feedback-bugs.html)-page on cyrusimap.org points people at a Bugzilla-server, which continues to resolve, but does not respond.

If Github is the official place for bug-reports, the documentation should point here.

**Comment by elliefm** [comment]
Thanks for reporting this.  This is fixed in 58b613e, and should take effect on the real website in about 40 mins :)

**Comment by UnitedMarsupials** [comment]
> should take effect on the real website in about 40 mins :)

10 hours later the published page's last modification date is November 17...

**Comment by rsto** [comment]
On Sat, Feb 11, 2017, at 01:08, UnitedMarsupials wrote:

>> should take effect on the real website in about 40 mins :)



> 10 hours later the published page's last modification date is
> November 17..


Might be an issue with your browser cache? I see that the link now
points to the Github issues tracker.


$ curl -I https://www.cyrusimap.org/feedback-bugs.html

HTTP/1.1 200 OK

Last-Modified: Fri, 10 Feb 2017 05:00:08 GMT



Cheers,

Robert
