### ISSUE TITLE
getMessageUpdates with fetchRecords returns 'invalidArguments'

### ISSUE THREAD

**Issue by wolfsage** [cyrusimap/cyrus-imapd#1836]
If you call getMessageUpdates with fetchRecords set to true and there have been no state changes, the internal call to getMessages fails and returns an 'invalidArguments' error.

I think getMessages with an empty list of ids should succeed as if none (or all!) of the ids were found.

Sample test here: https://github.com/pobox/JMAP-TestSuite/pull/5

**Comment by rsto** [comment]
Just uploaded a fix in https://github.com/cyrusimap/cyrus-imapd/commit/63e9cb56c622dbc654bacb98a7417824a1b9bd56. Tests pass both in https://github.com/cyrusimap/cassandane/commit/7ebf85b16d750fc5a29629b118ff92c8cd9b905c and JMAP-TestSuite.

Please close when you happy with it.
