### ISSUE TITLE
cyr_virusscan: handle virtual domains

### ISSUE THREAD

**Issue by hagedose** [cyrusimap/cyrus-imapd#1841]
I noticed this comment in append_notifications():

`/* XXX  Need to handle virtdomains */
`
We don't use virtual domains, so I can't tell if notifications fail with virtual domains enabled, but I thought that should be checked before 3.0 is released.

**Comment by elliefm** [comment]
Looks like it'll be fine.  I'm pretty sure that comment just applies to the To: header in the generated email, and won't cause problems for the append itself.

**Comment by brong** [comment]
This is indeed fine - the code is all using the good mbname_* functions now that have full virtdomains support
