### ISSUE TITLE
Make notification from cyr_virusscan localizable and/or customizable

### ISSUE THREAD

**Issue by hagedose** [cyrusimap/cyrus-imapd#1845]
Currently the notification that cyr_virusscan generates when an infected message has been deleted (and notifications are enabled) is hard-coded in English. I could live with an option for a site to customize that notification, but other sites might want to have localized notifications. @elliefm suggested that template support from CALDAV might be reused here.

**Comment by elliefm** [comment]
https://github.com/cyrusimap/cyrus-imapd/issues/2516#issuecomment-529267173
