### ISSUE TITLE
make jmap depend on xapian

### ISSUE THREAD

**Issue by elliefm** [cyrusimap/cyrus-imapd#1847]
quoth @rsto:
> The whole snippet codepath is failing without xapian as a search backend.
> I don’t see a reasonable way to backport what’s missing for JMAP in squat. We should just make xapian a required dependency for JMAP, anything else is prone to break sooner or later.

**Comment by elliefm** [comment]
Complication: JMAP support isn't conditional, which means if Xapian is mandatory for JMAP then Xapian is mandatory for Cyrus.

**Comment by elliefm** [comment]
I wonder how hard it would be to add a --disable-jmap for people who don't want to be forced onto xapian (especially while xapian isn't just as simple as apt-get install xapian)

**Comment by rsto** [comment]
Not that hard at all: https://github.com/rsto/cyrus-imapd/commit/9f4df728bd75b4bacbccb4e8537abda889d5979a

I have tested this on my build machine with both --enable-jmap and without. But I'm wary if my build setup is representative. Could you please also verify that Cyrus builds OK for you with and without JMAP?

**Comment by elliefm** [comment]
Seems to work okay for me, both with and without

**Comment by rsto** [comment]
Fixed with https://github.com/cyrusimap/cyrus-imapd/commit/892c3bdeaebbf1196000ad954468783a2e112ecb
