### ISSUE TITLE
imapd-2.5.10 - Random fatal errors in lib/cyrusdb_twoskip.c:1727

### ISSUE THREAD

**Issue by Saelberaen** [cyrusimap/cyrus-imapd#1872]
Hi,

I've just migrated from a 2.2-based server to a 2.5.10 based server and while investigating another issue (I had failed to upgrade the mailbox version of some mailboxes) I noticed the following sprinkled around my mail.log file:
`Fatal error: Internal error: assertion failed: lib/cyrusdb_twoskip.c: 1727: key && keylen`
Since I was running a self-patched version due to the other issue I added some debug print-outs and the database being accessed is tls_sessions. Tls_sessions was completely removed and allowed to re-create itself in the 2.2->2.5.10 migration so there should be no stale data in there.

I don't have much more to offer atm. Sometimes the reported run-time of the process is less than half a second and sometimes a couple of minutes, e.g:
`process type:SERVICE name:imaps path:/usr/lib/cyrus/bin/imapd age:0.172s pid:23460 exited, status 75`

This issue persists when using the stock 2.5.10 version from Debian/Stretch so my extra added log output should not be the cause of the assert triggering.

What more information do you need?

**Comment by elliefm** [comment]
That's weird.  Are you able to reproduce this on a server you can experiment on?

I wonder if a backtrace will expose anything useful here.  You could get one by adding an `abort()` call to `EXPORTED void fatal(const char *s, int code)` in `imap/imapd.c` and rebuilding/reinstalling -- that will make it dump core when this happens, instead of shutting down cleanly.  (Note that this might lead to database corruptions, so don't do it on a server you can't afford to corrupt!)  Then use gdb to examine the core file and get a backtrace -- please let me know if you need more detailed steps :)

**Comment by Saelberaen** [comment]
Sorry for the delay. Last week was way too hectic to be fun :/ I'll clone my mail server to a new virtual machine so I can experiment freely and get back to you in a few days.

**Comment by Saelberaen** [comment]
Update:

* It seems to be primarily iPads and iPhones that trigger this. I've not seen (so far) Thunderbird trigger this. In fact, it's almost guaranteed to get failures when connecting using an iPhone (iOS 10.2.1)
* The empty session ID/len comes from a call to SSL_SESSION_get_id in imap/tls.c : remove_session_cb.
* The empty session ID/len is sent from remove_session_cb to the local function remove_session which in turn tries to use them to remove an entry from the session cache (which is where we hit the assert).
* My knowledge of openssl internals is just epsilon above non-existent so I'm kind'a lost.

This is a stripped down excerpt from syslog:
`Apr 15 14:15:29 mda-test cyrus/imaps[14548]: inittls: Loading hard-coded DH parameters
Apr 15 14:15:29 mda-test cyrus/imaps[14548]: TLS server engine: No client CA certs specified. Client side certs may not work
Apr 15 14:15:29 mda-test cyrus/imaps[14548]: starttls: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits new) no authentication
Apr 15 14:15:29 mda-test cyrus/imaps[14548]: login: [192.168.10.245] <username> plaintext+TLS User logged in SESSIONID=<cyrus-14548-1492258529-1-7309509142786610107>
Apr 15 14:15:29 mda-test cyrus/imaps[14548]: client id: "name" "iPhone Mail" "version" "14D27" "os" "iOS" "os-version" "10.2.1 (14D27)"
Apr 15 14:15:32 mda-test cyrus/imaps[14548]: USAGE <username> user: 0.024000 sys: 0.032000
Apr 15 14:15:32 mda-test cyrus/imaps[14548]: Fatal error: Internal error: assertion failed: lib/cyrusdb_twoskip.c: 2339: key && keylen
Apr 15 14:15:32 mda-test cyrus/master[14524]: process type:SERVICE name:imaps path:/usr/lib/cyrus/bin/imapd age:3.713s pid:14548 exited, status 75
Apr 15 14:15:32 mda-test cyrus/imaps[14549]: inittls: Loading hard-coded DH parameters
Apr 15 14:15:32 mda-test cyrus/imaps[14549]: TLS server engine: No client CA certs specified. Client side certs may not work
Apr 15 14:15:32 mda-test cyrus/imaps[14549]: starttls: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits new) no authentication
Apr 15 14:15:32 mda-test cyrus/imaps[14549]: login: [192.168.10.245] <username> plaintext+TLS User logged in SESSIONID=<cyrus-14549-1492258532-1-11595859793003941986>
Apr 15 14:15:32 mda-test cyrus/imaps[14549]: client id: "name" "iPhone Mail" "version" "14D27" "os" "iOS" "os-version" "10.2.1 (14D27)"
Apr 15 14:15:33 mda-test cyrus/imaps[14550]: inittls: Loading hard-coded DH parameters
Apr 15 14:15:33 mda-test cyrus/imaps[14550]: TLS server engine: No client CA certs specified. Client side certs may not work
Apr 15 14:15:33 mda-test cyrus/imaps[14550]: Fatal error: Internal error: assertion failed: lib/cyrusdb_twoskip.c: 2339: key && keylen
Apr 15 14:15:33 mda-test cyrus/master[14524]: process type:SERVICE name:imaps path:/usr/lib/cyrus/bin/imapd age:0.085s pid:14550 exited, status 75
Apr 15 14:15:33 mda-test cyrus/imaps[14549]: USAGE <username> user: 0.052000 sys: 0.012000
Apr 15 14:15:33 mda-test cyrus/imaps[14549]: starttls: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits new) no authentication
Apr 15 14:15:33 mda-test cyrus/imaps[14549]: login: [192.168.10.245] <username> plaintext+TLS User logged in SESSIONID=<cyrus-14549-1492258533-1-2557587616344912297>
Apr 15 14:15:33 mda-test cyrus/imaps[14549]: client id: "name" "iPhone Mail" "version" "14D27" "os" "iOS" "os-version" "10.2.1 (14D27)"
Apr 15 14:15:36 mda-test cyrus/imaps[14549]: USAGE <username> user: 0.028000 sys: 0.020000`

I cannot find the core dump. Do I need to build using any specific flags/settings?

**Comment by brong** [comment]
OK, so what we're seeing here is a zero length key I suspect.



First of all - bloody Debian :(  They've clearly patched twoskip.c,
because that line number winds up in the middle of nowhere in my 2.5.10
tag checkout!


However assuming that it's in mystore, since that's the only assert that
matches the expression.


Both cyrusdb_store and cyrusdb_delete go through mystore, and reading
the log it smells like that's happening during session shutdown.


remove_session in imap/tls.c doesn't do a length check.



OK, so there are a variety of ways in to this codepath, but it looks
like the easy thing to do is just add a length check to remove_session.


I have added a patch to do that to 2.5, 3.0 and master.


Bron.



On Sat, 15 Apr 2017, at 22:55, Saelberaen wrote:

> Update:


>  * It seems to be primarily iPads and iPhones that trigger this. I've
>    not seen (so far) Thunderbird trigger this. In fact, it's almost
>    guaranteed to get failures when connecting using an iPhone (iOS
>    10.2.1)
>  * The empty session ID/len comes from a call to SSL_SESSION_get_id in
>    imap/tls.c : remove_session_cb.
>  * The empty session ID/len is sent from remove_session_cb to the
>    local function remove_session which in turn tries to use them to
>    remove an entry from the session cache (which is where we hit the
>    assert).
>  * My knowledge of openssl internals is just epsilon above non-
>    existent so I'm kind'a lost.
> This is a stripped down excerpt from syslog:

> Apr 15 14:15:29 mda-test cyrus/imaps[14548]: inittls: Loading hard-
> coded DH parameters Apr 15 14:15:29 mda-test cyrus/imaps[14548]: TLS
> server engine: No client CA certs specified. Client side certs may not
> work Apr 15 14:15:29 mda-test cyrus/imaps[14548]: starttls: TLSv1.2
> with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits new) no
> authentication Apr 15 14:15:29 mda-test cyrus/imaps[14548]: login:
> [192.168.10.245] <username> plaintext+TLS User logged in SESSIONID=<cyrus-14548-1492258529-1-
> 7309509142786610107> Apr 15 14:15:29 mda-test cyrus/imaps[14548]:
> client id: "name" "iPhone Mail" "version" "14D27" "os" "iOS" "os-
> version" "10.2.1 (14D27)" Apr 15 14:15:32 mda-test cyrus/imaps[14548]:
> USAGE <username> user: 0.024000 sys: 0.032000 Apr 15 14:15:32 mda-test
> cyrus/imaps[14548]: Fatal error: Internal error: assertion failed:
> lib/cyrusdb_twoskip.c: 2339: key && keylen Apr 15 14:15:32 mda-test
> cyrus/master[14524]: process type:SERVICE name:imaps
> path:/usr/lib/cyrus/bin/imapd age:3.713s pid:14548 exited, status 75
> Apr 15 14:15:32 mda-test cyrus/imaps[14549]: inittls: Loading hard-
> coded DH parameters Apr 15 14:15:32 mda-test cyrus/imaps[14549]: TLS
> server engine: No client CA certs specified. Client side certs may not
> work Apr 15 14:15:32 mda-test cyrus/imaps[14549]: starttls: TLSv1.2
> with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256 bits new) no
> authentication Apr 15 14:15:32 mda-test cyrus/imaps[14549]: login:
> [192.168.10.245] <username> plaintext+TLS User logged in SESSIONID=<cyrus-14549-1492258532-1-
> 11595859793003941986> Apr 15 14:15:32 mda-test cyrus/imaps[14549]:
> client id: "name" "iPhone Mail" "version" "14D27" "os" "iOS" "os-
> version" "10.2.1 (14D27)" Apr 15 14:15:33 mda-test cyrus/imaps[14550]:
> inittls: Loading hard-coded DH parameters Apr 15 14:15:33 mda-test
> cyrus/imaps[14550]: TLS server engine: No client CA certs specified.
> Client side certs may not work Apr 15 14:15:33 mda-test
> cyrus/imaps[14550]: Fatal error: Internal error: assertion failed:
> lib/cyrusdb_twoskip.c: 2339: key && keylen Apr 15 14:15:33 mda-test
> cyrus/master[14524]: process type:SERVICE name:imaps
> path:/usr/lib/cyrus/bin/imapd age:0.085s pid:14550 exited, status 75
> Apr 15 14:15:33 mda-test cyrus/imaps[14549]: USAGE <username> user:
> 0.052000 sys: 0.012000 Apr 15 14:15:33 mda-test cyrus/imaps[14549]:
> starttls: TLSv1.2 with cipher ECDHE-RSA-AES256-GCM-SHA384 (256/256
> bits new) no authentication Apr 15 14:15:33 mda-test
> cyrus/imaps[14549]: login: [192.168.10.245] <username> plaintext+TLS
> User logged in SESSIONID=<cyrus-14549-1492258533-1-
> 2557587616344912297> Apr 15 14:15:33 mda-test cyrus/imaps[14549]:
> client id: "name" "iPhone Mail" "version" "14D27" "os" "iOS" "os-
> version" "10.2.1 (14D27)" Apr 15 14:15:36 mda-test cyrus/imaps[14549]:
> USAGE <username> user: 0.028000 sys: 0.020000
> I cannot find the core dump. Do I need to build using any specific
> flags/settings?
> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].
> 



--

  Bron Gondwana

  brong@fastmail.fm






Links:

  1. https://github.com/cyrusimap/cyrus-imapd/issues/1872#issuecomment-294291642

**Comment by Saelberaen** [comment]
* Yes, it's the key length that is zero.
* Yes, the triggered assert is in mystore. Call chain is remove_session_cb -> remove_session -> cyrusdb_delete.
* I've got no idea why openssl is triggering the remove_session_cb callback with a session that has an invalid session ID, but it feels like a safe thing to just test for zero-length ID and ignore it if so. tls_prune should clean up any stale sessions anyway.
* The only thing that worries me is if this is an indication of another, deeper, error (I'm a compiler developer so I tend to get antsy when I don't understand why things go wrong :P).

**Comment by elliefm** [comment]
> The only thing that worries me is if this is an indication of another, deeper, error (I'm a compiler developer so I tend to get antsy when I don't understand why things go wrong :P).

Yeah, this smells weird and I don't entirely like it either, but...

> My knowledge of openssl internals is just epsilon above non-existent so I'm kind'a lost.

... same.

Sounds like maaaaybe the iOS SSL layer is interacting with OpenSSL in some strange way, and OpenSSL is passing the weirdness down?  I'm glad we're not crashing anymore, but I suspect finding a root cause here is going to be beyond me.

**Comment by elliefm** [comment]
> I cannot find the core dump. Do I need to build using any specific flags/settings?

Does the user you run cyrus as have appropriate ulimits?  I don't think any specific build flags are needed, but I don't know that Debian haven't disabled something that's enabled by default.  This is how I configure, if it's any help:

```
./configure \
    CFLAGS="-g -O0 -Wall -Wextra -Werror -Wl,--as-needed $CFLAGS" \
    XAPIAN_CONFIG="/usr/local/xapian/bin/xapian-config-1.5" \
    --prefix="$CYRUS_PREFIX" \
    --enable-http \
    --enable-calalarmd \
    --enable-unit-tests \
    --enable-replication \
    --with-openssl=yes \
    --enable-nntp \
    --enable-murder \
    --enable-idled \
    --enable-event-notification \
    --enable-sieve \
    --enable-autocreate \
    --enable-silent-rules \
    --enable-backup \
    --with-lmdb \
    --enable-xapian \
    --enable-jmap \
```

(I guess we no longer need a core dump at this point, but maybe this is helpful for the future.)

**Comment by sherpya** [comment]
it's in a1c917df8de04e108228f38f0010498bec3d81e8?

**Comment by elliefm** [comment]
Yep
