### ISSUE TITLE
Double-dash on configure options being turned into single dash in docs

### ISSUE THREAD

**Issue by nicolan** [cyrusimap/cyrus-imapd#1879]
On the http://cyrusimap.org/imap/reference/admin/eventsource.html, I see that the double-dash for configure options (e.g. '–enable_event_notification: Set this to “yes” to have Cyrus generate mailbox related events. This is enabled by default.' line) is replaced with a single long dash. I guess the same happens on other documentation pages.

**Comment by elliefm** [comment]
configure options should be `quoted in backticks` to avoid this

**Comment by elliefm** [comment]
... I was about to point to docsrc/imap/reference/admin/backups.rst as an example of good formatting, but then noticed a spot where I'd missed that very thing myself. Doh!

**Comment by nicolan** [comment]
This got merged, so I'm closing this issue. Yay!
