### ISSUE TITLE
git: remove docsrc/exts/themes/(cyrus,sphinx_rtd_theme)/__pycache__

### ISSUE THREAD

**Issue by dilyanpalauzov** [cyrusimap/cyrus-imapd#1894]
Remove `docsrc/exts/themes/cyrus/__pycache__/__init__.cpython-34.pyc` and `docsrc/exts/themes/sphinx_rtd_theme/__pycache__/__init__.cpython-34.pyc` as these are not supposed to be managed in git (and are useless if python != 3.4 is used).

**Comment by nicolan** [comment]
Fixed with commit 36083466b351405f80feac9372f93e7d9da098e3 on master
Backported to 3.0 with commit bf85d72f549af8303d1388af84e419c4177d3746

Thanks for the report!

**Comment by dilyanpalauzov** [comment]
.gitignore now includes twice *.pyc .

*.pyc and docsrc/**/__pycache__/ seem to be redundant together.

**Comment by elliefm** [comment]
I'm going to be doing a bunch of gitignore cleanups soon, this will be fixed up then

**Comment by elliefm** [comment]
gitignore tidied up on master, and will be on 3.0 too soon once some tests finish
