### ISSUE TITLE
Makefile.am: install sieve/varlist.h and sieve/grammar.h

### ISSUE THREAD

**Issue by dilyanpalauzov** [cyrusimap/cyrus-imapd#1895]
The file sieve/sieve_interface.h is installed, so that non-cyrus programs using libcyrus_sieve can use libcyrus_sieve.  However sieve_interface.h includes grammar.h and varlist.h, so that the latter need to be installed too.

**Comment by ksmurchison** [comment]
Fixed with https://github.com/cyrusimap/cyrus-imapd/commit/51d28de6f4ebed9692b235846293626bce284256
