### ISSUE TITLE
Makefile.am: be clear about distibuting _err.[ch] files in .tar

### ISSUE THREAD

**Issue by dilyanpalauzov** [cyrusimap/cyrus-imapd#1899]
Files included in EXTRA_DIST are put in the final .tar file upon `make dist`.  Source files mentioned as nodist_... are not included in the .tar .

imap/mupdate_err.c is  included both in EXTRA_DIST and in nodist_imap_libcyrus_imap_la_SOURCES.

If imap/mupdate_err.c is supposed to be included in the tar file, remove it from EXTRA_DIST and nodist_imap_libcyrus_imap_la_SOURCES and include it together with imap/mupdate_err.h in imap_libcyrus_imap_la_SOURCES .  If imap/mupdate_err is not supposed to be included in the .tarball remove if from EXTRA_DIST.

Likewise for the other *_err.[ch] files, as their treatment in regards to inclusion in the .tar fle needs to be consistent for the whole cyrus imap.

The same argument applies for imap/http_carddav_js.h and imap/http_caldav_js.h .

**Comment by ksmurchison** [comment]
A patch would be greatly appreciated

**Comment by dilyanpalauzov** [comment]
9d8cf8501fee99c0c86d7cc9d10eb75bef868305

**Comment by dilyanpalauzov** [comment]
The _err.c and _err.h files are now consistently prefixed with `nodist_`.
