### ISSUE TITLE
Makefile.am: overuse of EXTRA_DIST for imap/lmtpstats.c

### ISSUE THREAD

**Issue by dilyanpalauzov** [cyrusimap/cyrus-imapd#1900]
The files imap/lmtpstats.c, imap/pushstats.c and imap/rfc822_header.c are included in the final .tar file created by `make dist`, as they appear in imap_deliver_SOURCES, imap_imapd_SOURCES and imap_libcyrus_imap_la_SOURCES . There is no point to include them (conditionally or unconditionally) one more time in EXTRA_DIST.

Please move also lmtpstats.h, pushstats.h and rfc822_header.h from EXTRA_DIST to _SOURCES for consistency.

**Comment by ksmurchison** [comment]
A patch would be greatly appreciated

**Comment by dilyanpalauzov** [comment]
It is in #73 .

**Comment by dilyanpalauzov** [comment]
This does not apply any more.
