### ISSUE TITLE
libcyrus_(min, sieve).pc.in: update to contain exec_prefix

### ISSUE THREAD

**Issue by dilyanpalauzov** [cyrusimap/cyrus-imapd#1903]
./configure replaces @libdir@ in libcyrus_min.pc.in and libcyrus_sieve.pc.in by default with ${exec_prefix}, but ${exec_prefix} is not replaced under @exec_prefix@, as the latter is missing.  So ${exec_prefix} is left undefined.

Include in libcyrus_min.pc.in and libcyrus_sieve.pc.in the line
`exec_prefix = @exec_prefix@`

**Comment by elliefm** [comment]
Already on master, cherry-picked to 3.0
