### ISSUE TITLE
sieveshell: upload files, whose names end with ".script" without truncating the names

### ISSUE THREAD

**Issue by dilyanpalauzov** [cyrusimap/cyrus-imapd#1907]
sieveshell strips ".script" from the end of the script name, when uploading files.  This is neither documented nor desired:
```diff --git a/perl/sieve/lib/request.c b/perl/sieve/lib/request.c
--- a/perl/sieve/lib/request.c
+++ b/perl/sieve/lib/request.c
@@ -279,11 +283,6 @@ static char *getsievename(char *filename)
 
   strcpy(ret, ptr);
 
-  if ( strcmp( ret + strlen(ret) - 7,".script")==0)
-  {
-    ret[ strlen(ret) - 7] = '\0';
-  }
-
   return ret;
 }
```

Replace in perl/sieve/scripts/sieveshell.pl draft-ietf-managesieve-03.txt with RFC 5804.

**Comment by ajaysusarla** [comment]
Although https://tools.ietf.org/html/rfc5804#section-1.6 doesn't mention anything about the filename extensions. And it is unclear from the git logs (and the RFC) as to why `.script` is special. 
Need to check with either @brong or @ksmurchison about this. They will have a lot more context

**Comment by ajaysusarla** [comment]
From the `installsieve` [man page](https://github.com/cyrusimap/cyrus-imapd/blob/master/docsrc/imap/reference/manpages/usercommands/installsieve.rst):
```
    If *file* has the extension .script it is chopped when put on the
    server since sieve names may not contain a '.'.
```

**Comment by elliefm** [comment]
My understanding here is that if "foo" is the _name_ of the script, then "foo.script" is its uncompiled _filename_ and "foo.bc" is its compiled _filename_.  I believe the ".script" and ".bc" extensions are specific to how Cyrus stores this data.

In this context it makes sense that ".script" would be stripped from script _names_, because it is part of the _filenames_ only.  

A client theoretically doesn't know about the ".script" extension, and mostly wouldn't use it, because that is an internal Cyrus implementation detail.

**Comment by ajaysusarla** [comment]
As @elliefm has already summarised in the previous comment, the `.script` extension has some significance in Cyrus IMAP. 
Thanks for your time dilyanpalauzov, will close this issue.

**Comment by dilyanpalauzov** [comment]
Sieve script names may contain dot, according to the implementation of timsieve/actions.c:scriptname_valid() and https://tools.ietf.org/html/rfc5804#section-1.6.

The .script extension is trimmed in the client.  The server has no problem to accept x.script, store it as x.script.script and return it as x.script .

If there is a problem with uploading files ending in .script, then this shall be handled server-side.

**Comment by dilyanpalauzov** [comment]
>     If *file* has the extension .script it is chopped when put on the server since sieve names may not contain a '.'.

comes from commit fd2aa06f3f22f back in 1999.  At that time the upload protocol Walrus  was described in timsieved/PROTOCOL.description and the last line of the file is `<sievename> is a string where only certain characters are allowed and it must be at least 1 character long`.  At that time `installsieve` was probably the only managesieve/Walrus client, so it was safe to do the latter checks in the client instead of the server

**Comment by dilyanpalauzov** [comment]
The last sentence of the issue description was not tackled.
