### ISSUE TITLE
Makefile.am: libexec_PROGRAMS += imap/nntpd occurs twice

### ISSUE THREAD

**Issue by dilyanpalauzov** [cyrusimap/cyrus-imapd#1910]
The line `libexec_PROGRAMS += imap/nntpd` appears twice in Makefile.am . Including it once is enough.

**Comment by ksmurchison** [comment]
Fixed with https://github.com/cyrusimap/cyrus-imapd/commit/da3974d31cabd44020ec49ea0662a4c676a7f4fa
