### ISSUE TITLE
Cyrus-imap 2.4.17 consume more and more memroy

### ISSUE THREAD

**Issue by HongshanShi** [cyrusimap/cyrus-imapd#1924]
Dear sir/madam,

We upgrade our OS from RHEL5.3 to RHEL7.2, and the cyrus-imapd together upgrade from cyrus-imapd  2.3.7 to cyrus-imapd 2.4.17. But after upgrade, we found imapd process consume more and more memroy, and a lat make our server out of memory. 

Here is my configuration:
/etc/imapd.conf

configdirectory: /var/lib/cyrus-imapd/conf
partition-default: /var/lib/cyrus-imapd/data
admins: cyrus
allowplaintext: yes
annotation_db: berkeley
mboxlist_db: berkeley
sievedir: /var/lib/imap/sieve
hashimapspool: true
sasl_pwcheck_method: saslauthd
tls_cert_file: /etc/pki/cyrus-imapd/cyrus-imapd.pem
tls_key_file: /etc/pki/cyrus-imapd/cyrus-imapd.pem
tls_ca_file: /etc/pki/tls/certs/ca-bundle.crt
berkeley_cachesize: 512000
berkeley_locks_max: 50000
berkeley_txns_max: 1000
fulldirhash: true
expunge_mode:immediate

And here is the cyrus configuration
/etc/cyrus.conf
START {
  recover       cmd="ctl_cyrusdb -r"
  idled         cmd="idled"
}
 
SERVICES {
imap cmd="imapd" listen="IMAP:imap" prefork=5 maxfds=1024
  lmtpunix      cmd="lmtpd" listen="/var/lib/imap/socket/lmtp" prefork=1
}
EVENTS {
  checkpoint    cmd="ctl_cyrusdb -c" period=30
  tlsprune      cmd="tls_prune" at=0400
}

Hope your reply

Thanks,

Br,
Samuel

**Comment by dilyanpalauzov** [comment]
Fixed on cyrus-imapd-2.4 with commits 0b4212e8e64afe022216b0eaa7f4b7da3a0038ae and 3aa8ed0278e9de6a86ec63a146db9abe3ea30a77.
