### ISSUE TITLE
better error message than "IOERROR: reading message: unexpected end of file"

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#1926]
This particular IOERROR message is strictly an IOERROR, but it's a pretty common one.  It means that a client said it was going to upload N bytes in a LITERAL, and then disconnected before it had finished.  That's a thing that happens in the real world, and calling it an IOERROR does make it harder to detect real IOERRORs from logs.

It would be nice to log something like "DISCONNECT: client disconnected during upload of literal" instead.

**Comment by elliefm** [comment]
There's a few other occurrences of the "IOERROR: reading message: unexpected end of file" error, but unlike the one in imapd, these ones look like proper I/O errors and not merely client disconnections, so I've left them as is.

**Comment by slauffer** [comment]
After upgrading from 3.0.5 to 3.0.6 we notice these errors.

The main problem is that these cyrus processes will not be closed and are eating 100%  of cpu. This is the (new?) problem here.

I am sure we do not have such a problem in 3.0.5. Can I help with some debug informations?

**Comment by slauffer** [comment]
@elliefm: yes, you are right. Thanks!
