### ISSUE TITLE
User cleanup is not safe against Xapian indexing

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#1927]
If a squatter is indexing as a user gets deleted, the xapian directories get deleted out from underneath the squatter, leading to IOERROR messages in the logs.

The user cleanup code should take an exclusive lock on the xapianactive file while it deletes the indexes.

**Comment by elliefm** [comment]
How's this look?  Seems like it should be straightforward, but double checking cause I don't know the search code well.

https://github.com/cyrusimap/cyrus-imapd/compare/master...elliefm:v31/1927-xapian-lock-deleteuser
