### ISSUE TITLE
--with-mysql succeeds even without mysql/mariadb installed

### ISSUE THREAD

**Issue by jasontibbitts** [cyrusimap/cyrus-imapd#1931]
I was cleaning up what I pass to configure and noted that if I pass --with-mysql without actually having mysql/mariadb development libraries installed, configure outputs the following:

```
checking whether to use MySQL... ./configure: line 19082: mysql_config: command not found
./configure: line 19083: mysql_config: command not found
yes
```

Which is odd.  config.log isn't useful at all:

```
configure:19052: checking whether to use MySQL
configure:19091: result: yes
```

mysql shows as enabled in the summary.  I guess there might be a broken test in there, but autoconf is just not my thing so I didn't look much deeper.

**Comment by elliefm** [comment]
Yeah wow, good catch

**Comment by jasontibbitts** [comment]
Thanks!
