### ISSUE TITLE
Simplify process init/shutdown

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#1940]
At the moment pretty much every daemon or standalone command line tool has crap like this:

    /* so we can do mboxlist operations */
    mboxlist_init(0);
    mboxlist_open(NULL);

[...]

        /* so we can do quota operations */
        quotadb_init(0);
        quotadb_open(NULL);

        /* open the user deny db */
        denydb_init(0);
        denydb_open(0);

#ifdef WITH_DAV
        /* so we can do DAV operations */
        caldav_init();
        carddav_init();
#endif

        /* Initialize the annotatemore db (for sieve on shared mailboxes) */
        annotate_init(NULL, NULL);
        annotatemore_open();

        /* setup for statuscache invalidation */
        statuscache_open();

        /* setup for sending IMAP IDLE notifications */
        idle_init();

        /* setup for mailbox event notifications */
        mboxevent_init();
    }

....

and then later:

    mboxlist_close();
    mboxlist_done();

    if (!isproxy) {
#ifdef USE_SIEVE
        sieve_interp_free(&sieve_interp);
#else
        if (dupelim)
#endif
            duplicate_done();

        quotadb_close();
        quotadb_done();

        denydb_close();
        denydb_done();

#ifdef WITH_DAV
        carddav_done();
        caldav_done();
#endif

        annotatemore_close();
        annotate_done();

        idle_done();
    }

#ifdef HAVE_SSL
    tls_shutdown_serverengine();
#endif

....

This is (a) ridiculous amounts of boilerplate, and (b) we always miss something, as evidenced by the fact that calalarmd isn't sync_logging changes because it doesn't init the sync_log right now.  I'll fix that immediately, but long term, we shouldn't be doing all these independing init statements.  Things should init first time they are used, and should clean up from a single cyrus_done() as much as possible.

**Comment by rsto** [comment]
Fixed with 8e341bf1dcbd9a54dd3cfcf88f48f56532f20fa1 and a bunch of following commits
