### ISSUE TITLE
Index filenames of attachments 

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#1952]
Content-Disposition: attachment; filename="SK02_Iteration 2_P2.pdf"
Content-Id: <1491958860.611808.aff3fbc8c60e3c8affe025ae4d7c6eae3d534f96.42BF3E9E@content.messagingengine.com>
Content-Transfer-Encoding: base64
Content-Type: application/pdf; name="SK02_Iteration 2_P2.pdf"

We should index the filename and have it as a searchable field.

**Comment by rsto** [comment]
Done in 1f6e777d75b8df77ef313cc89626c6603a45e644 and 3ae75a70849139da7d378ca5f251e8d5c8726536
