### ISSUE TITLE
2.5.11 won't compile under Debian 7

### ISSUE THREAD

**Issue by Stephan76** [cyrusimap/cyrus-imapd#1964]
While compiling 2.5.11 on a Debian 7 system the following error occurs:

imap/imapd.o: In function `deadline_exceeded':
cyrus-imapd-2.5.11/imap/imapd.c:2882: undefined reference to `clock_gettime'

'man clock_gettime' says "Link with -lrt (only for glibc versions before 2.17)." Glibc version is 2.13 so this might be the issue. Configuring with 'LIBS="-lrt"' makes the error go away.

**Comment by brong** [comment]
Nicola, maybe a docs issue for 2.5.11 :)  Can at least doc the workaround.

ellie - I guess we could add a thing to configure to decide if -lrt is required, since 2.5.x is oldstable, it should still be supported.

**Comment by elliefm** [comment]
We already have some code in configure.ac for detecting and linking against librt (it's needed by fdatasync for cyrusdb_skiplist, if the comment is to be believed), so it's interesting that this is failing.

@Stephan76, are you able to paste the full line where imap/imapd.o is linked (rather than just the error)?  That might help me track down why we're not detecting it properly.

Thanks :)

**Comment by elliefm** [comment]
(I guess it may simply be that fdatasync doesn't actually need librt in Debian 7, so that test doesn't bother to include it, and so you don't get it -- this would become clear from the link command.)

**Comment by elliefm** [comment]
@Stephan76, I've put up a speculative fix here -- https://github.com/cyrusimap/cyrus-imapd/compare/cyrus-imapd-2.5...elliefm:v25/1964-need-rt-library

Are you able to try this out and see whether it detects librt correctly in your environment?

**Comment by Stephan76** [comment]
/bin/sh ./libtool  --tag=CC   --mode=link gcc -fPIC  -g -O2    -o imap/imapd imap/imap_proxy.o imap/imapd.o imap/mutex_fake.o imap/pushstats.o imap/proxy.o master/service.o  sieve/libcyrus_sieve.la imap/libcyrus_imap.la lib/libcyrus.la lib/libcyrus_min.la -lgssapi_krb5 -lkrb5 -lk5crypto -lcom_err -lkrb5support     -ldb-5.1 -lpcre -lpcreposix -lz  -lsasl2 -lssl -lcrypto   -lssl -lcrypto  -lcom_err -lwrap -lnsl -lgssapi_krb5 -lkrb5 -lk5crypto -lcom_err -lkrb5support     -ldb-5.1 -lpcre -lpcreposix -lz
libtool: link: gcc -fPIC -g -O2 -o imap/.libs/imapd imap/imap_proxy.o imap/imapd.o imap/mutex_fake.o imap/pushstats.o imap/proxy.o master/service.o  sieve/.libs/libcyrus_sieve.so imap/.libs/libcyrus_imap.so lib/.libs/libcyrus.so lib/.libs/libcyrus_min.so -lsasl2 -lssl -lcrypto -lwrap -lnsl -lgssapi_krb5 -lkrb5 -lk5crypto -lcom_err -lkrb5support -ldb-5.1 -lpcre -lpcreposix -lz -Wl,-rpath -Wl,/usr/local/cyrus-imapd-2.5.11/lib

**Comment by Stephan76** [comment]
It's still the same with the patch applied:

libtool: link: gcc -fPIC -g -O2 -o imap/.libs/imapd imap/imap_proxy.o imap/imapd.o imap/mutex_fake.o imap/pushstats.o imap/proxy.o master/service.o  sieve/.libs/libcyrus_sieve.so imap/.libs/libcyrus_imap.so lib/.libs/libcyrus.so lib/.libs/libcyrus_min.so -lsasl2 -lssl -lcrypto -lwrap -lnsl -lgssapi_krb5 -lkrb5 -lk5crypto -lcom_err -lkrb5support -ldb-5.1 -lpcre -lpcreposix -lz -Wl,-rpath -Wl,/usr/local/cyrus-imapd-2.5.11/lib
imap/imapd.o: In function `deadline_exceeded':
/root/src/cyrus/cyrus-imapd-2.5.11/imap/imapd.c:2882: undefined reference to `clock_gettime'

**Comment by elliefm** [comment]
Have your `configure` and `Makefile` been updated since applying the patch, or are they still the original versions from the release? (Look at timestamps, I suppose.)  If not, they'll need to be rebuilt.  You should be able to do this with something like:

```
make distclean
autoreconf -is
```

And then run `./configure` and `make` again as usual.

You might need to install the `autoconf` package if you don't have the `autoreconf` command

**Comment by Stephan76** [comment]
Actually I deleted the whole directory, untar/gzipped cyrus-imapd-2.5.11.tar.gz, applied https://github.com/cyrusimap/cyrus-imapd/compare/cyrus-imapd-2.5...elliefm:v25/1964-need-rt-library.diff, ran configure and then make, but it's still the same.

**Comment by elliefm** [comment]
Ah yep.  So, the `configure` script is a generated file, and its source file is `configure.ac`.  The patch only updates the source file, `configure.ac`, so after applying it you need to rebuild `configure` (using `autoreconf`) for the patch to have any effect.

**Comment by Stephan76** [comment]
Aaaah, okay, when I run autoreconf after patching make runs through !

**Comment by elliefm** [comment]
Great, thanks for verifying that!  This fix will be included in the next release :)
