### ISSUE TITLE
make mboxevents mandatory to compile in

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#1972]
At the moment you can compile without mboxevents, which means massive ifdef statements and we don't really test without them compiled in.

We should just strip all that so that we always compile mboxevents in and simplify the configuration job.

**Comment by nicolan** [comment]
This will also affect the docs. I need to know: if any compile time flags changed, and what library dependencies are affected.

**Comment by ajaysusarla** [comment]
A pull request is available here: https://github.com/cyrusimap/cyrus-imapd/pull/1973. @nicolan I've tried to update the references to `disable-event-notification` in the documentation. Hopefully I haven't missed any.
