### ISSUE TITLE
Make quota command take "-u" option to process users

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#1975]
Quota takes a horrible old mailbox prefix in internal format from the command line.  It should allow -u like all our other commands.  Actually, standardising command line flags for the next release would be a very good thing!

**Comment by elliefm** [comment]
See also #1766 :P

**Comment by nicolan** [comment]
Documentation needs to be updated to match.

**Comment by elliefm** [comment]
Done and done as per #1766
