### ISSUE TITLE
getCalendarEvents not limiting properties returned

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#1980]
[["getCalendarEvents",{"properties":["x-href","calendarId"],"ids":["04bca49b-8f23-4ded-a153-4babcee31fd8"]},"#1"]]

Returns the full event rather than just the requested properties.

**Comment by rsto** [comment]
Fixed in https://github.com/cyrusimap/cyrus-imapd/commit/b532f6430204a67f43959de505338ad02fa35200 and tested in https://github.com/cyrusimap/cassandane/commit/bebd2ecc6dd8bd95073bed58b2d4e1bb461adb44
