### ISSUE TITLE
cyr_expire: add a per-folder annotation which changes how long to keep deleted messages

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#1988]
This will be very handy for calendar and contacts, where we may want to keep them for many more weeks to support undo.

It would be good to define a full set of annotations to control the cyr_expire behaviour on folders and override command line flags.

**Comment by elliefm** [comment]
This already seems to exist for the `cyr_expire -E` functionality -- man page says:

>        The  expiration of messages is controlled by the /vendor/cmu/cyrus-imapd/expire
>        mailbox annotation which specifies the age (in days) of messages in  the  given
>        mailbox that should be deleted.  A value of 0 means that no expiration is to be
>        performed on that mailbox.
> 
>        The value of the /vendor/cmu/cyrus-imapd/expire annotation is inherited by  all
>        children  of  the  mailbox on which it is set, so an entire mailbox tree can be
>        configured by setting a single annotation on the root of that tree.  If a mail‐
>        box  does  not  have  a /vendor/cmu/cyrus-imapd/expire annotation set on it (or
>        does not inherit one), then no messages are expired from the mailbox.

Are you asking for a similar annotation mechanism for the `-A`, `-D` and `-X` functionalities?

**Comment by elliefm** [comment]
PR #2030

**Comment by ajaysusarla** [comment]
Tests merged to Cassandane(https://github.com/cyrusimap/cassandane/commit/c7b898025dcb1864f3848009942341e5e0d4a35c)

**Comment by ajaysusarla** [comment]
Closing this issue.
