### ISSUE TITLE
Docs: mention Openssl version mismatches

### ISSUE THREAD

**Issue by jasontibbitts** [cyrusimap/cyrus-imapd#2013]
It might be worth documenting the current mess with the migration from openssl 1.0 to 1.1.  Basically some things have moved over and some things haven't, and the mismatch causes problems for anything which tries to link against libraries in both groups.  This results in linker warnings like the following:

```
/usr/bin/ld: warning: libssl.so.10, needed by /usr/lib/gcc/x86_64-redhat-linux/7/../../../../lib64/libclamav.so, may conflict with libssl.so.1.1
/usr/bin/ld: warning: libcrypto.so.10, needed by /usr/lib/gcc/x86_64-redhat-linux/7/../../../../lib64/libclamav.so, may conflict with libcrypto.so.1.1
```

And, of course, you may also see segfaults in things like cyr_vyrusscan.  It doesn't always segfault, and for example the Cassandane tests which call cyr_virusscan will (for me) pass reliably on all architectures except for ppc64 where for whatever reason it fails consistently.

In the Fedora builds, I have to disable mysql and clamav support because of this.  Clamav will be fixed when 0.99.3 is released, but I have no idea when that will be; the Fedora maintainers may decide to patch it in sooner.  Mariadb was fixed with 10.2.6, which was released relatively recently and should hopefully show up in Fedora rawhide soon.  I will of course re-enable these things when possible, and it's probably not worth documenting things for specific distro versions as this is likely to change relatively quickly.   But it might be worth having some kind of general warning about it somewhere.

**Comment by elliefm** [comment]
Ouch.  Haven't seen this myself... turns out my system is still on 1.0.2 (but it has an upgrade pending to 1.1.0 that I haven't touched for reasons), so I wonder if this is yet another thing that will break when I update...

Insofar as I've tested linking against openssl 1.1.0, it's been using a custom built one, and only Cyrus is linked against it, my dependencies are mostly just system packages and therefore 1.0.2.  Didn't have any trouble with this configuration but it was a while ago I was testing 1.1.0 so maybe the world has changed under me there too?

Not sure where in the documentation this sort of thing might fit, any thoughts? Ping @nicolan @postilion

**Comment by nicolan** [comment]
We now have a dedicated compilation page: https://www.cyrusimap.org/imap/developer/compiling.html which mentions openssl. We can add in a special note about the versions. Though I'm not sure what to say. If someone can encapsulate the situation in something that would make sense, I can pop it into the docs.

**Comment by jasontibbitts** [comment]
I swear I submitted this last week, but I guess not.  Maybe something like this?

### OpenSSL Version Mismatches

Major updates of OpenSSL are not always compatible with each other at the API level, which means that programs which use it require code changes to accommodate these updates.  OpenSSL is used by very many libraries and system components and due to the changes necessary not all of those become compatible with the new version at the same time.  Some Linux distributions may choose to ship multiple OpenSSL versions and allow components to use whichever version is appropriate.  So it is possible that some libraries which Cyrus can use might be linked against different versions of the OpenSSL libraries, or that those may be different from the version which Cyrus itself will use.

It is generally not advisable to have two different versions of the OpenSSL libraries linked into one program.  Attempting to do this may result in warnings from the linker like the following:
```
/usr/bin/ld: warning: libssl.so.10, needed by /usr/lib/gcc/x86_64-redhat-linux/7/../../../../lib64/libclamav.so, may conflict with libssl.so.1.1
/usr/bin/ld: warning: libcrypto.so.10, needed by /usr/lib/gcc/x86_64-redhat-linux/7/../../../../lib64/libclamav.so, may conflict with libcrypto.so.1.1
```

In this case, ClamAV is still linked against OpenSSL 1.0, while Cyrus building with OpenSSL 1.1.  Attempting to run programs which are linked against multiple different versions of the same library may result in instability.  So if you see warnings similar to those, please exercise care and double check the versions of OpenSSL in use by the various components involved.

**Comment by nicolan** [comment]
Thanks for the information! I've included it in a few places on the compilation page for 3.0 and master.
