### ISSUE TITLE
Prefix style search snippets not being returned

### ISSUE THREAD

**Issue by nicolan** [cyrusimap/cyrus-imapd#2017]
Observed in FastMail (and Tx). Searching for "foo" suitably highlights the 'foo' text.

But searching for "foo*" should also highlight where 'foo' appears.

**Comment by rsto** [comment]
Fixed in https://github.com/cyrusimap/cyrus-imapd/commit/4edeee3f6ab3b9ec3f3d0cacb5b682024b341bed and tested in https://github.com/cyrusimap/cassandane/commit/65b2034fabaeb4b1288ddc82ac2ce4a104fa97c9
