### ISSUE TITLE
Docs: write man page for systemcommands/proxyd

### ISSUE THREAD

**Issue by nicolan** [cyrusimap/cyrus-imapd#2019]
There's a stub there saying it's a "work in progress". 

We should write this up!

**Comment by elliefm** [comment]
"proxyd" doesn't appear to be a thing that exists?

**Comment by brong** [comment]
It's a symlink to imapd if you build with murder


On Wed, 14 Jun 2017, at 11:15, elliefm wrote:
> "proxyd" doesn't appear to be a thing that exists?


> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].> 

--
  Bron Gondwana
  brong@fastmail.fm



Links:

  1. https://github.com/cyrusimap/cyrus-imapd/issues/2019#issuecomment-308291668

**Comment by postilion** [comment]
@nicolan Does Sphinx have any support for linked man pages?  Or is this something we need to handle in the Makefiles?

For example, all of the `*test` executables are in fact symlinks to `imtest`, yet we maintain separate man pages as httptest.rst, imtest.rst, lmtptest.rst, mupdatetest.rst, nntptest.rst, pop3test.rst,
sivtest.rst, smtptest.rst, and synctest.rst.

The same situation plays out with the various proxy daemons, which are themselves simply symlinks to the related daemon (non-proxy):
- /usr/lib/cyrus/bin/lmtpproxyd->lmtpd
- /usr/lib/cyrus/bin/pop3proxyd->pop3d
- /usr/lib/cyrus/bin/proxyd->imapd

Methinks we couldst make life easier if we could do manpage linkage.
-nic

**Comment by elliefm** [comment]
I remember a while ago there were symlinks -- possibly for this very thing! -- whereby the rst files were symlinked with the other names.  Sphinx would build the pages but would complain a lot (duplicate section id's etc) -- i.e. it didn't seem to handle the symlinks in any special way, just treated them as duplicated files.  So that's one approach, but it's not very nice.

Do we need to duplicate the man pages?  Can we not assume anyone looking closely at proxyd (etc) will notice that it's a symlink, and thus find the correct man page to read?

For what it's worth, the `imtest` program behaves differently based on the name as which it's invoked (see line 2738 and lines 2858-2877 of `imtest/imtest.c`), so it makes sense for it to have distinct man pages for each name.  I don't think the service daemons do this, by constrast, so it's not really an apples-apples comparison.

**Comment by nicolan** [comment]
I actually have no problems maintaining separate manpages for these.

Ideally, the man pages would not only note the underlying symlinkiness, but also the reason for it to be so. 

In proxyd's case, it's worthwhile noting that this is a murder-only artifact, for example. (I dunno why the others all exist: anyone have any insight? Or is it some sort of backwards compatibility after a name change? In which case should we look at removing the underlying tool symlinks?)

**Comment by elliefm** [comment]
Not sure. I guess if you wanted to drop in your own custom proxy layer (for some reason), you would remove those symlinks and put your proxy scripts there (or change the symlinks to point to your proxy scripts, or whatever).  But I don't know if this is a deliberate feature.  My gut feel is it's just a backwards compatibility thing, from some dark day when the service binaries didn't know about murder.

**Comment by elliefm** [comment]
It's worth noting that in traditional man pages there's some mechanism (which might actually just be symlinks, I'm not sure, and haven't looked) for mapping multiple names to the same man page.  E.g if you `man fdopen` (n.b. "d") on linux you get the `fopen(3)` man page, which documents `fopen()`, `fdopen()` and `freopen()`

It would be really nice if we could produce the same effect from Sphinx (such that `man proxyd` opens the `imapd(8)` man page -- assuming your cyrus install is in your $MANPATH), but I suspect that's not likely cause its primary goal is html/web.

**Comment by nicolan** [comment]
We could probably just put in some :include: into the extra man pages if that's sufficient. So you are at a separate page (whether html or man), but it has the underlying same content (no risk of having to keep two copies of info alive, and you don't have to manually look up the other command, if we just document it as a placeholder for the symlink)

**Comment by elliefm** [comment]
That seems pretty reasonable

**Comment by postilion** [comment]
@elliefm Links are the proper mechanism.  Following your example:
`nic@flabby::~$ locate fdopen`
`/usr/share/man/man3/fdopen.3.gz`
`/usr/share/man/man3/fdopendir.3.gz`
`nic@flabby::~$ ls -l /usr/share/man/man3/fdopen.3.gz`
`lrwxrwxrwx 1 root root 10 Dec 13  2016 /usr/share/man/man3/fdopen.3.gz -> fopen.3.gz`

So, that would be best, but perhaps @nicolan 's suggestion of includes would suffice.
-nic

**Comment by nicolan** [comment]
This is done!
