### ISSUE TITLE
usage of functions from jansson 2.5

### ISSUE THREAD

**Issue by scriptum** [cyrusimap/cyrus-imapd#2021]
Cyrus-imapd uses [json_array_foreach](http://jansson.readthedocs.io/en/2.8/apiref.html#c.json_array_foreach) from 2.5 but checks only for [version 2.3](https://github.com/cyrusimap/cyrus-imapd/blob/master/configure.ac#L1368).

Please note that RHEL 7 have only jansson 2.4. This makes impossible to compile 3.x.x in RHEL and CentOS.

**Comment by rsto** [comment]
I've pushed a fix for this on master and the 3.0 branch: https://github.com/cyrusimap/cyrus-imapd/commit/6e37245f7d341d24324f8f7990253538ff09ad31

I've verified it by compiling with Jansson 2.3 in my local setup. @scriptum does that work for you?

**Comment by scriptum** [comment]
This works for me, thanks!
