### ISSUE TITLE
JMAP: collapseThreads not reflected from call (false instead of NULL)

### ISSUE THREAD

**Issue by iNPUTmice** [cyrusimap/cyrus-imapd#2024]
I noticed that the `collapseThreads` attribute of a `messageList` response does not reflect the attribute from the `getMessageList` request when the attribute was NULL (missing) in the request. Instead it is set to false.

FWIW `sort` seems to behave correctly.

**Comment by rsto** [comment]
Yes, we set the default value, if this field isn't set (with `null` being equal to `false` semantically). I'll look into echoing back null.

**Comment by rsto** [comment]
Fixed in eef5daa500a44b2db94dc0b86eb0f8160666b8eb and tested in 6d33978ebb0055be41a5cb8e52958e100401bf26. Also cherry-picked into the 3.0 branch.
