### ISSUE TITLE
lmtp delivery no longer writes auditlog: append

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#2031]
LMTP deliveries are now logging "touched" rather than "append" auditlog lines, presumably due to how annotations are being added.  It should still log the append at the point where the record is added.

I have no specific plans for how this should be done, and I'm trying to avoid diving in and doing it myself!

**Comment by rsto** [comment]
Alright, after struggling 2 hours with Debian stretch messing up my Perl syslog packages, I got to the point of debugging this.

In constrast to pre-msgrecord, the append codepath now rewrites the index_record already in append_fromstage, which logs the "touched" message to syslog. Previously, we didn't have this rewrite, and the lmtpd final mailbox_commit caused the  "append" log message to appear.

The trouble with this is that at almost all other places where we use msgrecord we actually do wan't to transparently either append or rewrite the index_record, so I'll have to come up with a special treatment for append.

I'll continue working on this tomorrow.

**Comment by brong** [comment]
So I was wondering if we want msgrecord_rewrite and msgrecord_append
rather than just msgrecord_save - because you know whether you're
updating a record or not, and it makes for an extra sanity check...
Bron.


On Wed, 21 Jun 2017, at 02:44, Robert Stepanek wrote:
> Alright, after struggling 2 hours with Debian stretch messing up my
> Perl syslog packages, I got to the point of debugging this.> In constrast to pre-msgrecord, the append codepath now rewrites the
> index_record already in append_fromstage, which logs the "touched"
> message to syslog. Previously, we didn't have this rewrite, and the
> lmtpd final mailbox_commit caused the  "append" log message to appear.> The trouble with this is that at almost all other places where we use
> msgrecord we actually do wan't to transparently either append or
> rewrite the index_record, so I'll have to come up with a special
> treatment for append.> I'll continue working on this tomorrow.


> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].> 

--
  Bron Gondwana
  brong@fastmail.fm



Links:

  1. https://github.com/cyrusimap/cyrus-imapd/issues/2031#issuecomment-309818470

**Comment by rsto** [comment]
I've reworked the msgrecord code around append in b50af2797b1f2b215d45af17ca0e3a96ebacc688, including a refactor of _save to rewrite/append in 2f669d87abddb8f9f45c7155b659855617ef6191.

It all looks good now in the tests. I'll keep this issue open for a while in case we have to get back to it.

**Comment by rsto** [comment]
Looks like we can close this now.
