### ISSUE TITLE
validate that user flags only contain legal characters

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#2033]
A bug in the FastMail restore script created messages with [EXPUNGED] as a flag.  That's illegal according to the RFC.  We should validate flags as they're being set and not allow illegal characters.

**Comment by elliefm** [comment]
Looks like it's the ']' that makes it invalid (due to resp-specials being part of atom-specials).  Patch on the way, probably needs thorough testing to make sure this doesn't break something though?

**Comment by elliefm** [comment]
https://github.com/cyrusimap/cyrus-imapd/compare/master...elliefm:v31/2033-user-flags

We don't seem to have any tests that specifically exercise the imap parsing code, but this passes everything we do have.
