### ISSUE TITLE
JMAP folder create ACLs are weird

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#2059]
It looks like JMAP created folders are getting ACL 9 (DAV ACL READFB) even if they aren't calendars, and they also aren't inheriting the admin ACL from their parent.

**Comment by brong** [comment]
It should also be inheriting the "anyone p" ACL from the parent so that sieve folder delivery will work.  We should switch from mboxlist_createsync and/or read the parent ACL and manipulate it.

Also, we should only set READFB if it's a CALENDAR (not Outbox) mailbox.

**Comment by rsto** [comment]
Fixed in https://github.com/cyrusimap/cyrus-imapd/commit/ed63514779335c15aaae81ddf3a468addf4c6cdb
