### ISSUE TITLE
FR: include SESSIONID in client id log

### ISSUE THREAD

**Issue by robn** [cyrusimap/cyrus-imapd#2070]
The IMAP ID command causes a line to be emitted to the log.

```
2017-07-09T04:11:30.284596-04:00 imap24 sloti24t04/imapmail[3609860]: client id: "name" "iPad Mail" "version" "15A5304i" "os" "iOS" "os-version" "11.0 (15A5304i)"
```

On a busy server however its difficult to correlate this with a user. Usually you have to look for the login line:

```
2017-07-09T04:11:30.210522-04:00 imap24 sloti24t04/imapmail[3609860]: login: frontend1.nyi.internal [10.202.2.160] user@example.com plaintext User logged in SESSIONID=<sloti24t04-3609860-1499587890-1-3981128444319948130>
```

and then match the two lines by process ID.

If the client id logline included the SESSIONID it'd be much easier to connect these lines (and any other activity from that connection).

**Comment by elliefm** [comment]
In master as of b871067a5c2742753fe0101a41babe7df9bb83a0

**Comment by elliefm** [comment]
cherry-picked this to 3.0 too cause it's low impact and seems pretty useful

**Comment by falon** [comment]
Hello, for better log representation I could suggest something like

```
syslog(LOG_INFO, "sessionid=<%s> client id:%s", session_id(), buf_cstring(&logbuf));
```
or better:
```
syslog(LOG_INFO, "sessionid=<%s> client_id=<%s>", session_id(), buf_cstring(&logbuf));
```
In a perfect world a uniformed representation such as spaces or commas separated `<field_name>=<value>` could be optimal, in particular for data analysis instruments...
