### ISSUE TITLE
Changes made by annotator via xrunannotator aren't immediately visible

### ISSUE THREAD

**Issue by robmueller** [cyrusimap/cyrus-imapd#2071]
The "xrunannotator" IMAP command allows you to run the annotator against specific messages. However it appears the changes made by the annotator aren't immediately visible, which is confusing our (FastMail) web code at the moment.

```
  . select inbox
  ...
  . uid fetch 6287 flags
  * 5612 FETCH (FLAGS (\Seen hasnotd hasnoatt) UID 6287)
  . OK Completed (0.000 sec)
  . uid xrunannotator 6287
  . OK Completed (0.006 sec)
  . uid fetch 6287 flags
  * 5612 FETCH (FLAGS (\Seen hasnotd hasnoatt) UID 6287)
  . OK Completed (0.001 sec)
  . unselect
  . OK Completed
  . select inbox
  ...
  . uid fetch 6287 flags
  * 5612 FETCH (FLAGS (\Seen $X-ME-Annot-2) UID 6287)
  . OK Completed (0.001 sec)

```
As you can see, we run the annotator on a message, but nothing appears to change, but if I unselect + re-select the mailbox, the new flags do appear.

**Comment by brong** [comment]
Partha - can you please look at this and see if XRUNANNOTATOR isn't bumping MODSEQ or something else silly.

**Comment by ajaysusarla** [comment]
On doing a quick test on master, this is what I found:
```
=====> Cyrus::Annotator[239] Create Message A
=====> AnnotatorDaemon[112] annotate_message called
=====> AnnotatorDaemon[96] set_flag($X-ME-Annot-2)
=====> Cyrus::Annotator[255] 
C: 4 uid fetch 1 flags
S: * FLAGS (\Answered \Flagged \Draft \Deleted \Seen $X-ME-Annot-2)
S: * OK [PERMANENTFLAGS (\Answered \Flagged \Draft \Deleted \Seen $X-ME-Annot-2 \*)] Ok
S: * 1 EXISTS
S: * 1 RECENT
S: * 1 FETCH (FLAGS (\Recent $X-ME-Annot-2) UID 1)
```
Will talk to @robmueller to figure out if there is anything I'm missing.

**Comment by ajaysusarla** [comment]
Just an update. Thanks to Bron, I have a test to reproduce this issue. I'm working on the fix. As Bron already mentioned, `xrunannotator` isn't bumping `modseq`, which is the reason the flags aren't being shown.

**Comment by brong** [comment]
We worked together on this and fixed it by copying the code msgrec manipulation logic from index_store
