### ISSUE TITLE
assertion failure if trying to add/remove flags without permissions

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#2072]
2017-07-27T06:21:33.479229-04:00 imap22 sloti22d2t03/imapmail[463368]: Cannot notify event FlagsClear: missing parameters: flagNames
2017-07-27T06:21:33.483097-04:00 imap22 sloti22d2t03/master[979655]: process type:SERVICE name:imapmail path:/usr/cyrus/libexec/imapd age:5.470s pid:463368 signaled to death by signal 6 (Aborted, core dumped)

The underlying cause is this code in index.c:index_store()

            if (modified_flags.removed_flags) {
                if (flagsclear == NULL)
                    flagsclear = mboxevent_enqueue(EVENT_FLAGS_CLEAR, &mboxevents);

                mboxevent_add_flags(flagsclear, mailbox->flagname,
                                    modified_flags.removed_system_flags,
                                    modified_flags.removed_user_flags);
                mboxevent_extract_msgrecord(flagsclear, msgrec);
            }

The bug is that we're not actually extracting any flags there, causing flagNames not to be filled later in mboxevent.c.  This should be enough to build a testcase and track it down.  The underlying trigger was

tag store uid -flags \Seen

On a mailbox where the logged in user didn't have permission to setseen (at least I believe that's it from my debugging)

**Comment by rsto** [comment]
There must be more to this than bad permission handling: Any attempt in my Cassandane tests to set the `\Seen` flag on a mailbox as a user that doesn't have the `s` permissions set, fails appropriately with a `S: 7 NO Permission denied` error.

How could the logged in user even get this far into the codepath if the permission is missing?

I'm also not yet sure how to trigger this error. The codepath where this assert is located, is only called if we touch we index record. But in my Cassandane tests, I could only make this happen if the logged in user is also the owner of the mailbox. The admin user (or any other, for that matter) just clears the `\Seen` flag in their seen database, e.g. `conf/user/a/admin.seen`

We could easily replace the assert with an appropriate error handler, so not to crash. But I want to better understand how we even got the mess. it *could* be related to my msgrecord rewrite, but I'm not sure, yet.

**Comment by rsto** [comment]
Closing this one.

We are tracking a related issue internally. If it turns out to be a Cyrus upstream issue, we'll reopen or create a new issue that better reflects what's broken.
