### ISSUE TITLE
Docs: virtdomains defaults: release docs say userid, but actually off

### ISSUE THREAD

**Issue by nicolan** [cyrusimap/cyrus-imapd#2081]
From Stephan Lauffer on info-cyrus:
 
> This is a minor "problem"... just found it:
> 
> The Chapter "Updates to default configuration" from  
> https://www.cyrusimap.org/imap/download/release-notes/3.0/x/3.0.0.html  
> say:
> 
>    "virtdomains is now userid by default (was off)
> 
> Indeed virtdomains is still "off" by default.

Fix the 3.0.0 release notes (and possibly upgrade guide) to reflect that in all versions of 3.0 prior to know, virtdomains is still off. (and that there was an error in the docs previously).

**Comment by elliefm** [comment]
This documentation whoopsy was fixed in 07f36884cd

We have #2847 open for actually fixing the virtdomains setting (it's a big messy job, it'll probably require several major releases to step through)
