### ISSUE TITLE
httpd: meth_acl crashes with no principal

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#2084]
payload = {
      s = 0x173b2e0 "<?xml version=\"1.0\" encoding=\"utf-8\"?><D:acl xmlns:D=\"DAV:\"><D:ace><D:principal /><D:grant><D:privilege><D:all /></D:privilege>[...]

This causes

prin to remain blank, because there was no child ELEMENT.

3388	            for (child = ace->children; child; child = child->next) {
3389	                if (child->type == XML_ELEMENT_NODE) {
3390	                    if (!xmlStrcmp(child->name, BAD_CAST "principal")) {
3391	                        if (prin) {
3392	                            txn->error.desc = "Multiple principals in ACE\r\n";
3393	                            ret = HTTP_BAD_REQUEST;
3394	                            goto done;
3395	                        }
3396	
3397	                        for (prin = child->children; prin &&
(gdb) 
3398	                             prin->type != XML_ELEMENT_NODE; prin = prin->next);
[...]
3435	            if (!xmlStrcmp(prin->name, BAD_CAST "self")) {
3436	                userid = httpd_userid;
3437	            }

And then prin->name to be a NULL dereference crash.

**Comment by brong** [comment]
It would be good to start with a Cassandane test which reproduces the crash :)

**Comment by robn** [comment]
https://sentry.io/fastmail/cyrus/issues/325652619/

**Comment by ksmurchison** [comment]
Per RFC 3744 and Julian Reschke, the DAV:principal element in DAV:ace can NOT be empty.  Respond with 401

Fixed with https://github.com/cyrusimap/cyrus-imapd/commit/940a8a1f71eb1c2e1e2bd22c1907e452685eff08
