### ISSUE TITLE
Setting speicaluse on a folder to the same value is rejected

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#2086]
Unexpected use Sent on Sent
setmetadata failed Sent, /private/specialuse, \Sent: IMAP Command : 'setmetadata' failed. Response was : no - SPECIAL-USE flag conflict

....

There's some sanity code around setting specialuse which doesn't allow two folders to have the same specialuse value, or specialuse folders to be renamed as subfolders within a user (they must be top level) and doesn't allow specialuse folders to be deleted.

But it appears to be buggy in the slightly confused case of trying to set the same value again.  It wasn't an issue in this case because the code did a resync and noticed that it was already set - but it's annoying that we get an error.

This needs a cassandane test to prove the bug, then a fix in Cyrus :)

**Comment by ajaysusarla** [comment]
The fix for this is merged to master (c762711bcb13cd0d41590e456918963f39586764) and so is the Cassandane test.
