### ISSUE TITLE
docsrc/imap/developer/install-xapian.rst: state that unpatched Xapian can be used

### ISSUE THREAD

**Issue by dilyanpalauzov** [cyrusimap/cyrus-imapd#2090]
In `docsrc/imap/download/release-notes/3.0/x/3.0.0.rst` is written:

Major changes since the 2.5.x series
====================================

*   Optional Xapian_ integration for faster and shinier search. Note that this requires custom patches to Xapian, in this release. (See the ``search_engine`` option in :ref:`imapd.conf <imap-reference-manpages-configs-imapd.conf>`, and ``doc/README.xapian`` in the source distribution.)) Compiling Xapian support requires gcc 4.9 or later.

(has a bracket too much)

`docsrc/imap/download/release-notes/3.0/x/3.0.1.rst` states:

Changes Since 3.0.0
===================

Dependency changes
------------------

* Cyrus can now be built with Xapian 1.4 (the current upstream release), if CJK support is not required in your environment.  If you need CJK support, you will still need to use the cyruslibs Xapian fork.

So, since 3.0.1 vanilla Xapian can be used for non CJK-functionality.

But then `docsrc/imap/developer/install-xapian.rst` says "Before compiling Cyrus with the ``--enable-Xapian`` option, Xapian must first be patched and compiled."  The latter needs to reflect, that Xapian can also be integrated when unpatched.

**Comment by nicolan** [comment]
Fixed in 3.0 and master. Thanks for the report!
