### ISSUE TITLE
Clarify whether idled goes in START or DAEMON in cyrus.conf for 3.0

### ISSUE THREAD

**Issue by dilyanpalauzov** [cyrusimap/cyrus-imapd#2091]
In `cyrus-imap 2.5:docsrc/imap/admin/systemcommands/idled.rst` and `cyrus-imap 3.0:docsrc/imap/reference/manpages/systemcommands/idled.rst` suggests putting idled in the START section of cyrus.conf .

In cyrus-imap 3.0 doc/examples/cyrus_conf/* suggest putting idled in the DAEMON section.

Please clarify, whether for 3.0 idled is supposed to be in START or in DEAEMON and in the latter case, reflect the change in `docsrc/imap/download/upgrade.html`.

**Comment by nicolan** [comment]
@ksmurchison says it should be in DAEMON. I will update in all places.

**Comment by nicolan** [comment]
Updated in master and 3.0. Thanks!
