### ISSUE TITLE
backport sieve fixes to 3.0

### ISSUE THREAD

**Issue by dilyanpalauzov** [cyrusimap/cyrus-imapd#2092]
Please backport to 3.0:

738066a0d bc_eval.c: don't short-circuit BODY test and leak bodyparts
238a6a41d bc_eval.c: don't leak content_types array if we don't find matching bodyparts
f2990c6bc Fixed issue #1714: Sieve runtime failure on use of COUNT match without numeric comparator
1147e7fe7 bc_eval.c: properly handle null reverse-path

**Comment by ajaysusarla** [comment]
Won't be able to backport f2990c6bc2a04f31b4dd056b409dde24637927fe, since it depends on rewrite in master for script parsing. The other patches should be doable.

**Comment by ajaysusarla** [comment]
Backported:
* 0e7204add987a5d1172e57c4574c9ec511cd8f75 - bc_eval.c: properly handle null reverse-path
* 38e9f7ba6c1f3d8d598e37d353c13be585207667 - bc_eval.c: don't short-circuit BODY test and leak bodyparts
* 6ffecaa3e8338e09620fc5c32394235aabea131f - bc_eval.c: don't leak content_types array if we don't find matching bodyparts
