### ISSUE TITLE
doc example murder-frontend.conf with wrong proxyservers parameter

### ISSUE THREAD

**Issue by xinrag** [cyrusimap/cyrus-imapd#2099]
The example murder-frontend.conf contains a comment about proxyservers and a default/example for this parameter.

Poorly this is completely wrong in this configuration. Compared to the manpage...

"A  list  of  users  and  groups that are allowed to proxy for other users, separated by spaces.  Any user               listed in this will be allowed to login for any other user: use with caution.  In a standard murder  this               option should ONLY be set on backends.  DO NOT SET on frontends or things won't work properly."

The most important sentence is the last one... the last should be added to the example for the backend and the whole part of proxyservers removed from murder-frontend.conf .

See also: https://lists.andrew.cmu.edu/pipermail/cyrus-devel/2017-August/004127.html

**Comment by nicolan** [comment]
@postilion You wrote up the example config. I don't have enough knowledge to verify and correct. Any thoughts?

**Comment by xinrag** [comment]
...why not just remove the lines 29-34 (all the comments about proxyservers plus the config line "proxyservers: mailproxy"

**Comment by postilion** [comment]
@nicolan Sorry to have missed this for so long!  I was travelling when first posted.  @xinrag You are close to correct.  Actually lines 29-35 need removing, as lmtp_admins has no meaning to a frontend host.

This is fixed in PR #2205
