### ISSUE TITLE
'mkimap' not installed

### ISSUE THREAD

**Issue by surfermarty** [cyrusimap/cyrus-imapd#2130]
When doing a ‘make install’ the ‘mkimap’ utility isn’t installed, but the
document describing how to set up Cyrus references it.

I can work around this easily myself, but I'm guessing that it should be 'installed' somewhere by 'make install'.

Version 3.0.3 on SmartOS

**Comment by ajaysusarla** [comment]
`mkimap` is a developer tool and, as you might have already noticed, is only available in the `cyrus-imapd` source repository.
The installation instructions [here](https://www.cyrusimap.org/setup.html) are for those building from source in which case the tools directory is available. (Is there some place else you see `mkimap` being used?)

**Comment by dilyanpalauzov** [comment]
Can this case be closed?

**Comment by ajaysusarla** [comment]
yup! Thanks @dilyanpalauzov
