### ISSUE TITLE
Xapian - use conversations db to detect already-indexed GUIDs

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#2135]
At the moment Xapian opens all rest of the read-only databases when indexing so that it can check if a *G* key is already indexed and avoid re-indexing.

This is expensive in terms of IO on potentially slow drives, so it would be nice to avoid.

One possibility is to use conversations_guid_foreach with a cyrus.indexed.db lookup for the folder/uid pairs.

(cyrus.indexed.db also needs to be converted from indexing by folder name to indexing by folder uniqueid to handle folder renames - matching the user.seen behaviour)

Another optimisation would be to build a cached "merged cyrus.indexed.db" file in the writable tier, which contained the union of all the cyrus.indexed.db files for all the read-only databases.  This could also have a key for the list of covered databases, allowing it to be discarded if they change.  This would avoid having to do any reads at all from the lower tiers in the common case.

**Comment by rsto** [comment]
https://github.com/rsto/cyrus-imapd/commit/5d94a123941ba41e0438e4da1415aa9109dc880e contains a simplistic variant for this.

It keeps a cache of sequence sets per mailbox during the lifetime of the search update receiver. Whenever the current mailbox is rewritten, it purges the cache for the search update, causing potentially a read-from-disk after the mailbox updates have been flushed. Still, it's a start.

I haven't refactored indexed.db to story by uniqueid. With the current approach that wouldn't even be necessary. If we switch from mailbox name to uniqueid, I guess we need to address migrating from the key scheme. That could be done on the fly, even.

I plan to prototype the improvement with a merged indexed.db cache on high tier media. But that requires throwing out code from the existing code, so I need to take extra care doing that.

**Comment by brong** [comment]
My theory for caching was this very simple hack:

when opening the sequence set for tier:n (e.g. data:5), first look in
the front (writable) database's cyrus.indexed.db, as follows
(pseudocode):
user.xapianactive contains "temp:45 data:5 data:6 archive:1"

Open /tmpfs-cyrus/path/to/user/xapian.45/cyrus.indexed.db as 'indexdb'.
char *prefix = strconcat("#", tier, NULL);  // #data:5
if (cyrusdb_fetch(indexdb, prefix, ...) {
   // #data:5 key doesn't exist
   struct cyrusdb *thisdb = NULL;
   struct copy_to_indexdb_rock rock;
   rock.tier = tier;
   rock.indexdb = indexdb;
   cyrusdb_open(tier_to_indexdb_path(tier), &thisdb); //
   /mnt/search/data/path/to/user/xapian.5/cyrus.indexed.db   cyrusdb_foreach(thisdb, "", ..., &copy_to_indexdb, &rock);
   cyrusdb_store(thisdb, prefix, strlen(prefix), "", 0, &rock.txn);
   cyrusdb_commit(indexdb, rock.txn);
}

cyrusdb_fetch(indexdb, "#data:5#<mailboxname>", &data, &len);

// use data


...

int copy_to_indexdb(char *key, size_t keylen, char *data, size_t
datalen, void *rock){
    struct copy_to_indexdb_rock *crock = rock;

    if (!keylen) return 0;
    if (key[0] == '#') return 0;  // don't duplicate cache data
    from old DBs.
    struct buf newkey = BUF_INITIALIZER;
    buf_putc(&newkey, '#');
    buf_appendcstr(&newkey, crock->tier);
    buf_putc(&newkey, '#');
    buf_appendmap(&newkey, key, keylen);
    int r = cyrusdb_store(crock->indexdb, newkey.s, newkey.len, data,
    datalen, &crock->txn);  // #data:5#domain.com!user.foo    buf_free(&newkey);
    return r;
}

---

Does that all make sense?  The earlier cyrus.indexed.dbs are all
immutable, so we can copy data from them into the current indexed.db and
then store a key to say that we've done it.  From then on, we don't need
to open the other DBs any more, just read the keys from the cache
version.  And we don't need any more DBs to do it.
The if (key[0] == '#') test in the copy code means that when we store
this DB down, even though we keep the cyrus.indexed.db in the -o case
(just copy one DB), we don't wind up with multiple levels of # cache
being copied around.
On Tue, 19 Sep 2017, at 03:25, Robert Stepanek wrote:
> rsto/cyrus-imapd@5d94a12 contains a simplistic variant for this.


> It keeps a cache of sequence sets per mailbox during the lifetime of
> the search update receiver. Whenever the current mailbox is rewritten,
> it purges the cache for the search update, causing potentially a read-from-
> disk after the mailbox updates have been flushed. Still, it's a start.> I haven't refactored indexed.db to story by uniqueid. With the current
> approach that wouldn't even be necessary. If we switch from mailbox
> name to uniqueid, I guess we need to address migrating from the key
> scheme. That could be done on the fly, even.> I plan to prototype the improvement with a merged indexed.db cache on
> high tier media. But that requires throwing out code from the existing
> code, so I need to take extra care doing that.> — You are receiving this because you were assigned. Reply to this
> email directly, view it on GitHub[1], or mute the thread[2].> 

--
  Bron Gondwana, CEO, FastMail Pty Ltd
  brong@fastmailteam.com



Links:

  1. https://github.com/cyrusimap/cyrus-imapd/issues/2135#issuecomment-330293993

**Comment by rsto** [comment]
I've updated the prototype for this: https://github.com/rsto/cyrus-imapd/compare/search_guid_index

It caches on two levels, one resulting in increased disk (or tmpfs) usage of the top search tier, the other in increased memory:

First, whenever squatter starts incremental indexing, it pulls in all search tiers that aren't cached into the top-tier indexed.db. It does so eagerly, that is, it copies *all* (non-cache) entries of unmerged databases. Alternatively, it could just pull in on-demand by mailbox name, but that might result in more IO.

Secondly, whenever a parsed and merged sequence set for a mailbox is requested during indexing, it only parses the sequence sets once. These parsed sequence sets can't change (except the currently indexed mailbox) are cached in a hash table. This second optimisation is an effect of looking across mailbox boundaries by GUID if a message needs to be indexed.

What's missing is to throw away the cache entries during tier compression. I deliberately postponed until we decide to continue with the current design (or implement another).

**Comment by rsto** [comment]
Merged https://github.com/rsto/cyrus-imapd/commit/0a5b4d86453648e220d4e04c23fb5b9c2df82757 and created a follow-up issue for mailbox unique id: https://github.com/cyrusimap/cyrus-imapd/issues/2174
