### ISSUE TITLE
reconstruct usage: -V

### ISSUE THREAD

**Issue by dilyanpalauzov** [cyrusimap/cyrus-imapd#2141]
./reconstruct -h does not mention "-V", neither does the synopsis at https://www.cyrusimap.org/imap/reference/manpages/systemcommands/reconstruct.html .

**Comment by ajaysusarla** [comment]
Thanks for reporting this. The commit 60c74929e10f9bf3f1491d38aa7c71200eae6a76 fixes this issue.

**Comment by dilyanpalauzov** [comment]
In imap/cyrdump.c:usage() the parameter 'name' seems to be unused.

The top of reconstruct.rst leaves the impression, that -V is supposed to be used without version parameter.

**Comment by ajaysusarla** [comment]
Thanks @dilyanpalauzov - I've fixed those issues now.
