### ISSUE TITLE
Redact Authorization header in httpd telemetry

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#2145]
When telemetry logging, the full Authorization header is written (at least for JMAP).

We redact the password in imapd logging, and should do the same when logging http request headers if it's not too hard.

**Comment by rsto** [comment]
That should be easy to do, if I remember my HTTP auth code correctly. I'll look at it tomorrow.

**Comment by ksmurchison** [comment]
The telemetry happens in the prot layer, so it a level below the HTTP auth code.  We will probably have to add a telemetry callback that can process HTTP headers
