### ISSUE TITLE
Leading [ stripped from subjects in snippet responses

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#2167]
See https://github.com/brong/cassandane/commits/subjectsnippet for a test which proves this.

Please figure out why the leading [ is being stripped and stop that for subjects - subjects should always be the full subject line, or at least include the start if they're stupidly long. This is a fairly short example subject - the rest of the line appears.

**Comment by rsto** [comment]
It's the Xapian snippet generator that strips off the starting bracket. I'll have to understand why it does that, most probably I'll add a flag that we can set for SUBJECT message parts during snippet generation.

**Comment by brong** [comment]
Yep, something like that sounds like a plan :)


On Thu, 28 Sep 2017, at 17:44, Robert Stepanek wrote:
> It's the Xapian snippet generator that strips off the starting
> bracket. I'll have to understand why it does that, most probably I'll
> add a flag that we can set for SUBJECT message parts during snippet
> generation.> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].> 

--
  Bron Gondwana, CEO, FastMail Pty Ltd
  brong@fastmailteam.com



Links:

  1. https://github.com/cyrusimap/cyrus-imapd/issues/2167#issuecomment-332755694

**Comment by rsto** [comment]
Caveat: this needs a rebuild of cyruslibs/xapian in addition to the Cyrus build.
