### ISSUE TITLE
JMAPMail: anchor position isn't calculated correctly in large list

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#2170]
There's a test in:

https://github.com/brong/cassandane/tree/anchor

Which shows the bug - in a long list, the 'position' in the response should be the position in the full list where the response starts, but the anchor calculation is instead finding a much earlier number.

**Comment by rsto** [comment]
Fixed with https://github.com/cyrusimap/cyrus-imapd/commit/d54eb7a3d3609f477a3f3c16a13a96b46cc20b27
