### ISSUE TITLE
FR: pass current username to sendmail command

### ISSUE THREAD

**Issue by robn** [cyrusimap/cyrus-imapd#2175]
It would be useful for us to know which user Cyrus is sending mail on behalf of when calling the sendmail command (Sieve reject/forward/vacation). Then we could add authentication information.

Probably the least invasive would be a `CYRUS_SENDMAIL_FROM` (or something) environment variable. The default `/usr/lib/sendmail` won't care, but I can write a wrapper that looks for it and does the right thing if that's what I want.

**Comment by rsto** [comment]
For JMAP, we recently added support to talk to a SMTP host (rather than forking into a sendmail executable): https://github.com/cyrusimap/cyrus-imapd/commit/34b5ec47ef09f82172234c1ae5f07d4bbc7b979b

Any preferences, how should we pass the user id via SMTP?

**Comment by robn** [comment]
Not totally sure to be honest, because its going to depend on how people have their MTA set up.

* Easiest way is to put the username in the envelope-from (`MAIL FROM:`) but there might be considerations around where bounces go.
* Authenticating as the user might be good, but realistically that means a shared password or a username/password lookup (with cleartext stored passwords available). At FM we'd use a shared or dummy password, but not every site will have that kind of control.
* Passing the pre-authenticated user along with the envelope-from (`AUTH=`, [RFC4954 section 5](https://tools.ietf.org/html/rfc4954#section-5)) would give the most flexibility (separate envelope sender, no authentication). That's not widely supported by MTAs though (FM has a local patch to support it internally).

If you did `AUTH=` it would work at FM with no further config necessary and shouldn't break anyone else, so if you just want to do the simplest thing, do that.

**Comment by rsto** [comment]
@ksmurchison I can add AUTH SMTP extension support to JMAP. But looking at the Sieve code, I'm not sure how to identify the user the sieve scripts are acting upon?

**Comment by ksmurchison** [comment]
sieve_interp_t includes the interp_context field.  lmtpd.c sets this to a pointer to a structure whose field is the userid of the owner of the mailbox that the sieve script is running against.

**Comment by rsto** [comment]
I created two patches for this, one covering the sieve/CalDAV relevant parts and the other JMAP.

@ksmurchison could you please review https://github.com/rsto/cyrus-imapd/commit/d0e2b4ef7037ea3c626b5ad5409a3a3af1d510d9 ? 

the JMAP patch is at https://github.com/rsto/cyrus-imapd/commit/5bce318b09addbaf99b00b38d8f5f44a242d1c8e

**Comment by ksmurchison** [comment]
The non-JMAP stuff looks ok.

**Comment by rsto** [comment]
Fixed in https://github.com/cyrusimap/cyrus-imapd/commit/293a460e618b5c9c8f5e32c461794d77ed19a4af
