### ISSUE TITLE
twoskip out of order when db has records with "." and "-" 

### ISSUE THREAD

**Issue by slimlv** [cyrusimap/cyrus-imapd#2180]
cyrus 2.5.11
simple test case:
* create plain-text file with content "test.plain"
  alta.net!user.bel       0 default bel@alta.net  lrswipkxtecda
  alta-test.net!user.bel  0 default bel@alta-test.net     lrswipkxtecda
* convert to maiboxes.db using `ctl_mboxlist -u -f /mailboxes.db <test.plain`
* run `cyr_dbtool /mailboxes.db twoskip consistent`:
DBERROR: twoskip out of order /dev/shm/new.db: alta-test.net!user.bel (00000150) <= alta.net!user.bel (000001E0)

cyr_dbtool /mailboxes.db twoskip dump:
```
HEADER: v=1 fl=0 num=2 sz=(00000268/00000150)
00000040 DUMMY kl=0 dl=0 lvl=31 ()
        000001E0 
        00000150 00000000 00000000 00000000 00000000 00000000 00000000 00000000 
        00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 
        00000000 00000000 00000000 00000000 00000000 00000000 00000000 00000000 
        00000000 00000000 00000000 00000000 00000000 00000000 00000000 
00000150 RECORD kl=22 dl=62 lvl=1 (alta-test.net!user.bel)
        00000000 
        00000000 
000001C8 COMMIT start=00000150
000001E0 RECORD kl=17 dl=57 lvl=1 (alta.net!user.bel)
        00000000 
        00000150 
00000250 COMMIT start=000001E0
```

**Comment by brong** [comment]
The problem is that you're using tools with two different sort orders because you have improved_mboxlist_sort turned on in ctl_mboxlist and not in cyr_dbtool.  It's a problem, but the bug isn't in twoskip directly, it's that sort order can be externally loaded in.

If I was doing it again, I'd put a flag in the header saying which sort algorithm the databased used rather than allowing them to be pluggable.

Bron.

**Comment by slimlv** [comment]
how to force cyr_dbtool to use proper settings from imapd.conf ?

**Comment by brong** [comment]
You can't, but you can pass -M if you're working on a database file
that's in mboxlist sort.  It's a low level tool with not many niceties.
Bron.


On Fri, 10 Nov 2017, at 20:01, Deniss Gaplevsky wrote:
> how to force cyr_dbtool to use proper settings from imapd.conf ?


> — You are receiving this because you commented. Reply to this email
> directly, view it on GitHub[1], or mute the thread[2].> 

--
  Bron Gondwana, CEO, FastMail Pty Ltd
  brong@fastmailteam.com



Links:

  1. https://github.com/cyrusimap/cyrus-imapd/issues/2180#issuecomment-343416147

**Comment by slimlv** [comment]
oh, I missed -M option. Thanks for pointing.
