### ISSUE TITLE
load dh_params from distinct file (easier to use with LE Certs)

### ISSUE THREAD

**Issue by MASHtm** [cyrusimap/cyrus-imapd#2186]
cyrus tries to load dh_params from the key or cert files. This makes using Let's Encrypt Certificates and dh_params quite difficult. It would be nice to have a configuration option to set a specific file.

I currently use a quick and dirty patch without option
```
--- cyrus-imapd-2.5.9/imap/tls.c.orig	2016-12-20 02:30:45.312786040 +0100
+++ cyrus-imapd-2.5.9/imap/tls.c	2017-09-26 23:35:31.013338517 +0200
@@ -327,7 +327,11 @@
     DH *ret=NULL;
     BIO *bio = NULL;
 
-    if (keyfile) bio = BIO_new_file(keyfile, "r");
+    const char *harddhfile = "/etc/cyrus_dhparam";
+
+    bio = BIO_new_file(harddhfile, "r");
+
+    if ((bio == NULL) && keyfile) bio = BIO_new_file(keyfile, "r");
 
     if ((bio == NULL) && certfile) bio = BIO_new_file(certfile,"r");
 
```

**Comment by elliefm** [comment]
What do you think of #2196?  I believe it should cherry-pick cleanly to 2.5 (with `-X ignore-all-space`), tls.c doesn't change very often.

**Comment by MASHtm** [comment]
hunk #4 for tls.c fails because dh_params is still dh_freeme in 2.5 tree
besides that it works as expected.

**Comment by ksmurchison** [comment]
Implemented with https://github.com/cyrusimap/cyrus-imapd/pull/2196
