### ISSUE TITLE
sieve vacation doesn't allow "mailbox-list" for :from parameter, naively just wraps value in <...>

### ISSUE THREAD

**Issue by robmueller** [cyrusimap/cyrus-imapd#2189]
https://tools.ietf.org/html/rfc5230#section-4.3

  A ":from" parameter may be used to specify an alternate address to
   use in the From field of vacation messages.  The string must specify
   a valid [RFC2822] mailbox-list.  Implementations SHOULD check the
   syntax and generate an error when a syntactically invalid ":from"
   parameter is specified.

mailbox-list    =       (mailbox *("," mailbox)) / obs-mbox-list
mailbox         =       name-addr / addr-spec
name-addr       =       [display-name] angle-addr
angle-addr      =       [CFWS] "<" addr-spec ">" [CFWS] / obs-angle-addr

So using a paramater of `:from "foo bar <foo@bar.com>"` should work, but in the cyrus code it does:

imap/lmtp_sieve.c
...
` buf_printf(&header, "From: <%s>\r\n", src->fromaddr);`

So it generates:

`From: <foo bar <foo@bar.com>>`

Which is of course completely wrong.

**Comment by brong** [comment]
I'll punt this one to you, Ken :)

**Comment by ksmurchison** [comment]
Should be fixed by https://github.com/cyrusimap/cyrus-imapd/commit/187dfb06e622bf4f769c027e6f4ba450a42121f1

**Comment by robmueller** [comment]
Is there a particular reason to wrap in <...> at all, rather than just putting the value in the header then? The RFC says:

Implementations SHOULD check the
   syntax and generate an error when a syntactically invalid ":from"
   parameter is specified.

Which we're definitely not doing. Do we consider that a bug?

**Comment by ksmurchison** [comment]
No particular reason other than that's what we've been doing forever.

The :from value is run through verify_address() which checks the address against the ABNF for mailbox-list (in addr.y).  I think this satisfies the SHOULD.
