### ISSUE TITLE
cyrus-imapd 3.0.4: segfault on xfer in mbname_localpart ()

### ISSUE THREAD

**Issue by xinrag** [cyrusimap/cyrus-imapd#2192]
Hello!

We tried to xfer a mailbox from a 3.0.4 to another 3.0.4 in a cyrus muder (all 3.0.4.)...

The bt...:

Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f07a2eb3950 in mbname_localpart () from /usr/lib64/libcyrus_imap.so.0.0.0
Missing separate debuginfos, use: zypper install glibc-debuginfo-2.22-8.4.x86_64 krb5-debuginfo-1.12.5-7.17.x86_64 libcom_err2-debuginfo-1.42.11-15.1.x86_64 libdb-4_8-debuginfo-4.8.30-33.16.x86_64 libgcc_s1-debuginfo-7.1.1+r248970-1.4.x86_64 libjansson4-debuginfo-2.7-6.3.x86_64 libkeyutils1-debuginfo-1.5.9-7.13.x86_64 libpcre1-debuginfo-8.41-3.1.x86_64 libpcreposix0-debuginfo-8.41-3.1.x86_64 libselinux1-debuginfo-2.5-4.17.x86_64 libsqlite3-0-debuginfo-3.8.10.2-10.2.x86_64 libstdc++6-debuginfo-7.1.1+r248970-1.4.x86_64 libwrap0-debuginfo-7.6-888.16.x86_64 libz1-debuginfo-1.2.8-13.15.x86_64
(gdb) bt
#0  0x00007f07a2eb3950 in mbname_localpart () from /usr/lib64/libcyrus_imap.so.0.0.0
#1  0x00000000004246a9 in xfer_addmbox ()
#2  0x00007f07a2eab5fb in find_cb () from /usr/lib64/libcyrus_imap.so.0.0.0
#3  0x00007f07a2bb61e6 in myforeach () from /usr/lib64/libcyrus.so.0.0.0
#4  0x00007f07a2ea950b in mboxlist_find_category () from /usr/lib64/libcyrus_imap.so.0.0.0
#5  0x00007f07a2ea9d8d in mboxlist_do_find () from /usr/lib64/libcyrus_imap.so.0.0.0
#6  0x00007f07a2eaef01 in mboxlist_findallmulti () from /usr/lib64/libcyrus_imap.so.0.0.0
#7  0x00007f07a2eaefa7 in mboxlist_findall () from /usr/lib64/libcyrus_imap.so.0.0.0
#8  0x0000000000416c51 in cmd_xfer ()
#9  0x0000000000428477 in cmdloop ()
#10 0x000000000042ce28 in service_main ()
#11 0x000000000041bee9 in main ()

Sidenote: It was possible to xfer an empty, just created mailbox with no mails and no subfolders in it.

**Comment by rsto** [comment]
Would you be able to reproduce this issue on a build with debugging symbols compiled in?

**Comment by xinrag** [comment]
ok... would you like to have a "bt full"?

(gdb) bt
#0  mbname_localpart (mbname=0x0) at imap/mboxname.c:1193                                                                                                                                                                                                                                                                                                  
#1  0x0000000000423789 in xfer_addmbox (data=0x7ffe7ddc18d0, rock=0x7ffe7ddc2840) at imap/imapd.c:11617                                                                                                                                                                                                                                                    
#2  0x00007f8eab807afb in find_cb (rockp=rockp@entry=0x7ffe7ddc26f0, key=<optimized out>, keylen=<optimized out>, data=data@entry=0x7f8ea65fb982 <error: Cannot access memory at address 0x7f8ea65fb982>, datalen=datalen@entry=82) at imap/mboxlist.c:2410                                                                                                
#3  0x00007f8eab514746 in myforeach (db=0x8c18c0, prefix=0x7ffe7ddc1e90 "user.zuo347", prefixlen=0, goodp=0x7f8eab807930 <find_p>, cb=0x7f8eab8079d0 <find_cb>, rock=0x7ffe7ddc26f0, tidptr=<optimized out>) at lib/cyrusdb_twoskip.c:1580                                                                                                                 
#4  0x00007f8eab805abb in mboxlist_find_category (rock=rock@entry=0x7ffe7ddc26f0, prefix=prefix@entry=0x7ffe7ddc1e90 "user.zuo347", len=len@entry=0) at imap/mboxlist.c:2685                                                                                                                                                                               
#5  0x00007f8eab8062fd in mboxlist_do_find (rock=rock@entry=0x7ffe7ddc26f0, patterns=patterns@entry=0x7ffe7ddc27b0) at imap/mboxlist.c:2873                                                                                                                                                                                                                
#6  0x00007f8eab80b231 in mboxlist_findallmulti (namespace=<optimized out>, namespace@entry=0x0, patterns=patterns@entry=0x7ffe7ddc27b0, isadmin=isadmin@entry=1, userid=userid@entry=0x0, auth_state=auth_state@entry=0x0, proc=proc@entry=0x423740 <xfer_addmbox>, rock=rock@entry=0x7ffe7ddc2840) at imap/mboxlist.c:2938                               
#7  0x00007f8eab80b2d7 in mboxlist_findall (namespace=namespace@entry=0x0, pattern=pattern@entry=0x8cae70 "user.zuo347", isadmin=isadmin@entry=1, userid=userid@entry=0x0, auth_state=auth_state@entry=0x0, proc=proc@entry=0x423740 <xfer_addmbox>, rock=rock@entry=0x7ffe7ddc2840) at imap/mboxlist.c:2951                                               
#8  0x0000000000416932 in cmd_xfer (tag=0x8c7a10 "7", name=0x8c8320 "user.zuo347", toserver=0x8c8830 "pmailfr-hx", topart=0x0) at imap/imapd.c:11677                                                                                                                                                                                                       
#9  0x0000000000427859 in cmdloop () at imap/imapd.c:2295                                                                                                                                                                                                                                                                                                  
#10 0x000000000042c398 in service_main (argc=<optimized out>, argv=<optimized out>, envp=envp@entry=0x7ffe7ddc5ab8) at imap/imapd.c:1000                                                                                                                                                                                                                   
#11 0x000000000041b21d in main (argc=<optimized out>, argv=<optimized out>, envp=0x7ffe7ddc5ab8) at master/service.c:634

**Comment by xinrag** [comment]
the "bt full"...

[gdb.txt](https://github.com/cyrusimap/cyrus-imapd/files/1446092/gdb.txt)

**Comment by rsto** [comment]
@xinrag I've pushed a fix to master and will wait for automated integration tests to greenlight the patch. If all is fine, I'll merge this into the 3.0 branch in the next hour. Are you able to rebuild from source and test?

**Comment by xinrag** [comment]
Thanks! Yes, I could patch our builds. :)

**Comment by rsto** [comment]
Great. Our tests went OK, I've cherry-picked this on the 3.0 branch.

**Comment by xinrag** [comment]
Perfect, fixed the problem here! :)
