### ISSUE TITLE
[3.0.4] typo in reconstruct report message (imap/mailbox.c)

### ISSUE THREAD

**Issue by xinrag** [cyrusimap/cyrus-imapd#2195]
Hello!

https://github.com/brong/cyrus-imapd/blob/master/imap/mailbox.c lines 6326 and 6335...:

Instead "Marking file as..." you mean "Marking file has...", nor?

**Comment by ajaysusarla** [comment]
Hello @xinrag Thanks for reporting. The message is "Marking file as..", suggesting that a specific mailbox has been marked as 'archive', so there is no typo.

Thanks!
