### ISSUE TITLE
moving mailboxes to other partitons in murder setup can lead missing entries in mailboxes.db

### ISSUE THREAD

**Issue by MichaelMenge** [cyrusimap/cyrus-imapd#2199]
Quoting my mail to the cyrus devel list on Sep 15. 2017
> 
> i discovered that my patch for bug #3862  (rollback db changes on mupdate failure),
> on the old cyrus bugtracker which was includes in cyrus-imapd 2.4.19, 2.5.8 and 3.0.0-beta2, 
> has a bug if a mailbox is moved to an other partition and a rollback is needed.
> 
> For the rollback my old patch did recreate the old entry and then delete the new entry.
> But in case of moving the mailbox to a other partition the oldname and newname are
> the same, so the mailbox will be deleted for the mailboxes.db
> Recovery form this error is tricky. Reconstruct (reconstruct -p oldpartiton "mailboxname")
> will fail because the mupdate master still has the entry the the mailbox.
> So you have to manually add the mailbox to the mailboxes.db on the backend,
> or delete the mailbox from the mailboxes.db on the mupdate master.
> 
> 
> Attached is a patch for 2.4.20 which will reverse the order, so the "new" mailbox is
> deleted first and then the old entry is recreated.

I was unable to upload the patch to github
but the mail and the attachmend can be found on the listarchive
https://lists.andrew.cmu.edu/pipermail/cyrus-devel/2017-September/004147.html

> 
> The same is needed for the other branches.

**Comment by elliefm** [comment]
Sorry for the delayed response, I've been away on medical leave for a while and am still easing back into it.  I've had your patch email pinned in my Inbox until I'm able to spend some time thinking about it -- hoping to get it reviewed/merged in the next week or so. :)

**Comment by elliefm** [comment]
Thanks for the patch, it's now on 2.4 and I've also forward ported it to the other branches :)
