### ISSUE TITLE
Reduce code duplication in JMAP code

### ISSUE THREAD

**Issue by rsto** [cyrusimap/cyrus-imapd#2215]
Now that both the JMAP spec and its Cyrus implementation are stabilising we should reduce redundant code.

Most of the JMAP methods are processed in order of

1. Validating the JSON format
2. Processing the method in a generic way (e.g. almost all getFooList commands following the same workflow).
3. Processing the method according to its specific object-type (this is the stage where the JMAP world is mapped onto the Cyrus APIs).

Stage 1 looks like the best first shot to remove redundancies. One solution I have in mind is to apply a schema (either custom-built or existing JSON schema mechanism), which need to properly handle back-references (`#foo`) anyways. The caveat is that the getFooList method filters are polymorph, so not any JSON schema might be appropriate.

Stage 2 would also be great, and the recent changes of the JMAP spec seem to have generalised almost all methods to a generic scheme. A JMAP code would then just be stage 3 probably implemented by a set of callbacks triggered by a generic processing layer for stages 1 and 2.

I guess with stages 1 and 2 rewritten we could throw away at least hundreds if not thousands of lines of code!

**Comment by ksmurchison** [comment]
@rsto I think we're pretty close to having most everything consolidated.  Should we close this?

**Comment by rsto** [comment]
Yes.  I kept this open as a reminder to refactor the handlers from the
Mail code. So I think we are done with this.
On Wed, Aug 29, 2018, at 05:12, Ken Murchison wrote:
> @rsto[1] I think we're pretty close to having most everything
> consolidated.  Should we close this?> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[2], or mute the thread[3].
Links:

  1. https://github.com/rsto
  2. https://github.com/cyrusimap/cyrus-imapd/issues/2215#issuecomment-416809645

**Comment by ksmurchison** [comment]
This is mostly done, except for filter parsing.
