### ISSUE TITLE
Japanese search highlighting doesn't get all the matching characters:

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#2217]
<1513319997<3 xsnippets ((INBOX 1108730345 (85007))) utf-8 FUZZY TEXT "<E5><88><A9><E3><81><AA><E6><83><85>" not folder "INBOX.Junk Mail
" not folder "INBOX.Trash" not folder "INBOX.Notes"
>1513319997>* SNIPPET "INBOX" 1108730345 85007 SUBJECT {34}
<E6><9D><A5><E5><9C><92><E6><99><82><E3><81><AB><E4><BE><BF><E5><88><A9><b><E3><81><AA></b><E6><83><85><E5><A0><B1>
* SNIPPET "INBOX" 1108730345 85007 LISTID {71}
<E6><9D><A5><E5><9C><92><E6><99><82><E3><81><AB><E4><BE><BF><E5><88><A9><b><E3><81><AA></b><E6><83><85><E5><A0><B1>...<E6><9D><A5><E5>
<9C><92><E6><99><82><E3><81><AB><E4><BE><BF><E5><88><A9><b><E3><81><AA></b><E6><83><85><E5><A0><B1>
* SNIPPET "INBOX" 1108730345 85007 BODY {181}
...<b><E3><81><AA></b><E6><83><85><E5><A0><B1> Helpful information for the park -- Bron Gondwana brong@brong.net ... class="v-GroupSumma
ry-title" style="text-transform:none"&gt;<E6><9D><A5><E5><9C><92><E6><99><82><E3><81><AB><E4><BE><BF><E5><88><A9><b><E3><81><AA></b>...
3 OK Completed (in 0.003 secs)

As you can see, the highlight is only on 来園時に便利**な**情報 and not the full search term 利な情.

**Comment by rsto** [comment]
`来園時に便利な情報` splits into the terms: `来　園　時に　便利　な　情報`, so the search term `利な情` actually starts at the second character of a two-character term.

The snippet starts from the first matching term within the search query, and that’s `な`. It could be a perfectly sane thing to update the snippet generator to start at `便利`, I just lack the knowledge if that actually would make more sense to a native speaker.

Update: we'll wait for the feedback from our native speaker contact.

**Comment by elliefm** [comment]
What do we do in English when a search for "k n r" matches the phrase "rock n roll"?

**Comment by brong** [comment]
It doesn't match.  Not if it's a phrase.  If it's words, then yes - the
'n' is the only word.  So that was me misunderstanding the word
boundaries when I copied I guess!  I wonder if that means that the
Japanese was actually searching three words, two of which weren't
complete or real words, and hence didn't match.  That would make sense,
and mean my bug is invalid :)
Bron.


On Mon, Dec 18, 2017, at 15:33, elliefm wrote:
> What do we do in English when a search for "k n r" matches the phrase
> "rock n roll"?> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].> 

--
  Bron Gondwana, CEO, FastMail Pty Ltd
  brong@fastmailteam.com



Links:

  1. https://github.com/cyrusimap/cyrus-imapd/issues/2217#issuecomment-352323708

**Comment by rsto** [comment]
I guess we can close this one?
