### ISSUE TITLE
Be lenient with double // in URLs

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#2228]
The Sailfish OS Jolla C phone has a bug where it inserts a second slash into URLs:

PUT https://USERNAME@SERVER/dav/addressbooks/user/USERNAME/Default//UID.vcf

It would seem reasonable to either parse that URL without objecting, or return a 307/308 to the canonical version.

**Comment by ksmurchison** [comment]
Its pretty trivial to parse this, but a few questions:
- Do we allow consecutive slashes anywhere in the URL?
- Do we allow more than 2 consecutive?
- Do we return the original URL in a multistatus or the rewritten one?  Not sure what a client would do with a mismatch.

**Comment by ksmurchison** [comment]
The other question would be, if a client is poor enough to use a double slash, would it know enough to follow a 307 redirect?

**Comment by ksmurchison** [comment]
Proposed patch.  Parses, but doesn't re-write.

[URL_multiple_slash.diff.txt](https://github.com/cyrusimap/cyrus-imapd/files/1607465/URL_multiple_slash.diff.txt)

**Comment by brong** [comment]
Looks good to me.
