### ISSUE TITLE
squatter: get rid of undocumented -c option

### ISSUE THREAD

**Issue by elliefm** [cyrusimap/cyrus-imapd#2242]
As far as I can tell, this existed mainly so that the Sphinx search engine could be handheld through its boot process, and also so that squatter would shut down when master does.  

Since the Sphinx engine is gone on master, and the shut down problem has been solved by the DAEMON section of cyrus.conf, we should be able to throw away the code supporting the `-c` option as well?

**Comment by dilyanpalauzov** [comment]
If sphinx search is gone on master,  this needs to be reflected in the 3.1 release notes.

**Comment by elliefm** [comment]
I've updated the release notes for the 3.1.4 tag, so this note will be included in future 3.1.x tags.
