### ISSUE TITLE
Date parser doesn't appear to handle FWS correctly

### ISSUE THREAD

**Issue by robmueller** [cyrusimap/cyrus-imapd#2247]
A user reported that certain emails always sorted as if they had the current date even though they had a valid Date header. Looking at the header I saw:

```
Date: Tue, 13  Jul  2010 09:13:42 -0700
```

Note that there's 2 spaces between 13 and Jul and between Jul and 2010. According to RF5322, this should be fine:

```
   date            =   day month year

   day             =   ([FWS] 1*2DIGIT FWS) / obs-day

   month           =   "Jan" / "Feb" / "Mar" / "Apr" /
                       "May" / "Jun" / "Jul" / "Aug" /
                       "Sep" / "Oct" / "Nov" / "Dec"

   year            =   (FWS 4*DIGIT FWS) / obs-year
```

There's arbitrary FWS after the day digits and before the year digits.

However a quick test suggests this isn't working correctly. I added emails with the following headers to a mailbox.

```
Date: Tue, 13  Jul  2010 09:13:42 -0700
Date: Tue, 13 Jul 2010 09:13:42 -0700
Date: Tue, 13 Jul 2010 08:13:42 -0700
Date: Tue, 13 Jul 2010 10:13:42 -0700
```

```
. fetch 1:* envelope
* 1 FETCH (ENVELOPE ("Tue, 13  Jul  2010 09:13:42 -0700" "foo" ((NIL NIL "foo" "bar.com")) ((NIL NIL "foo" "bar.com")) ((NIL NIL "foo" "bar.com")) NIL NIL NIL NIL NIL))
* 2 FETCH (ENVELOPE ("Tue, 13 Jul 2010 08:13:42 -0700" "foo" ((NIL NIL "foo" "bar.com")) ((NIL NIL "foo" "bar.com")) ((NIL NIL "foo" "bar.com")) NIL NIL NIL NIL NIL))
* 3 FETCH (ENVELOPE ("Tue, 13 Jul 2010 09:13:42 -0700" "foo" ((NIL NIL "foo" "bar.com")) ((NIL NIL "foo" "bar.com")) ((NIL NIL "foo" "bar.com")) NIL NIL NIL NIL NIL))
* 4 FETCH (ENVELOPE ("Tue, 13 Jul 2010 10:13:42 -0700" "foo" ((NIL NIL "foo" "bar.com")) ((NIL NIL "foo" "bar.com")) ((NIL NIL "foo" "bar.com")) NIL NIL NIL NIL NIL))
```
Performing a sort on date, I'd expect the result to be `2 1 3 4` (or `2 3 1 4`) but instead...
```
. sort (date) utf-8 all
* SORT 2 3 4 1
. OK Completed (4 msgs in 0.001 secs)
```
I'm guessing here that it's failing to parse the Date headers on id 1, and just using "now", so it sorts at the end.

**Comment by elliefm** [comment]
I've cooked up a cunit test for this which currently fails!  So I should have a fix shortly :)

```
  Test: parse_rfc822_fws ...FAILED
    1. ./cunit/times.testc:230  - CU_ASSERT_EQUAL(r=33,31=31)
    2. ./cunit/times.testc:236  - CU_ASSERT_EQUAL(r=33,31=31)
    3. ./cunit/times.testc:243  - CU_ASSERT_EQUAL(r=33,31=31)
```

Interestingly, the checks which seem to fail are the return status (expected r=31, got r=33), but the time_t seems to be correct.

**Comment by elliefm** [comment]
Oh, the "return status" is actually the number of bytes parsed, so my test was invalid.  Hmm.

**Comment by elliefm** [comment]
Okay we have library functions in lib/times.c that succeed at parsing a date like this, and those library functions have unit tests, but we don't seem to use them?

**Comment by elliefm** [comment]
Oh no, there it is, found it...

**Comment by elliefm** [comment]
```
  Test: rfc5322 ...FAILED
    1. ./cunit/times.testc:546  - CU_ASSERT_EQUAL(r=-1,33=33)
    2. ./cunit/times.testc:547  - CU_ASSERT_EQUAL(t=0,1497919778=1497919778)
```

Reproduced it, and properly this time I believe.

Turns out `time_from_rfc822()` supported fws here properly, but we no longer use that.  The newer `time_from_rfc5322()`, which we now use, contains a regression.
