### ISSUE TITLE
MailboxRights missing entries

### ISSUE THREAD

**Issue by wolfsage** [cyrusimap/cyrus-imapd#2256]
The spec (https://github.com/jmapio/jmap/blob/master/spec/mail/mailbox.mdown) lists MailboxRights as having:

    mayReadItems
    mayAddItems
    mayRemoveItems
    maySetSeen
    maySetKeywords
    mayCreateChild
    mayRename
    mayDelete
    maySubmit

but cyrus doesn't provide `maySetKeywords`, `maySetSeen`, or `maySubmit`.

I'm not sure if this is a bug or if the server is allowed to omit these...

**Comment by rsto** [comment]
Fixed in https://github.com/cyrusimap/cyrus-imapd/commit/172eb24f36c35bee75fc1924abfd2c34249d2e3a
