### ISSUE TITLE
Mailbox/set create response does not include properties (default/server-set)

### ISSUE THREAD

**Issue by wolfsage** [cyrusimap/cyrus-imapd#2258]
https://github.com/jmapio/jmap/blob/master/spec/jmap/api.mdown#set says, in the Response section:

````
created: String[Foo]|null A map of the creation id to an object containing any properties of the created Foo object that were not sent by the client. This includes all server-set properties (such as the id in most object types) and any properties that were omitted by the client and so set to a default by the server.
````

However the server only responds with the 'id' property.

**Comment by rsto** [comment]
That would degrade in the worst-case to the same effort as running a /get immediately following a /set, with all the I/O and server-side text body/attachment processing overhead involved.

Are there some properties that you are currently missing for a specific use-case?

**Comment by wolfsage** [comment]
Nope, but this does not follow the spec. I'm not sure how strictly we want to adhere....

**Comment by rsto** [comment]
> I'm not sure how strictly we want to adhere....

As much as possible. It's just, for this particular requirement I find the requirement

    [...] and any properties that were omitted by the client

odd. Does that mean we should return e.g. a text-rendering of a HTML body in a Email/set response, if the client just set the `htmlBody` property? Most of the JMAP properties come for free once we fetched the object from storage, or are cheap to produce. But some properties are quite expensive.

I'll raise this today in our weekly Cyrus developer chat. Feel free to join.

Cheers,
Robert

**Comment by rsto** [comment]
As discussed in the last Cyrus hangout, this is a no-fix, and we expect the JMAP spec to change on that topic soon.
