### ISSUE TITLE
Email/query returns ids: null rather than ids: [] for empty result set

### ISSUE THREAD

**Issue by robmueller** [cyrusimap/cyrus-imapd#2266]
From the JMAP spec on /query

ids: String[] The list of ids for each foo in the search results, starting at the index given by the position argument of this response, and continuing until it hits the end of the results or reaches the limit number of ids. If position is >= total, this MUST be the empty list.

This is an array of strings, but it appears cyrus is returning null if the query returns an empty set.

**Comment by rsto** [comment]
Fixed with https://github.com/cyrusimap/cyrus-imapd/commit/c818b8d86cefb13b186b564feb649d113740b181
