### ISSUE TITLE
Segfaults in squatter due to code error in imap/xapian_wrap.cpp

### ISSUE THREAD

**Issue by jasontibbitts** [cyrusimap/cyrus-imapd#2267]
So for weeks I've been chasing some segfaults in squatter that are turned up in a cassandane run.  Outside of our build system they've been really difficult to reproduce.

The issue stems from this rather important compiler warning:
```
imap/xapian_wrap.cpp: In function 'int stem_version_set(Xapian::WritableDatabase*, int)'
imap/xapian_wrap.cpp:267:1: warning: no return statement in function returning non-void [-Wreturn-type]
```
There's a mailing list thread at  https://lists.fedoraproject.org/archives/list/devel@lists.fedoraproject.org/thread/YRPTEF6Z45YXBUH7QCBT3I5IK4FISHZN/#YRPTEF6Z45YXBUH7QCBT3I5IK4FISHZN but basically this code goes well into undefined behavior territory and while it used to work, it now (with recent Fedora rawhide that has gcc 8 and glibc 2.27 among other really new things) causes segfaults in the stack unwinding code down in libgcc.  Naturally that makes it look like a bug somewhere other than the cyrus code, but it does seem that this is really a cyrus bug.

Here's the info from GCC developer Jakub Jelinek explaining the issue (formatted to look reasonable in markdown):

> Ok, so the problem is ignoring important warnings, in this case:
> ```
> imap/xapian_wrap.cpp: In function 'int stem_version_set(Xapian::WritableDatabase*, int)':
> imap/xapian_wrap.cpp:267:1: warning: no return statement in function returning non-void [-Wreturn-type]
> ```
> Don't do that, especially not for C++.  While for C there is UB only if you
> actually use the returned value that hasn't been returned, i.e. in the
> caller, and if you never use the return value, nothing bad happens,
> in C++ the UB happens already in the callee, so the compiler in:
> 
>     static int stem_version_set(Xapian::WritableDatabase *database, int version)
>     {
>         std::ostringstream convert;
>         convert << version;
>         database->set_metadata(XAPIAN_STEM_VERSION_KEY, convert.str());
>     }
>
> can (and does) assume that if this function is called, then it will never
> fall-through from the last call into following code, because that is UB,
> even when the caller is doing just:
>
>     stem_version_set(dbw->database, dbw->stem_version);
>
> Didn't have time to try that, but I think ```-fsanitize=undefined``` should have
> diagnosed that too in addition to the warning.  And the effect in the
> generated code is just that there is no edge from that set_metdata method
> call to anything that follows it, so the call is followed by whatever other
> code happened to be emitted next, in this case some C++ EH code that ends
> with _Unwind_Resume and assumed it is invoked only when throwing or
> rethrowing an exception.
>
> So, effective summary, in C++ >>NEVER<< ignore -Wreturn-type warning.
>
>  Jakub

**Comment by rsto** [comment]
This was fixed on master but apparently never made it back to the stable branch.

I just pushed https://github.com/cyrusimap/cyrus-imapd/commit/24af24aa77144e0c1ab976657833b470502be7a8 to the 3.0 branch.

@jasontibbitts could you please check if this solves the issue? I didn't get the warnings using g++ 6.3.0.

**Comment by jasontibbitts** [comment]
Yes, this appears to fix that issue for me.

**Comment by rsto** [comment]
cool. closing this now. thanks for reporting this.

**Comment by elliefm** [comment]
I never got a warning for this (before applying the fix):

```
$touch imap/xapian_wrap.cpp
$make V=1 imap/imap_libcyrus_imap_la-xapian_wrap.lo
/bin/bash ./libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I.  -I./com_err/et -I. -I./lib -I. -I./lib -DLIBEXEC_DIR=\"/dev/shm/cyrus/main/libexec\" -DSBIN_DIR=\"/dev/shm/cyrus/main/sbin\" -DSYSCONF_DIR=\"/etc\" -DHAVE_CONFIG_H      -I/usr/include/libxml2  -I/usr/local/libical/include       -I/usr/local/xapian/include/xapian-1.5 -g -O2 -MT imap/imap_libcyrus_imap_la-xapian_wrap.lo -MD -MP -MF imap/.deps/imap_libcyrus_imap_la-xapian_wrap.Tpo -c -o imap/imap_libcyrus_imap_la-xapian_wrap.lo `test -f 'imap/xapian_wrap.cpp' || echo './'`imap/xapian_wrap.cpp
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I./com_err/et -I. -I./lib -I. -I./lib -DLIBEXEC_DIR=\"/dev/shm/cyrus/main/libexec\" -DSBIN_DIR=\"/dev/shm/cyrus/main/sbin\" -DSYSCONF_DIR=\"/etc\" -DHAVE_CONFIG_H -I/usr/include/libxml2 -I/usr/local/libical/include -I/usr/local/xapian/include/xapian-1.5 -g -O2 -MT imap/imap_libcyrus_imap_la-xapian_wrap.lo -MD -MP -MF imap/.deps/imap_libcyrus_imap_la-xapian_wrap.Tpo -c imap/xapian_wrap.cpp  -fPIC -DPIC -o imap/.libs/imap_libcyrus_imap_la-xapian_wrap.o
mv -f imap/.deps/imap_libcyrus_imap_la-xapian_wrap.Tpo imap/.deps/imap_libcyrus_imap_la-xapian_wrap.Plo
```

I'm looking in that and I guess I don't have any extra warnings turned on for C++ (but I would've thought a warning of this importance level would be an on-by-default??)

But, I've just added this to my build script, and now I do get that warning (and a bunch of extras, whee):

```
+    CXXFLAGS="-g -O0 -Wall -Wextra -Werror $CXXFLAGS" \
```

So, that's good to know

**Comment by jasontibbitts** [comment]
I can tell you that Fedora passes a big pile of flags by default:
```
CFLAGS='-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -mcet -fcf-protection
```
not to mention the things that come in via specs. We want maximum noise in our build logs.

**Comment by elliefm** [comment]
CFLAGS isn't used(?) by c++ builds, which is where I got tripped up as well --  I already have a lot of stuff turned on in CFLAGS but it doesn't affect the xapian wrapper because it's c++, not c.  Hence needing to add CXXFLAGS too

**Comment by elliefm** [comment]
Cherry-picking 8c599bc3a from the master branch has sorted out the rest of the warnings, woot

**Comment by jasontibbitts** [comment]
Actually we set CXXFLAGS identically to CFLAGS.  (And we set FFLAGS and FCFLAGS to something quite similar, and LDFLAGS is `-Wl,-z,relro  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld`.
