### ISSUE TITLE
Mailbox/set create: invalid form (non-string) for parentId is ignored

### ISSUE THREAD

**Issue by wolfsage** [cyrusimap/cyrus-imapd#2278]
If you try to create a mailbox with, for example, `parentId: ["foo"]` (instead of `parentId: "foo"`), the create will succeed and the bad `parentId` is ignored.

**Comment by rsto** [comment]
Can't reproduce, could you please dump the request/response you are making on latest Cyrus master?

    {
        "methodCalls": [
            [
                "Mailbox/set",
                {
                    "create": {
                        "1": {
                            "name": "foo",
                            "parentId": [
                                "foo"
                            ],
                            "role": null
                        }
                    }
                },
                "R1"
            ]
        ],
        "using": [
            "ietf:jmapmail"
        ]
    }

    {
      "methodResponses": [
        [
          "Mailbox/set",
          {
            "accountId": "cassandane",
            "oldState": "20",
            "notCreated": {
              "1": {
                "type": "invalidProperties",
                "properties": [
                  "parentId"
                ]
              }
            },
            "newState": "20"
          },
          "R1"
        ]
      ]
    }

**Comment by wolfsage** [comment]
Apologies, you are correct. There is no bug here. My serializer did something I did not expect. In the future I will examine/include raw requests/responses
