### ISSUE TITLE
Small memory leak in SELECT / SEARCH code

### ISSUE THREAD

**Issue by robmueller** [cyrusimap/cyrus-imapd#2280]
Bron noticed an imapd process over 5G in size on one of our servers. It appears to be a very long lived process connected to some client with some "smart mailbox" type functionality. The client wakes up regularly, and then does a select, a large bunch of searches, another select, a large bunch of searches, etc until it's completed it's list and goes to sleep for a while. Rinse and repeat over and over for many days.

My account currently has about 50 messages in the INBOX and 1700 message in the Trash. Running the loop below on my account appears to show a small but continuous memory leak on the imapd process (only about 30 kb per 10000 iterations)

```
for (1..1000000) {
  $m->select("INBOX") || die $@;
  $m->search(qw(charset utf-8 ALL UNSEEN)) || die $@;
  $m->select("Trash") || die $@;
  $m->search(qw(charset utf-8 ALL SUBJECT foobarbaz)) || die $@;
}
```
If I remove the selects and just have searches, the leak seems to stop (I think). If I remove the searches and just have selects, the leak seems to stop (I think). Strange. Not sure what's actually leaking, but would be good to track down and fix.

**Comment by brong** [comment]
Just tested by repeating that sequence and this leak is fixed :)
