### ISSUE TITLE
ptloader: canonification should work across multiple domains

### ISSUE THREAD

**Issue by tpokorra** [cyrusimap/cyrus-imapd#2282]
Currently the ptloader expects the user to connect with a full e-mail address. If the user connects just with the UID, ptloader does not know which domain the user belongs to.

The solution in the pull request attached with this bug is: if there is no @ character in the canon_id, then collect all domains available from LDAP, and query each domain for the user with that UID. base will be set to that domain where the user exists.

**Comment by elliefm** [comment]
I've just cherry-picked this across to the 3.0 branch too, it's very useful.
