### ISSUE TITLE
Email/queryChanges returns too many added emails in some cases

### ISSUE THREAD

**Issue by robmueller** [cyrusimap/cyrus-imapd#2294]
The script below reproduces this problem, assuming $j is a Mail::JMAPTalk object. Set $a and $m as appropriate for your test account.

The general sequence in the code is:
1. delete all messages in a mailbox
2. create 2 new messages
3. get an id list via Email/query, shows 2 id's as expected
4. mark a message as read
5. create a new message
6. get an update via Email/queryChanges from the state as at step 3 above

This shows two "added" entries rather than one.

```
ids: $VAR1 = [
          'M92676d97f809dc3e9b74589e',
          'M0fc51267bce3a387295eb1f9'
        ];
$VAR1 = [
          [
            'Email/queryChanges',
            {
              'total' => 3,
              'oldState' => '18695',
              'sort' => [
                          {
                            'isAscending' => bless( do{\(my $o = 0)}, 'JSON::XS::Boolean' ),
                            'property' => 'receivedAt'
                          }
                        ],
              'removed' => [],
              'newState' => '18698',
              'upToId' => undef,
              'accountId' => 'test1@robmtest.vm',
              'filter' => {
                            'inMailbox' => '1bfc127d-a1e6-44f6-8a4c-fa4c6bed6efb'
                          },
              'added' => [
                           {
                             'id' => 'M92676d97f809dc3e9b74589e',
                             'index' => 0
                           },
                           {
                             'index' => 2,
                             'id' => 'Mc9fe60a1b2625be91047ed59'
                           }
                         ]
            },
            'e1'
          ]
        ];

```

```
my $a = q{test1@robmtest.vm};
my $m = "1bfc127d-a1e6-44f6-8a4c-fa4c6bed6efb";

# Remove existing messages
my @r = $j->CallMethods([
  [ "Email/query", { accountId => $a, filter => { inMailbox => $m } }, "e1" ],
  [ "Email/set", { accountId => $a, "#destroy" => { name => "Email/query", resultOf => "e1", path => "/ids" } }, "d1" ]
]);

my $e = {
  mailboxIds => { $m => JSON::true },
  from => [ { email => q{test1@robmtest.vm}, name => q{} } ],
  to => [ { email => q{foo@bar.com}, name => q{} } ]
};

# Add 2 emails
@r = $j->CallMethods([
  [ "Email/set", { accountId => $a, create => { k1 => $e, k2 => $e } }, "c1" ]
]);
my $mid = $r[0]->[0]->[1]->{created}->{k1}->{id};

# Get message list
@r = $j->CallMethods([
  [ "Email/query", { accountId => $a, filter => { inMailbox => $m }, sort => [ { property => "receivedAt", isAscending => JSON::false } ] }, "e1" ],
]);
my $s = $r[0]->[0]->[1]->{state};
warn "ids: " . Dumper($r[0]->[0]->[1]->{ids});

# Mark an email read
@r = $j->CallMethods([
  [ "Email/set", { accountId => $a, update => { $mid => { "keywords/\$seen" => JSON::true } } }, "u1" ]
]);

# Create another email
@r = $j->CallMethods([
  [ "Email/set", { accountId => $a, create => { k1 => $e } }, "c1" ]
]);

# Now get changes since message previous Email/query call
@r = $j->CallMethods([
  [ "Email/queryChanges", { accountId => $a, filter => { inMailbox => $m }, sort => [ { property => "receivedAt", isAscending => JSON::false } ], sinceState => $s }, "e1" ],
]);
print Dumper(@r);
```

**Comment by rsto** [comment]
Just to be sure: you don't think that the current result is correct? The `added` list contains all items that have been added to the result list since the last state. It's not just newly added items. E.g. marking the message as read bumps its modseq, so it get "re-added" to the result list.

**Comment by robmueller** [comment]
I'm pretty sure this isn't right.

http://jmap.io/spec-core.html#/querychanges

If you look at the example, it should be able to splice out the removed items and add in the added items in the index positions to get the right result list, which definitely isn't what it's returning right now.

**Comment by neilj** [comment]
@rsto: @robmueller is correct. Let's talk about this in London, and I'll see what I can do to make the spec clearer. In this case the sort is only on an immutable property, and the search is on a property that we can treat as immutable because we store the mailbox data structure, so we should be able to give exact results:

`added: [{ id: "Mc9fe60a1b2625be91047ed59", index: 2 }], removed: []`

Now, if you don't have the data to know for sure nothing has moved position (for example, if the sort was based on seen status) then you may need to include extra items. But you must include them in BOTH removed and added, as the spec states.

**Comment by neilj** [comment]
See the algorithms for calculating this at http://jmap.io/server.html#email/querychanges

**Comment by robmueller** [comment]
Most of this (thought slightly different) should already have been implemented in the IMAP xconvmultisort command, so not sure if it's worth looking at that as a starting point.

**Comment by rsto** [comment]
The current Email/queryChanges implementation was written by brong, so I'm pretty sure it already follows the XCONVMULTISORT logic. The issue is that the same codebase is used for lots of other JMAP message search I'm assessing the impact of this code change, and if it's worthwhile to fix before we refactor the overall search code.

**Comment by rsto** [comment]
@robmueller I've updated the code to return both updated and newly created messages in the `removed` and `added` properties. That's not elegant, but consistent with the results if collapseThreads is enabled (which again uses another codepath in Cyrus and is done similar for XCONVMULTISORT).

In my understanding there is a critical piece in Cyrus missing for the concise result representation. I'll have to discuss this with brong.
