### ISSUE TITLE
Email/set textBody \n handling issues

### ISSUE THREAD

**Issue by robmueller** [cyrusimap/cyrus-imapd#2300]
In the current Email/set code you can set a textBody parameter. However it appears any LF's in the message become doubled up. e.g.

"textBody": "a\n\b\nc\n",

Results in an email with a text body of:

```
a<LF>
<LF>
b<LF>
<LF>
c<LF>
<LF>
```

Additionally, it appears raw LF's are sent to the smtp_host backend, as well as an extra CRLF before the . (END-OF-DATA marker) so you end up with this sent as the DATA portion of the SMTP transaction:

```
MIME-Version: 1.0<CRLF>
From: Test User <test1@robmtest.vm><CRLF>
...
Content-Type: text/plain;charset=UTF-8<CRLF>
<CRLF>
a<LF>
<LF>
b<LF>
<LF>
c<LF>
<LF>
<CRLF>
.<CRLF>
```

As I mentioned in the email, we should probably standardise things to using \n inside the JSON, but that means conversion is required when generating the email.

1. Decode the the JSON string value
2. If there's no LF on the end, add one
3. Remove any CR's (lone CR's are just going to create weird bugs)
4. When generating the email content, convert LF -> CRLF (cyrus stores IMAP emails with CRLF line endings) 
5. When sending via smtp_host, add a .CRLF to end the data, not CRLF.CRLF. Action (2) above should ensure this works correctly without adding a stray extra newline

Ditto in reverse, when generating the JSON

1. Read the section from disk
2. Apply any CTE decoding
3. Apply charset decoding
4. Convert CRLF -> LF
5. Remove any CR's
6. (implicit in generating the JSON string value, do JSON LF -> \n encoding)

Does this all sound right to you?

**Comment by rsto** [comment]
For the double LF characters I've pushed a fix to master, the split algorithm was bogus: https://github.com/cyrusimap/cyrus-imapd/commit/bceb13de72e13b802194ceb8adeefb2001d16aa3

It's tested here: https://github.com/cyrusimap/cassandane/commit/118d4b7668daa91e68f67a4e30575db124c1f869

Regarding step 5 in the JSON-to-text algorithm, I'm uncertain: RFC 5321 states in [section 4.5.2](https://tools.ietf.org/html/rfc5321#section-4.5.2)

    Without some provision for data transparency, the character sequence
   "<CRLF>.<CRLF>" ends the mail text and cannot be sent by the user.

And this is what the SMTP client implementation in Cyrus does: https://github.com/cyrusimap/cyrus-imapd/blob/master/imap/smtpclient.c#L472

This client is used by multiple modules within Cyrus, so the "magic" JSON to text conversion wouldn't apply there.

With the bogus LF characters fixed, is this actually still an issue? If the text body ends with a lone newline, it should be preserved, right?

**Comment by robmueller** [comment]
The problem is if you have a message of:

```
this is my message<CRLF>
```

Then when you add "<CRLF>.<CRLF>" you end up with:

```
this is my message<CRLF>
<CRLF>
.<CRLF>
```

The message now has an extra blank line on the end of it. Basically you shouldn't be adding the <CRLF> before the . if the message already ends in <CRLF>

Looking at the code, it doesn't appear that you've fixed step 4, the LF -> CRLF conversion when writing the actual email content? So currently your email headers use CRLF line endings, but the email content uses LF line endings.

And actually you've actually raised another issue here, line lengths. I see that writetext() is just breaking long lines. What we should be doing here is using quoted-printable transfer encoding and breaking long lines at 997 chars and adding "=<CRLF>" on the end. That way the lines are limited to 998 chars + 2 EOL chars at the RFC5322 level, but logically when decoded, they're arbitrary length. This is what the current web ui does and it works very well. It provides good interop, without users seeing random line breaks.

**Comment by rsto** [comment]
FYI - I've just pushed https://github.com/cyrusimap/cyrus-imapd/commit/c9faffef400ddb785e58112717ec81d5f7994a9e which implements the JMAP to MIME conversion. I'll rewriting the other way round probably only for the new Email object.

**Comment by robmueller** [comment]
Has all of this been fixed with the new Email object?

**Comment by rsto** [comment]
Not the MIME to JMAP part, yet.
