### ISSUE TITLE
2.5.11: Cannot import key for verifying release tarball with gpg

### ISSUE THREAD

**Issue by dusek** [cyrusimap/cyrus-imapd#2306]
Hi,

```
$ gpg --verify cyrus-imapd-2.5.11.tar.gz.sig 
gpg: assuming signed data in 'cyrus-imapd-2.5.11.tar.gz'
gpg: Signature made Tue May  9 05:23:40 2017 CEST
gpg:                using RSA key 554F04FEB36378E0
gpg: Can't check signature: No public key

$ gpg --keyserver pgp.mit.edu --recv-keys 554F04FEB36378E0
gpg: keyserver receive failed: No data

$ gpg --version
gpg (GnuPG) 2.2.5
libgcrypt 1.8.2
```

The .sig (and the corresponding .tar.gz) downloaded from the "Download via FTP" of the [Cyrus IMAP 2.5.11 Release Notes](https://www.cyrusimap.org/2.5/imap/release-notes/2.5/x/2.5.11.html).

How can one get the GPG key?

**Comment by elliefm** [comment]
Hi Boris,

Congratulations, you're the first person who's ever asked for a copy of the public key in as long as I've been doing releases! :)

I've just tried to add it to the MIT key-server but it's not currently working.  I'll try again in a few days, in case the Easter weekend has complicated things somehow.

In the meantime, here's the public key.

Cheers,

ellie

-----BEGIN PGP PUBLIC KEY BLOCK-----

mQENBFU5pZUBCAC+m05W9nJnBkrfFO9I+iimF1WCsSZNFoASJ3WEeZxIkOQO9BZj
aKf8EP/nK7nEfNGZ2m+OrAtQU/+I8Sk1ppHuwZgENLvRzLsBGbv80kDKBw31Nd1f
sCpVQs4b8zlohXjq0UN8tT5NcGJnGE7ahoOHzJk/0Ll76oVmOZvSw+WHBp1945m2
Q8CbIbfmyuv7NF6GtGDVilPeIPsDnh5w5usjpKsxjYHKpy6Rtf4MbcCLtkRbHFra
KJD+xum0PgPdCAEEbQsSXQgwOd0TZ59avRVVef674PjWqIuudUGUhJ/f9OWOj7LG
6QgJR6yvCy7Bc2eAN4RnIIzaUZGaJDKDCNozABEBAAG0ImVsbGllIHRpbW9uZXkg
PGVsbGllQGZhc3RtYWlsLmNvbT6JATgEEwECACIFAlU5pZUCGwMGCwkIBwMCBhUI
AgkKCwQWAgMBAh4BAheAAAoJEFVPBP6zY3jgb9gH/3GPDLGybo7SYZMtBmfe+Udf
tcRkTtH+o2pf2rh6KwPhhEDuOXWVCIUPWXsWIVU2K5Y8AdBIHOEoSUp3n8juV57I
u9CfDI718/WaHgEpYrq5DqyROAFr+sGahcb6C40+V/CeUSAmKVhFGniuALUSAQ+B
XVj/i2EAFNg/5ALkPYDnDYDqm7Ak6odDbktYQz987y38sg3EMC/2wi2EoOG1VWeG
twFD8HKmXZw+u6cYtFh9K1hOBZm+PhLHr3h1MHTuWYeBKkT3YqaGtXMwi704LlNr
HU8beOHSNBSsVYJ61B4kgBA7p+qnx6xIpU2KfAJl8cgjCYwrq8yo+Lm9TazagfM=
=dIwC
-----END PGP PUBLIC KEY BLOCK-----


On Mon, Apr 2, 2018, at 4:55 PM, Boris Dušek wrote:
> Hi,


> $ gpg --verify cyrus-imapd-2.5.11.tar.gz.sig 
gpg: assuming signed data in 'cyrus-imapd-2.5.11.tar.gz'
gpg: Signature made Tue May  9 05:23:40 2017 CEST
gpg:                using RSA key 554F04FEB36378E0
gpg: Can't check signature: No public key

$ gpg --keyserver pgp.mit.edu --recv-keys 554F04FEB36378E0
gpg: keyserver receive failed: No data

$ gpg --version
gpg (GnuPG) 2.2.5
libgcrypt 1.8.2

**Comment by dusek** [comment]
Thanks Ellie, with the help of the above key, I just verified the signature as being OK for 2.5.11.

**Comment by elliefm** [comment]
I've uploaded my public key to the MIT key-server successfully now, and I've checked and it looks like @ajaysusarla's public key is already in there. I've also updated our releasing documentation so that any future release person gets a prompt to upload theirs. So I think we're done here! :)
