### ISSUE TITLE
LIST command with RETURN METADATA "/.../uniqueid" very slow

### ISSUE THREAD

**Issue by robmueller** [cyrusimap/cyrus-imapd#2309]
In a JMAP world, we'll be using the folder UUID as the externally visible mailboxId. This means inside FastMail we'll need to store the UUID with each folder in the DB. I thought this would be easy to get via:

$IMAP->list("", "*", "return", [ "metadata", "/shared/vendor/cmu/cyrus-imapd/uniqueid" ]);

That works, but is VERY slow. Comparison on one of our biggest users with 10,000 folders:

```
$ perl -e '... use Time::HiRes qw(gettimeofday tv_interval); $s = [ gettimeofday ]; $m->list("", "*"); print tv_interval($s), "\n";'
0.843158
$ perl -e '... use Time::HiRes qw(gettimeofday tv_interval); $s = [ gettimeofday ]; $m->list("", "*", "return", [ "metadata", "/shared/vendor/cmu/cyrus-imapd/uniqueid" ]); print tv_interval($s), "\n";'
145.036163
```

I presume it's doing some open/close on each LIST item returned rather than holding a DB structure open from the start to the end of the LIST call.

Is this easy to fix?

If not, or alternatively, a better way of fixing this might be combining:

https://tools.ietf.org/html/rfc5819
https://datatracker.ietf.org/doc/draft-ietf-extra-imap-uniqueid/?include_text=1

To allow returning MAILBOXID as a status item during a LIST call.

**Comment by robmueller** [comment]
And just to confirm, I also checked:

```
$m->getmetadata("*", "/shared/vendor/cmu/cyrus-imapd/uniqueid");
```

And it's equally as slow as well.

**Comment by elliefm** [comment]
LIST looks like it's doing an `annotate_state_new()` / `annotate_state_abort()` pair for each mailbox (in `printmetadata()`) which on first glance seeems like the culprit.

But, GETMETADATA looks like it does a single `annotate_state_new()` / `annotate_state_abort()` pair for the entire array/pattern (in `cmd_getmetadata()`), yet is still slow, which contraindicates that.

@brong @ksmurchison is this one of those things you just know about off the top of your head?  I don't really know the annotations API at all, I'd need to do some profiling to get deeper into this.

**Comment by ksmurchison** [comment]
I'm not sure why there is a difference.  It could be by design or by accident.

**Comment by brong** [comment]
This got fixed.
