### ISSUE TITLE
JMAP downloads of top-level messages blobs is broken

### ISSUE THREAD

**Issue by robmueller** [cyrusimap/cyrus-imapd#2312]
Trying to download a known blobId appears to return a weird and rubbish result.

```
GET /jmap/download/robm_test@fastmail.fm/Ga0f823912c45481851ee4bc53b99408705b4162a/foo?... HTTP/1.1
User-Agent: curl/7.38.0
Host: 10....
Accept: */*
Authorization: Basic ...
```

```
HTTP/1.1 200 OK
Date: Thu, 12 Apr 2018 02:11:10 GMT
Vary: Accept-Encoding
Accept-Ranges: none
Content-Type: multipart/alternative; boundary="_----------=_1510806741399899391082"
Content-Disposition: attachment; filename="foo"
Content-Length: 0
```

Why is content-type "multipart/alternative"? This is an email blob, it should be message/rfc822.

Why is content-length 0?

A cassandane test so this core functionality doesn't get broken in the future would be nice as well :)

**Comment by robmueller** [comment]
Sorry, I didn't realise it was only top-level messages that were broken. That just happened to be the first thing I checked and just assumed all downloads were.

**Comment by rsto** [comment]
Tested in https://github.com/cyrusimap/cassandane/commit/8729b7e048071798becb85e6cf5481674fa9fb81

**Comment by rsto** [comment]
@robmueller No worries. Should be all fixed now.
