### ISSUE TITLE
Immutable properties in Mailbox/set update should throw invalidProperties if provided but don't match

### ISSUE THREAD

**Issue by wolfsage** [cyrusimap/cyrus-imapd#2314]
https://github.com/jmapio/jmap/blob/master/spec/jmap/api.mdown#set says:

````
Any server-set properties MAY be included in the patch if their value is identical to the current server value (before applying the patches to the object). Otherwise, the update MUST be rejected with an invalidProperties SetError.
````

It looks like Mailbox/set update ignores *all* immutable properties (but id) being passed in but wrong.

**Comment by wolfsage** [comment]
Test here: https://github.com/fastmail/JMAP-TestSuite/pull/15

**Comment by brong** [comment]
We can implement this, but it does have some cost because we need to fetch and calculate the value!

So we may want to deviate from the spec here and just ignore the value, assuming that it's always correct.

Maybe have an annotation which includes the parsed value?

**Comment by elliefm** [comment]
> We can implement this, but it does have some cost because we need to fetch and calculate the value!
> 
> So we may want to deviate from the spec here and just ignore the value, assuming that it's always correct.
> 
> Maybe have an annotation which includes the parsed value?

Do we want to/can we do something with this for 3.2?  Or shall I tag it back to master(3.1) and let it happen when it happens?

**Comment by rsto** [comment]
The server-set properties of Mailbox that we would need to check currently are:

- totalEmails
- unreadEmails
- totalThreads
- unreadThreads
- myRights

The first four come at the cost of reading from converstations.db, for myRights we need to look up the ACL. I guess we should be fine checking that without adding too much latency to the request.

I have no preference if this should go into 3.2 or not, though.
