### ISSUE TITLE
immutable properties in Mailbox/set create should be allowed if they match

### ISSUE THREAD

**Issue by wolfsage** [cyrusimap/cyrus-imapd#2315]
https://github.com/jmapio/jmap/blob/master/spec/jmap/api.mdown#set says:

````
invalidProperties: (create; update) The record given is invalid in some way. For example:

    [...]
    It contains a property that may only be set by the server (e.g. "id") and are different to the current value. Note, to allow clients to pass whole objects back, it is not an error to include a server-set property so long as the value is identical to the current value on the server (or the value that will be set by the server if a create).
````

To me this sounds like if I create a mailbox providing the proper myRights values and *counts values, the server should accept it, and error otherwise.

Tests here: https://github.com/fastmail/JMAP-TestSuite/pull/15/commits

**Comment by elliefm** [comment]
Mailbox/Set is one of the standardised JMAP features, so it would be really good to have this sorted out for 3.2. Is that reasonable in the next couple of weeks?

**Comment by rsto** [comment]
This issue description now is out of date. The published spec for [Foo/set](https://jmap.io/spec-core.html#set) states

> The client MUST omit any properties that may only be set by the server (for example, the id property on most object types).

I have added a Cassandane test that asserts this ([here](https://github.com/cyrusimap/cassandane/commit/ff894bb70f6595fd19c1a30c78ddfac8c70347a3)). That test did reveal a copy/paste error in the error message (fixed [here](https://github.com/cyrusimap/cyrus-imapd/commit/9b101bb6488d78583a42ace34b796cbc8e80cef5)).
