### ISSUE TITLE
mailbox/Set create doesn't provide errors for all bad myRights immutable values (or any unknown ones)

### ISSUE THREAD

**Issue by wolfsage** [cyrusimap/cyrus-imapd#2316]
If I try to pass in all myRights fields and provide values that don't match the defaults, cyrus responds with errors for only some of them.

The ones it does not provide values for:
````
            # Missing: 'myRights/mayCreateChild', 'myRights/maySetKeywords', 'myRights/maySetSeen', 'myRights/maySubmit'
````

Also it checks specific keys only. If I pass in junk keys it doesn't error/care. It should I believe?

**Comment by elliefm** [comment]
Mailbox/Set is one of the standardised JMAP features, so it would be really good to have this sorted out for 3.2.  Is that reasonable in the next couple of weeks?

**Comment by rsto** [comment]
We should fix that together with https://github.com/cyrusimap/cyrus-imapd/issues/2314
