### ISSUE TITLE
Audit use of EOF and eatline

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#2321]
Check this out:

. LIST 
. BAD Missing required argument to List
. LIST 
. BAD Missing required argument to List: reference name
* BAD Invalid tag

The second one was ". LIST ", with a trailing space.

The bug is this:

c = getlistargs();
eatline(imapd_in, c);

We're conflating the actual next character which was read (a space, or "\r" or something) with the error code.  The problem is in eatline:

EXPORTED void eatline(struct protstream *pin, int c)
{
    for (;;) {
        if (c == '\n') return;
        if (c == EOF) return;

We came in with EOF, so we don't wind up eating the line.  There's a couple of choices here, but we need to be really careful that what we feed in is the ACTUAL last character which was read, or we may fail to detect literals.

**Comment by elliefm** [comment]
Ahh, I see what you mean:

https://github.com/cyrusimap/cyrus-imapd/blob/9e20610e1603cd54861072f3910eef096c23b5a3/imap/imapd.c#L7752-L7760

```
    /* Read in reference name */
    c = getastring(imapd_in, imapd_out, &reference);
    if (c == EOF && !*reference.s) {
        prot_printf(imapd_out,
                    "%s BAD Missing required argument to List: reference name\r\n",
                    tag);
        eatline(imapd_in, c);
        return;
    }
```

The problem arises here, in getxstring:

https://github.com/cyrusimap/cyrus-imapd/blob/9e20610e1603cd54861072f3910eef096c23b5a3/imap/imapparse.c#L100-L109

```
    switch (c) {
    case EOF:
    case ' ':
    case '(':
    case ')':
    case '\r':
    case '\n':
        /* Invalid starting character */
        goto fail;

[...]

fail:
    buf_cstring(buf);
    if (c != EOF) prot_ungetc(c, pin);
    return EOF;
}
```

Note that the EOF return value is overloaded: it could mean "we actually reached EOF" or "we reached some other character that we don't like".  In the case of a real EOF, `eatline(..., EOF)` is legit.  But we can't tell the difference between a real EOF and a getxstring() parse error.

This is as far as I've looked so far, there might be more parts of imapparse.c that overload EOF like this?

**Comment by elliefm** [comment]
It looks like places that return EOF when EOF has not been reached yet are mostly unget'ing the actual character for the next read.

If that assumption holds consistently, then eatline() could maybe do something like:

```
  ...
  if (c == EOF) c = prot_getc(pin);
  if (c == '\n') return;
  if (c == EOF) return;
  /* see if it's a literal */
  ...
```

**Comment by elliefm** [comment]
There might be a faster way than calling `prot_getc(pin)` (perhaps checking `pin->eof`?) to avoid calling into the buffer fill routines when the protstream already knows that it's really at EOF.  But, I don't know what side effects might be there, whereas the proper protstream API is pretty robust.

**Comment by elliefm** [comment]
Here's a bad one:

https://github.com/cyrusimap/cyrus-imapd/blob/9e20610e1603cd54861072f3910eef096c23b5a3/imap/imapparse.c#L185-L186

**Comment by elliefm** [comment]
And another:
https://github.com/cyrusimap/cyrus-imapd/blob/9e20610e1603cd54861072f3910eef096c23b5a3/imap/imapparse.c#L210-L224

**Comment by elliefm** [comment]
Not sure about this one:

https://github.com/cyrusimap/cyrus-imapd/blob/9e20610e1603cd54861072f3910eef096c23b5a3/imap/imapparse.c#L398-L399

**Comment by elliefm** [comment]
I'm not really sure what to unget in these cases? They're all "slurp up a longer string, then check it as a whole" type deals.  We probably can't unget the entire string in most cases, or even necessarily "just the chunk from the bad byte onward"

Looking further, `get_search_annotation` and `get_search_return_opts` are both bad in a bunch of places.  And I've reached the end of imapparse.c

So there's some EOF returns to fix but not too terribly many

**Comment by ksmurchison** [comment]
Without digging into this just yet, my initial thoughts (having thought about this crap previously):
- We can certainly check s->eof (or write a prot_IS_EOF() macro)
- We can/should have a prot_peek() function to see what the next char is going to be to consolidate al of the getc/ungetc stuff
- We shoudn't be overloading EOF as both EOF and "we don't like this char".  We should have a different value for the latter(e.g. -2 or INT_MIN, or something else)

**Comment by ksmurchison** [comment]
I agree that its not necessary to unget() if we detected something bad if we're going to eatline() it anyways.  I think the only time that we want/need to unget() is in the case of peeking at the next char and determining that want to pass the stream in its current state off to something else.

**Comment by ksmurchison** [comment]
The referenced commit seems to catch most, if not, all of the troublesome spots: getxstring, getmodseq, parsecreateargs, parse_annotate_store_data, etc

**Comment by elliefm** [comment]
> We shoudn't be overloading EOF as both EOF and "we don't like this char". We should have a different value for the latter(e.g. -2 or INT_MIN, or something else)

I was thinking about this on Friday but I decided I didn't like it as an option, because it'd require auditing/rewriting the entire parser to take this new possibility into account, which is a massive scope creep from just making the current EOF handling consistent with the bits that already work :)

_If_ we were to rewrite the parser from scratch for some reason, I'd advocate for fundamentally separating "return status" and "the next byte is", but I can't imagine why we'd completely rewrite it!

**Comment by elliefm** [comment]
I think I've now fixed up the inconsistent EOF-without-unget cases that I identified last week (see referenced commits) from imapparse.c

Probably should check over imapd.c and make sure it doesn't have any of its own parsers hiding statically in there, while do that now...

**Comment by elliefm** [comment]
Okay, I think everything is nice and consistent now.  Can anyone see anything else that's been missed?

These commits have all cherry-picked cleanly to the 3.0 branch, so I'll probably include them in 3.0.6 too.

**Comment by elliefm** [comment]
These two calls to `eatline()` are bothering me -- they're passing an explicit `' '` (space) rather than the `c` value.  I guess this might once have been a rudimentary workaround for this same issue?  

https://github.com/cyrusimap/cyrus-imapd/blob/466fd314bb6c2a16df7869adf5d309fb10dab53f/imap/imapd.c#L5874-L5879

https://github.com/cyrusimap/cyrus-imapd/blob/466fd314bb6c2a16df7869adf5d309fb10dab53f/imap/imapd.c#L5962-L5966

I had a dig through history, and this particular usage dates back to 2000: a5ac7e5d3

Probably need to audit `eatline()` calls too (so far I've specifically focused on EOF returns).

**Comment by elliefm** [comment]
On further review, I think the getint parsers will need the same fix that getmodseq did, but what I'm gonna do is write some unit tests first to confirm my suspicion, and also verify as many as possible of my other fixes.

I really want to get these onto 3.0 but I'm not throwing untested code there and calling it stable! :)

**Comment by elliefm** [comment]
3.0.6 includes the eatline EOF fix (01ca38dd4521b0b65f62f7abafeb6c098b1481be) and the BAD STATUS sync loss fix (48dc27cc84cf154b4e3d6bea6e7175d9c965c362), but not the rest of the general improvements at this stage -- I don't trust them yet and still have more tests to write.

I still intend to have all the work relating to this issue backported to 3.0, but it's too new to just throw out there today.  But I also didn't want to keep delaying 3.0.6!

**Comment by elliefm** [comment]
NIL/NELLY/NILE parsing is now about as robust as we're going to get it, short of rewriting the guts of the protstream library to always have space for ungetc.

@murch I'd appreciate a second set of eyes on prot_peek() (currently unused) and prot_lookahead(), thanks :)

**Comment by elliefm** [comment]
NIL/NELLY/NILE parsing is now about as robust as we're going to get it, short of rewriting the guts of the protstream library to always have space for ungetc.

@ksmurchison I'd appreciate a second set of eyes on prot_peek() (currently unused) and prot_lookahead(), thanks :)

**Comment by brong** [comment]
Are we happy this all got done?  @elliefm I think all your work got merged.

**Comment by ksmurchison** [comment]
AFAICT its been fixed

**Comment by elliefm** [comment]
My work is all on master, but I think I'm holding this open until I trust it enough to fully backport to 3.0 (and/or decide that it's too intrusive to backport), but I haven't thought about it in a while, whoops!

**Comment by brong** [comment]
@elliefm I think this one is fine to close really, it's too invasive for 3.0 backport and it's clearly not a common problem!
