### ISSUE TITLE
Split the system_flags field in struct index_record

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#2331]
Right now, the system_flags field is a 32 bit field as follows:

typedef enum _MsgFlags {
    FLAG_ANSWERED           = (1<<0),
    FLAG_FLAGGED            = (1<<1),
    FLAG_DELETED            = (1<<2),
    FLAG_DRAFT              = (1<<3),
    FLAG_SEEN               = (1<<4),
    FLAG_SPLITCONVERSATION  = (1<<27),
    FLAG_NEEDS_CLEANUP      = (1<<28),
    FLAG_ARCHIVED           = (1<<29),
    FLAG_UNLINKED           = (1<<30),
    FLAG_EXPUNGED           = (1U<<31),
} MsgFlags;

The first 5 are the real system flags, the other 5 are internal bookkeeping.  In particular, FLAG_ARCHIVED and FLAG_UNLINKED have semantics about how the message is handled on disk.

Lots of code that manipulates system_flags has to remember about these different meanings.  It would make more sense to keep system_flags for just those first 5 again, and for the rest, create unsigned int foo:1 for each.

Those fields could be serialised and deserialised then in mailbox_buf_to_index_record and mailbox_index_record_to_buf without needing to handle the fact that they're stored in the same 32 bit field ANYWHERE ELSE in the code any more!

**Comment by ajaysusarla** [comment]
Fix is on master: https://github.com/cyrusimap/cyrus-imapd/commit/77246af0f3a47ffc04b541745fb3e7782c0ead08
