### ISSUE TITLE
Implement UNAUTH

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#2335]
draft-ietf-extra-imap-unauth provides an UNAUTHENTICATE command.  It's on track to become a standard.  Add support for this.

**Comment by ksmurchison** [comment]
Should we allow this command to be used by all users, or restrict it to admins only?

**Comment by ksmurchison** [comment]
Implemented with commit above.  Whether to restrict this to admins only is still an open question

**Comment by ksmurchison** [comment]
Resolved by https://github.com/cyrusimap/cyrus-imapd/commit/63f00cd536bb2ad7e2e5c36dcd7b9ee1907a5e04
