### ISSUE TITLE
Make intermediate mailboxes real entries in mailboxes.db

### ISSUE THREAD

**Issue by robmueller** [cyrusimap/cyrus-imapd#2339]
If you create an IMAP mailbox without it's parent such as:
```
. create INBOX.foo.bar
```
Then currently *no* "INBOX.foo" entry is created in mailboxes.db. This is painful when dealing with hierarchies, and currently breaks JMAP because it fails to find the parent mailbox for INBOX.foo.bar and just appears it give it the id of the "INBOX" mailbox as it's parentId, causing the hierarchy to be wrong in JMAP land

Talking with Bron, we think the best thing to do here is:

* Always create a complete hierarchy in mailboxes.db (e.g. creating INBOX.foo.bar implicitly creates INBOX.foo if it doesn't exist). This ensures that all mailboxes have a UUID and a consistent hierarchy always exists in mailboxes.db
* Make cyrus startup create appropriate intermediate folders if they don't already exist
* Give the intermediate mailboxes a new type, so we don't create cyrus.* files on the underlying storage and still return a \Noselect result for it
* If all the child folders of an intermediate mailbox are deleted, delete the intermediate mailbox as well

**Comment by ksmurchison** [comment]
After getting back to this and looking at the amount of code that I have touched so far, I'm wondering why we don't just have a new function for JMAP to locate the actual parent, even if it doesn't exist in the hierarchy (or add an option to the existing mboxlist_findparent()).

**Comment by ksmurchison** [comment]
@brong  Understood, but it seems a lot easier to have a function that returns INBOX.foo as the parent of INBOX.foo.bar for JMAP rather than reworking all of the other tooling to skip over new placeholder entries in mboxlist.db.
Or is this mostly about needing a UUID for the placeholder?

**Comment by brong** [comment]
You need the UUID for JMAP.  "INBOX.foo" isn't a thing in JMAP, it's just name, id and parentId.  parentId for INBOX.foo.bar needs to be a UUID for INBOX.foo.

**Comment by ksmurchison** [comment]
What should the JMAP response for an intermediate mailbox look like?  All of the elements in the myRights object are false?  Anything else?

**Comment by ksmurchison** [comment]
Hmm.  If we have:
INBOX.a
INBOX.a.b.c.d

and INBOX.a gets deleted, we need to create a "dummy" record for it in mailboxes.db, but how to do that if we also leave a "deleted" tombstone behind?

**Comment by brong** [comment]
The deleted record needs to be an intermediate record instead I guess.

Bron.


On Fri, Jun 22, 2018, at 06:44, Ken Murchison wrote:
> Hmm.  If we have:
>  INBOX.a
>  INBOX.a.b.c.d


> and INBOX.a gets deleted, we need to create a "dummy" record for it in
> mailboxes.db, but how to do that if we also leave a "deleted"
> tombstone behind?> — You are receiving this because you were mentioned. Reply to this
> email directly, view it on GitHub[1], or mute the thread[2].
--
  Bron Gondwana, CEO, FastMail Pty Ltd
  brong@fastmailteam.com


Links:

  1. https://github.com/cyrusimap/cyrus-imapd/issues/2339#issuecomment-399237599

**Comment by ksmurchison** [comment]
The code on this branch now seems to do the right thing for JMAP.  I need to work through a couple of rename failures in the Cass tests.  I also need to handle deletions and then look into replication.

https://github.com/cyrusimap/cyrus-imapd/tree/intermediate-mailboxes

**Comment by brong** [comment]
Let's declare this bit done :)
