### ISSUE TITLE
Set up www.cyrusimap.org and ftp.cyrusimap.org as Git repos backed on github pages

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#2340]
Having looked at various options for new homes, and given that github pages now support https:

https://blog.github.com/2018-05-01-github-pages-custom-domains-https/

We should just move everything there.  The one wrinkle is automatic updates, but I think we should solve this by having the docs built by our cyrus.works automated testing environment.

There's no particular urgency on this, so I've tagged ellie to hopefully do the bulk of the work, and Chris to help with how to set up a docker image that runs and pushes built docs back to the git repo for the site.

**Comment by FMQA** [comment]
@elliefm : Do we have any instructions on how to build the docs

**Comment by brong** [comment]
The main bit is "cd $checkout; cd docsrc; make html" - here's the whole script for completeness

root@www-01:~# cat /root/docs/run.sh
#!/bin/sh

set -e

export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games

# set up a clean target
rm -rf /root/docs/target
rsync -av /root/docs/original/ /root/docs/target

# add files from this repo
# XXX there's probably a better way to achieve this
cp -p /root/docs/robots.txt /root/docs/target/
cp -p /root/docs/sitemapindex.xml /root/docs/target/

# add the 2.5 docs
cd /root/docs/cyrus-imapd-2.5/
git fetch
git checkout -q origin/cyrus-imapd-2.5
cd docsrc
make html
rsync -av /root/docs/cyrus-imapd-2.5/docsrc/build/html/ /root/docs/target/2.5

# add the 3.0 docs
cd /root/docs/cyrus-imapd-3.0/
git fetch
git checkout -q origin/cyrus-imapd-3.0
cd docsrc
make html
rsync -av /root/docs/cyrus-imapd-3.0/docsrc/build/html/ /root/docs/target
rsync -av /root/docs/cyrus-imapd-3.0/docsrc/build/html/ /root/docs/target/stable
rsync -av /root/docs/cyrus-imapd-3.0/docsrc/build/html/ /root/docs/target/3.0

# add the development docs
cd /root/docs/cyrus-imapd/
git fetch
git checkout -q origin/master
cd docsrc
make html
rsync -av /root/docs/cyrus-imapd/docsrc/build/html/ /root/docs/target/dev

# add sasl
cd /root/docs/cyrus-sasl/
git fetch
git checkout -q origin/master
cd docsrc
make html
rsync -av /root/docs/cyrus-sasl/docsrc/build/html/ /root/docs/target/sasl

# copy the new docs to the website
rsync -av --delete /root/docs/target/ /var/www/html

**Comment by elliefm** [comment]
Or website scripts are in the https://github.com/cyrusimap/cyrusimap.org repo these days, fwiw (I gitified them last time www was acting up, in case we had to start from scratch!)

**Comment by elliefm** [comment]
I'm just having a quick read through Google Pages documentation, and it sounds like it expects your website to just be a repository full of html files and such, which means we'd still need some infrastructure somewhere to generate those files and commit them into the repository, ick.

They do support generation of content, using Jekyll (some blog-oriented ruby thing); but to make use of that we'd need to convert all our content over from Sphinx (some python thing, lol) format, yeuch.

We could fudge this but it'd be even more of a nasty hack than the current website is, do we want to go down that path?

Whereas doing it properly would mean a major rethink of how we maintain and version-control our documentation.  Which would be great to have gotten done, but a horrible job to actually do (at least, for a bunch of grumpy old C programmers)

**Comment by elliefm** [comment]
We'd still need somewhere to host all the release tarballs/signatures, and afaict Github Pages doesn't provide an FTP end point so we'd need to retire FTP hosting (not the end of the world, but someone will probably sook about it).

**Comment by postilion** [comment]
Hey kids.  Sorry to be so late coming to the ball, but just what the devil is this all about?  At first, in seeing this thread, I figured there was a sick web server somewhere, but now there's discussion of switching documentation schemes?  And just when I have wrapped my brain (or some non-trivial part of it) around Sphinx?
Please, someone explain, what's the deal?

**Comment by jbergstroem** [comment]
> @elliefm said: We'd still need somewhere to host all the release tarballs/signatures, and afaict Github Pages doesn't provide an FTP end point so we'd need to retire FTP hosting (not the end of the world, but someone will probably sook about it).

Github releases page supports hosting both (auto-generated) tarballs from git tags as well as any artifacts you choose via their API. As you correctly say, it would require change in your release procedure though.

**Comment by brong** [comment]
Dave contacted me recently about this again - we should get on with it!

**Comment by elliefm** [comment]
Closing this cause we actually dealt with this ages ago
