### ISSUE TITLE
Email group names put in "email" not "name"

### ISSUE THREAD

**Issue by robmueller** [cyrusimap/cyrus-imapd#2341]
A message with this header:
```
To: foo: a@b.com;
```
Generates:
```
to: [ { name: null, email: "foo" }, { name: null, email: "a@b.com" }, { name: null, email: null } ]
```
The current spec doesn't include the group end marker (e.g. { name: null, email: null }). However talking with neil, to make this more consistent with IMAP, we think that should be added, so leave that in and neil will update the spec.

However, the group name has { name: null, email: "foo" }, the JMAP spec says the group name should go in "name" not "email". This is different to IMAP, which does put the group name in the mailbox part. That actually feels weird given the email spec.

```
         An address structure is a parenthesized list that describes an
         electronic mail address.  The fields of an address structure
         are in the following order: personal name, [SMTP]
         at-domain-list (source route), mailbox name, and host name.
...
         [RFC-2822] group syntax is indicated by a special form of
         address structure in which the host name field is NIL.  If the
         mailbox name field is also NIL, this is an end of group marker
         (semi-colon in RFC 822 syntax).  If the mailbox name field is
         non-NIL, this is a start of group marker, and the mailbox name
         field holds the group name phrase.
```
```
   mailbox         =   name-addr / addr-spec
   name-addr       =   [display-name] angle-addr
   group           =   display-name ":" [group-list] ";" [CFWS]
   display-name    =   phrase
   group-list      =   mailbox-list / CFWS / obs-group-list
```
Why they put the group display-name in the "mailbox name" field rather than the "personal name" field even though both are "display-name" in the email RFC, I'm not sure. I think the JMAP spec is "more right" here.

So we have to detect this case, and put the group name in the JMAP "name" field rather than JMAP "email" field.

**Comment by rsto** [comment]
Parsing groups for addresses is done in Cyrus lib/parseaddr: https://github.com/cyrusimap/cyrus-imapd/blob/ae82066eea5fbcd7d307bf3cfe82c75b6555cae6/lib/parseaddr.c#L96-L100

For JMAP, we currently use the parseaddr library to dissect a string into its addresses. I'd like to keep it that way, so we'll have to tweak parseaddr to do the proper splitting, e.g. based on flags passed to the parser.

**Comment by robmueller** [comment]
Well either you can pass flags to parseaddr, or you can just add an extra check in _emailaddresses_from_addr when it converts it to JSON. If addr->name and addr->domain are null but addr->mailbox isn't, then it must be a group start, so put it in the { name: ... } JSON bit, rather than the { email: ... } JSON bit. Does that sound right?

**Comment by rsto** [comment]
Sounds about right! Fixed in https://github.com/cyrusimap/cyrus-imapd/commit/6ac968e94744b75a6980d8bb195de33bb67fa5c4 and tested in https://github.com/cyrusimap/cassandane/commit/087e269e064d18b57d6dcdf16350547be7dff467
