### ISSUE TITLE
JMAP: Update algorithm to decompose body structure

### ISSUE THREAD

**Issue by neilj** [cyrusimap/cyrus-imapd#2351]
There have been several tweaks to the suggested algorithm in the spec for deciding which parts go in htmlBody, textBody etc. since I first wrote it, as we discovered several bugs after putting it into practice. Please update Cyrus to match the [latest revision](https://jmap.io/spec-mail.html#properties-of-the-email-object).

**Comment by rsto** [comment]
Fixed in https://github.com/cyrusimap/cyrus-imapd/commit/3d4850ab9814739fad559c277a6b56d60dc9822e

Also see https://github.com/cyrusimap/cyrus-imapd/commit/a1db70e674466944022ee05ef2a11004e49a7516
