### ISSUE TITLE
JMAP: CalendarEvent/get returning null time zone for all events

### ISSUE THREAD

**Issue by neilj** [cyrusimap/cyrus-imapd#2353]
All the events I'm fetching appear to be getting `null` for the timeZone property, even though I know the event actually does have a time zone set in the ICS original.

**Comment by rsto** [comment]
This sounds odd, and I'm not experiencing that with any of our tests. E.g. the `calendarevent_get_endtimezone` uses this ICS file as event data (note: in Cyrus we allow the VEVENT to have no embedded VTIMEZONE):

    BEGIN:VCALENDAR
    VERSION:2.0
    PRODID:-//Apple Inc.//Mac OS X 10.9.5//EN
    CALSCALE:GREGORIAN
    BEGIN:VEVENT
    TRANSP:TRANSPARENT
    DTSTART;TZID=Europe/London:20160928T130000
    DTEND;TZID=Europe/Vienna:20160928T150000
    SUMMARY:Foo
    UID:3edfa67a-9e92-4ed7-b0cf-c07ad63ab8f8
    DTSTAMP:20150928T132434Z
    CREATED:20150928T125212Z
    END:VEVENT
    END:VCALENDAR

and a `CalendarEvent/get` returns 

    {
        "@type": "jsevent",
        "alerts": null,
        "calendarId": "Default",
        "created": "2015-09-28T12:52:12Z",
        "description": "",
        "duration": "PT1H",
        "freeBusyStatus": "free",
        "htmlDescription": null,
        "id": "3edfa67a-9e92-4ed7-b0cf-c07ad63ab8f8",
        "isAllDay": false,
        "keywords": null,
        "links": null,
        "locale": null,
        "locations": {
            "8678da4464d3e6be4d2e51ae4913a6a52d9cef69": {
                "rel": "end",
                "timeZone": "Europe/Vienna"
            }
        },
        "participants": null,
        "privacy": "public",
        "prodId": "-//Apple Inc.//Mac OS X 10.9.5//EN",
        "recurrenceOverrides": null,
        "recurrenceRule": null,
        "relatedTo": null,
        "replyTo": null,
        "sequence": 0,
        "start": "2016-09-28T13:00:00",
        "timeZone": "Europe/London",
        "title": "Foo",
        "uid": "3edfa67a-9e92-4ed7-b0cf-c07ad63ab8f8",
        "updated": "2015-09-28T13:24:34Z",
        "x-href": "/dav/calendars/user/cassandane/Default/3edfa67a-9e92-4ed7-b0cf-c07ad63ab8f8.ics"
    }

I wonder where Cyrus could trip up for your ICS files. Could you share one?

**Comment by rsto** [comment]
Update: this happens if libical is built with USE_BUILTIN_TZDATA=true but the cyrus-timezones package is not installed. Using USE_BUILTIN_TZDATA=false has shown to make problems when generating VTIMEZONES: the resulting DST rules might be excessively long, instead of defining a generic RRULE for DST changes.

**Comment by rsto** [comment]
Closing this a a FastMail-internal ops issue.
