### ISSUE TITLE
JMAP extension: Email#calendarEvents

### ISSUE THREAD

**Issue by neilj** [cyrusimap/cyrus-imapd#2359]
We need to add support for the following extra Email object property:

- **calendarEvents**: `String[JSCalendar]|null`
  A map of *partId* to **JSCalendar Event** object for each attachment of type
  `text/calendar` that can be parsed into a single VEVENT, or `null` if none.

**Comment by rsto** [comment]
I assume this property is read-only, right?

**Comment by brong** [comment]
I'm fine with it being read-only, at least to start off with.  We will definitely only be using it read-only at FastMail.

We do need to probably normalise our extension namespace and define the JMAP names and get Cyrus reporting them correctly for the supported "using" standards.
