### ISSUE TITLE
mailbox_lock_index should either release or refresh cache files

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#2360]
found from a nasty bug with JMAP where an open, but not locked, mailbox was being left on open_mailboxes between sessions - and then when a newly appended record was seen, the mapped cache file wasn't big enough.

The underlying cause is that unlocked mailboxes sit in open_mailboxes, and then when they're re-locked - the cyrus.index map gets extended, but the cache files don't.  They should be!

We're using mappedfile - so they could be refreshed by adding a mappedfile_refresh() API call which checked filesize and extended the map, or just by releasing.

**Comment by rsto** [comment]
@brong what do you think of https://github.com/rsto/cyrus-imapd/commit/d7fb6cd0f36b451d6e182adc448b25bc8096de2a ?

It releases the cache files in mailbox_lock_internal before rereading the headers. My tests ran OK with it, but I haven't really got into reproducing the race conditions that caused that issue to really do damage.

**Comment by brong** [comment]
Looks perfect.  From investigating the problem and reading the surrounding code, that's a complete solution to the bug path we saw.
