### ISSUE TITLE
JMAP: Mailboxes from shared accounts don't have correct "role" properties

### ISSUE THREAD

**Issue by robmueller** [cyrusimap/cyrus-imapd#2365]
When you do a Mailbox/get from a shared account, only the Inbox folder has a "role" property (which is correctly "inbox"), but no other mailboxes have "role" properties, even ones that have an IMAP special-use set.

Unlike IMAP list where only the users own special-use folders should have the special use attributes present (which makes sense, since shared folders appear in a global mailbox listing), with JMAP I believe all folders in shared accounts should have a "role" property if they have the corresponding special-use attribute set (because you access mailbox lists per-account).

**Comment by neilj** [comment]
Yes, the *role* should be returned for mailboxes in shared accounts too.

**Comment by brong** [comment]
right: so this is going to be a matter of looking for the annotation as the mailbox owner rather than the logged in user.
