### ISSUE TITLE
Make cyrus to use xapian for all kind of search

### ISSUE THREAD

**Issue by jas01** [cyrusimap/cyrus-imapd#2367]
Currently, with cyrus-imapd 3.0.6, compile with mainstrean xapian, a standard search make throught Thunderbird seam to use the basic cyrus search engine (no index). As I understand, cyrus-imapd use xapian only for fuzzy search. But first Thunderbird are still very common MUA, and second cyrus-imapd cannot be configure to use two engine (SQUAT and Xapian), so that's mean for 99% of the search xapian index are useless.
So that would be awesome if any search pass to xapian when xapian are configure.

**Comment by brong** [comment]
I think I like the idea of a configuration option which enables the fuzzy hack we currently use for IOS on all useragents.  Should be very trivial to add.

**Comment by rsto** [comment]
Implemented in https://github.com/cyrusimap/cyrus-imapd/commit/11f0bae309699d1b4e1eec7b7265af383d2cdb11 and tested in https://github.com/cyrusimap/cassandane/commit/73a8c27437bcc25917700b946c533249d44ac529

@elliefm we might want to backport this to the 3.0 stable branch.

**Comment by elliefm** [comment]
This is now on the 3.0 branch
