### ISSUE TITLE
JMAP: Email/queryChanges not returning correct response

### ISSUE THREAD

**Issue by neilj** [cyrusimap/cyrus-imapd#2371]
A list of unread threads in a mailbox uses a `filter` like this:

```
"filter": {
          "operator": "AND",
          "conditions": [
            {
              "operator": "NOT",
              "conditions": [
                {
                  "allInThreadHaveKeyword": "$seen"
                }
              ]
            },
            {
              "inMailbox": "23cfa8094c0f41e6"
            }
          ]
        },
```

Cyrus returns `canCalculateChanges: true`, so we use *Email/queryChanges* but it is not returning anything as removed after I have marked all messages in a thread as read.

**Comment by brong** [comment]
Pretty sure I fixed this with 7422508344e529c1d663e9a7cb13b74a07364849

(basically: can't calculate changes on previously unread)
