### ISSUE TITLE
[FR] ACL on autocreate folders

### ISSUE THREAD

**Issue by anatoli26** [cyrusimap/cyrus-imapd#2372]
Feature Request: to add an option to define ACL on any auto-created folder.

The config syntax would look like as follows, with multiple `autocreate_acl` possible, one for each folder/user (group)/permission:

`autocreate_acl    <folder> <user> <acl>`, e.g. `autocreate_acl plus anyone p`

The rationale: today almost all basic new account configuration could be accomplished with various auto-configuration features (autocreate_XXX, x-list, etc.), so there's mostly no need for custom scripts to setup new accounts, except for one setting: "anyone p" ACL for plus+addressing on folders that should be able to receive such emails.

This feature would make the auto-creation process complete, i.e. no custom provisioning scripts would be needed for standard mailbox configurations (it would also permit defining ACLs for shared folders).

About this feature implementation level of effort, according to @elliefm:

> In my opinion, any new feature for ACL's is inherently high complexity -- even if it's just a two line patch -- just because of the amount of work involved in checking for side effects, error handling, and making sure the documentation is up to scratch (so that people don't accidentally configure it wrong and get into trouble).
> 
> That said, the code for reading config settings already exists, as does the code for parsing and applying ACL's. So in theory it should be a "simple" matter of bolting these bits together in the right place(s). I'd be happy to review/advise on a pull request along these lines!

**Comment by elliefm** [comment]
would we expect to want to set multiple acl's per folder with this, and if so, would we do it with a single `autocreate_acl folder identifier rights [identifier rights]...` config line, or with a separate `autocreate_acl folder identifier rights` line for each identifier:rights pair?

**Comment by elliefm** [comment]
One per line, multiple lines seems like the easier implementation path...

I've got a sketch of this implemented here:

https://github.com/elliefm/cyrus-imapd/tree/v31/2372-autocreate-acl

@anatoli26 if you could test out this patch and give feedback on its utility (i.e. whether you can use it to solve the problems you need to solve), that'd be awesome.  I can test it as implemented, but I don't have a real-world context to try it out in and see whether the implementation is useful in practice

**Comment by elliefm** [comment]
Very basic Cassandane test for the above implementation here: https://github.com/elliefm/cassandane/tree/2372-autocreate-acl

**Comment by anatoli26** [comment]
Hi @elliefm,

> One per line, multiple lines seems like the easier implementation path...

Yes, this was my initial idea, like the xlist-X flags.

> I've got a sketch of this implemented here

Checked the code superficially, looks good. I'll try to test it this week.

Thanks a lot Ellie!

**Comment by anatoli26** [comment]
> Very basic Cassandane test for the above implementation here: https://github.com/elliefm/cassandane/tree/2372-autocreate-acl

This is exactly the use-case I had in mind. If it passes, it's good for me. Anyway, I'll test it these days.

**Comment by elliefm** [comment]
This is on master now.
