### ISSUE TITLE
Mailbox/set httpd endless loop

### ISSUE THREAD

**Issue by zvasilev** [cyrusimap/cyrus-imapd#2377]
If you call Mailbox/set create and set non existent reference "#" for the 'parentId' parameter, httpd enter in endless loop.

**Comment by rsto** [comment]
Thanks for reporting this! It even looped for all requests where there's only missing creationIds in parentId, so that really needed a fix.

**Comment by rsto** [comment]
Tested in https://github.com/cyrusimap/cassandane/commit/3190f45fa70414a15290adfa7c81f9dedd14f0ba

**Comment by rsto** [comment]
@zvasilev Your JMAP request looks OK to me.

Could you please create a new issue including the Mailbox/set request and response, and the response of a subsequent Mailbox/get for the two mailboxes?
