### ISSUE TITLE
JMAP JSCalendar: update recurrenceOverrides to use `excluded: true`

### ISSUE THREAD

**Issue by neilj** [cyrusimap/cyrus-imapd#2380]
1. Needs to be updated to use { "excluded": true } for EXDATE.
2. The *duration* property is returning "W" (week) components for events, but the JSCalendar spec says only D, H, M and S are allowed.

**Comment by rsto** [comment]
I've split this issue so we can track the two issues separately. The duration issue is tracked in #2381
