### ISSUE TITLE
"Mailbox/set" doesn't honor "parentId" argument.

### ISSUE THREAD

**Issue by zvasilev** [cyrusimap/cyrus-imapd#2382]
Attempt to create "Inbox" subfolder creates a folder as a sibling.
API call payload is 
{"methodCalls":[["Mailbox/set",{"create":{"1":{"name":"folder_123","parentId":"c8f73a59-4b7c-4549-8c03-0e267583b4e2"}}},"#13"]],"using":["ietf:jmap","ietf:jmapmail"]}

Folder(mailbox) structure is

{"methodResponses":[["Mailbox/get",{"state":"360","list":[{"id":"c8f73a59-4b7c-4549-8c03-0e267583b4e2","name":"Inbox","parentId":null,"myRights":{"mayReadItems":true,"mayAddItems":true,"mayRemoveItems":true,"mayCreateChild":true,"mayDelete":false,"maySubmit":true,"maySetSeen":true,"maySetKeywords":true,"mayRename":false},"role":"inbox","totalEmails":3,"unreadEmails":0,"totalThreads":2,"unreadThreads":0,"sortOrder":0},{"id":"45219a7a-b080-40da-ba63-d210d29f008f","name":"Drafts","parentId":null,"myRights":{"mayReadItems":true,"mayAddItems":true,"mayRemoveItems":true,"mayCreateChild":true,"mayDelete":true,"maySubmit":true,"maySetSeen":true,"maySetKeywords":true,"mayRename":true},"role":null,"totalEmails":1,"unreadEmails":0,"totalThreads":1,"unreadThreads":0,"sortOrder":0},{"id":"7cfdbf1c-26f9-4206-aad1-a38cefba0328","name":"fld2","parentId":"c8f73a59-4b7c-4549-8c03-0e267583b4e2","myRights":{"mayReadItems":true,"mayAddItems":true,"mayRemoveItems":true,"mayCreateChild":true,"mayDelete":true,"maySubmit":true,"maySetSeen":true,"maySetKeywords":true,"mayRename":true},"role":null,"totalEmails":1,"unreadEmails":0,"totalThreads":1,"unreadThreads":0,"sortOrder":0},{"id":"35d85974-caea-44fd-b4b9-00d880fa42ae","name":"sub_folder_1","parentId":"c8f73a59-4b7c-4549-8c03-0e267583b4e2","myRights":{"mayReadItems":true,"mayAddItems":true,"mayRemoveItems":true,"mayCreateChild":true,"mayDelete":true,"maySubmit":true,"maySetSeen":true,"maySetKeywords":true,"mayRename":true},"role":null,"totalEmails":2,"unreadEmails":0,"totalThreads":2,"unreadThreads":0,"sortOrder":0},{"id":"b00816e6-c93e-44a8-8a0f-3098bee6aa8f","name":"Sent","parentId":null,"myRights":{"mayReadItems":true,"mayAddItems":true,"mayRemoveItems":true,"mayCreateChild":true,"mayDelete":true,"maySubmit":true,"maySetSeen":true,"maySetKeywords":true,"mayRename":true},"role":null,"totalEmails":4,"unreadEmails":0,"totalThreads":4,"unreadThreads":0,"sortOrder":0},{"id":"c8257929-0b84-4b26-adc5-6fa7b1effa8a","name":"Trash","parentId":null,"myRights":{"mayReadItems":true,"mayAddItems":true,"mayRemoveItems":true,"mayCreateChild":true,"mayDelete":true,"maySubmit":true,"maySetSeen":true,"maySetKeywords":true,"mayRename":true},"role":null,"totalEmails":0,"unreadEmails":0,"totalThreads":0,"unreadThreads":0,"sortOrder":0}],"notFound":[],"accountId":"u1@cyrus.mailtemi.com"},"#01"]]}

**Comment by rsto** [comment]
Yes, I can reproduce that. It boils down to how we map IMAP mailboxes to JMAP. In Cyrus IMAP, any user mailbox is underneath the inbox, e.g. your Trash is INBOX.Trash. That's why we chose to return a null parentId for any direct descendant of Inbox.

There's no quick fix I can provide to you, if any. I'll ping the team to discuss this matter, but if we truly want to distinguish between mailboxes with paretnId null and parentId inbox, we'll have to fall back to some mailbox annotation magic.

**Comment by brong** [comment]
Adding myself to this as well - I had some partial ideas for this that I'll get back to at some point.

**Comment by brong** [comment]
This was fixed a little while back :)
