### ISSUE TITLE
JMAP: Can base64 message/rfc822 sections be handled relatively easily?

### ISSUE THREAD

**Issue by robmueller** [cyrusimap/cyrus-imapd#2385]
Although RFC2046 clearly says:
```
https://tools.ietf.org/html/rfc2046#section-5.2.1

No encoding other than "7bit", "8bit", or "binary" is permitted for
the body of a "message/rfc822" entity. The message header fields are
always US-ASCII in any case, and data within the body can still be
encoded, in which case the Content-Transfer-Encoding header field in
the encapsulated message will reflect this. Non-US-ASCII text in the
headers of an encapsulated message can be specified using the
mechanisms described in RFC 2047.
```
Unfortunately we intermittently see attached message/rfc822 attachments that are base64 encoded. Currently these appear as completely empty when Email/parse is called on the particular blobId.
```
    [
      "Email/parse",
      {
        "accountId": null,
        "notFound": null,
        "notParsable": null,
        "parsed": {
          "Ge6092e4091cf1f554a10fd75555a5a08bd6ac92e": {
            "subject": null,
            "id": null,
            "cc": null,
            "from": null,
            "sentAt": null,
            "to": null,
            "replyTo": null,
            "bodyStructure": {
              "size": 0,
              "location": null,
              "type": "text/plain",
              "name": null,
              "blobId": "Gda39a3ee5e6b4b0d3255bfef95601890afd80709",
              "charset": "us-ascii",
              "disposition": null,
              "language": [],
              "cid": null,
              "partId": "2.1"
            },
            "bcc": null,
            "size": 34489,
            "bodyValues": {
              "2.1": {
                "isEncodingProblem": false,
                "isTruncated": false,
                "value": ""
              }
            }
          }
        }
      },
      "0"
    ]
```
There's always a tradeoff in situations like this. You can tell users GIGO, but when it works at many other places, users are still annoyed. Depending on how often this happens vs how easy to fix, it may or may not be worth fixing.

I thought I'd check, would this be easy to fix in cyrus jmap to handle base64 encoded message/rfc822 sections, even if it's in a less efficient way (e.g. re-parse entire message content + throw away after request is done) so it at least displays something sensible?

**Comment by rsto** [comment]
I've added support for base64-encoded RFC822 messages to Email/parse here https://github.com/cyrusimap/cyrus-imapd/commit/d179ee8ebfc87dfcb25df574d204a90ae6919005. It's tested in the test suite (https://github.com/cyrusimap/cassandane/commit/ac9cf835b538adf7857d807048cf791ebcbbcca0).

That's probably not the end of the story, though, so I'll keep this issue open.

- I might move support for base64 messages up in core message.C API so we can also extract the RFC822 info during an APPEND. 
- Email/set hasn't been updated, yet, so if a client calls Email/parse on a base64 encoded RFC822 message, it would have no idea that the raw blob is not spec-compliant. Accordingly, an Email/set using that blobId would currently result in Cyrus replicating the bogus encoding. What we should be doing is decode the message, check its contents, and either use 7bit, 8bit or binary encoding accordingly.

This might need to wait for a few weeks time, though.

**Comment by rsto** [comment]
This issue on the backlog is related: https://github.com/cyrusimap/cyrus-imapd/issues/1179

**Comment by robmueller** [comment]
Yes, ideally we'd extract structure during APPEND, because at the moment I'm guessing the IMAP bodystructure element is incomplete (it shows a message/rfc822 component, but doesn't have the appropriate sub-structure). Again, this is nicer longer term, but probably after JMAP is done.

Ditto the attaching a blob. Yes, it means we're generating a badly formatted email, but it only really occurs if someone forwards an existing email, I can't see any really cases which would cause someone to attach a base64 encoded message/rfc822 to a new message?

**Comment by robmueller** [comment]
Yeah, I can see how 2 is very tricky with all the offsets. Thinking about it, I wouldn't actually do 2. For our UI, being able to use Email/parse on the sub-messages will make these work for the JMAP UI. For IMAP clients, let them work it out properly if they want to rather than presenting a "fake" decoded message to them, which is just a lot of work to get right.

**Comment by rsto** [comment]
Couple of weeks ago I started an experimental branch to add base64-encoded rfc822 message support to the core Cyrus mail parser. Even supporting option (1) as described above turned out to be more tricky than I imagined, and it will take some more time to implement this properly. I plan not to implement option (2), but please let me know if you see good reasons why I should (e.g. @brong?)

**Comment by rsto** [comment]
https://github.com/cyrusimap/cyrus-imapd/commit/d179ee8ebfc87dfcb25df574d204a90ae6919005#diff-4b10471f43b34871c0f0815c86c973be and following commits seem to be doing fine for JMAP. Closing this one, while keeping https://github.com/cyrusimap/cyrus-imapd/issues/1179 open for IMAP.
