### ISSUE TITLE
HTTP OPTIONS

### ISSUE THREAD

**Issue by dilyanpalauzov** [cyrusimap/cyrus-imapd#2390]
With cyrus 3.0 a carddav collection belongs to user1 and is available at `http://host/dav/addressbooks/user/user1/Z`.  cyradm grants none prileveges to user2.  If user2 does `curl -D- -XOPTIONS -u user2:xyz http://host/dav/addressbooks/user/user1/Z/` the server answers with:
```
Allow: OPTIONS, GET, HEAD, POST, PUT, DELETE
Allow: PROPFIND, REPORT, COPY, MOVE, PROPPATCH, LOCK, UNLOCK, ACL
```
Since user2 cannot do anything on the collection, DELETE shall not be returned by HTTP OPTIONS.

Even if I set explicit rights to user2, the Allow isn't changed anyhow.

The further cyradm lists as permission `c` for the owner, but neither https://www.cyrusimap.org/imap/reference/manpages/systemcommands/cyradm.html nor https://www.cyrusimap.org/imap/download/installation/http/caldav.html explain what permission `c` means.

**Comment by ksmurchison** [comment]
Is this breaking a client or is this just a nit?

Currently, the Allow header generation doesn't take into account user permissions.  Its based solely on what operations are allowed on the given path (collection, resource, etc), as if the user is an admin.  User perms are checked at the time a DELETE request is made.

Since CalDAV and CardDAV require support for WebDAV ACL, a client should be using that facility to see what methods are allowed.  For other services supported by Cyrus HTTPd, we may have to fix Allow header generation if it misleads clients.

**Comment by ksmurchison** [comment]
https://tools.ietf.org/html/rfc7231#section-7.4.1

states that Allow lists methods allowed on the target resource, without mention of user permissions.  That's why there are 2 different responses codes: 403 (Permission Denied) and 405 (Method Not Allowed)

**Comment by dilyanpalauzov** [comment]
It is not breaking a client.  I was expecting with `curl -XOPTIONS -uuser:password url` to find the correct permissions, as this is much easiert than utilizing WebDAV ACLs on the command line.  I wanted to find our if changing the properties of a CardDav collection with cyradm to make it readonly indeed works, by checking the OPTIONS after and before the change.

Anyway after authentication it is better if OPTIONS returns the methods the user can perform.  This is irrespective of WebDav.

Maybe RFC7231#7.4.1 doesn't mention user permissions because at the time it was written nobody raised the concern.

**Comment by ksmurchison** [comment]
I don't know why it doesn't mention user permissions.  It could be intentional or an oversight.  If you feel it needs addressing, raise an issue here: https://github.com/httpwg/http-core

**Comment by dilyanpalauzov** [comment]
A consensus on this seems unlikely.

**Comment by dilyanpalauzov** [comment]
I mean at ietf-http-wg@w3.org it was stated, that irrespective of the fact whether it was overseen to specify for Allow that it shall consider the currently authenticated principal, nowadays it is not feasible for backward compatibility to insert in the specification for Allow that it shall consider the authentication credentials.
