### ISSUE TITLE
Content-Disposition: ...; filename=whatever

### ISSUE THREAD

**Issue by dilyanpalauzov** [cyrusimap/cyrus-imapd#2394]
The `Content-Disposition` header allows hinting the browser under what name to store downloaded resources, and whether the resource shall be rendered in the browser, when possible, or immediately downloaded.  For freebusy URLs, `httpd` sends `Content-Diposition: attachment; filename=username.ifb` and in turn the browser immediately downloads the file.

See [RFC2183: Communicating Presentation Information in Internet Messages: The Content-Disposition Header Field](https://tools.ietf.org/html/rfc2183) sections "2.1 The Inline Disposition Type" and "2.2 The Attachment Disposition Type".

I propose changing the disposition type from `attachment` to `inline`, so that the browser first tries to display the resource and if it can't, to download it:
```diff
diff --git a/imap/httpd.c b/imap/httpd.c
--- a/imap/httpd.c
+++ b/imap/httpd.c
@@ -2959,7 +2959,7 @@ EXPORTED void response_header(long code, struct transactio
n_t *txn)
 
         if (resp_body->fname) {
             simple_hdr(txn, "Content-Disposition",
-                       "attachment; filename=\"%s\"", resp_body->fname);
+                       "inline; filename=\"%s\"", resp_body->fname);
         }
         if (txn->resp_body.enc) {
             /* Construct Content-Encoding header */
```

**Comment by elliefm** [comment]
This looks like it would apply to all http responses that contain a filename, not just freebusy info. Is that likely to be a problem?

**Comment by dilyanpalauzov** [comment]
I am not sure to whom the question is, but I am aware of the wide consequences and I see no problems with the change, considering that anyway all the communication with Cyrus is supposed to be done by other software and not with people requesting in browsers some things (with the exception of the admin caldav/carddav interface).

In the case when a user uploads over (pure, drive) WebDav an object, which has Content-Type: text/plain, and the user requests the object via its http-URL in a browser, with `Content-Disposition; inline; filename=uuu.txt` the browser will display the file inline, with `Content-Disposition: attachment; filename=uuu.txt` the browser will download the file.  I guess the users would like in such cases to see the files in the browsers.  In the browsers anyway cannot handle the Content-Type they download the files.

**Comment by ksmurchison** [comment]
Resolved by https://github.com/cyrusimap/cyrus-imapd/commit/cfbc403645e1175eba0e9e3ca0db5cde36d9d5ba
