### ISSUE TITLE
"group:" acl identifiers do not work when reverseacls is enabled

### ISSUE THREAD

**Issue by elliefm** [cyrusimap/cyrus-imapd#2398]
The reverse ACL's optimisation avoids the expensive whole-db sweep during LIST operations by looking up the reverse ACL records, and only examining mailboxes that the user has access to.

Group ID's are currently not stored as reverse ACL's, so any mailboxes that a user has access to via a group membership are totally ignored.

In the meantime, the workaround is that if you use groups for managing access controls, you cannot also use the reverseacls optimisation.

The solution will be to extend the reverseacl's optimisation to handle groups.

Tagging this as 3.0 and 3.1 because it affects both, but the fix might not make it back to 3.0 -- depends on how intrusive it is.

**Comment by elliefm** [comment]
Implementation here: https://github.com/cyrusimap/cyrus-imapd/compare/master...elliefm:v31/2398-group-racls

Tests here: https://github.com/cyrusimap/cassandane/compare/master...elliefm:ldap-group-racls

Still needs more testing.  Seems to work okay for LIST, but I want to exercise a bunch of other stuff too.

**Comment by elliefm** [comment]
@brong, @ksmurchison, any thoughts on code paths or specific corner cases that this needs tests for?

**Comment by brong** [comment]
The sort is inside mboxlist_racl_matches - but when you call it the second time for the shared mailboxes, they'll sort with the user mailboxes rather than always afterwards.  Tiny little thing, but I think it's a change in behaviour that we may not want.  I'd probably actually make it a loop that runs twice, once for isuser and once without, and does the "forone" on the results of each.

Otherwise looks really good :)

**Comment by elliefm** [comment]
Yeah I went back and forth on whether/where to sort for a while (I eventually decided that an ACL could match the same user by both direct username and group membership, and thus sorting was mandatory if for no other reason than being able to then uniq the list...).

One of my intermediate (squashed out) versions had mboxlist_racl_matches explicitly not sorting the list, so that the caller needed to deliberately sort|uniq it themselves as appropriate.  This version had mboxlist_usermboxtree called it with two separate strarray_t's which it then sort|uniq'd independently and concatenated together, but I didn't like all the code duplication and brought it into mboxlist_racl_matches...

> I'd probably actually make it a loop that runs twice, once for isuser and once without, and does the "forone" on the results of each.

Yeah wow, that's a hundred times cleaner than what I'd come up with, hah.  Will just do that! :)

I'd still love ideas on other things it needs testing for.  It looks and feels okay to me as is, but it's changes to ACL behaviour and I'm deeply uncomfortable making those without some regression proofing!

**Comment by elliefm** [comment]
(Sounds to me like I at least want a test for "stuff is listed in the expected order"!)

**Comment by elliefm** [comment]
> (Sounds to me like I at least want a test for "stuff is listed in the expected order"!)

welp, this shook out #2420 so I'm glad I spent the time!

**Comment by elliefm** [comment]
This is on master now, not backporting to 3.0 though.
