### ISSUE TITLE
JMAP: Return performance information with JMAP calls

### ISSUE THREAD

**Issue by robmueller** [cyrusimap/cyrus-imapd#2400]
To help improve performance in the future, we have to be able to measure it.

As a start, I'd like to see 3 simple metrics computed for each JMAP method call.

1. total wall time
2. user cpu time
3. system cpu time

Wall time can be calculated with http://man7.org/linux/man-pages/man2/clock_gettime.2.html and user/system cpu time can be calculated with http://man7.org/linux/man-pages/man2/getrusage.2.html

The middleware layer will be able to take this data and log it/aggregate it in some way so we can measure backend performance over time to see which areas to focus on in the future.

One question is where to return this, I can see either:

* Return it as a separate "performance" result property for each method. e.g.
```
[[ "Email/query", {
    "accountId": "1",
    "filter": { "inMailbox": "id_of_inbox" },
...
    "performance": { "real": 0.345, "user": 0.123, "system": 0.023 }
}, "t0" ],
```

Probably enabled by adding an appropriate value to the "using" property (e.g. "https://www.cyrusimap.org/dev/performance" or something like that) 

2. Return it in a header on the response. e.g.

```
X-Cyrus-Performance: [["Email/query", { "real": 0.345, "user": 0.123, "system": 0.023 }],[ ... ]]
```

Probably activated by setting a header on the request (e.g. X-Cyrus-Performance-Enable: yes)

**Comment by ksmurchison** [comment]
Implemented with https://github.com/cyrusimap/cyrus-imapd/commit/b830693d32511f9399cfe056284427aca9bc6e40

Note that I used http:/cyrusimap.org/ns/performance as the capability to match the same namespace used in our *DAV code
