### ISSUE TITLE
Delete docsrc/Makefile

### ISSUE THREAD

**Issue by dilyanpalauzov** [cyrusimap/cyrus-imapd#2409]
Cyrus iIMAPD s supposed to support VPATH build (call `./configure && make`, including `make doc-html`) from a directory different from the top source directory).

`docsrc/Makefile` contains `PERL2RST      = ../tools/perl2rst` which is not correct for VPATH builds.

Rather than fixing PERL2RST for VPATH builds, providing that the Makefile.am provides all options in docrcs/Makefile, delete the latter.

**Comment by elliefm** [comment]
We currently use the `docsrc/Makefile` for building the documentation for the website, which we need to be able to do without dealing with all the dependencies of a full autotools environment.  I think it's also used by some of our documentation writers for similar reasons.

I would like this file to not exist someday, but for the time being it needs to stay.

**Comment by dilyanpalauzov** [comment]
Then update the `singlehtml`, `dirhtml` and other targets to depend on the `init` target.  This has [caused problems](https://rt.cpan.org/Public/Bug/Display.html?id=124710#txn-1776382).

**Comment by elliefm** [comment]
Good catch, I guess these got neglected cause we don't use those targets ourselves.  They're now fixed on the master and 3.0 branches. :)
