### ISSUE TITLE
JMAP Filename with spaces isn't quoted in Content-Disposition header filename parameter

### ISSUE THREAD

**Issue by robmueller** [cyrusimap/cyrus-imapd#2411]
I attached a file called `FastMail Incoming Email Flow.xml` to an email. The generated email had a MIME section:
```
--ce06a21415c7461582fa330dd14f51c3
Content-Disposition: attachment;filename=FastMail Incoming Email Flow.xml
Content-Type: text/xml; name="FastMail Incoming Email Flow.xml"
Content-Transfer-Encoding: BASE64
```

Note the lack of quoting on the filename parameter in the Content-Disposition header.

**Comment by rsto** [comment]
Fixed in 391faeeb67c5f8b56d408a595eaa5c9ba0082ac8
