### ISSUE TITLE
Lonely .conversations files

### ISSUE THREAD

**Issue by dilyanpalauzov** [cyrusimap/cyrus-imapd#2413]
I use cyrus 3.0.7.  In /var/imap/user/x/ I found a x.conversations file for a mailbox deleted long time ago.  So yesterday I created in cyradm "cm user/xaxa" and verified that the xaxa.conversations file was created.  Then I deleted "dm user/xaxa" and I believe I verified that the xaxa.conversations file was gone.  Today the xaxa.conversations file is back.  Its timestamp conicides with the time cyr_expire was called.

Creating a user/xexe mailbox today created xexe.conversations, deleting the mailbox user/xexe deleted xexe.conversations and cyr_expire isn't called yet.

Note, that sometimes terminating cyrus-master in the normal way does not work, so I kill -9 it.  I might have done so after deleting the mailbox.

Why did the xaxa.conversations file reappear?

**Comment by dilyanpalauzov** [comment]
Indeed, the xexe.conversations was resurrected and I have these files:

$mbox_lockpath/DELETED/user/xexe/5B3561DF.lock
$mbox_lockpath/user/xexe.lock
/usr/local/var/imap/user/x/xexe.conversations
/usr/local/var/spool/imap/DELETED/user/xexe/5B3561DF/cyrus.header
/usr/local/var/spool/imap/DELETED/user/xexe/5B3561DF/cyrus.index

Where would 5B3561DF come from?

**Comment by brong** [comment]
That's a hex encoded timestamp for when the deletion happened.

Bron.


On Sun, Jul 1, 2018, at 08:02, Дилян Палаузов wrote:
> Indeed, the xexe.conversations was resurrected and I have these files:> $mbox_lockpath/DELETED/user/xexe/5B3561DF.lock
>  $mbox_lockpath/user/xexe.lock
>  /usr/local/var/imap/user/x/xexe.conversations
>  /usr/local/var/spool/imap/DELETED/user/xexe/5B3561DF/cyrus.header
>  /usr/local/var/spool/imap/DELETED/user/xexe/5B3561DF/cyrus.index


> Where would 5B3561DF come from?


> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].
--
  Bron Gondwana, CEO, FastMail Pty Ltd
  brong@fastmailteam.com


Links:

  1. https://github.com/cyrusimap/cyrus-imapd/issues/2413#issuecomment-401568902

**Comment by elliefm** [comment]
> Its timestamp conicides with the time cyr_expire was called.

Hmm...

- Are you able to determine which combination of `cyr_expire` options is causing the conversations files to reappear?
- How big are these conversations files?
- If you do the same steps as your previous tests, then run `cyr_expire` with also the `-c` option, does the conversations file reappear?  Or does it only happen without `-c`?

I haven't looked yet, but I'm wondering if cyr_expire's "expire conversations" codepath is perhaps a) operating on DELETED mailboxes, and b) autocreating the conversations db when it opens it for expiry.  I think this combination of behaviours would result in the conversations db coming back when cyr_expire is run.

**Comment by dilyanpalauzov** [comment]
`cyr_expire -E180` without -c resurrects the .conversations file.

`cyr_expire -E180 -c` does not revive the .conversations file.

I have attached it: 184 bytes for a mailbox, that had no messages (was deleted one minute after it was created for experimenting with cyr_expire)

The synopsis in the manual page for cyr_expire does not mention `-c`, `-x` and `-a`.

[zzz1.conversations.txt](https://github.com/cyrusimap/cyrus-imapd/files/2154719/zzz1.conversations.txt)

**Comment by elliefm** [comment]
Okay, so it does sound like "expire conversations" codepath is the culprit, thanks for that.  Will have a look :)

**Comment by elliefm** [comment]
Some information about what's going on here:

- If you have delete_mode=delayed (default), then when a folder "x" is deleted, it actually just gets renamed to DELETED/x/timestamp, where timestamp is the hex-encoded time_t from when it was deleted.  Only admins can see the DELETED.* namespace.
- When you delete a user inbox in particular (e.g. `dm user/xexe`), in addition to the mailbox data being renamed as above, `user_deletedata()` is also called to clean up the various bits of non-mailbox data associated with the user (including conversations).  This is why the xexe.conversations file initially disappears
- The conversations functions do not ignore DELETED.* mailboxes, but they do ignore the fact they're deleted. So when cyr_expire iterates over the mailboxes, it finds these mailboxes, and when it calls into the conversations api to open/prune/close the relevant database, the xexe.conversations database gets resurrected.

You can expire the DELETED.* mailboxes using the -D option to cyr_expire.  Once they're gone, cyr_expire should no longer resurrect the conversations database for deleted users.  Except that cyr_expire currently processes the conversations database before it processes the -D option, so it will still do so once... (sigh)

I'll have a patch for this for 3.0 cyr_expire soon.   I'm not sure if master is also affected, its cyr_expire has been refactored a little while ago and this may have already been fixed.

**Comment by elliefm** [comment]
The fix for this is now on 3.0 and master, and there's a test for it in Cassandane.

cyr_expire now ignores DELETED.* mailboxes when looking up conversations databases, so a user who has been recently deleted (and thus still has DELETED.* mailboxes, but no real mailboxes) won't have their conversations db accidentally resurrected by cyr_expire.

Reopening cause the cyr_expire synopsis still needs updating to mention the -c, -x, -a options

**Comment by elliefm** [comment]
Docs updated too :)
