### ISSUE TITLE
JMAP: Contact#avatar property not returned

### ISSUE THREAD

**Issue by neilj** [cyrusimap/cyrus-imapd#2435]
The `avatar` property is no longer being returned when you fetch contact objects (it doesn't work if you try to explicitly fetch the property either). I swear this used to work with JMAP, not sure when it broke.

**Comment by rsto** [comment]
@ksmurchison I think you are working on this?

**Comment by ksmurchison** [comment]
Contact/set and Contact/get of avatar should now work properly on master as of 
https://github.com/cyrusimap/cyrus-imapd/commit/998cbc8486b1a6c38110919e492ed55b3a9297fc
