### ISSUE TITLE
JMAP: add isDeleted/width/height/exif_orientation parameters to EmailBodyPart

### ISSUE THREAD

**Issue by robmueller** [cyrusimap/cyrus-imapd#2437]
isDeleted/width/height/exif_orientation properties are all FastMail extensions to the EmailBodyPart.
```
- **isDeleted**: `Boolean`
  True if the attachment has been deleted.
- **width**: `Number|null`
  The width (in px) of the image, if the type is an image and the server is able to determine this information for the image.
- **height**: `Number|null`
  The height (in px) of the image, if the type is an image and the server is able to determine this information for the image.
- **exif_orientation: `Number|null`
  The exif orientation information extracted from the image (1-8) if present
```

width/height/exif_orientation are stored in the `/vendor/messagingengine.com/imagesize` annotation, which if present and set is a JSON string, which is a JSON object which maps "IMAP.part.number": [ width, height, exif-orientation (optional) ].

isDeleted is true if the mime type of the attachment is text/x-me-removed-file, otherwise it is false

**Comment by rsto** [comment]
I started working on this and we agreed to not require a FastMail-specific JMAP capability for now. I'm wondering, though: could we move the image-specific properties into their own property, e.g.

    "imageSize": { "width": 1, "height": 2, "exifOrientation": 3 }

I'm OK if we use snake case vs camel casing, but it just occurred to me that the properties don't adhere to the normal JMAP naming conventions. I would prefer to have them in their own "imageSize" property, though, as this would make the code cleaner.

**Comment by neilj** [comment]
I'm fine with that. Let's go with this as the spec:

- **imageSize**: `ImageSize|null`
  Information about the width/height/orientation of the image, if the EmailBodyPart type is an image and the server is able to determine this information for the image.

    An **ImageSize** object has the following properties:

    - **width**: `Number`
      The width (in px) of the image.
    - **height**: `Number`
      The height (in px) of the image.
    - **exifOrientation**: `Number|null`
      The exif orientation information extracted from the image (1-8),
      if present.

**Comment by rsto** [comment]
I've added both `imageSize` and `isDeleted`. Note that Cyrus does not check the validity of the `imageSize` property value, other than requiring the object keys to be part IDs. E.g. the annotator is free to change the type signature to whatever it pleases.
