### ISSUE TITLE
Email/parse does not fill in default charset

### ISSUE THREAD

**Issue by wolfsage** [cyrusimap/cyrus-imapd#2442]
If Email/parse is called on an attached email and the email has text/plain subparts that don't specify a charset, the charset comes back null when it should be 'us-ascii'.

**Comment by wolfsage** [comment]
(Tested with an attached email as message/rfc822, encoded base64

**Comment by rsto** [comment]
In my understanding returning `null` in this case is exactly what the spec asks for:

Currently, the spec defines:

    charset: String|null The value of the charset parameter of the Content-Type header field, if     
    present, or null if the header field is present but has no charset parameter. If there is no Content-
    Type header field, this is the implicit charset as per the MIME standard (us-ascii).

E.g. If you provide a Content-Type header on the MIME part, but no charset parameter, then the charset property MUST be null. See also these new tests: https://github.com/cyrusimap/cassandane/commit/0fbdc0478d0f61dc0c73753594f1e2cbc1058229 that assert this.

Frankly, there could be an issue still, as I haven't round-tripper all combinations on Email/parse with and without base64 or Email/get. But as it currently stands, I don't think the current implementation is violating the spec.

**Comment by wolfsage** [comment]
I think the spec may be wrong here. Depending on what we mean this field to mean I suppose.

charset is 'us-ascii' if the header isn't there *OR* if the header is present but does not include a charset specification as far as I understand it.

Also I'll note that Email/get appears to be defaulting the charset to us-ascii in either case, but Email/parse is not, I think

**Comment by rsto** [comment]
> charset is 'us-ascii' if the header isn't there OR if the header is present but does not include a charset specification as far as I understand it.

Yes, that would make sense to me as well.

> Also I'll note that Email/get appears to be defaulting the charset to us-ascii in either case, but Email/parse is not, I think

That's likely. Unfortunately they do not share the same parser code due to internals... I'd like Email/parse and Email/get to return consistent results, but without a spec change we'd need to make Email/get return JSON `null` for undefined `charset` parameters on an existing `Content-Type` header.
