### ISSUE TITLE
Add caching to Foo/query responses

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#2446]
A frequent pattern is to fetch the first N records (position: 0, limit: 30) and then almost immediately fetch the next page from the same query (position: 31, limit 30).

If we cache the dataset for a particular query at a particular modseq, then while there are no changes, the next responses can be made very quickly!

This could also be used to calculate very accurate /queryChanges by having the old state to compare to the new state rather than having to do scanning based on modseq, if the old queryState is present.

**Comment by rsto** [comment]
Implemented in https://github.com/cyrusimap/cyrus-imapd/commit/f353a15260c6bf9b5854b481c31afb4a6bfe5577
