### ISSUE TITLE
Cache conversation/message ids in request

### ISSUE THREAD

**Issue by rsto** [cyrusimap/cyrus-imapd#2447]
Almost all Email-related JMAP methods in Cyrus require us to traverse conversations.db for a mapping from conversation id to message ids. We should speed up these requests, by caching the mappings in-memory.

**Comment by brong** [comment]
I'm less convinced by this than I was - unless you really know you need it, the cost of maintaining the hash it wasted, and that code is a lot of mallocs and not really cheap.  We'd want to create a special datastructure if we did this.

**Comment by rsto** [comment]
Agree. Let's close this until it shows up to eat too much runtime resources.

**Comment by elliefm** [comment]
In case this comes back, can the "a lot of mallocs" be avoided by using our hash table implementation's memory pool functionality?  Or would the cache lifetime make that unsuitable?
