### ISSUE TITLE
Provide a way to see Intermediate folders in LIST output via IMAP

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#2468]
This is the flip side of having all those lovely INTERMEDIATEs available via JMAP.  We also want a way to see the MAILBOXIDs via IMAP, which means allowing LIST "" * RETURN (MAILBOXID) to return them along with \Noselect or \NonExistant.

Some options:

* LIST "" RETURN (MAILBOXID INTERMEDIATES)
* An imapd.conf option to turn it on
* always return them (is there a protocol requirement not to?)

**Comment by ksmurchison** [comment]
So, are we actually proposing a new LIST return option for MAILBOXID or are we just going to leverage LIST-STATUS and the MAILBOXID STATUS attribute?  If the former, how will MAILBOXID actually be returned?

**Comment by ksmurchison** [comment]
Hmm.  If the mailbox is \NonExistent (its an intermediate) can we actually return a STATUS response?  Perhaps we do need a new MAILBOXID return option.

**Comment by ksmurchison** [comment]
And this from RFC 5258 also complicates things:

   The "\NonExistent" attribute indicates that a mailbox name does not
   refer to an existing mailbox.  Note that this attribute is not
   meaningful by itself, as mailbox names that match the canonical LIST
   pattern but don't exist must not be returned unless one of the two
   conditions listed below is also satisfied:

   a.  The mailbox name also satisfies the selection criteria (for
       example, it is subscribed and the "SUBSCRIBED" selection option
       has been specified).

   b.  "RECURSIVEMATCH" has been specified, and the mailbox name has at
       least one descendant mailbox name that does not match the LIST
       pattern and does match the selection criteria.

**Comment by ksmurchison** [comment]
Has the current implementation proven sufficient?

**Comment by brong** [comment]
It looks great to me - it hasn't been deployed widely and tested fully
yet though.

On Wed, Aug 15, 2018, at 00:47, Ken Murchison wrote:
> Has the current implementation proven sufficient?


> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].
--
  Bron Gondwana, CEO, FastMail Pty Ltd
  brong@fastmailteam.com



Links:

  1. https://github.com/cyrusimap/cyrus-imapd/issues/2468#issuecomment-412898184
