### ISSUE TITLE
Implement addedDates and removedDates support

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#2476]
FastMail specific foo, but eventually supposed to be part of imapdata in JMAP maybe.

**Comment by robmueller** [comment]
Quick look at the code, (...I think...) since we already lookup and open each mailbox in _email_mailboxes and find the record, we should update that to extract the added date and removed date timestamps in that loop, rather than doing it yet again in a separate loop

**Comment by ksmurchison** [comment]
https://github.com/cyrusimap/cyrus-imapd/pull/2828
