### ISSUE TITLE
update _email_expunge to take a UID list and create a single mboxevent

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#2478]
One downside of the current JMAP _email_expunge is that, unlike UID STORE 1,3,4 +FLAGS \Deleted followed by UID EXPUNGE 1,3,5 in IMAP, it generates on MBOXEVENT per expunge.  We could optimise this by passing a list of UIDs rather than a single UID down to _email_expunge.

**Comment by rsto** [comment]
Fixed by brong in https://github.com/cyrusimap/cyrus-imapd/commit/2f5b644028445b4b15dc8ff3e739e2e0c1f44122
