### ISSUE TITLE
Email/copy from secondary account to primary account fails

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#2485]
1 | {…}
-- | --
create | {…}
copy0 | {…}
id | M6b7e46f9f6b7f670f2b7934f
keywords | {…}
mailboxIds | {…}
f308221c-64e5-4149-80c2-8bf71c644025 | true
fromAccountId | ub6744117
toAccountId | uac7641b2

Response is:

1 | {…}
-- | --
created | null
fromAccountId | ub6744117
accountId | uac7641b2
toAccountId | uac7641b2
not_created | {…}
copy0 | {…}
type | invalidProperties
properties | […]
0 | mailboxIds

I am brong@brong.net and this is the destination folder:

brong.net!user.brong.Test4	%(A %(admin lrswipkxtecdan brong@brong.net lrswipkxtecdn anyone p) I f308221c-64e5-4149-80c2-8bf71c644025 P default V 1534469981 C 38847234 F 38852368 M 1534940263)

uac is me, ub6 is test2@brong.net, my testing account I'm trying to copy from.  I have "lrs" ACL on the source folder.

**Comment by ksmurchison** [comment]
Are you not running this request as yourself?  I added an (uncommitted) test to JMAPMail.email_copy that copies the email from the destination mailbox back to the source and it works just fine - after disabling the bogus alreadyExists check in Cyrus (it simply checks whether the GUID exists regardless of whether the email has been expunged)

**Comment by brong** [comment]
It turns out my issue was that the FastMail middleware wasn't translating the accountIds into CyrusName format properly.  Fixed that, and it works fine.  Sorry for the noise.
