### ISSUE TITLE
Headers fetch is inefficiently loading all headers before determining if cache will satisfy

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#2489]
Gonna give both of you this one to look at!  The FastMail UI starts by fetching:

"properties":["threadId","mailboxIds","keywords","hasAttachment","from","to","subject","receivedAt","size","preview","header:x-spam-score","trustedSender"] 

Unfortunately, the header:, despite being available from the cache, triggers a load of all headers, and those headers are loaded from disk.

We want anything that only needs cache to only load cache, so headers:foo requests will need to be filtered for cache status and only the cache headers loaded if that's all that's needed.  I think this should be reasonably easy, a pre-processing stage to say "only needs cache" and then read from there.  Obviously full headers, or if there's even ONE non-cached header, can all come from the actual message at the same cost as pull them from cache

(imapd doesn't have those smarts, it will load both cache AND disk file if there are headers from both)

**Comment by rsto** [comment]
Fixed with https://github.com/cyrusimap/cyrus-imapd/commit/d34ffcc8ec92e3f76f1c921767039344f00c21b6
