### ISSUE TITLE
Just doing Contact/set#update { "importance" : ... } shouldn't need write access

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#2491]
importance is a per-user annotation.  It should be allowed to be updated without needing WRITE ACLs.

Tagging both of you in here since there's probably space for discussion of where to do the ACL checks and normalising them across the codebase.

(this will be a real issue for shared addressbooks for non-admins at FastMail)

**Comment by brong** [comment]
Likewise for setting Seen on messages, etc.  Though that might already be fixed.

**Comment by ksmurchison** [comment]
I assume this is mostly aimed at changing JUST importance rather than the vCard data itself?

**Comment by ksmurchison** [comment]
Never mind, the subject already says that.
