### ISSUE TITLE
Setting recurrenceRule/until doesn't change the event

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#2502]
I just tried the delete this and future via JMAP again:

a6e31a35-bccf-41ee-acf1-0948534d86dc | {…}
-- | --
recurrenceRule/until | 2018-09-07T09:00:00
relatedTo/937a8d91-ae2a-4070-a8c9-bff44e82c3e2 | {…}
relation | {…}
0 | next

It claims to have worked, but the RRULE in the event on disk doesn't have an end.

**Comment by rsto** [comment]
Fixed in https://github.com/cyrusimap/cyrus-imapd/commit/099335c1b94904aab93ef1d8204d9f9704d96138
