### ISSUE TITLE
JMAP creates calendar events which CalDAV rejects

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#2506]
The JMAP code creates:

```
PRODID:-//CyrusJMAP.org/Cyrus 3.1.5-402-ged1dc7a-fmnext-20180831v1//EN
BEGIN:VTIMEZONE
TZID:Australia/Melbourne
COMMENT:[AU] Victoria
LAST-MODIFIED:20180528T034953Z
X-LIC-LOCATION:Australia/Melbourne
TZUNTIL:20180906T020000Z
BEGIN:STANDARD
TZNAME:AEST
TZOFFSETFROM:+1000
TZOFFSETTO:+1000
DTSTART:20180906T110000
END:STANDARD
END:VTIMEZONE
```

But this same event is rejected over CalDAV:

```
<D:error xmlns:D="DAV:" xmlns:C="urn:ietf:params:xml:ns:caldav">
  <C:valid-calendar-data/>
  <D:responsedescription>Failed iTIP restrictions for COMMENT property. Expected 0 instances of the property and got 1</D:responsedescription>
</D:error>
```

**Comment by ksmurchison** [comment]
Update to latest libical

**Comment by brong** [comment]
OK, I'm doing that :)  Question though - will that mean these events are accepted over CalDAV?  If not, we'll have to go through and fix all existing events.

**Comment by ksmurchison** [comment]
They should be accepted over CalDAV unedited.

**Comment by ksmurchison** [comment]
Did upgrading libical solve the problem?

**Comment by brong** [comment]
So... maybe, but this does raise a question of "are we sending these things out via IMIP?" because if they aren't going to be accepted by all systems, we probably need to stop that too!

**Comment by brong** [comment]
This is fixed in master now.
