### ISSUE TITLE
CalendarEvent/get#participants doesn't include ORGANIZER if not also an ATTENDEE

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#2512]
Particularly when you receive an iTIP message, it contains just the ORGANIZER and the ATTENDEE for the recipient.  When that gets fetched, the ORGANIZER's email address is in the replyTo, but not in the participants object.

The Organizer's address should be in the participants, with just the "owner" role.

**Comment by rsto** [comment]
We'll rework the whole participant/replyTo mapping from/to iCalendar

**Comment by rsto** [comment]
Done in https://github.com/cyrusimap/cyrus-imapd/commit/3d0006e9427ef937da5e533450910d1135fb35d0
