### ISSUE TITLE
CalendarEvent/get#participantId should come from x-schedule-user-address header

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#2513]
We add a header X-Schedule-User-Address to every message with scheduling data when storing it to disk.  The "participantId" value should come from that header if it's present, using the same logic as caldav uses in propfind_scheduser().

Similarly we need to set that header when creating new calendar events (this may also be happening, I havne't checked that).

**Comment by rsto** [comment]
Fixed in https://github.com/cyrusimap/cyrus-imapd/commit/29fd40ff405da3103d7be016e3c7d84c3e2bb1ac
