### ISSUE TITLE
Email/query filtering on 'bcc' does not work

### ISSUE THREAD

**Issue by wolfsage** [cyrusimap/cyrus-imapd#2514]
We should be able to filter on 'bcc' according to the spec:

````
bcc: String Looks for the text in the Bcc header field of the message.
````

but this does not appear to limit results at all.

**Comment by rsto** [comment]
I can't reproduce this issue, e.g. this test passes fine https://github.com/cyrusimap/cassandane/commit/40b6305450f73dcffe6b638a5b3c2ded04e82002

Could you please let me know the setup of your test case?
