### ISSUE TITLE
Message text for cyr_virusscan should be controllable

### ISSUE THREAD

**Issue by postilion** [cyrusimap/cyrus-imapd#2516]
The current message template for reporting viruses, in cyr_virusscan, is hard coded in append_notifications().  This should be controllable by the admin, to allow for local site preference, or language needs.

**Comment by jh1995** [comment]
Duplicate of https://github.com/cyrusimap/cyrus-imapd/issues/1845 ? Anyway, this enhancement is needed.

**Comment by elliefm** [comment]
This is probably easy to backport to 3.0 but it's not really tested enough to be shipping as a stable feature.

If you'd like a 3.0 backport of this to test and provide feedback on, @ me and I'll rebase a branch for you.  Otherwise, it'll be master-only until 3.2 ships :)
