### ISSUE TITLE
setseen on shared accounts is broken if the message it in two folders

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#2520]
This is regardless of whether the user can see them both or not!  I have added three tests in:

https://github.com/brong/cassandane/commits/shared-twofolder

Which show how it should behave.  I have debugged this to:

_email_bulkupdate_plan_keywords does:

```
8393	            int r = seen_open(bulk->req->userid, SEEN_CREATE, &plan->seendb);
8394	            if (!r) seen_lockread(plan->seendb, plan->mbox->uniqueid, &plan->old_seendata);
```

NOTE: there's a bug here already that the result of seen_lockread isn't being checked.

But the deeper problem is, seen_db is global per user, and it's for the logged in user, so it should be stored in the request, not in the per-folder plan.  It should also be loaded on request, so that we don't later open it again when we go to read in the keywords:

```
8463	            /* Convert flags to JMAP keywords */
8464	            struct email_keywords keywords = _EMAIL_KEYWORDS_INITIALIZER;
8465	            _email_keywords_init(&keywords, bulk->req->userid, &seenseq_by_mbox_id);
8466	            msgrecord_t *mr = NULL;
8467	            int r = msgrecord_find(plan->mbox, uidrec->uid, &mr);
8468	            if (!r) _email_keywords_add_msgrecord(&keywords, mr);
```

Because that does its own seen db open and read, and the seen_db is already open!

Likewise when we write, we should accumulate a list of all messages per mailbox which are updated (either adding or removing seen), then write out the seendb entry for that uniqueid just the once at the end.  This is just an efficiency thing.  In fact, _email_keywords_add_msgrecord should really be using a seen state stored in to the plan as well, so that it can avoid having to parse the full sequence for every message.

(In fact - maybe even the BEST approach would be to store the seen state in the struct mailbox, and do all the read/update/delete from there, so the seen commit can happen along with the mailbox commit!)

**Comment by rsto** [comment]
Agreed, I'm working on a fix to move seendb out of the per-mailbox loops. Note that we already cache both sequence sets in /get and /set, and write them once per mailbox in /set. I'll port the same bulk update logic to /copy.

**Comment by rsto** [comment]
Fixed in https://github.com/cyrusimap/cyrus-imapd/commit/e636207cee6052c61bc18945562c106489508607 and https://github.com/cyrusimap/cyrus-imapd/commit/5981187fa08d7a02efe2b379c7c5ab8d70f07be1

After discussion we decided not to implement bulk Email/copy until there is a clear need for its performance gain.
