### ISSUE TITLE
JMAP: Don't break encoded mime headers across character boundaries

### ISSUE THREAD

**Issue by robmueller** [cyrusimap/cyrus-imapd#2529]
The current JMAP MIME header encoder can create invalid encodings.
```
  Each 'encoded-word' MUST represent an integral number of characters.
  A multi-octet character may not be split across adjacent 'encoded-
  word's.
```
An example generated when sending a message via JMAP. The following subject line:
```
😀😃😄😁😆😅😂🤣☺️😊😇
```
Which is these unicode code points:
```
\x{1f600}\x{1f603}\x{1f604}\x{1f601}\x{1f606}\x{1f605}\x{1f602}\x{1f923}\x{263a}\x{fe0f}\x{1f60a}\x{1f607}"
```
Which has this utf-8 encoding (spaces added between each unicode code point only for clarity)
```
\xf0\x9f\x98\x80 \xf0\x9f\x98\x83 \xf0\x9f\x98\x84 \xf0\x9f\x98\x81 \xf0\x9f\x98\x86 \xf0\x9f\x98\x85 \xf0\x9f\x98\x82 \xf0\x9f\xa4\xa3 \xe2\x98\xba \xef\xb8\x8f \xf0\x9f\x98\x8a \xf0\x9f\x98\x87
```
But this is the header we generate:
```
Subject: =?UTF-8?Q?=F0=9F=98=80=F0=9F=98=83=F0=9F=98=84=F0=9F=98=81=F0=9F=98=86=F0?=
 =?UTF-8?Q?=9F=98=85=F0=9F=98=82=F0=9F=A4=A3=E2=98=BA=EF=B8=8F=F0=9F=98=8A?=
 =?UTF-8?Q?=F0=9F=98=87?=
```
Note how we split the bytes in a single code point between separate "encoded-word"s. :(

Ironically, we don't display these emails correctly, but there's actually a separate issue about trying to fix them up because other systems generate this rubbish!

https://github.com/cyrusimap/cyrus-imapd/issues/2471

If we had fixed that issue, we wouldn't have as easily noticed this issue! We should probably create a cassandane test to detect this brokenness and make sure we don't accidentally generate in the future again, even if we do end up detecting and fixing it when reading back an email.

**Comment by brong** [comment]
I've fixed this one by making it run a little longer to split at the right point.
