### ISSUE TITLE
Spam in IRC channel

### ISSUE THREAD

**Issue by jasontibbitts** [cyrusimap/cyrus-imapd#2536]
I'm sure this isn't the right place, but if any of the devs has ops in the IRC channel or can find someone who has ops or ask the Freenode staff or, well, anything...  Could the channel mode get set to require registration?  Most other channels have done that to cut down on the spam that's plaguing Freenode.  I don't know enough about IRC to know what the magic sequence is, but I can find out.

I figure someone changes the topic on the channel so someone must have ops.

Edit: those I've asked say to use either mode `+r` or `+q $~a`.  The latter lets ops see messages from unidentified users (so they can still get some help on getting registered) but everyone else is free from spam.

**Comment by brong** [comment]
We've been having trouble finding someone with Ops.  I've emailed Freenode and asked them if they can help.

**Comment by jasontibbitts** [comment]
So this got taken care of; I ended up with ops in the channel and set the mode to `+q $~a` to quiet all unauthenticated nicks.  The channel has been free of spam for a few hours now, so maybe that was enough.  I'd say this is done, though maybe having another Fastmail person with ops wouldn't be a bad idea.
