### ISSUE TITLE
JMAP: Implement Mailbox#isSeenShared

### ISSUE THREAD

**Issue by neilj** [cyrusimap/cyrus-imapd#2563]
(This is a custom extension and should eventually be put behind the same capability strings as `Mailbox#shareWith`)

Add support to get/set the following Mailbox property:

- **isSeenShared**: `Boolean` (default: true)
  If true, everyone sees the same read/unread state. If false, each sharee gets their own read/unread status for messages in this mailbox.

**Comment by rsto** [comment]
@ksmurchison can we close this one?
