### ISSUE TITLE
Making idle socket addresses should not be wrapped in assert()

### ISSUE THREAD

**Issue by zlynx** [cyrusimap/cyrus-imapd#2564]
In imap/idle.c the following two lines are dangerously wrong:

    122     assert(idle_make_client_address(&local));
    123     assert(idle_make_server_address(&idle_remote));

Asserts should never be used for necessary program functions.

Even if arguing that idle.c uses the lib/assert.h which is not affected by `#define NDEBUG` instead of the C Library assert.h is risky because the cyrus source code is not consistent on this point: some source files use `#include <assert.h>` and sometimes `#include "assert.h"`. If relying on particular behavior from a function named `assert()` it should use a different name than the standard library version of it. Maybe `xassert()`.

A quick check with grep seems to show that these two lines are the only assert calls with necessary side effects.

They should be changed to assign to a result variable, then assert that result variable is true.

**Comment by elliefm** [comment]
Thanks for the PR, I've also cherry-picked this to the 3.0 branch :)
