### ISSUE TITLE
JMAP: Implement custom Email/query sort option: `addedDates`

### ISSUE THREAD

**Issue by neilj** [cyrusimap/cyrus-imapd#2568]
Sort by `[{"property": "addedDates", "mailboxId": "foo" }]` should sort messages in the query by the date they were added to mailbox with id `foo` (can use either SAVEDATE information or IMAP UID; should give the same result either way). If the message is not in mailbox `foo` sort it after one that is.

(The name will tie in to exposing SAVEDATE over JMAP)

**Comment by brong** [comment]
Basic implementation that will work for our use case slapped together in d0242b6428d69d55aebd1220c95f46ab08d92b94
