### ISSUE TITLE
JMAP: Sort by `from` is not correct

### ISSUE THREAD

**Issue by neilj** [cyrusimap/cyrus-imapd#2574]
The spec says:

**from** – This is taken to be either the “name” part, or if null/empty then the “email” part, of the first `EmailAddress` object in the from property. If still none, consider the value to be the empty string.

But if you sort by from, Cyrus currently seems to just look at the localpart of the email address (not even the full email address including the domain for some reason).

**Comment by rsto** [comment]
OK, so that's because Cyrus sorts according to IMAP [RFC 5256]( https://tools.ietf.org/html/rfc5256):

         FROM
         [IMAP] addr-mailbox of the first "From" address.

and likewise for `CC` and `TO`.

Which means, for JMAP we'll need to add additional sort operators for these fields to the Cyrus search API.
