### ISSUE TITLE
Email/query with mailboxId filter showing deleted emails from up to a week ago

### ISSUE THREAD

**Issue by robmueller** [cyrusimap/cyrus-imapd#2576]
If I search by Inbox for:

`subject:"[plumbing]"`

The UI generates an Email/query this filter:
```
filter {…}
  inMailbox 7ca07c9844751b4f
  subject "[plumbing]"
```
The list of emailIds returned:
```
ids […]
0 Mebe497d3d7db3dbd37cd5195
...
11 M157d36503fde30733caced66
```
But the Email/get query on those id's shows things like (looking at the last one for example):
```
from […]
hasAttachment false
id M157d36503fde30733caced66
keywords {…}
mailboxIds {…}
  0ad75de34850a900 true
preview ...
receivedAt 2018-10-23T00:45:27Z
size 23274
spamScore 0
subject ...
threadId T848eefb134b73b61
to […]
trustedSender null
```
Note that mailboxIds has only 0ad75de34850a900 in it (my Archive folder), not 7ca07c9844751b4f as was in the original filter (by Inbox).

As @brong speculated:
> What's the chance it was originally in the Inbox and got deleted from there within the past week?

Yes, this seems likely to be the case, it's only showing emails in my inbox back to Oct 23, 1 week ago!

**Comment by rsto** [comment]
We need #2528 resolved to fix this.

**Comment by rsto** [comment]
I've just pushed b5990f0 to master, which fixes this. Once the conversations.db patch is merged successfully I'll close this issue.

**Comment by rsto** [comment]
Now that conversations.db is rewritten, this isn't an issue anymore.
