### ISSUE TITLE
JMAP: Incorrect Email/query results

### ISSUE THREAD

**Issue by neilj** [cyrusimap/cyrus-imapd#2578]
Steps to reproduce:
1. Search within a mailbox (alt-enter in the search box in FastMail)
2. Move one of the messages to another folder.
3. Note the message does not disappear from the message list – this is because Email/query still returns it as a result, even though the message is no longer in the mailbox. You can even reload the page and still see it appear, but if you open the message you'll see it's actually just in the other folder.

**Comment by rsto** [comment]
We need https://github.com/cyrusimap/cyrus-imapd/issues/2528 resolved to fix this.

**Comment by rsto** [comment]
I've just pushed https://github.com/cyrusimap/cyrus-imapd/commit/b5990f0aceffc1aaa040d1f2eff248332753518f to master, which fixes this. Once the conversations.db patch is merged successfully I'll close this issue.
