### ISSUE TITLE
Search indexes non-visible text

### ISSUE THREAD

**Issue by neilj** [cyrusimap/cyrus-imapd#2579]
(I'm presuming this is the same for JMAP and IMAP). Our search is indexing all sorts of non-user visible text which makes the search results appear broken if you hit one of them:

1. HTML tags. We should be ignoring these (and CSS/JS too). e.g. Try searching for "div"…
2. iCalendar structure. e.g. search for "rrule" – we should only be matching the user-inserted text, not any surrounding structural guff.

**Comment by neilj** [comment]
> I just tested this and tags are omitted from the index for text/html messages. I can reproduce this issue if the Content-Type header erroneously is set to text/plain, though. Could that be the issue?

You're right. There's not a bug here, this was just broken emails where the sending system just shoved the HTML in as a text/plain alternative part directly. *Sigh*. Don't worry about that.

Would be good to index the iCalendar files better though.

**Comment by rsto** [comment]
Meh, what a pain. The iCalendar fix already landed on master at https://github.com/cyrusimap/cyrus-imapd/commit/1595a1e06d9d477f0861b15df39ee321491069eb
