### ISSUE TITLE
JMAP Email#set rejecting references without @

### ISSUE THREAD

**Issue by neilj** [cyrusimap/cyrus-imapd#2580]
When setting the `references` property (a.k.a `header:References:asMessageIds`) Cyrus seems to be rejecting it if there's a string in the array that's not got an `@` in it. While technically invalid, if the message being replied to has this as a message id, that's what we need to use! I think it would be better for Cyrus just to treat these as opaque strings. Other than stripping any illegal characters (e.g. newline), just wrap them in angle brackets and put a space between each one.

Example of the References header from the email being replied to (which Cyrus parses correctly and returns to the client as an array of strings):

```
References: <1534611546.4022715.1478441344.3208AB2C@webmail.messagingengine.com> <201808182023.w7IKNJ1F091375@flpd596.prodigy.net> <cCjl1y02r2fuMPN01CjnwL> <000101d475bc$6ee5ea90$4cb1bfb0$@cox.net> <BN6PR04MB06422A5C2823A574012AA471B1CB0@BN6PR04MB0642.namprd04.prod.outlook.com> <201811061236.wA6CavVH072754@alph739.prodigy.net>
```

**Comment by rsto** [comment]
We introduced strict message-id parsing in response to #2499. I agree that we need make the check more lenient, if there's bogus message-ids out there. For now, I'll make Cyrus accept message-ids in the following forms

    [CFWS] "<" id-left "@" id-right ">" [CFWS]

and

    [CFWS] "<" id-left ">" [CFWS]

**Comment by rsto** [comment]
Digging more into the code, it's not that simple. conversations.db is doing its own check on msg-id, including a check for `@` and aborting with INVALID_IDENTIFIER if not found.

I wonder how the message of your example could actually end up in Cyrus, it should have failed on APPEND. Is that a recently created mail?
