### ISSUE TITLE
JMAP: Translation of ATTACH to JSCalendar

### ISSUE THREAD

**Issue by neilj** [cyrusimap/cyrus-imapd#2583]
When translating an iCalendar `ATTACH` property into a JSCalendar `link`, the *Link* object should always have a `"rel": "enclosure"` property. This is what signifies the link should be considered an attachment to the event.

(Likewise, when translating back from JSCalendar, if there's a rel="enclosure" property then this should be made into an `ATTACH` iCalendar property. Otherwise, it should probably be a `URL` iCalendar property.)

**Comment by rsto** [comment]
This patch should cover the current issue: https://github.com/cyrusimap/cyrus-imapd/commit/6adf9db3a63079ab798f9cd8e57cf9747fb2896c 

It sets `rel: enclosure` for all `ATTACH` properties that haven't explicitly set `rel` to some other value or deleted it. It still allows JMAP clients to not set `rel` at all, so we should decide how to handle this.

I'm not convinced the `URL` property is the right fallback for Links that aren't `enclosure`. Its description in [RFC 7986](https://tools.ietf.org/html/rfc7986#section-5.5) reads more like what we try to accomplish with `rel: describedby` in a JSCalendar Link:

       This property may be used to convey a location where a more
       dynamic rendition of the calendar information can be found.

and this is a pain:

       This property can be specified once in an iCalendar object.

The current patch complies with JSCalendar, as it allows clients to set no `rel` at all. A non-existent `rel` is currently represented in our internal iCalendar store as an empty X parameter value:

      ATTACH;X-REL=:http://example.com/some.url

I'd prefer to amend the spec and make `enclosure` the default value for a Link objects `rel` property, so there's always a `rel` set. I think we should keep on using `ATTACH` with our `X-REL` parameter in iCalendar.

**Comment by neilj** [comment]
OK, so then we translate `rel=describedby` to `URL` and everything else to `ATTACH` and we make the `rel` property in JSCalendar default to `enclosure` if omitted, right?

**Comment by neilj** [comment]
I'm happy with that.

**Comment by rsto** [comment]
> OK, so then we translate rel=describedby to URL and everything else to ATTACH and we make the rel property in JSCalendar default to enclosure if omitted, right?

We can do that for one Link having `rel=describedby`, but if there are multiple we either need to fall back using a custom `X-URL` property or use an `ATTACH` property. I'd rather use `ATTACH` in this case, as we would otherwise hide the link from iCalendar clients.

**Comment by neilj** [comment]
OK, sounds good.

**Comment by rsto** [comment]
Fixed in https://github.com/cyrusimap/cyrus-imapd/commit/ba5c85b344f581e2762a8cb33e7da04cb151856b
