### ISSUE TITLE
JMAP: Email/query sort by addedDates is reversed

### ISSUE THREAD

**Issue by neilj** [cyrusimap/cyrus-imapd#2584]
If I sort by `addedDates` with `isAscending: false`, the results should go from "most recently added" to "least recently added" (the added date should be decreasing in value as you go through the list). At the moment it looks like this might be reversed.

**Comment by rsto** [comment]
That was supposed to be fixed a couple of days ago in https://github.com/cyrusimap/cyrus-imapd/commit/f064fc274fc46ebcfc1d9af7ed908dbcc65026e4 and is tested in https://github.com/cyrusimap/cassandane/commit/78970e49ae4668d942e7a6c853aac911be27e2e7.
