### ISSUE TITLE
VALARMS need to contain properties per RFC5545 when created via JMAP

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#2610]
https://tools.ietf.org/html/rfc5545#section-3.6.6

VALARM must contain ATTENDEE, DESCRIPTION and SUMMARY.

**Comment by rsto** [comment]
Fixed in https://github.com/cyrusimap/cyrus-imapd/commit/979b344953cfea74c66d8f1ae2f36f597e9fd99b
