### ISSUE TITLE
Build failure with clamav 0.101

### ISSUE THREAD

**Issue by jasontibbitts** [cyrusimap/cyrus-imapd#2621]
It appears that clamav 0.101 has changed API.  Sadly you can't compile anything with 0.101 because somehow the header files are messed up, but if you apply the patch which will soon be released as 0.101.1 then you get the following failure:
```
imap/cyr_virusscan.c: In function 'clamav_scanfile':
imap/cyr_virusscan.c:197:21: error: 'CL_SCAN_STDOPT' undeclared (first use in this function); did you mean 'CL_DB_STDOPT'?
                     CL_SCAN_STDOPT);
                     ^~~~~~~~~~~~~~
                     CL_DB_STDOPT
imap/cyr_virusscan.c:197:21: note: each undeclared identifier is reported only once for each function it appears in
make[2]: *** [Makefile:4816: imap/cyr_virusscan.o] Error 1
```
Looking at the source, I think CL_SCAN_STDOPT is just gone.  This appears to be the clamav commit which removed it: 
https://github.com/Cisco-Talos/clamav-devel/commit/048a88e61558726bd9ba66ec3195b63d61d8a430#diff-62d8b38a9494ba8e4e7a6fad6d61a935L181
It appears from other changes in that commit that you're just supposed to use ~0 now.

Anyway, sadly it doesn't appear that they maintained compatibility so while I can bodge something together on my end but I don't know the best way to support both old and new clamav libraries.  Here's how another Fedora package is handling the change: https://src.fedoraproject.org/rpms/klamav/blob/master/f/klamav-0.46-clamav-0.101.patch

**Comment by jasontibbitts** [comment]
Here's what I'm using in Fedora.  It applies against 3.0.8, builds and passes Cassandane tests (which do at least do some testing of virus scanning).

```
diff --git a/imap/cyr_virusscan.c b/imap/cyr_virusscan.c
index 863a858..b6c8980 100644
--- a/imap/cyr_virusscan.c
+++ b/imap/cyr_virusscan.c
@@ -192,9 +192,19 @@ int clamav_scanfile(void *state, const char *fname,
     struct clamav_state *st = (struct clamav_state *) state;
     int r;

-    /* scan file */
+#ifndef CL_SCAN_ARCHIVE /* clamav >= 0.101 */
+    struct cl_scan_options options;
+    memset(&options, 0, sizeof(struct cl_scan_options));
+    options.parse |= ~0; /* enable all parsers */
+    options.general |= CL_SCAN_GENERAL_HEURISTICS; /* enable heuristic alert options */
+
+    r = cl_scanfile(fname, virname, NULL, st->av_engine,
+                    &options);
+
+#else
     r = cl_scanfile(fname, virname, NULL, st->av_engine,
                     CL_SCAN_STDOPT);
+#endif

     switch (r) {
     case CL_CLEAN:
```

**Comment by elliefm** [comment]
> +    struct cl_scan_options options;
> +    memset(&options, 0, sizeof(struct cl_scan_options));

Is there a particular reason for the separate memset, vs just initialising to zeros (with something like `struct cl_scan_options options = {0};`)?  Some APIs provide initialiser macros for this sort of thing, like PTHREAD_MUTEX_INITIALIZER, so I wonder if the new ClamAV does?

Also, our style these days is to use sizeof() on the identifier (e.g. `sizeof(options)`, rather than on the type (`sizeof(struct cl_scan_options)`). We've been bitten by a bunch of bugs in the past where a variable's type has been changed (e.g. from char to int) but some sizeof()'s were missed, which wouldn't have been a problem if they'd used the variable's identifier rather than its type in the first place.

I realise these are kinda nitpicky comments, but what that really means is "nice patch, thanks" and I'm just overthinking the details a little!

Do you have any further feedback on how this one is working on Fedora?  I'm happy to merge it I think, but I'm on Debian stable so I probably won't see an API-breaking ClamAV myself for ages.

**Comment by jasontibbitts** [comment]
To be fair, I'm only using code copied directly from the clamav example code.  I don't even know enough C to be able to comment on the memset versus initialization issue, and if some other Fedora package didn't already have a patch for this then I would have been lost trying to come up with it myself.

I wouldn't expect that you would take that patch directly; I just included it to show you how the API changed.  You probably want to at least have a look at the scan options which are being enabled. (Maybe even make them configurable, though that seems like it would be quite a pain.)

As far as it working, all I really have is the Cassandane test and a lack of anyone complaining that it's broken.  I can't see why it wouldn't work but it's not something I can really test properly since we do filtering on the MX side before things get to Cyrus.

**Comment by elliefm** [comment]
Thanks for the context!

The Cassandane test working or not is literally the entirety of what I go on, too. I'll have a quick look at the scan options, but "scan general heuristics" sounds defaulty enough, and if it's what their example code uses....

People who actually use the ClamAV feature can always chime in with an issue/pr if they have an opinion on some other way it should be done. :)

**Comment by elliefm** [comment]
Ohh lmao.  This is actually already fixed in git, just waiting for a new release -- #2614 was the PR :)

**Comment by jasontibbitts** [comment]
So, unfortunately 3.0.9 fails to build for me:
```
BUILDSTDERR: imap/cyr_virusscan.c: In function 'clamav_scanfile':
BUILDSTDERR: imap/cyr_virusscan.c:198:21: error: 'CL_SCAN_STDOPT' undeclared (first use in this function); did you mean 'CL_DB_STDOPT'?
BUILDSTDERR:   198 |                     CL_SCAN_STDOPT);
BUILDSTDERR:       |                     ^~~~~~~~~~~~~~
BUILDSTDERR:       |                     CL_DB_STDOPT
BUILDSTDERR: imap/cyr_virusscan.c:198:21: note: each undeclared identifier is reported only once for each function it appears in
BUILDSTDERR: make[2]: *** [Makefile:5987: imap/cyr_virusscan-cyr_virusscan.o] Error 1
```
So the code here is
```
#if LIBCLAMAV_MAJORVER < 9
    r = cl_scanfile(fname, virname, NULL, st->av_engine,
                    CL_SCAN_STDOPT);
#else
    static struct cl_scan_options options;

    memset(&options, 0, sizeof(struct cl_scan_options));
    options.parse |= ~0; /* enable all parsers */

    r = cl_scanfile(fname, virname, NULL, st->av_engine, &options);
#endif
```
and... I'm having trouble figuring out where LIBCLAMAV_MAJORVER is supposed to come from.  It's not in clamav.h and it isn't referenced anywhere else in the cyrus code.  It seems FreeBSD has a file clamav-config.h that doesn't seem to be installed by the clamav code.

Will patch in Fedora to conditionalize on `CL_SCAN_ARCHIVE` like I've been doing all along.

**Comment by elliefm** [comment]
Does this PR do the right thing for you? #2672 

I can't really test any of this, because I'm on debian stable and already have a clamav installation (of the older, working, version)

**Comment by jasontibbitts** [comment]
Yes, that does basically the same thing that I've been doing in Fedora.  It uses a different symbol but still one that's not defined by the current API.  So it should work fine.
