### ISSUE TITLE
JMAP: Not decoding name from MIME headers

### ISSUE THREAD

**Issue by neilj** [cyrusimap/cyrus-imapd#2623]
A user has an email which has a multipart/mixed part with headers like this:

```
--5de66f51bad94db9a957d57b4dd13aab
Content-Disposition: attachment;
 filename*0*="YGB-51-000-CON-GEN-AGR-0002 Power Station Owner's Assistance";
 filename*1*=" (FINAL 2).pdf"
Content-Type: application/pdf; name="=?UTF-8?Q?YGB-51-000-CON-GEN-AGR-0002_Power_Station_Owner=27s_Assistance?=
 =?UTF-8?Q?_=28FINAL_2=29=2Epdf?="
Content-Transfer-Encoding: BASE64

```

When fetched via JMAP, the body structure is returning `null` for the name though. The `type` and `disposition` fields are correctly returned (as `application/pdf` and `attachment` respectively).

**Comment by brong** [comment]
This appears to be ext-parameters, per:

https://tools.ietf.org/html/rfc5987

Combined with the existing way to split up long properties defined here:

https://tools.ietf.org/html/rfc2231#section-3

So I guess we need to be able to handle those!

**Comment by rsto** [comment]
That's odd, because we support these parameters since over a year. Eg. look at the tests here: https://github.com/cyrusimap/cassandane/blob/master/Cassandane/Cyrus/JMAPEmail.pm#L497

I'll look into why it doesn't work for the headers in the issue description.

**Comment by rsto** [comment]
The issue with the header value is that the extended `filename` parameter value contains an unencoded `'` character, which is a TSPECIAL according to [RFC2231](https://tools.ietf.org/html/rfc2231).

I've updated the charset library and JMAP mail parser to leniently handle this.
