### ISSUE TITLE
JMAP: Recurrence rule UNTIL conversion to/from iCalendar is broken

### ISSUE THREAD

**Issue by neilj** [cyrusimap/cyrus-imapd#2635]
I created a recurring event in timezone Australia/Melbourne with UNTIL set to 2018-02-11T23:59:59. When I fetch it back I get 2018-02-11T12:59:59.

Because iCalendar stupidly specifies that UNTIL must be in UTC, I'm presuming Cyrus is translating it from local time (as it is in JSCalendar) when converting to/from iCalendar. However it looks like the translation is not happening in one of the directions, so the incorrect value is either stored or returned, not sure which.

**Comment by ksmurchison** [comment]
Fixed with https://github.com/cyrusimap/cyrus-imapd/commit/bbfa572a4202caeb3fb788417bc35f7717351ad6
