### ISSUE TITLE
JMAP: Updating your participation status sets the event's sequence to 0

### ISSUE THREAD

**Issue by neilj** [cyrusimap/cyrus-imapd#2644]
Steps to reproduce:
1. Get sent an invitation with `SEQUENCE=1` and add it to your calendar
2. Patch your participation status to say you're going. Something like this:

```
[
      "CalendarEvent/set",
      {
        "accountId": "ue150411c",
        "update": {
          "a5fd2188-ff58-4673-9aea-966dce2fdcc1": {
            "participants/ced11a53269b358ad04a03e63c29cc02624000bc/participationStatus": "accepted"
          }
        }
      },
      "0"
    ]
  ],
```
3. Refetch the event.

Expected result: the `sequence` property of the event is still `1`.
Actual result: the `sequence` property of the event is now `0`!

**Comment by rsto** [comment]
Fixed in https://github.com/cyrusimap/cyrus-imapd/commit/295c68a090a424520e3278739b04b2b0a7e39ca2
