### ISSUE TITLE
reserved identifier violation

### ISSUE THREAD

**Issue by elfring** [cyrusimap/cyrus-imapd#2646]
I would like to point out that identifiers like “[`__CYRUS_IMAP_PARSE_H__`](https://github.com/cyrusimap/cyrus-imapd/blob/bb88f7f37e5fd3c3f3cf4fbd488839dec232f678/imap/imapparse.h#L43 "Update candidate")” and “[`_PASTE`](https://github.com/cyrusimap/cyrus-imapd/blob/bb88f7f37e5fd3c3f3cf4fbd488839dec232f678/imap/xstats.h#L53 "Another update candidate")” [do not fit](https://www.securecoding.cert.org/confluence/display/cplusplus/DCL51-CPP.+Do+not+declare+or+define+a+reserved+identifier "Do not declare an identifier which is reserved for the compiler implementation.") to the expected naming convention of the C++ language standard.
Would you like to adjust your selection for unique names?

**Comment by elliefm** [comment]
Cyrus is primarily a C project, not a C++ project, so the C++ language standard is not the appropriate standard to adhere to.  Do you have a similar reference for the C language?

**Comment by elfring** [comment]
How do you think about to [avoid](https://stackoverflow.com/questions/228783/what-are-the-rules-about-using-an-underscore-in-a-c-identifier#answer-228797 "What are the rules about using an underscore in a C++ identifier?") that this software [depends on undefined behaviour](https://www.securecoding.cert.org/confluence/display/c/CC.+Undefined+Behavior#CC.UndefinedBehavior-ub_106 "Avoiding undefined behaviour?")?

**Comment by elliefm** [comment]
Again, that stackoverflow link is about the _C++_ language and is largely not relevant to Cyrus (and your examples of issues in Cyrus are not from any of our small sections of C++ code).

The second link _is_ actually about C, but just says that using reserved identifiers is undefined.

**Comment by elfring** [comment]
Please [reduce the tampering with the reserved name space](https://en.cppreference.com/w/c/language/identifier#Reserved_identifiers "Description for reserved identifiers").
Would you like to achieve compliance with known programming standards?
