### ISSUE TITLE
GET /jmap returns 404 + Location (when missing trailing /); well-known redirects to /jmap

### ISSUE THREAD

**Issue by iNPUTmice** [cyrusimap/cyrus-imapd#2653]
Hi,

I’m encountering a problem when trying to do auto discovery for JMAP.
* `/.well-known/jmap` redirects to `/jmap` while it should probably redirect directly to `/jmap/`
* `/.well-know/jmap/` redirects to `/jmap/` (That doesn’t buy us anything since clients will request the well-know without the trailing `/`. But I found that interesting.)
* `/jmap` gives a `404` (when authenticated) and includes a Location Header (for `/jmap/`). I’m expecting a `301` instead so I can follow the redirect.
* `/jmap/` works and is the proper endpoint

I’m running cyrus master from a couple of weeks ago. After finally getting it to compile and running I don’t dare to recompile latest HEAD just now. But I looked through recent commits and this doesn’t seem fixed.

**Comment by rsto** [comment]
Thanks for reporting this. Fixed.

**Comment by iNPUTmice** [comment]
The 404 is indeed is in fact fixed. However I would suggest to make `.well-known/jmap` redirect directly to `/jmap/` instead of `/jmap` or else clients need to follow an entirely unnecessary redirect.

**Comment by rsto** [comment]
This would require more changes on the core HTTP handlers in Cyrus. I expect it's reasonable for clients to follow the two redirects for the initial handshake. Further requests should go to the final URL anyway.
