### ISSUE TITLE
JMAP: a Blob/get API which returns data about a blob

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#2654]
This is useful for things which do further filtering on the client, e.g. the FastMail support ticket mode, where only messages from a particular folder are visible - everything else is replaced by Lorem Ipsum in the middleware.

Right now, blob downloads (e.g. attachments) can't work in this mode, as it's not possible to ACL check individual blobs with anything other than Cyrus level ACLs.

This API would be a standard Foo/get with:

```
accountId: "X",
ids: [blobIds],
properties: ['mailboxIds', 'emailIds', 'threadIds', 'calendarId', 'calendarEventIds', ...] basically every type of ID of a container which could contain a blob.
```

Each of the properties is a map from "id": true if the blobId is present within the object of that id in that account.

**Comment by robmueller** [comment]
@rsto FYI the current implementation of Blob/get doesn’t support passing a properties argument at all. It appears it calls jmap_get_parse with a NULL 4th argument, which causes any lookup in jmap_property_find to fail and return an invalidArguments error

**Comment by rsto** [comment]
Thanks, fixed in https://github.com/cyrusimap/cyrus-imapd/commit/b926594e87cf8068d1c42f9e789f11660fe27791
