### ISSUE TITLE
JMAP: Mailbox/set + creation id in Email/set leads to SetError(invalidProperties)

### ISSUE THREAD

**Issue by iNPUTmice** [cyrusimap/cyrus-imapd#2656]
I’m trying to simultaneously create a new mailbox and update an email to be in this mail box. I’m trying to use the creation id in the path of the patch object. 

```json
{"using":["urn:ietf:params:jmap:mail"],"methodCalls":[["Mailbox/set",{"create":{"archive-mb-id":{"name":"Archive","role":"archive"}}},"yxmtxdvtpr"],["Email/set",{"update":{"Mb42db631dc1672d39d4d357a":{"mailboxIds/a9615867-1d82-4c1c-a2c3-bdb93bc1fd29":null,"mailboxIds/#archive-mb-id":true}}},"agexrbpfaf"]]}
```

The mailbox is created but the email update fails with `invalidProperties`. Should I be able to use creation ids in the path of PatchObjects? I couldn’t find an example in the JMAP spec for this and no text that explicitly forbids or allows that.

**Comment by iNPUTmice** [comment]
Putting the creation id in the object that we want to patch instead of the path like this:
```json
 {"using":["urn:ietf:params:jmap:mail"],"methodCalls":[["Mailbox/set",{"create":{"cid0":{"name":"Trash","role":"trash"}}},"hsavomcnvl"],["Email/set",{"update":{"M07e9beb76599006b975c4a29":{"mailboxIds":{"#cid0":true}}}},"fofomifrwp"]]}
```
doesn’t work either.

**Comment by rsto** [comment]
Tested in https://github.com/cyrusimap/cassandane/commit/8c43d695cb12896966c3a662f827c4aecf9bbf85

**Comment by iNPUTmice** [comment]
This fix works for update calls. But I’m pretty sure I’m seeing a related problem for create calls (Create a mailbox and a new email and place that email in the newly created mailbox with a create-id reference.)
This is a bit annoying for me to debug as the create mailbox call succeeds and thus I can only test it once per account (or go to the server and delete the mailbox manually or something.)
I’m pretty sure I also got the httpd to segfault once
```
Mar 10 14:02:02 ganymede cyrus/http[12161]: login: localhost [127.0.0.1] zeta@ltt.rs Basic User logged in SESSIONID=<cyrus-1552222922-12161-3-5674198800275506947>
Mar 10 14:02:02 ganymede kernel: [11047915.809742] traps: httpd[12161] general protection ip:7fbebef16860 sp:7ffddb720c58 error:0
Mar 10 14:02:02 ganymede kernel: [11047915.811446]  in libjansson.so.4.11.0[7fbebef13000+c000]
Mar 10 14:02:02 ganymede cyrus/master[22435]: process type:SERVICE name:http path:/usr/local/libexec/httpd age:6.255s pid:12161 signaled to death by signal 11 (Segmentation fault)
```
Will attempt to make it more reproducible and also provide the jmap calls that cause it and open a new issue.

**Comment by iNPUTmice** [comment]
Is the test still running? I don’t know how to independently verify this. However I think I’m seeing the exact same bug again.

```jmap
{
    "using": [
        "urn:ietf:params:jmap:mail"
    ],
    "methodCalls": [
        [
            "Mailbox/set",
            {
                "ifInState": "27",
                "create": {
                    "mb-important": {
                        "name": "Important",
                        "role": "important"
                    }
                }
            },
            "0"
        ],
        [
            "Email/set",
            {
                "update": {
                    "Mbad757dfdd0f9adae89223ce": {
                        "mailboxIds/#mb-inbox": true
                    }
                }
            },
            "1"
        ]
    ]
}
```
gives me invalidProperties. Despite that the mailbox is created.

**Comment by brong** [comment]
On Fri, Nov 8, 2019, at 04:27, Daniel Gultsch wrote:
> Is the test still running? I don’t know how to independently verify this. However I think I’m seeing the exact same bug again.

> `{
    "using": [
        "urn:ietf:params:jmap:mail"
    ],
    "methodCalls": [
        [
            "Mailbox/set",
            {
                "ifInState": "27",
                "create": {
                    *"mb-important":* {`

...

> `                        "name": "Important",
                        "role": "important"
                    }
                }
            },
            "0"
        ],
        [
            "Email/set",
            {
                "update": {
                    "Mbad757dfdd0f9adae89223ce": {
                        "mailboxIds/*#mb-inbox*": true`

One of these things is not like the other.

BUT: I'm not sure that you can use references as part of a patch object like this anyway. I can see why it would be nice to have - but given that the syntax in core doesn't support it, it'll need to be an extension.

Bron.

--
 Bron Gondwana, CEO, Fastmail Pty Ltd
 brong@fastmailteam.com

**Comment by iNPUTmice** [comment]
> BUT: I'm not sure that you can use references as part of a patch object like this anyway. I can see why it would be nice to have - but given that the syntax in core doesn't support it, it'll need to be an extension.

You mean as part of a path? But the following would be possible?
```json
"update": {
     "Mbad757dfdd0f9adae89223ce": {
         "mailboxIds": {
           "#mb-important": true,
           "12344": true
     }
}
```

**Comment by brong** [comment]
On Fri, Nov 8, 2019, at 17:59, Daniel Gultsch wrote:
>> BUT: I'm not sure that you can use references as part of a patch object like this anyway. I can see why it would be nice to have - but given that the syntax in core doesn't support it, it'll need to be an extension.

> You mean as part of a path? But the following would be possible?

> "update": {
     "Mbad757dfdd0f9adae89223ce": {
         "mailboxIds": {
           "#mb-important": true,
           "12344": true
     }
}

Yes, that should work.

Actually, looking at the code the patch version might very well work as well... but I don't think the spec requires it. Interesting oversight - regardless of whether it was intended, the wording wasn't clear to me when I re-read it.

Bron.

--
 Bron Gondwana, CEO, Fastmail Pty Ltd
 brong@fastmailteam.com
