### ISSUE TITLE
JMAP: Create mailbox and email in one go returns serverError=mailbox does not exists

### ISSUE THREAD

**Issue by iNPUTmice** [cyrusimap/cyrus-imapd#2664]
I’m attempting to create a mailbox and a new email that is in that mailbox. I’m using this call.
Mailbox get's created just fine but the `Email/set` call fails with mailbox does not exist.

(The additional mailbox in that call is just my inbox that does in fact exists)

JMAP call:
```json
{"using":["urn:ietf:params:jmap:mail"],"methodCalls":[["Mailbox/set",{"create":{"mb-drafts":{"name":"Drafts","role":"drafts"}}},"vwhmrcvias"],["Email/set",{"create":{"e0":{"mailboxIds":{"544f9253-0154-44f7-b469-ac81054da1a8":true,"#mb-drafts":true},"keywords":{"$draft":true},"from":[{"email":"eta@ltt.rs"}],"to":[{"name":"…","email":"…"}],"subject":"This is a test","bodyValues":{"1":{"value":"This is a message"}},"textBody":[{"partId":"1","type":"text/plain"}]}}},"gwpyatrvii"]]}
```

I think I have also seen the httpd seg fault  when attempting to do this. I’m not able to replicate this now. I think it happened when I chained an `EmailSubmission/set` onto the call seen above. (My library would usually do all three in one request and I just separated `Mailbox/set` and `Email/set` out for debugging purposes.

```
Mar 10 14:02:02 ganymede cyrus/http[12161]: login: localhost [127.0.0.1] zeta@ltt.rs Basic User logged in SESSIONID=<cyrus-1552222922-12161-3-5674198800275506947>
Mar 10 14:02:02 ganymede kernel: [11047915.809742] traps: httpd[12161] general protection ip:7fbebef16860 sp:7ffddb720c58 error:0
Mar 10 14:02:02 ganymede kernel: [11047915.811446]  in libjansson.so.4.11.0[7fbebef13000+c000]
Mar 10 14:02:02 ganymede cyrus/master[22435]: process type:SERVICE name:http path:/usr/local/libexec/httpd age:6.255s pid:12161 signaled to death by signal 11 (Segmentation fault)
```

**Comment by brong** [comment]
This looks like a general case of "not enough creation id lookups" :)

**Comment by rsto** [comment]
The cause for this particular issue was a bit different: libjansson isn't happy with the loop body messing with the iterator state. Fixed this. For regression there's a test at https://github.com/cyrusimap/cassandane/commit/5ddfc2f352eb2f731f0816b05a2b28273704c608

I also tested this with failing already at Mailbox/set or Email/set, and the error handling now looks sane to me.
