### ISSUE TITLE
JMAP: identity/get returns no state

### ISSUE THREAD

**Issue by iNPUTmice** [cyrusimap/cyrus-imapd#2671]
Hi,

I noticed that calling `Identity/get` does not return a state. I’m wondering if this is a bug or on purpose. It’s not a big deal since clients will probably just store 'no state' and then call `get` again the next time instead of `changes`. However it would still be nice to have a state there and cut down on traffic a little bit. (Also I’m wondering if this is legal according to the spec. The spec doesn’t mention that state can be null.

**Comment by rsto** [comment]
Tested at https://github.com/cyrusimap/cassandane/commit/3c7b2741dfdedcefbd25d38a6af0f5bc7e599003
