### ISSUE TITLE
JMAP: queryEmail anchor + anchorOffest

### ISSUE THREAD

**Issue by iNPUTmice** [cyrusimap/cyrus-imapd#2674]
I apologize in advanced because this might just be me not understanding the spec (possibly due to a language barrier) but I’m unsure on who to ask to clarify the spec.

So I’m trying to get all Emails **after** emailId *c* (where email ids are sequentials a, b, c, d, e, f)

So my expectation reading the spec is that I call queryEmail with `anchor=c` and `anchorOffset=1`. Internally c would resolve to position 2; +1 for the offset so the first element returned position 3 that is id d.

However on Cryrus on need to call it with -1 to get d as the first element. Calling it with 1 gives me b.

Edit: What confuses me about the spec that it also uses -1 as an example. Assuming I’m right with what I described above -1 seems like a weird use case. I mean why would you get an overlapping page? +1 seems to be a much more common use case.

**Comment by rsto** [comment]
It looks as if there is a bug. Do you have JMAP search caching enabled? It is enabled, if the imapd.conf option `jmap_emailsearch_db_path` is set.

**Comment by iNPUTmice** [comment]
I had not `jmap_emailsearch_db_path` set. Setting it didn’t make a difference. I’ll keep that enabled for now. Sounds like a option to set anyway :-)

**Comment by rsto** [comment]
Fixed in https://github.com/cyrusimap/cyrus-imapd/commit/d4794507040547a14472056f878e1d20cd7a95bf. Tested in https://github.com/cyrusimap/cassandane/commit/9f5dd7fdec5fe63d75b201275ab12071940cd41b.
Thanks for finding this!
