### ISSUE TITLE
JMAP: Contact/copy fails for contacts with avatars

### ISSUE THREAD

**Issue by neilj** [cyrusimap/cyrus-imapd#2675]
If I try to copy a contact between two accounts, using `Contact/copy`, the server rejects it if the contact has an avatar:

```
{
    "methodResponses": [
        ["Contact/copy", {
            "notCreated": {
                "k1723": {
                    "properties": ["x-hasPhoto", "avatar"],
                    "type": "invalidProperties"
                }
            },
            "created": null,
            "accountId": "uf6c241b7",
            "fromAccountId": "ue150411c"
        }, "0"]
    ]
}
```

It should copy the vCard over directly, including the embedded image.

**Comment by ksmurchison** [comment]
@rsto  I wrote and rewrote several pieces of code and settled on this as the simplest solution.  Please review.

BTW, I abandoned the patch the vCard idea because the existing Contact/set{update} doesn't handle removing an existing property, so Contact/copy wouldn't have been able to copy without an avatar by setting it to NULL

**Comment by ksmurchison** [comment]
@neil  I believe this is fixed with the commit above.  I made the decision that overriding an existing avatar MUST use a blobId contained in fromAccount, mostly because it was a hell of a lot easier to implement, and it seemed logical.  Perhaps the spec should explicitly state where the blob comes from.

**Comment by ksmurchison** [comment]
Any feedback on the commit?  Has it been tested?

**Comment by neilj** [comment]
@ksmurchison Sorry, about not replying to this earlier. I have retested, and it seems to work for me; I can now move a contact with an avatar between accounts.

> I made the decision that overriding an existing avatar MUST use a blobId contained in fromAccount

This is not quite right, sorry. Any property you override in the "/copy" is presumed to reference the destination account if it contains ids, e.g. if you do Email/copy you need to override the mailboxIds property to reference mailboxes in the destination account.

**Comment by ksmurchison** [comment]
@neilj A couple of clarifications/questions (perhaps ignorance on my part):

- So when overriding an avatar via /copy, the referenced blobId is in the upload area of the destination account?  Is that even allowed?  
- How would the user know a blobId in the other account?  Is the user supposed to upload the overriding avatar to the destination account first?
- Is the override behavior of avatars for /copy special to Contacts or can it be inferred from the /copy spec in core?  If the latter, I can't find the text that describes this.
-

**Comment by neilj** [comment]
> So when overriding an avatar via /copy, the referenced blobId is in the upload area of the destination account? Is that even allowed?

Well, it may be in the upload area or anywhere else in that account in theory (e.g. an attached part of an email). A JMAP blob id just references the binary content. Cyrus can store it wherever.

> How would the user know a blobId in the other account? Is the user supposed to upload the overriding avatar to the destination account first?

Either the user uploads to the destination account with the JMAP upload handler, or it uses a blobId that already exists in the account (e.g. which might come from an avatar of another contact, or a message attachment etc. etc.)

> Is the override behavior of avatars for /copy special to Contacts or can it be inferred from the /copy spec in core? If the latter, I can't find the text that describes this.

The behaviour of copying the referenced blob across is not core and is special to Contacts. The behaviour of any overridden ids being scoped to the destination account id is just standard JMAP behaviour; the object would not be valid in the destination account if the referenced ids are not valid in that account (e.g. Email/copy you must override the `mailboxIds` property because the mailbox ids of the message in the original account are not valid in the destination account).

It is [in core](https://jmap.io/spec-core.html#/copy).
