### ISSUE TITLE
Contact/get can be expensive on massive addressbooks

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#2716]
We should speed up the fetch by caching the data in a more readable format in a single file faster database, so we don't have to re-read the entire DB.

This could be done in the sqlite DB, or a twoskip, or whatever.  Actually, sqliteDB will be the fastest by far since we already have to open it - and it's generated data, we should just do that!

We should do the same for calendarEvents while we're at it.  Convert them to a fast-read representation and add it to the sqlite DB on write.

**Comment by robmueller** [comment]
One thing is the JMAP structure of calendars and contacts is likely to change a bit as specs change, so it's probably worth storing some sort of JMAP version number on each row as well, so it's easy to tell if the stored structure is up to date or needs regenerating.

**Comment by brong** [comment]
Yeah, good point, thanks.

**Comment by ksmurchison** [comment]
@brong You already added JMAP response (+ version) to DAV DB, can we close this issue?

**Comment by brong** [comment]
Yes, we can.
