### ISSUE TITLE
Rename the calendar and contact urns to be something temporary

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#2726]
Right now we're using stuff from the ietf namespaces, but there's not even drafts!  Need to fix that for 3.2.

**Comment by brong** [comment]
using a cyrusimap.org URI for now

**Comment by rsto** [comment]
Fixed in https://github.com/cyrusimap/cyrus-imapd/commit/62e73c54a529620c5dccfa2cd9d55837471668a6

We use capabilities `https://cyrusimap.org/ns/jmap/calendars` and `https://cyrusimap.org/ns/jmap/contacts`.
