### ISSUE TITLE
running the annotator fails for messages with a basethrid

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#2727]
. uid xrunannotator 62945
. NO Permission denied (0.005 sec)

SHOULD NEVER HAPPEN.  Let's see:

. UID FETCH 62945 (ANNOTATION (/* (value.shared)))
* 29689 FETCH (UID 62945 ANNOTATION (/vendor/cmu/cyrus-imapd/basethrid (value.shared “fef22041d0edfc0e”) /comment (value.shared NIL) /altsubject (value.shared NIL)))

Since writing to "basethrid" is restricted, this fails.  We should at least not reject a write of the SAME value.

**Comment by robmueller** [comment]
As an FYI, the annotator isn't trying to write to basethrid. I presume what's happening is something like:
1. Calculate all existing flags + annotations and pass them to annotator
2. The annotator can add/delete flags and annotations, and pass the result to set on the message back to cyrus
3. It's trying to write all the annotations back, including any that weren't actually changed

**Comment by brong** [comment]
This is indeed what was happening.  Fixed on master, with Cassandane tests to match
