### ISSUE TITLE
Use of qsort_r in `jmap_mailbox.c`

### ISSUE THREAD

**Issue by chmanie** [cyrusimap/cyrus-imapd#2736]
I am building cyrus-imapd in a alpine linux environment and trying to do that with jmap support. While building I stumbled upon a similar issue to #63 (which was solved in #1803). `qsort_r` is used [here](https://github.com/cyrusimap/cyrus-imapd/blob/e9036739e52aaed308fed15f34e5b78918f0b242/imap/jmap_mailbox.c#L1207) as well which ultimately leads to portability issues.

I patched it for my build using the `qsort` fallback: https://github.com/cyrusimap/cyrus-imapd/pull/1803/files#diff-229279ffab38354a200b7635e05aa6abR508

While this seems to be working for me, it's not very portable either. Maybe something like suggested [here](https://github.com/cyrusimap/cyrus-imapd/pull/1803#issuecomment-275595418) would do.

I'd do a PR myself but my `C` skills leave a lot to be desired, so I'm just logging the issue and hope that someone will pick it up.

Thanks for all the good work! And if there's some interest in my experiences on how to build this on alpine linux (including the `cyruslibs`), I'll happily share them.

**Comment by rsto** [comment]
Fixed in https://github.com/cyrusimap/cyrus-imapd/commit/3302c80b6f8ce0515b5b74f567e87c5961cdfda7

**Comment by rsto** [comment]
@chmanie thanks for reporting this. please reopen this issue if the fix doesn't work out for you

**Comment by chmanie** [comment]
Wow, thanks, that was quick! I wanted to stick to the official release (3.1.6) as closely as possible but I might just cherry-pick this one as a patch (if that's possible). Thank you so much again and I'll surely report back!

**Comment by rsto** [comment]
You might run into issues when cherry-picking this, as the JMAP mailbox code hasn't been backported to the latest stable release. I haven't checked if backporting is straight-forward. Not sure how our release manager @elliefm wants to manage this, I understand that a 3.2 release is coming soon.

Looking forward to your feedback, I just tested this on my local GNU-based build system.

**Comment by chmanie** [comment]
OK, I'll run a build from the `master` branch then to test this in my environment. I'm really looking forward to the 3.2 version (is this going to be with official stable jmap support?)! Thanks again.

**Comment by chmanie** [comment]
I just built `master` without any problems. Thanks for the fix!
