### ISSUE TITLE
Foo/get should return the value for each requested property, even if it's the default

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#2738]
e.g.

    if (jmap_wantprop(rock->get->props, "color")) {
        struct buf attrib = BUF_INITIALIZER;
        static const char *color_annot =
            DAV_ANNOT_NS "<" XML_NS_APPLE ">calendar-color";
        r = annotatemore_lookupmask(mbentry->name, color_annot,
                                    httpd_userid, &attrib);
        if (!r && attrib.len)
            json_object_set_new(obj, "color", json_string(buf_cstring(&attrib)));
        buf_free(&attrib);
    }

This only sets "color" if it's present in the calendar, but it should always be returned.

**Comment by rsto** [comment]
There are couple of properties which needs to be updated. But this example isn't: the spec doesn't define a default value for "color", so we can't return anything (the empty string is not a valid CSS color).
