### ISSUE TITLE
Create and link imap/jmap_err.c only when JMAP support is enabled

### ISSUE THREAD

**Issue by dilyanpalauzov** [cyrusimap/cyrus-imapd#2743]
Currently imap/jmap_err.c is linked into imap/httdp, even when JMAP support is not enabled, which is likeley false.

**Comment by ksmurchison** [comment]
Should be fixed by
https://github.com/cyrusimap/cyrus-imapd/commit/320aef9e3403b3dbc3db70786f5b549da4b8ec19
