### ISSUE TITLE
Do not link everything with libcurl

### ISSUE THREAD

**Issue by dilyanpalauzov** [cyrusimap/cyrus-imapd#2744]
Commit 964e4afea introduce dependency on libcurl.  Libcurl shall be linked only, when necessary (when linking libcyrus_imap.la), on with every single program.  Likewise, CURL_CFLAGS shall be passed only when compiling the dependencies for libcyrus_imap.

**Comment by brong** [comment]
Ken resolved this already :)  But see #2754 for new bug created by the fix!
