### ISSUE TITLE
Detect and repair lock inversions

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#2752]
An example syslog line would be something like:

```
IOERROR: locking /$confpath/domain/e/example.com/user/f/foo.xapianactive: Resource deadlock avoided
```

The underlying issue is - locks need to be taken and released in a particular order to avoid lock inversions:

1. We need to track down why the current lock inversions are happening
2. We need test cases to make sure they aren't creeping back in - aka, a way to reliably reproduce these inversions.  This is tricky because often they're race conditions.
3. It would be great to have some tracking infrastructure in place around lock ordering such that the code would already know which locks were currently held so it could detect an illegal (aka: could invert) access pattern, so we don't have to create this infrastructure from scratch every time we debug one of these.  Adding assertions about ordering would conver the above "these are race conditions" to "the one who does it wrong gets killed off and it's really obvious!

**Comment by elliefm** [comment]
Do we have any expectation of being able to do this, properly, in the next couple of weeks?  If not, I'll remove the 3.2 and blocker tags and throw this back in the general master pool.

**Comment by ksmurchison** [comment]
I don't think I will get to this in the near future.

**Comment by dilyanpalauzov** [comment]
What is the status here?  Are lock inversions still observed, or are there hints for their existence?

**Comment by elliefm** [comment]
I think #4359 took care of it
