### ISSUE TITLE
Support patch of contactIds and otherAccountContactIds in ContactGroup/set

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#2761]
With otherAccountContactIds there's also patch overriding just a single user or patch creating/deleting just a single instance within a single user!

**Comment by brong** [comment]
Oh - it appears they are arrays - so actuallyit's just otherAccountContactIds that needs to be patchable...

**Comment by rsto** [comment]
Fixed in https://github.com/cyrusimap/cyrus-imapd/commit/af57a408e170833a83f6b009cd9c157cc3d0d298
