### ISSUE TITLE
squatter: on reporting “more than 1000 header lines”, reference that message

### ISSUE THREAD

**Issue by dilyanpalauzov** [cyrusimap/cyrus-imapd#2782]
When squatter prints “ERROR: message has more than 1000 header lines, not caching any more”, it shall say which message (mail) is meant.

**Comment by dilyanpalauzov** [comment]
The above is for 3.0.

Likewise, when reporting “squatter: message_parse_charset: unknown charset -1 for text/HTML” also report which message is meant (ideally by referencing the exact file locarion on the file system).

The purpose of the change is to be able to open the message and verify that squatter is right.  Otherwise there is no way to process the warning.

**Comment by elliefm** [comment]
There's also "mime boundary limit %i exceeded, not parsing anymore", "too many references, skipping the rest", and some others like this. They're all in `imap/message.c`

All the parser functions that actually do real work receive a 'struct msg *' as a parameter, but it's just a wrapper around an mmap.  By the time we're this deep in the parser the functions don't know/care where the message file is (it could conceivably not even exist on disk).  So to be able to log the filename from the error messages, we'd need to hand that down through the layers from `message_parse()` itself (which gets a `const char *fname` argument).

**Comment by elliefm** [comment]
Fixed in master.  I won't backport it to 3.0, but it will be in 3.2.
