### ISSUE TITLE
imap/search_xapian.c:begin_search() review

### ISSUE THREAD

**Issue by dilyanpalauzov** [cyrusimap/cyrus-imapd#2784]
The lines:

```C
bb->mailbox = mailbox;
bb->opts = opts
```
in imap/search_xapian.c:begin_search() do nothing.  The address of ` xapian_builder_t *bb` is not used anywhere.

That said, I do not see a `free()` corresponding to `xapian_builder_t *bb = xzmalloc(sizeof(xapian_builder_t));`.

**Comment by rsto** [comment]
Are you reviewing latest master? We use `bb->opts` for example in `https://github.com/cyrusimap/cyrus-imapd/blob/master/imap/search_xapian.c#L1686`

**Comment by dilyanpalauzov** [comment]
Alright, I have overseen that `bb` and `bb->super` have the same address.
