### ISSUE TITLE
update mailing list links

### ISSUE THREAD

**Issue by elliefm** [cyrusimap/cyrus-imapd#2786]
https://www.cyrusimap.org/imap/support/feedback-mailing-lists.html shows a bunch of links into the mailman list server on the cmu servers, but the links are to specific server names that don't exist anymore. They need to be reviewed and updated to the "lists.andrew.cmu.edu" url style

**Comment by marclaporte** [comment]
This looks like it's done, no?

**Comment by marclaporte** [comment]
ah no, not in the Archives section

**Comment by elliefm** [comment]
Looks like #2964 will take finish this up
