### ISSUE TITLE
"Unable to commit transaction" when running a CALL in Sendmail.conf

### ISSUE THREAD

**Issue by scotia70** [cyrusimap/cyrus-imapd#2792]
Hi,

I'm using cyrus-sasl-sql 2.1.27 on FreeBSD 11 and 12 and builtin sendmail.
I use Cyrus SASL to authenticate SMTP users.
My /usr/local/lib/sasl2/Sendmail.conf looks like:

```pwcheck_method: auxprop
auxprop_plugin: sql
sql_engine: mysql
sql_user: xxx
sql_passwd: yyy
sql_hostnames: sql-host
sql_database: userdb
sql_select: CALL select_smtp_password('%u')
sql_usessl: no
log_level: 3
```

When inbound SMTP users perform a LOGIN my auth.log is populated with:
```Jun  8 17:48:03 mail-01 sm-mta[93492]: sql query failed: Commands out of sync; you can't run this command now
Jun  8 17:48:03 mail-01 sm-mta[93492]: Unable to commit transaction
Jun  8 17:48:03 mail-01 sm-mta[93492]: sql query failed: Commands out of sync; you can't run this command now
Jun  8 17:48:03 mail-01 sm-mta[93492]: sql query failed: Commands out of sync; you can't run this command now
Jun  8 17:48:03 mail-01 sm-mta[93492]: Unable to commit transaction`
for each LOGIN attempt.
```
Note that the query succeeds and everything works.  I'm wondering if using a stored procedure and a CALL (which I do) is interacting poorly with the ./plugins/sql.c code (which I assume is normally called with an SQL SELECT statement).

I have tried two variants of the stored procedure:
```BEGIN
START TRANSACTION;
INSERT INTO smtp_auths (name,count,last) VALUES (my_id,'1',NOW()) ON DUPLICATE KEY UPDATE count=count+1, last=NOW();
COMMIT;
SELECT clear FROM userdb WHERE id = my_id AND smtpauth = 'Y';
END
```

AND

```BEGIN
INSERT INTO smtp_auths (name,count,last) VALUES (my_id,'1',NOW()) ON DUPLICATE KEY UPDATE count=count+1, last=NOW();
SELECT clear FROM userdb WHERE id = my_id AND smtpauth = 'Y';
END
```

I think the final "settings->sql_engine->sql_commit_txn" in ./plugins/sql.c is perhaps the culprit.

Thanks

**Comment by dilyanpalauzov** [comment]
Does it work, if you do not use transactions, but a single SELECT?

**Comment by dilyanpalauzov** [comment]
Does the stored procedure have the same return type as as a working SELECT?

**Comment by scotia70** [comment]
Hi @dilyanpalauzov,

If I use the call to the stored procedure as above, but remove the START TRANSACTION and COMMIT (which I thought might be handled by Cyrus) I get the same error.

If I change the CALL to a SELECT:

```
sql_select: SELECT clear FROM userdb WHERE id = '%u' AND smtpauth = 'Y'
```

I get no errors (and it succeeds).

**Comment by dilyanpalauzov** [comment]
Does the stored procedure have the same return type (a single column) as the SELECT?

Does a CTE SELECT work for you?

**Comment by scotia70** [comment]
Hi,
the SELECT statement in the SP returns a single column from a single row (it matches against the primary key). 
I’ll try a CTE statement when I get home in a few hours. 
Thanks

**Comment by dilyanpalauzov** [comment]
Per https://dev.mysql.com/doc/refman/8.0/en/create-procedure.html a stored function has a return type.  You do not say what is the return type of the CALL call.

**Comment by scotia70** [comment]
This is a stored procedure rather than a stored function:
```
CREATE DEFINER=`xxx` PROCEDURE `select_smtp_password`(IN my_id VARCHAR(128))
BEGIN
START TRANSACTION;
INSERT INTO smtp_auths (name,count,last) VALUES (my_id,'1',NOW()) ON DUPLICATE KEY UPDATE count=count+1, last=NOW();
COMMIT;
SELECT clear FROM userdb WHERE id = my_id AND smtpauth = 'Y';
END
```
and as such does not have a return type.

I get the same messages without that INSERT too.

This is the block of messages I get for a single LOGIN attempt:
```
Jun  9 18:21:23 mail-01 sm-mta[95094]: sql plugin: no result found
Jun  9 18:21:23 mail-01 sm-mta[95094]: sql query failed: Commands out of sync; you can't run this command now
Jun  9 18:21:23 mail-01 sm-mta[95094]: Unable to commit transaction
Jun  9 18:21:23 mail-01 sm-mta[95094]: sql plugin: no result found
Jun  9 18:21:23 mail-01 sm-mta[95094]: sql query failed: Commands out of sync; you can't run this command now
Jun  9 18:21:23 mail-01 sm-mta[95094]: sql query failed: Commands out of sync; you can't run this command now
Jun  9 18:21:23 mail-01 sm-mta[95094]: Unable to commit transaction
```

Maybe I should try a FUNCTION instead.

**Comment by scotia70** [comment]
Hi again,

I've found the issue.  Because of nature of the CALL statement, there is residual return data that needs to be consumed before another query can be made.

See [https://bugs.mysql.com/bug.php?id=71044](url)

My fix was to add the line:
```
mysql_next_result(conn);
```

after
```
mysql_free_result(result);
```
(line 158 of `plugins/sql.c`).

The change works regardless of the type of query (SELECT or CALL).

**Comment by dilyanpalauzov** [comment]
Strictly speaking, this does not belong to https://github.com/cyrusimap/cyrus-imapd but to https://github.com/cyrusimap/cyrus-sasl/ , however the same persons are involved in handling both repositories.

Considering that there are cases like https://github.com/cyrusimap/cyrus-sasl/pull/546 which are not handled within reasonable time, it is unpredictable whether your case will be handled, here or there.

**Comment by scotia70** [comment]
No worries.  I'm just glad to have solved the issue.  It should remain open though, yes?

**Comment by dilyanpalauzov** [comment]
Please report this to https://github.com/cyrusimap/cyrus-sasl/issues and close the case here.  The rationale is, that this ticket should be about Cyrus IMAP, but is about Cyrus SASL and thus a different story.

I do not say, whether the problem is already fixed upstream, or whether retypimg the problem at https://github.com/cyrusimap/cyrus-sasl/issues wouldlead to merging your patch upstream in reasonable time.  The latter is just not predictable.

**Comment by scotia70** [comment]
Moved to: https://github.com/cyrusimap/cyrus-sasl/issues/639
