### ISSUE TITLE
3.0.10 fails cunit test 'get_search_program' on ppc (32bit, Big Endian)

### ISSUE THREAD

**Issue by ernsteiswuerfel** [cyrusimap/cyrus-imapd#2795]
Built 3.0.10 from git with cunit tests. It fails the `get_search_program` test. This problem is around since at least 3.0.4. (Gentoo downstream bug report: https://bugs.gentoo.org/662896).

```
autoreconf -i
./configure --enable-unit-tests --enable-coverage
make
make check
[...]
Suite: search_expr
  Test: get_search_program ...FAILED
    1. ./cunit/search_expr.testc:90  - CU_ASSERT_STRING_EQUAL(actual_out="(and (lt internaldate 0))",expected_out="(and (lt internaldate 1354885200))")
    2. ./cunit/search_expr.testc:157  - CU_ASSERT_STRING_EQUAL(actual_out="(and (and (lt internaldate 0) (ge internaldate 0)))",expected_out="(and (and (lt internaldate 1354971600) (ge internaldate 1354885200)))")
    3. ./cunit/search_expr.testc:179  - CU_ASSERT_STRING_EQUAL(actual_out="(and (lt sentdate 0))",expected_out="(and (lt sentdate 1354885200))")
    4. ./cunit/search_expr.testc:189  - CU_ASSERT_STRING_EQUAL(actual_out="(and (and (lt sentdate 0) (ge sentdate 0)))",expected_out="(and (and (lt sentdate 1354971600) (ge sentdate 1354885200)))")
    5. ./cunit/search_expr.testc:194  - CU_ASSERT_STRING_EQUAL(actual_out="(and (ge sentdate 0))",expected_out="(and (ge sentdate 1354885200))")
    6. ./cunit/search_expr.testc:199  - CU_ASSERT_STRING_EQUAL(actual_out="(and (ge internaldate 0))",expected_out="(and (ge internaldate 1354885200))")
  Test: unserialise ...passed
  Test: duplicate ...passed
  Test: normalise ...passed
  Test: countability ...passed
  Test: split_by_folder_and_index ...passed
[...]
```
[check.log](https://github.com/cyrusimap/cyrus-imapd/files/3272304/check.log)

**Comment by elliefm** [comment]
Hmmm, one thing that all these failing tests have in common is they're using the "uint64_t" field of a union to store a "time_t" value, instead of its "time_t" field.  I guess that's probably neither here nor there on platforms where time_t _is_ uint64_t, but I'm guessing your 32bit platform also has 32bit time_t!

If you add this patch to Cyrus and rebuild, do these tests start passing?

https://github.com/elliefm/cyrus-imapd/commit/28f7d3af807a082c8b688018e6e5c381ca44482f.diff

**Comment by ernsteiswuerfel** [comment]
Yes, after applying your patch to 3.0.10 all tests pass on ppc32. Thanks!

**Comment by elliefm** [comment]
Great, thanks for testing that! I'll merge it properly and it'll be in the next real release :)

**Comment by elliefm** [comment]
Hmm, if you also apply these two patches, do the tests still pass on ppc32?

https://github.com/elliefm/cyrus-imapd/commit/bb832cb9eb01e6d4a852d1aec95605af939f6154.diff
https://github.com/elliefm/cyrus-imapd/commit/d119900407f129bb1863a20ac3a9c765a88572f7.diff

**Comment by ernsteiswuerfel** [comment]
Yes, the tests just continue passing with these two additional patches applied.

**Comment by elliefm** [comment]
Great, thanks for the additional testing! :)  All three are now on the 3.0 branch and will be in the next 3.0 release, and forward-ported to master where master didn't already have a different but similar fix in place
