### ISSUE TITLE
Installation of development version of cyradm only

### ISSUE THREAD

**Issue by sstubbs** [cyrusimap/cyrus-imapd#2800]
Hi,

I am not sure if this is a bug or a question for the group. If it should be in the group sorry to waste your time. I have an installation of the dev branch of cyrus imap from source. Running cyradm info user gives me the information I need. 

I have another server with a web app and on that server I have installed only cyradm via apt install cyrus-admin

listmailbox, sam and dm work via this remote install however info does not and I get the error Remote does not support ANNOTATEMORE. info does work if i run the copy of cyradm on the server with the dev branch of cyrus installed.

So I am not sure if it's an issue with issuing the command from a remote copy of cyradm or because it's a different version of cyrus admin. Is this a known limitation of running cyradm remotely or could it be because it is a different version and if so what would be the best way to install the latest version of cyradm on the remote server without installing the full cyrus imap?

**Comment by dilyanpalauzov** [comment]
Your question is, why you cannot utilize over `cyradm` ANNOTATEMORE towards the master branch, while it works with 3.0. 

ANNOTATEMORE was an internet draft, which ended as RFC5465 and the chosen name for the feature is METADATA.  Cyrus Imap has implemened METADATA in 2.5 and has disabled by default ANNOTATEMORE support on the master/develop branch, unless it is enabled explicitly with `annotate_enable_legacy_commands`.

See the discussion from Sep-Okt 2018 on the cyrus-devel mailing list, https://lists.andrew.cmu.edu/pipermail/cyrus-devel/ .

**Comment by dilyanpalauzov** [comment]
So you use cyradm from 3.0 towards an imap server in the master branch?

Looking in the differences between cyrus-imap-3.0 and master, I see
```diff
diff --git a/perl/imap/IMAP/Admin.pm b/perl/imap/IMAP/Admin.pm
index 5ca657bd0..6515d9c65 100644
--- a/perl/imap/IMAP/Admin.pm
+++ b/perl/imap/IMAP/Admin.pm
@@ -75,7 +75,7 @@ sub new {
   # but the API makes it difficult to get at the results of that command.
   if(defined($self)) {
     $self->{support_referrals} = 0;
-    $self->{support_annotatatemore} = 0;
+    $self->{support_annotatemore} = 0;
     $self->{support_list_extended} = 0;
     $self->{support_list_special_use} = 0;
     $self->{support_create_special_use} = 0;
```
and the further, the getinfo function in that file changed singnificantly:
```diff
@@ -826,125 +828,6 @@ sub _attribname2access {
   }
 }
 
-sub getinfo {
-  my $self = shift;
-  my $box = shift;
-  my @entries = @_;
-
-  if(!defined($box)) {
-    $box = "";
-  }
-
-  if(!$self->{support_annotatemore}) {
-    $self->{error} = "Remote does not support ANNOTATEMORE.";
-    return undef;
-  }
-
…
```
In the past it called expcitly ANNOTATEMORE towards the server and did many other things, now it does just: diff
```
@@ -1159,6 +1071,23 @@ sub getmetadata {
 }
 *info = *getmetadata;
 
+sub getinfo {
+  my $self = shift;
+  my $box = shift;
+  my @entries = @_;
+  my @myentries;
+
+  if(scalar(@entries)) {
+      foreach my $annot (@entries) {
+          push @myentries, '/private' . $annot;
+          push @myentries, '/shared' . $annot;
+      }
+  }
+  return $self->getmetadata($box, @myentries);
+}
+*info = *getinfo;
+
+
 sub setmetadata {
   my ($self, $mailbox, $entry, $value, $private) = @_;
 
```
I would say, unless you enable explictly ANNOTATEMORE support on the server, you shall use cyradm from the master branch for the `info` command.

**Comment by dilyanpalauzov** [comment]
> Is this a known limitation of running cyradm remotely 
I would not say it has to do something with remote calling, executing locally (cyradm localhost) the result will be the same.  Looking at the code, this change in cyradm makes sense.

> or could it be because it is a different version and if so what would be the best way to install the latest version of cyradm on the remote server without installing the full cyrus imap?

You could try compiling cyrus-imap, by passing --disable-server to ./configure, it shall build less stuff then.

You could login to the server, where cyrus-imap runs, and execute there `cyradm info`, that cyradm should be accurate.

You can get cyradm from the same place, where you got the dev variant from cyrus-imap (I have no idea what this place could be, but it very likely provides also cyradm/perl).

**Comment by sstubbs** [comment]
Thank you very much for the details information that makes sense I will try build it with --disable-server and see if it works.

**Comment by sstubbs** [comment]
I can confirm that installing from source with --disable-server works perfectly.

**Comment by elliefm** [comment]
I believe it's generally expected that cyradm only works properly with the cyrus version it came from?  It's probably mostly okay to use a newer cyradm with an older cyrus, but I wouldn't want to rely on using an older cyradm with a newer cyrus.
