### ISSUE TITLE
Make init_mechlist thread safe

### ISSUE THREAD

**Issue by vlmarek** [cyrusimap/cyrus-imapd#2813]

**Comment by vlmarek** [comment]
Hi,

We are doing some housekeeping in the changes we use in cyrus-sasl in Solaris.

https://github.com/oracle/solaris-userland/tree/master/components/cyrus-sasl/patches

And I have noticed that we have in the pipeline a fix which never got to be used. It seems simple enough, but I can't judge if this is something you would consider having. If yes, I'm happy to try to port it to current version and create a pull request. If no I will just drop it because we don't need it internally anymore.

That said I don't even see lib/client.c in your code so probably this is pointless ...

Thank you
__ 
  Vlad

**Comment by vlmarek** [comment]
[116-race-condition.txt](https://github.com/cyrusimap/cyrus-imapd/files/3331156/116-race-condition.txt)

**Comment by elliefm** [comment]
Hi, thanks for the patch.  The right place for this is the cyrus-sasl repository, https://github.com/cyrusimap/cyrus-sasl -- do you want to re-open this issue there?  If not, I will eventually, but if you do it yourself then github will give you the notifications/etc.

(I don't know sasl well enough to comment on the patch myself, but if it's in the right place it can attract the right eyes!)

**Comment by elliefm** [comment]
Moved to https://github.com/cyrusimap/cyrus-sasl/issues/584
