### ISSUE TITLE
In sieve reject and redirect, add account name to auditlog record

### ISSUE THREAD

**Issue by robmueller** [cyrusimap/cyrus-imapd#2814]
When a sieve reject or redirect occurs, the auditlog records looks like:

auditlog: reject sessionid=<...> message-id=<...> target=<where-reject-is@sent-to>

There's nothing logged about the user account the sieve script comes from. It's not actually possible to see from cyrus what users sieve script caused the reject message to be generated by.

We should add a username=<...> (? or is there some other standard field name when we need to log the account?) field to the reject and redirect auditlog lines to show which account the sieve script was being run from.

**Comment by elliefm** [comment]
Looks like `smmapd(8)` calls it "userid":

```
412:                syslog(LOG_NOTICE, "auditlog: ok userid=<%s> client=<%s>", key, smmapd_clienthost);
```

and duplicate detection (`lmtpd`, `nntpd`) calls it "user":

```
211:        syslog(LOG_NOTICE, "auditlog: duplicate sessionid=<%s> action=<%s> message-id=%s user=<%s> date=<%s>",
```

So there are existing places where this is logged, but it's not very standardised!

Internally we usually (but not always) call this "userid" so I'm inclined to do the same here
