### ISSUE TITLE
You can attempt to URLFETCH someone else's data but it crashes

### ISSUE THREAD

**Issue by wolfsage** [cyrusimap/cyrus-imapd#2827]
You can attempt to urlfetch from someone else’s account, and we crash because this assert fails in cleanup:

https://github.com/cyrusimap/cyrus-imapd/blob/master/imap/imapd.c#L1244

```
/* ensure we didn't leak anything! */
assert(!open_mailboxes_exist());
```

**Comment by elliefm** [comment]
I think the problem starts here (we set `doclose=1` if we opened the index successfully, but then `goto err` if you don't have ACL_READ on the mailbox):

https://github.com/cyrusimap/cyrus-imapd/blob/6a681b5862068958f2985cb5f29df19f4e2b95b3/imap/imapd.c#L13935-L13949

and then finishes here, where the `err:` label is _after_ the bit that closes the index if we needed to...

https://github.com/cyrusimap/cyrus-imapd/blob/6a681b5862068958f2985cb5f29df19f4e2b95b3/imap/imapd.c#L13963-L13966

which means, I think, that the fix will be to move the `err:` label a smidge earlier

**Comment by elliefm** [comment]
Would love a Cassandane test for this, but like in #2826 I still don't know URLFETCH well enough to write a test I trust!

**Comment by elliefm** [comment]
The fix doesn't break any of our existing tests though, so there it is ^^
