### ISSUE TITLE
Data loss due to skipping index records with MODSEQ = 0

### ISSUE THREAD

**Issue by mdoggydog** [cyrusimap/cyrus-imapd#2839]
In attempting to upgrade a cyrus-imapd 2.4.17 installation (e.g., Debian jessie) to 3.0.8 (Debian buster, the recent stable release), I noticed messages disappeared from mailboxes.  The message files are still in the spool, but are not advertised to IMAP clients and do not appear to utilities like `mbexamine`.  It appears that the common trait of all of these messages is a MODSEQ of zero in their index records.

In #1029 there is evidence that at some point there was some code to try to reinitialize zero MODSEQ's to ones (which apparently never happened to all the messages I am looking at).  I didn't see anything in the 2.4.17 code base that would obviously apply this kind of fix.  Nonetheless, 2.4.17 (and probably 2.5.x) seems to happily process zero MODSEQ messages.

At some point in the 3.x branch, however, the `mailbox_iter` abstraction was added, along with [this line of code](https://github.com/cyrusimap/cyrus-imapd/blob/650604c73b3c131759e51dafe5cee6662178acd2/imap/mailbox.c#L7042)
```
        if (record->modseq <= iter->changedsince) continue;
```
which has the effect of ignoring/discarding all MODSEQ = 0 records, even if `iter->changedsince` itself is set to zero (which seems to be used by callers to indicate "ignore modseq when iterating").  This means that these index records are ignored even by `reconstruct`.

I suspect that simply changing that one line to
```
        if ((iter->changedsince > 0) && 
            (record->modseq <= iter->changedsince)) continue;
```
will solve the problem while retaining the existing meaning for `changedsince` --- but I don't know enough about the semantics of MODSEQ to know if this will be ok. (And I haven't tried it out yet myself.)

**Comment by mdoggydog** [comment]
FYI, I have also filed a debian bug report referencing this one:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=933163

**Comment by brong** [comment]
yes, this is a legit and pretty bad bug - sorry about that!  Your fix is fine.  I've pushed equivalent code to the master and 3.0 branches.

**Comment by elliefm** [comment]
For people who don't have this patch yet, is there something they can invoke to safely initialise affected modseqs to non-zero?

The patch from #1029 looks like it was on the 'reconstruct -V' code path, but it looks like the specific "detect and fix zero" behaviour was lost in the big pre-2.5 refactors.  I haven't yet looked into whether the behaviour is still in 2.4

**Comment by elliefm** [comment]
Just checking the 2.4 branch and it was the big "The Rest" commit (fdc0eb3d0) that replaced the original patched modseq handling with refactored code, which precedes gitk tells me precedes 2.4.0.  I'm not sure if the re-initialize on upgrade behaviour was necessarily lost at this point, but the comment explaining what it was definitely was...

So I guess anyone who previously upgraded _to_ 2.4 from an earlier version, and now upgrades to 3.0 from there, might potentially trip over this, even if they try to be cautious and reconstruct -V max before upgrading. Uggh

**Comment by elliefm** [comment]
There will be a new 3.0 release in the next few days containing this fix, just getting release notes and other relevant documentation in order

**Comment by elliefm** [comment]
Just released 3.0.11 containing this fix :)

**Comment by mdoggydog** [comment]
(Thank you for the very speedy validation and fix-up release!)

**Comment by mdoggydog** [comment]
(Oh, and, well, it looks like the 3.0.11 release notes inadvertently point to #2389 instead of #2839 --- i.e., the 8 and 3 got transposed.)

**Comment by elliefm** [comment]
crap, retconning...

**Comment by elliefm** [comment]
Fixed in git, website should rebuild on the next hour. Thanks!

**Comment by elliefm** [comment]
For package maintainers that can't easily bump to a new numbered version, but can apply a patch to what you've currently got, the commit you want is 028405057

**Comment by elliefm** [comment]
The same 2839/2389 typo was also in the upgrade documentation, which I've just discovered and corrected, and will be live on the web in a few minutes.
