### ISSUE TITLE
Sieveshell failing to create needed user script directories

### ISSUE THREAD

**Issue by nekatak** [cyrusimap/cyrus-imapd#2841]
This looks like a bug in the Debian packaging and not sure if this is the correct place to report.
While timsieve server is installed with the debian package cyrus-imapd (running Debian 9 and installed version of `cyrus-imapd` is `2.5.10-3+deb9u1 amd64`) when trying to connect with the sieveshell command you get the following error:
```
<user>@mail:~$ sieveshell localhost
connecting to localhost
Please enter your password: 
unable to connect to server at /usr/lib/cyrus/bin/sieveshell line 200, <STDIN> line 1.
```
The error message is not very useful to understand what might be wrong while the logs make clear the issue
```Aug  4 14:35:00 mail cyrus/sieve[12384]: IOERROR: creating directory /usr/sieve: Permission denied
Aug  4 14:35:00 mail cyrus/sieve[12384]: mkdir /usr/sieve/n/<user>: Permission denied
Aug  4 14:35:00 mail cyrus/sieve[12384]: error in actions_setuser()
Aug  4 14:35:00 mail cyrus/sieve[12384]: Lost connection to client -- exiting
```
the /usr/sieve directory missing and cyrus doen't have correct permissions to create it.
This could be fixed in the debian package and/or mention in the documentation that you can check for logs.

**Comment by elliefm** [comment]
I think documentation for actually configuring timsieved needs to be added in here: 
https://www.cyrusimap.org/imap/reference/admin/sieve.html#configure-sieve (i.e. docsrc/imap/reference/admin/sieve.rst).  Currently all it mentions is the port numbers, which implies that it works out of the box with no additional configuration or handholding (but, clearly, it doesn't!)

**Comment by elliefm** [comment]
Documentation updated per 75091652534e4ddc89d35c8397ff5d6ab5a3e14f and 40eeee61ec662a7d41b5f638ea6f1b6e7275cab8 (the web version will auto-update just after the next hour).

Use of the syslog LOCAL6 channel is fairly fundamental to the Cyrus design, and is documented right up top of the [Installing Cyrus](https://www.cyrusimap.org/imap/installing.html#setting-up-syslog) doc, so the rest of the documentation assumes the admin will already know to check syslog if something weird happens.

I guess you'd need to report this to the debian bug tracker to get the packaging fixed, for this to work out of the box.  I think the updated documentation should aid with that?
