### ISSUE TITLE
Cyrus may not send iMIP message with STATUS:CANCELLED and Content-Type: text/calendar;  method=REQUEST

### ISSUE THREAD

**Issue by dilyanpalauzov** [cyrusimap/cyrus-imapd#2843]
When the orginizer PUTs a VEVENT with changed STATUS to CANCELLED, cyrus generates a message containing both `Content-Type: text/calendar; charset=utf-8; method=REQUEST; component=VEVENT` and `STATUS:CANCELLED`.

This violates RFC 5546, which permits STATUS:CANCELLED only with method=CANCEL and permits method=REQUEST only with STATUS: TENTATIVE/CONFIRMED/(absent status)

**Comment by dilyanpalauzov** [comment]
When a VEVENT with STATUS:CONFIRMED is HTTP DELETED, cyrus sends iMIP message with `Content-Type: text/calendar; charset=utf-8; method=CANCEL; component=VEVENT` and `STATUS:CONFIRMED`.  If STATUS is present with method=CANCEL, then STATUS must be CANCELLED.

**Comment by ksmurchison** [comment]
Fixed by https://github.com/cyrusimap/cyrus-imapd/commit/207b8b643f270e8dc97ade4a8c686c1bea772077

**Comment by elliefm** [comment]
cherry-picked to 3.2 as faeb70665a
