### ISSUE TITLE
ipurge events

### ISSUE THREAD

**Issue by giena** [cyrusimap/cyrus-imapd#2848]
On ipurge execution, there's MessageExpunge event.
The events that we get from ipurge are like this:
{"event":"MessageExpunge","timestamp":"2019-08-12T11:44:40.754+02:00","service":"ipurge","mailboxID":"xxxxxxxxxxxx","uri":"imap://host/user;UIDVALIDITY=1508183802","uidset":"550:554","pid":103826,"user":"","vnd.cmu.mbtype":"","serverFQDN":"msfrb1406","vnd.cmu.mailboxACL":"xxxxxxxxxxx\tlrswipkxtecda\tadmcyr\tlrwipkxtecda\t"} 

The uri syntax is not complete, so we are unable to parse it. The folder is missing.

**Comment by giena** [comment]
version 3.0.8

**Comment by elliefm** [comment]
To clarify, is this only affecting MessageExpunge events that are generated by ipurge? Or is it affecting all MessageExpunge events?

**Comment by elliefm** [comment]
ipurge.c never calls `mboxevent_setnamespace()`, so I think `mboxevent_extract_mailbox()` is unable to derive an extname, leaves the `mailbox` field blank in the `struct imapurl`, and so `imapurl_toURL()` generates a url without a mailbox in it

**Comment by elliefm** [comment]
This patch seems to fix it for me.  I'm not sure if it's exactly correct, but it's enough for the mailbox to be included in the URI:

```
diff --git a/imap/ipurge.c b/imap/ipurge.c
index 80c51716b..e58f7436e 100644
--- a/imap/ipurge.c
+++ b/imap/ipurge.c
@@ -178,6 +178,7 @@ int main (int argc, char *argv[]) {
 
   /* setup for mailbox event notifications */
   mboxevent_init();
+  mboxevent_setnamespace(mboxname_get_adminnamespace());
 
   mboxlist_init(0);
   mboxlist_open(NULL);
```

**Comment by elliefm** [comment]
Ahh, I see what happened: it wasn't so much that the URI didn't include the mailbox, but rather, the mailbox it included was truncated at the first hierarchy separator, because the uninitialised namespace meant the hierarchy separator used was '\0'!   Thus, "imap://host/user" instead of "imap://host/user.foo.somemailbox"

**Comment by elliefm** [comment]
This was broken on master too, though the fix was a little different.  master is fixed by 7bdaf7c26, 3.0 by efa4ca55e

**Comment by elliefm** [comment]
And a cassandane test: https://github.com/cyrusimap/cassandane/commit/d54d817915d35973fa9849fb900154bd475e288e

**Comment by giena** [comment]
Sorry for the late reply but yes it was only for ipurge binary. And thank you for the correction.
