### ISSUE TITLE
SASL Internal Error -4 in ../../lib/server.c near line 1762

### ISSUE THREAD

**Issue by sstubbs** [cyrusimap/cyrus-imapd#2860]
I've been running the master branch of 3.1 for a few years and upgrading every few months. I've just installed the 3.1.7 release and am getting this error.
`SASL Internal Error -4 in ../../lib/server.c near line 1762`
However authentication is working. I have never had this error before. Any idea what it could be?

**Comment by dilyanpalauzov** [comment]
No.  You have to debug this yourself and provide more information.  server.c near line 1762 contains:
```c
  if (!s_conn->mech_list || s_conn->mech_length <= 0)
      INTERROR(conn, SASL_NOMECH);
```
This could mean, that no SASL mechanisms were allowed.  Can you debug this and say the values of `s_conn->mech_lenght` and `s_conn->mech_list`?

**Comment by sstubbs** [comment]
Thanks. I managed to get this fixed a few months ago. It was an issue with libpam-pgsql.

**Comment by dilyanpalauzov** [comment]
Can this case be closed?
