### ISSUE TITLE
Various non-standard JMAP Email/query parameters aren't behind 'using' checks

### ISSUE THREAD

**Issue by wolfsage** [cyrusimap/cyrus-imapd#2894]
Email/query allows these non-standard filters:
 * attachmentType
 * attachmentName

And these non-standard sort fields:
 * addedDates
 * spamScore
 * threadSize
 * snoozedUntil

but doesn't hide them behind a 'using' flag. It should!

**Comment by wolfsage** [comment]
What about the sort fields?

**Comment by rsto** [comment]
Here: https://github.com/cyrusimap/cyrus-imapd/commit/f7daa5ee9fecba854b32bb279484458d95826c1a

Github only references the commit that fixes an issue
