### ISSUE TITLE
User rename doesn't maintain partition on 3.0.8

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#2907]
```
. RENAME user/ren@devenv.blue user/rename@devenv.blue bm-master__devenv_blue
. NO Cross-server or cross-partition move w/rename not supported
. RENAME user/ren@devenv.blue user/rename@devenv.blue
```

But `user/ren@devenv.blue` was on `bm-master__devenv_blue`, and `user/rename@devenv.blue` winds up on `default` with the second rename.

**Comment by elliefm** [comment]
Reproduced with cassandane, also affects master

**Comment by elliefm** [comment]
Looks like this only affected user renames -- any deeper level mailbox rename would use the partition of its parent, and stay sane.  But a user rename wouldn't have a higher-level mailbox to get the partition from, so in absence of an explicit partition, would follow the "new mailbox, choose a partition" logic
