### ISSUE TITLE
JMAP: Identity needs to be in submission and not in mail namespace

### ISSUE THREAD

**Issue by iNPUTmice** [cyrusimap/cyrus-imapd#2912]
The Identity data type and the corresponding get method belong to the `urn:ietf:params:jmap:submission` namespace according to [RFC 8621 Section 1.3.2](https://tools.ietf.org/html/rfc8621#section-1.3.2). When calling Cyrus with a correct 'using' it responds with methodNotFound.

**Comment by rsto** [comment]
Thanks!
