### ISSUE TITLE
FR: Reaching limits should be logged

### ISSUE THREAD

**Issue by asy972** [cyrusimap/cyrus-imapd#2913]
Some limits can be configured in imapd.conf (such as maxlogins_per_host, maxlogins_per_user, popminpoll). Reaching limits should be logged for properly diagnostic.

Hm... I'm surprised that github doesn't support diff type attachments... Ok. I sent patches to cyrus-devel: https://lists.andrew.cmu.edu/pipermail/cyrus-devel/2019-November/004531.html

**Comment by elliefm** [comment]
I renamed the patches from the mailing list from ".diff" to ".diff.txt", and then github let me attach them.  So here they are for history:

[cyrus-2.5.13-logging-limit.diff.txt](https://github.com/cyrusimap/cyrus-imapd/files/3856376/cyrus-2.5.13-logging-limit.diff.txt)
[cyrus-3.0.11-logging-limit.diff.txt](https://github.com/cyrusimap/cyrus-imapd/files/3856377/cyrus-3.0.11-logging-limit.diff.txt)

**Comment by elliefm** [comment]
Thanks for the patches, this is now on 2.5, 3.0 and master branches :)

**Comment by asy972** [comment]
> I renamed the patches from the mailing list from ".diff" to ".diff.txt", and then github let me attach them. 

I tried to do so and I tried using tar.gz. It's strange. Maybe it's a problem in my browser.
Thanks.
