### ISSUE TITLE
Email/set update with invalid mailboxId/foo patches error response looks wrong

### ISSUE THREAD

**Issue by wolfsage** [cyrusimap/cyrus-imapd#2917]
If I do:

```
  "Email/set":{
    "update":{
      "<id>":{
        "mailboxIds/<mailboxid>":false,
      },
    },
  },
```
(Note that false is an invalid value, it should be true or undef)

I get this response:

```"notUpdated": {
  "<id>": {
    "type": "invalidProperties",
    "properties": [
      "mailboxIds~1<mailboxid>"
    ]
  }
},
```

The mailboxId patch spec is being encoded as a json pointer in the response. This seems wrong to me...

**Comment by ksmurchison** [comment]
Fixed with: https://github.com/cyrusimap/cyrus-imapd/commit/4adbecfaff404f97e6e964647370f5bc8b52adae
