### ISSUE TITLE
dav_reconstruct needs to examine delayed submissions and snoozes

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#2927]
We need to make sure for everything which uses the sqlite database that dav_reconstruct touches, that a dav_reconstruct will rebuild them for that user safely and consistently!

**Comment by brong** [comment]
I'm tagging everyone on this one - to make sure we don't forget!

**Comment by elliefm** [comment]
Is this a "we know (or suspect) that it's broken", or more just a "we better make real sure it's good before we call it good"?

**Comment by ksmurchison** [comment]
This is "we know it currently doesn't reconstruct caldavalarm DB entries for snoozed emails or delayed submissions
