### ISSUE TITLE
Add DELETEDMODSEQ to counters for each datatype

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#2930]
Right now there's an issue where calendar/contacts changes in JMAP don't check the deletedmodseq on each mailbox, so a /changes query could fail to notice deletes for messages that have been unlinked.

This is a spec bug, so it needs fixed!  Best way it to keep the highwatermark for deletedmodseq for each datatype in the counters file, that way it's always going to be cheap to check!

**Comment by elliefm** [comment]
We have two weeks before I branch 3.2 off for release.  Can we do this in that time?  Have we done this already?

**Comment by ksmurchison** [comment]
I'll have to look to see if this has been done yet.

**Comment by ksmurchison** [comment]
@brong If we keep the highwatermark of all deletedmodseq for a datatype and use that to determine /changes, won't we possibly be excluding changes for a mailbox whose deletedmodseq is below the highwatermark?

Or perhaps, I'm not fully understanding the problem and proposed solution.

**Comment by ksmurchison** [comment]
Implemented by 4c9a3909332c2f264da928c0c9814397e6e36f12 and subsequent commits
