### ISSUE TITLE
JMAP: onSuccessUpdateEmail fails with 'unknownMethod' if mail namespace is not set.

### ISSUE THREAD

**Issue by iNPUTmice** [cyrusimap/cyrus-imapd#2958]
Apparently when utilizing `onSuccessUpdateEmail` the call fails if we don’t put `urn:ietf:params:jmap:mail` in the `using` attribute.

Here is the full request and the full response:
```json
{
    "methodCalls": [
        [
            "EmailSubmission/set",
            {
                "onSuccessUpdateEmail": {
                    "#es0": {
                        "keywords/$draft": null,
                        "mailboxIds": {
                            "da8d00c5-f86f-4175-aa0d-6c9970135f29": true
                        }
                    }
                },
                "accountId": "beta@ltt.rs",
                "create": {
                    "es0": {
                        "emailId": "M05255dd1915df81dc5a5771b",
                        "identityId": "beta@ltt.rs"
                    }
                }
            },
            "0"
        ]
    ],
    "using": [
        "urn:ietf:params:jmap:submission"
    ]
}
```

```json
{
    "methodResponses": [
        [
            "EmailSubmission/set",
            {
                "oldState": "6087",
                "newState": "6089",
                "created": {
                    "es0": {
                        "id": "S9",
                        "undoStatus": "final",
                        "sendAt": "2019-12-22T14:12:46Z"
                    }
                },
                "updated": null,
                "destroyed": null,
                "notCreated": null,
                "notUpdated": null,
                "notDestroyed": null,
                "accountId": "beta@ltt.rs"
            },
            "0"
        ],
        [
            "error",
            {
                "type": "unknownMethod"
            },
            "0"
        ]
    ],
    "sessionState": "0"
}
```

I have similar calls where I `Email/set` a draft and then submit it in the same request that work fine. (The first call to Email/set will cause my library to include the namespace in the request.)

I couldn’t find any mention in the RFC regarding using and namespaces of implicit calls. Personally I would not expect that I have to include it.

The same call used to work before Cyrus started validating `using`.

**Comment by brong** [comment]
Wow - interesting case.  Thinking about this, I would argue that you requiring you to ask for the `:mail` namespace is correct, and the logic is this: the content of the `onSuccessUpdateEmail` is a patch object against the email, and hence you need to be `using` the specification for the Email object.  Of course `onSuccessDestroyEmail` uses nothing but the ID, but it will also require it.

There could be an argument that `onSuccess*` should implicitly add `:mail` to `using` - the tricky bit here is what happens once you start using mail extensions as well - if you don't include those explicitly, then the request will still fail if it touches something in the Email object which the extension covers.

**Comment by iNPUTmice** [comment]
What happens if we have another method called `Email/set` in a future `:mail2` namespace. Will explicitly setting a `:mail2` namespace make `EmailSubmission/set` use that? Or will `EmailSubmission/set` still use `Email/set` from `:mail`. I would assume it does the latter. So if `EmailSubmission/set` will make its own namespace decisions anyway I don’t see why the user would have to specify that.

Anyway I guess I personally don’t have strong feelings in either direction. I was originally just coming from a discoverability perspective (It is unclear to the user that they have to do it.) and from a perspective of my library not automatically adding it (for which I have a branch that fixes that.)

I don’t know how Errata work but do you think that is something the RFC should clarify?

**Comment by ksmurchison** [comment]
I agree that implicit method calls on a data type different from the one in the explicit method needs to be clarified in one of the 2 RFCs:
- RFC8620 if we want generic language to handle this case and any others that may appear in extensions
- RFC8621 if this mixing of data types and methods is limited to Submission and Email

My preference would be to deal with this generically, but I won't argue strongly for either position.
The simplest solution would be to state that urn:ietf:params:jmap:submission implies urn:ietf:params:jmap:mail, since I don't know how a client would have access to an emailId for submission without having support for mail.  I might even argue that submission should've been a sub-capability of mail.

**Comment by rjbs** [comment]
> What happens if we have another method called Email/set in a future :mail2 namespace. Will explicitly setting a :mail2 namespace make EmailSubmission/set use that? 

If two capabilities can provide one method, you will only be able to use one, and you'd get the one you request.  (IMHO, but I feel good about it.)

**Comment by rsto** [comment]
The `emailId` property of the EmailSubmission object has type Email. But the Email object type is defined to exist in the `mail` capability (see [https://tools.ietf.org/html/rfc8621#section-1.3.1](https://tools.ietf.org/html/rfc8621#section-1.3.1)). IMHO this means that the submission capability requires the mail capability to fully define its objects types.

It also looks to me as if Cyrus failing with a `unknownMethod` error comes way too late. It should already reject a EmailSubmission method if the mail capability isn't included. Unfortunately it's not entirely clear what error to return: returning `unknownMethod` for the EmailSubmission method isn't really an option. We could return `emailId` as invalid property along with a description which states that the mail capability is required.

Probably @neilj would like to join the discussion for how to handle this spec-compliant?

**Comment by neilj** [comment]
I think there are two valid options here:

1. You consider the submission capability to require the mail capability as well and [reject the whole request](https://tools.ietf.org/html/rfc8620#section-3.6.1) at the HTTP level (although we don't really have a suitable error type defined to return).

2. Cyrus's current behaviour. The behaviour is specified as an implicit call to `Email/set` after the `EmailSubmission/set` call completes. The result of that method should be the same as if it were called explicitly, so without the require you get an `unknownMethod` error response.

I actually lean towards (2), i.e. keeping the current behaviour, as you could conceivably use the Identity objects on their own, and more importantly I could see other extensions combining with submission in the future to be able to send things without wanting to require mail.

> Will explicitly setting a :mail2 namespace make EmailSubmission/set use that

Yes, but I don't think that's necessarily a problem. The caller of the API is in complete control as to what capabilities they require and whether they use the onSuccess* methods. You couldn't require both `:mail` and `:mail2` as they would have conflicting namespaces, so it would never be ambiguous.

**Comment by ksmurchison** [comment]
@neilj What about failing the EmailSubmission/set with invalidArguments and a description along the lines of  "onSuccessUpdateEmail requires the use of urn:ietf:params:jmap:mail"

**Comment by brong** [comment]
Yes, good point!  It will reference an argument which can't be resolved without `:mail`.  Nice.

**Comment by neilj** [comment]
Sure, that seems fine.
