### ISSUE TITLE
JMAP: some recipient addresses parsed as `null`

### ISSUE THREAD

**Issue by wiktor-k** [cyrusimap/cyrus-imapd#2959]
Hello,

I'm using cyrus-imapd through Fastmail and noticed that for some e-mails JMAP JSON response contains `null` values in e-mail field. I did report it to Fastmail and the CTO responded that I should file the bug report here.

It seems that when the `To` header contains `undisclosed-recipients:;` the returned e-mail structure is as follows:
```
{
  "from": [
    {
      "name": "David Anderson",
      "email": "cw4763558@gmail.com"
    }
  ],
  "mailboxIds": {
    "0e384f2f-837d-4389-b6a9-f321ccca193d": true
  },
  "subject": "Approved to me that you got my mail.",
  "size": 10198,
  "snoozed": null,
  "keywords": {
    "$ismailinglist": true,
    "$seen": true,
    "$flagged": true,
    "$x-me-annot-2": true
  },
  "id": "M2256f8c460e77d88a02b9dd6",
  "spamScore": 0.8,
  "threadId": "Tb3a521256b8e769a",
  "receivedAt": "2019-12-22T06:15:39Z",
  "trustedSender": null,
  "preview": "-- \n*Dear Friend,*\n*I am David Anderson. I work as a procurement assistant. I got your\ncontact details in my search for a reliable and neutral company or\nindividual to partner with me in area of investment. I need your",
  "to": [
    {
      "email": null,
      "name": "undisclosed-recipients"
    },
    {
      "email": null,
      "name": null
    }
  ],
  "removedDates": {},
  "hasAttachment": false
}
```
Notice the `to` property. JMAP spect [section 4.1.2.3](https://tools.ietf.org/html/rfc8621#section-4.1.2.3) explicitly marks the `email` field as non-nullable (unlike the `name` field that can be `null`) and this cyrus behavior causes some clients to crash (see https://github.com/iNPUTmice/lttrs-android/issues/7). The spec says that the `email` field does not need to be addr-spec so maybe they should be `undisclosed-recipients:` and `` (empty string) in this case?

I can provide raw e-mails if necessary although I think this should be enough to reproduce.

CC @iNPUTmice

**Comment by brong** [comment]
We'll be talking about this one at tomorrow's Cyrus call :)  Thanks for reporting it.

**Comment by wiktor-k** [comment]
No problem @brong, I'm using a [third-party JMAP client](https://ltt.rs/) so it's easier to spot any spec misalignment w.r.t. Fastmail server.

Maybe it would be a good idea to also add this case to [JMAP test suite](https://fastmail.blog/2016/12/09/jmap-test-suite/) for example as a [Email/parse](https://www.rfc-editor.org/rfc/rfc8621.html#section-4.9) test?

**Comment by rjbs** [comment]
I added a test suite test (but for Email/get): https://github.com/fastmail/JMAP-TestSuite/pull/31

**Comment by rsto** [comment]
The JMAP spec defines two header forms for RFC5322 address headers: [Addresses](https://tools.ietf.org/html/rfc8621#section-4.1.2.3) and [GroupedAddresses](https://tools.ietf.org/html/rfc8621#section-4.1.2.4).

In the `Address` header form , the `undisclosed-recipients:;` header will result in an empty Address list. Note that the spec requires to ignore any comments or group information in this header form.

In the `GroupedAddress` header form,it will result in a GroupedAddress, with the name set to `undisclosed-recipients` and an empty `addresses` field.

I have implemented the forms for `Email/get` and am in the process updating `Email/set` to support both header forms.

**Comment by wiktor-k** [comment]
Is there an ETA when will this fix be deployed on Fastmail servers? I'd like to re-test this before my test  Fastmail JMAP account expires :)

**Comment by rjbs** [comment]
I would not like to promise any sooner than January 6th, but if you contact Fastmail support I will make sure the account in question does not expire before it's deployed.  Reference my username and this GitHub ticket.
