### ISSUE TITLE
Memory leak in charset_lookupname

### ISSUE THREAD

**Issue by josephg** [cyrusimap/cyrus-imapd#2963]
Probably nobody will run into this in practice but if you run into a charset that has an alias but is missing from libicu for some reason, [`charset_lookupname`](https://github.com/cyrusimap/cyrus-imapd/blob/934e7a18bb4aaa7587b3f7a457e31decd4923bd8/lib/charset.c#L1980) will quietly leak memory.

1. On line 1980 `s->name = xstrdup(name);` will use malloc to copy the name alias into `s->name`
2. Flow continues to the end of the function (line 2004) where we call `free(s);`

And the region allocated for `s->name` is leaked.

The fix is adding a call to `free(s->name);` before the call to `free(s);` [here in charset_lookupname](https://github.com/cyrusimap/cyrus-imapd/blob/934e7a18bb4aaa7587b3f7a457e31decd4923bd8/lib/charset.c#L2004).

**Comment by brong** [comment]
Fixed on master - thanks :)
