### ISSUE TITLE
LinkedIn group: Any objections?

### ISSUE THREAD

**Issue by marclaporte** [cyrusimap/cyrus-imapd#2965]
I would like to start a Cyrus IMAP LinkedIn group as a way to help grow the community.

Any objections?

**Comment by brong** [comment]
That sounds great to me.  Thanks for organising this.

**Comment by marclaporte** [comment]
Super! While we are at it, we'll also start a JMAP group.

Thanks!

**Comment by marclaporte** [comment]
Started https://www.linkedin.com/groups/13807819/

**Comment by marclaporte** [comment]
@brong Please join us https://www.linkedin.com/groups/13807819/
