### ISSUE TITLE
Support ContactGroup/query as well

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#2966]
Right now, there's no "ContactGroup/query" - which makes sense if you are only ever getting all of them or getting them by id, but is going to be an issue once we switch from uid to jmapid as the default id, and then need to find the group with a particular uid!

**Comment by rsto** [comment]
The spec at https://jmap.io/spec-contacts.html#contact-groups doesn't define /query, so it's really up to us what we want to query by. I'll scaffold support for query by uid, we might want to think of supporting query by ContactGroup.name as well.

**Comment by rsto** [comment]
Done. In the process I came to learn that the current code currently ignores comparators, so I created a new issue for that: https://github.com/cyrusimap/cyrus-imapd/issues/2967

**Comment by brong** [comment]
I agree that by name makes sense.

Thanks for getting this done so quick :)
