### ISSUE TITLE
IMAP: ESORT (RFC 5267)

### ISSUE THREAD

**Issue by kael** [cyrusimap/cyrus-imapd#2975]
An IMAP extension request.

The [ESORT extension](https://tools.ietf.org/html/rfc5267#section-3) would be quite useful as a complement to ESEARCH.

Since Cyrus supports SORT and ESEARCH, it wouldn't be too complicated to implement ESORT, would it ?

**Comment by ksmurchison** [comment]
ESORT will appear in Cyrus 3.3+

**Comment by kael** [comment]
Thanks a lot. :pray:  Cheers !

**Comment by dilyanpalauzov** [comment]
Clarification: Cyrus supports the ESEARCH capability, this is imap response (RFC 4731) announced with the ESEARCH capability.

The ESEARCH command, as introduced by RFC 7377 (IMAP4 Multimailbox SEARCH Extension), “MULTISEARCH” capability string, is not supported.
