### ISSUE TITLE
Site cyrusimap.org not available

### ISSUE THREAD

**Issue by worldworm** [cyrusimap/cyrus-imapd#3009]
your page is not available.
http://cyrusimap.org/

If the URL has changed, please open a pull request at
https://github.com/Kickball/awesome-selfhosted or create an issue. Thank you!

awesome-selfhosted/awesome-selfhosted#1767

**Comment by elliefm** [comment]
known issue, will be back... eventually (sorry, I don't have a timeline)

in the meantime, https://www.cyrusimap.org works fine
