### ISSUE TITLE
Potential bug on actions_setuser

### ISSUE THREAD

**Issue by nicowaisman** [cyrusimap/cyrus-imapd#3025]
Hey CyrusImap team,
I found a small bug on the `actions_setuser`:

`strlcpy` and `strlcat` are size-bounded string copying and concatenation functions. They are designed to be safer and less error prone. Unlike `strcpy`/`strcat`, these functions restrict the copy to a provided size and guarantee that the resulting string is NUL-terminated.

The problem with these functions exists in the fine print of their intended functionality:
```
The strlcpy() and strlcat() functions return the total length of the string they tried to create. For strlcpy() that means the length of src. For strlcat() that means the initial length of dst plus the length of src. While this may seem somewhat confusing, it was done to make truncation detection simple.
```
A correct implementation of strlcpy requires that its return value is checked against the size argument to see if it's bigger. 

This is the problem with `actions_setuser`
```
int actions_setuser(const char *userid)
{
  char userbuf[1024], *user, *domain = NULL;
  size_t size = 1024, len;
  int result;

  char *sieve_dir = (char *) xzmalloc(size+1);

  sieved_userid = xstrdup(userid);
  user = (char *) userid;
  if (config_virtdomains && strchr(user, '@')) {
      /* split the user and domain */
      strlcpy(userbuf, userid, sizeof(userbuf));
      user = userbuf;
      if ((domain = strrchr(user, '@'))) *domain++ = '\0';
  }

  len = strlcpy(sieve_dir, sieve_dir_config, size); // [1]

  if (domain) {
      char dhash = (char) dir_hash_c(domain, config_fulldirhash);
      len += snprintf(sieve_dir+len, size-len, "%s%c/%s",
                      FNAME_DOMAINDIR, dhash, domain); // [2]
  }
```
At [1] there is a call to strlcpy to copy the `sieve_dir_config` string, this string is taken from a configuration file, however if this string is bigger than 1024, the function will return 1024 on the variable `len`.

At [2], the sprintf is called, however `len` will be bigger than `size`, making it a negative number and disable any restriction on copy size.

This bug pose not risk, since the original string that allow the overflow to happen is on the cyrus-imap configuration file. If an attacker have write access to the configuration file, the problems are much more bigger than this bug.

**Comment by ksmurchison** [comment]
Fixed with 
https://github.com/cyrusimap/cyrus-imapd/commit/cdbbb46a1f3e99f6c4c567e50839c31ec2d835fc
