### ISSUE TITLE
we need to start collating "release notes for 3.3"

### ISSUE THREAD

**Issue by elliefm** [cyrusimap/cyrus-imapd#3027]
This will eventually be in the same format as the release notes for (specifically) 3.0.0 and 3.2.0 are.  i.e. it should be a list of the new features, major improvements, and anything that's not backwards compatible, since the last major release (in this case, that is "since 3.2").

For the 3.1 development series (go look at those release notes), we kept a series of documents, where each one was the previous one plus the new big changes.  This was TREMENDOUSLY helpful in preparing release notes for 3.2.0, because by the time we got there, we already had a big list of everything that had changed since 3.0!

It's time to start thinking about creating the same convenience for ourselves when 3.4 arrives, by recording what we're doing on master now.  This will also form the initial release notes for the first 3.3.0 development snapshot (to be released sometime after 3.2.0 lands).

If you have top-of-head recollection of new features/etc we've built since we forked 3.2 in february, please summarise them briefly here.  Anything else, we'll need to figure out from reading the commit log, which is less pleasant than simply remembering.

Thanks!

**Comment by dilyanpalauzov** [comment]
Isn’t this obsolete now?
