### ISSUE TITLE
Build fails on RHEL 7 when using --enable-http

### ISSUE THREAD

**Issue by hagedose** [cyrusimap/cyrus-imapd#3038]
I have successfully built 3.2.0 on RHEL 7 without --enable-http, but I wanted to try prometheus stats. When I ran a build with --enable-http configure was happy:

```
Cyrus Server configured components

   gssapi:             yes
   autocreate:         no
   idled:              yes
   httpd:              yes
   kerberos V4:        no
   murder:             yes
   nntpd:              no
   replication:        yes
   sieve:              yes
   srs:                no
   calalarmd:          no
   jmap:               no
   objectstore:        no
   backup:             yes
   com_err:

External dependencies:
   ldap:               yes
   openssl:            yes
   zlib:               yes
   jansson:            yes
   pcre:               yes
   clamav:             no
   snmp:               no
   -----------------------
   caringo:            no
   openio:             no
   -----------------------
   nghttp2:            no
   wslay:              no
   brotli:             no
   zstd:               no
   xml2:               yes
   ical:               yes
   icu4c:              yes
   shapelib:           no
   chardet:            no
   cld2:               no

Database support:
   mysql:              no
   postgresql:         no
   sqlite:             yes
   zeroskip:           no

Search engine:
   squat:              yes
   xapian:             yes
   xapian_cjk_tokens:  ngrams

Hardware support:
   SSE4.2:             yes

Documentation dependencies:
   sphinx-build:       /usr/bin/sphinx-build
   Pod::POM::View::Restructured:  no
   GitPython:          no

Installation directories:
   prefix:             /usr
   sysconfdir:         /etc

Build info:
   shared:             yes
   static:             no
   cflags:             -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic
   cxxflags:           -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -std=c++11
   libs:                -lgssapi_krb5 -lkrb5 -lk5crypto -lcom_err -lkrb5support -ljansson    -lpcre -lpcreposix -lz -lxml2   -lical -licalss -licalvcal    -lsqlite3
   ldflags:            -Wl,-z,relro
   unit tests (cunit):
```

But the build failed here:

```
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I. -I./lib -I. -I./lib -DLIBEXEC_DIR=\"/usr/lib/cyrus-imapd\" -DSBIN_DIR=\"/usr/lib/cyrus-imapd\" -DSYSCONF_DIR=\"/etc\" -DHAVE_CONFIG_H -I/usr/include -I/usr/include/libxml2 -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -std=c++11 -c imap/icu_wrap.cpp  -fPIC -DPIC -o imap/.libs/imap_libcyrus_imap_la-icu_wrap.o
imap/icu_wrap.cpp: In function ‘char* icu_getIDForWindowsID(const char*)’:
imap/icu_wrap.cpp:64:5: error: ‘getIDForWindowsID’ is not a member of ‘icu_50::TimeZone’
     icu::TimeZone::getIDForWindowsID(uWinID, NULL, uID, status);
     ^
make[2]: *** [imap/imap_libcyrus_imap_la-icu_wrap.lo] Error 1

```

RHEL 7 has libicu-50.2-4.el7_7.x86_64

Is that version too old?

**Comment by dilyanpalauzov** [comment]
icu::TimeZone::getIDForWindowsID was invented on [22 May 2013](https://github.com/unicode-org/icu/commit/7e0d7fa) but was behind `#ifndef U_HIDE_DRAFT_API` until [16 March 2015](https://github.com/unicode-org/icu/commit/7d74634fa).

As of http://site.icu-project.org/download/50: 

ICU4C 50.1.2 was released on 17 December 2012 and 50.2 added on 11 April 2019 [just the tz2019a data and New Japanese era Reiwa support](https://github.com/unicode-org/icu/releases/tag/release-50-2).

ICU 52 up to 54.2 contain getWindowsID with `ifndef U_HIDE_DRAFT_API`, ICU 55.1 contains getWindowsID without `ifndef U_HIDE_DRAFT_API`.

So https://www.cyrusimap.org/imap/developer/compiling.html needs to state that at least ICU 55 is necessary and configure.ac:PKG_CHECK_MODULES(icu, ) has to insist that at least ICU55, released 2015, is installed. It is irrelevant that ICU 52…54 can also be used with the DRAFT_API directive, as these are anyway outdated enough.

**Comment by hagedose** [comment]
Hm, I tried building on CentOS 8, but there were so many other missing dependencies that I decided to build a local copy of libicu for RHEL 7 instead. I took the SRPM for RHEL 8,  and built that. Instead of the system paths, I installed everything under /usr/local. By setting` ICU_CFLAGS=-I/usr/local/include/unicode` I managed to compile the source, but I can't get it to link.

I tried both
`ICU_LIBS="-L/usr/local/lib -licui18n -licuuc -licudata"`
and
`ICU_LIBS="-R/usr/local/lib -licui18n -licuuc -licudata"`
but neither works. The linking stage fails at

```
/bin/sh ./libtool  --tag=CC   --mode=link gcc -fPIC  -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic  -R/usr/local/lib -licui18n -licuuc -licudata -lxml2    -lical -licalss -licalvcal    -ljansson        -lm  -ljansson   -Wl,-z,relro  -o imap/imapd imap/imap_proxy.o imap/imapd.o imap/mutex_fake.o imap/proxy.o imap/sync_support.o master/service.o  imap/pushstats.o sieve/libcyrus_sieve.la lib/libcyrus.la lib/libcyrus_min.la -lgssapi_krb5 -lkrb5 -lk5crypto -lcom_err -lkrb5support -ljansson    -lpcre -lpcreposix -lz -lxml2   -lical -licalss -licalvcal    -lsqlite3 -lsasl2 -lssl -lcrypto   -lssl -lcrypto   imap/libcyrus_imap.la lib/libcyrus.la lib/libcyrus_min.la -lgssapi_krb5 -lkrb5 -lk5crypto -lcom_err -lkrb5support -ljansson    -lpcre -lpcreposix -lz -lxml2   -lical -licalss -licalvcal    -lsqlite3 -lsasl2 -lssl -lcrypto   -lssl -lcrypto   -lcom_err -lwrap -lnsl  -ljansson   -lgssapi_krb5 -lkrb5 -lk5crypto -lcom_err -lkrb5support -ljansson    -lpcre -lpcreposix -lz -lxml2   -lical -licalss -licalvcal    -lsqlite3
libtool: link: gcc -fPIC -fvisibility=hidden -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches -m64 -mtune=generic -Wl,-z -Wl,relro -o imtest/.libs/imtest imtest/imtest_imtest-imtest.o  -licui18n -licuuc -licudata -lm lib/.libs/libcyrus.so lib/.libs/libcyrus_min.so -lsasl2 -lssl -lcrypto -lgssapi_krb5 -lkrb5 -lk5crypto -lcom_err -lkrb5support -ljansson -lpcre -lpcreposix -lz -lxml2 -lical -licalss -licalvcal -lsqlite3 -Wl,-rpath -Wl,/usr/lib64 -Wl,-rpath -Wl,/usr/local/lib
lib/.libs/libcyrus.so: undefined reference to `ucnv_toUnicode_60'
lib/.libs/libcyrus.so: undefined reference to `unorm2_quickCheck_60'
lib/.libs/libcyrus.so: undefined reference to `u_strFromUTF8_60'
lib/.libs/libcyrus.so: undefined reference to `unorm2_normalize_60'
lib/.libs/libcyrus.so: undefined reference to `ucnv_getName_60'
lib/.libs/libcyrus.so: undefined reference to `ucnv_close_60'
lib/.libs/libcyrus.so: undefined reference to `unorm2_getNFCInstance_60'
lib/.libs/libcyrus.so: undefined reference to `ucnv_reset_60'
lib/.libs/libcyrus.so: undefined reference to `ucnv_fromUnicode_60'
lib/.libs/libcyrus.so: undefined reference to `u_strToUTF8_60'
lib/.libs/libcyrus.so: undefined reference to `utf8_nextCharSafeBody_60'
lib/.libs/libcyrus.so: undefined reference to `ucnv_open_60'
lib/.libs/libcyrus.so: undefined reference to `ucnv_convert_60'
collect2: error: ld returned 1 exit status
```

Any ideas how to fix that?

**Comment by elliefm** [comment]
On Fri, May 15, 2020, at 1:02 AM, Sebastian Hagedorn wrote:
> Hm, I tried building on CentOS 8, but there were so many other missing dependencies that I decided to build a local copy of libicu for RHEL 7 instead. I took the SRPM for RHEL 8, and built that. Instead of the system paths, I installed everything under /usr/local. By setting` ICU_CFLAGS=-I/usr/local/include/unicode` I managed to compile the source, but I can't get it to link.


> I tried both
> `ICU_LIBS="-L/usr/local/lib -licui18n -licuuc -licudata"`
>  and
> `ICU_LIBS="-R/usr/local/lib -licui18n -licuuc -licudata"`
>  but neither works.


Do you mean to say that you set those ICU_* variables in the environment, and then it was able to compile, but unable to link?

Cyrus expects pkg-config to provide the correct values for those variables. Is there a reason you don't simply let pkg-config find it? If you installed icu to /usr/local, then you may just need to add /usr/local/lib/pkgconfig to your $PKG_CONFIG_PATH. There ought to be icu-*.pc files in that directory -- if there's not, that's weird?

**Comment by elliefm** [comment]
@dilyanpalauzov Thanks for sleuthing out the minimum version number.  I've updated configure.ac and the compiling document on both cyrus-imapd-3.2 and master branches :)

**Comment by hagedose** [comment]
> Do you mean to say that you set those ICU_* variables in the environment, and then it was able to compile, but unable to link?

Correct.

>  Cyrus expects pkg-config to provide the correct values for those variables. Is there a reason you don't simply let pkg-config find it? If you installed icu to /usr/local, then you may just need to add /usr/local/lib/pkgconfig to your $PKG_CONFIG_PATH. There ought to be icu-*.pc files in that directory -- if there's not, that's weird?

I did not know about that. Thanks, that was the hint I needed!

**Comment by dilyanpalauzov** [comment]
As ICU is needed only for `--enable-http` it shall be moved in `docsrc/imap/develope/compiling.rst` from `Required Build Dependencies` to `Optional Build Dependencies`.

**Comment by elliefm** [comment]
If I remember correctly, ICU recently became a core dependency (it is now used by things other than httpd).  But, it looks like if you compile without `--enable-http`, then the function that's missing in pre-55 isn't used, which is why the old version worked for @hagedorn up until he enabled http.

I guess we could say "if you `--enable-http` then you need ICU 55+; but if you `--disable-http` then you still need ICU, but an older version may suffice".  But to be honest, that sounds like more nuisance/confusion than anything else; much easier to simply require ICU 55.

**Comment by dilyanpalauzov** [comment]
Ok
