### ISSUE TITLE
SET METADATA error with user defined annotation

### ISSUE THREAD

**Issue by falon** [cyrusimap/cyrus-imapd#3043]
Hello,

  let suppose I define in imapd.conf
`annotation_definitions: /etc/annoIMAP.conf`

and `annoIMAP.conf` is:

```/vendor/EXAMPLE/partition/mypart,server,string,backend,value.priv,lrswipkxtea```

Then the SETMETADATA fails:
```
a SETMETADATA "" (/private/vendor/EXAMPLE/partition/mypart "prova1")
a NO Permission denied 

```
I have to write the name downcase in annotation_definitions:

```/vendor/example/partition/mypart,server,string,backend,value.priv,lrswipkxtea```
In this last case:
```
a SETMETADATA "" (/private/vendor/EXAMPLE/partition/mypart "prova1")
a OK Completed
```

The RFC5464 says:

> "Except as noted otherwise, all alphabetic characters are case-
>    insensitive.  The use of upper or lower case characters to define
>    token strings is for editorial clarity only.  Implementations MUST
>    accept these strings in a case-insensitive fashion."

this is true in IMAP query, but in the definition file the names must be downcase.

I don't know if you can consider this like a bug. At least the man of imapd.conf could remember to set the  annotation_definitions names in downcase fashion.

See also [here](https://lists.andrew.cmu.edu/pipermail/info-cyrus/2020-April/041217.html).
Thank you

**Comment by elliefm** [comment]
I think the fix for this might be as simple as adding an `lcase(ae->name);` after this line:
https://github.com/cyrusimap/cyrus-imapd/blob/94ecc2c44a252f76b0746cbbc3504a05d9265b92/imap/annotate.c#L4046

I haven't seen this option before.  We have cunit tests for the parser for it, but we don't seem to have cassandane tests for its behaviour, and maybe we should.

**Comment by elliefm** [comment]
I don't have a strong opinion on whether or not this is a bug, but it looks like the case-sensitivity of that file has existed for as long as the option to use it has, wow.

**Comment by falon** [comment]
I agree. The real behavior is quite confusing. I need to explain better, because the possible bug is not really related to the downcase in 3.x version, but is related to the different behavior from SETANNOTATION on 2.4 releases and SETMETADATA on 3.x releases.

Let suppose to provide:

```
/vendor/EXAMPLE/partition/comune.prova.it,server,string,backend,value.priv,lrswipkxtea
```
with the exact case shown above on 2.4 and 3.2 Cyrus IMAP servers.

With the 2.4 Cyrus IMAP server the command

```
a SETANNOTATION "" "/vendor/EXAMPLE/partition/comune.prova.it"  ("value.priv" "prova1")
a OK Completed
```
works! The SETANNOTATION command seems to require the exact case provided in the definition file, because with "/vendor/example/partition/comune.prova.it" will fail.

Instead, on the 3.x server, the command

```
a SETMETADATA "" (/private/vendor/EXAMPLE/partition/comune.prova.it "prova1")
a NO Permission denied
```
fails. The SETMETADATA command seems to need the name in the definition file all lowercase. If this requirement is respected, then SETMETADATA works with **any** case, instead.

Anyway, the proposed patch seems to uniform the behavior as expected.

**Comment by elliefm** [comment]
wip here (also adds a unit test): https://github.com/cyrusimap/cyrus-imapd/compare/master...elliefm:v33/3043-annotations-case

**Comment by elliefm** [comment]
Think I found a bug in annotate.c while chasing a quirk in the cunit test... pasting from slack:

> annotate_init() calls init_annotation_definitions() to populate the server_entries, mailbox_entries, and message_entries arrays.  init_annotation_definitions() just appends everything it needs to whatever's already there... but then annotate_done() never clears them.
> so if you do `annotate_init(); ...; annotate_done(); ...; annotate_init(); ...; annotate_done();` those arrays get longer and longer and longer
> and if you're, say, some cunit tests expecting to have different sets of possible annotations each time, the ones you thought were gone are maybe still around!

I need to tap out for the day, but I'll chase this further next week.

**Comment by elliefm** [comment]
This is fixed on the master branch now.  I'm not convinced about backporting it to 3.2, because it changes behaviour a little, and the current 3.2 behaviour has existed (for good or ill) for a several major versions already.
