### ISSUE TITLE
RFC2231 support on boundary param?

### ISSUE THREAD

**Issue by alecpl** [cyrusimap/cyrus-imapd#3048]
I just find out that Cyrus Imap 2.5.13 is not able to parse an email with such header:
```
X-Mailer: szn-ebox-5.0.4
Content-Type: multipart/alternative; boundary*0*=us-ascii''%3D_7ea0b6022f2f24b72b654878%3D10e51b18-ade7-5448-803;
 boundary*1*=3-b658d5dbbbbd_%3D
```
It returns a dummy BODYSTRUCTURE: `("TEXT" "PLAIN" ("CHARSET" "us-ascii") NIL NIL "7BIT" 0 0 NIL NIL NIL NIL)`.

Has this been fixed in newer versions?

**Comment by elliefm** [comment]
Looks like the code for this functionality lives in imap/message.c and the tests in cunit/message.testc.  Neither implementation seems to have had substantial changes recently, so I guess it's probably still broken?

The tests pass, but they don't exercise the behaviour for the boundary parameter specifically.  I wonder if boundary parsing is handled differently from other parameters?

I'm assuming for now that the failing example is valid; I'm not familiar with this RFC.

**Comment by alecpl** [comment]
It is valid. See example in https://tools.ietf.org/html/rfc2231#section-4.1 This syntax is more commonly used for encoding attachment name parameter(s).

**Comment by ksmurchison** [comment]
Fixed with commit above
