### ISSUE TITLE
promstatsd has no manpage

### ISSUE THREAD

**Issue by hagedose** [cyrusimap/cyrus-imapd#3049]
promstatsd needs a manpage. There is some documentation here, but as a separate binary it should have its now manpage:

https://www.cyrusimap.org/3.2/imap/reference/admin/monitoring.html

**Comment by elliefm** [comment]
Good call!  I've created a man page for it (65d183ffe8 on cyrus-imapd-3.2, 6029e05bc6 on master) and updated the Monitoring page to link to it as well.

The promstatsd.8 man page will be included in 3.2.1, and will be available on the website at https://www.cyrusimap.org/3.2/imap/reference/manpages/systemcommands/promstatsd.html in about 10 minutes or so, once the rebuild script fires :)
