### ISSUE TITLE
FR: add the ability to use the client's IP in an SQL query

### ISSUE THREAD

**Issue by asy972** [cyrusimap/cyrus-imapd#3072]
Hello.

It would be nice to be able to use the client's IP address in an SQL query in sasl_sql_select in imapd.conf. This would allow to restrict IP access individually per E-Mail.

**Comment by elliefm** [comment]
Thanks for the feature request.  The "sasl_" options in imapd.conf are mostly passed directly through to the SASL library, so I think this enhancement needs to be made there, not here.

I've created https://github.com/cyrusimap/cyrus-sasl/issues/615 for you, and tagged you in it.  You may need to manually subscribe yourself to it to get notifications when it's updated, I'm not sure.

**Comment by asy972** [comment]
> The "sasl_" options in imapd.conf are mostly passed directly through to the SASL library, so I think this enhancement needs to be made there, not here.

I thought about it but then decided that Cyrus-IMAP should pass IP to SASL

> I've created cyrusimap/cyrus-sasl#615 for you,

Thanks.
