### ISSUE TITLE
Wrongfully HasNoChildren when another folder uses whitespaces

### ISSUE THREAD

**Issue by slangenhorst** [cyrusimap/cyrus-imapd#3074]
Hi,

couldn't boil it down to one codepart for now, sorry.

`localhost> cm user.foo`
`localhost> cm user.foo.Sent`
`localhost> cm user.foo.Sent.2020`
`localhost> lm user.foo.*`
`user.foo.Sent (\HasChildren)`
`user.foo.Sent.2020 (\HasNoChildren)`
That's fine.

Now add "Sent Mails":
`localhost> cm "user.foo.Sent Mails"`
`localhost> lm user.foo.*`
`user.foo.Sent (\HasNoChildren)`
`user.foo.Sent Mails (\HasNoChildren)`
`user.foo.Sent.2020 (\HasNoChildren)`

As you see, the folder "Sent" looses its parenthood in progress.

In IMAP likewise:
`. list * *`
`* LIST (\HasNoChildren) "." INBOX`
`* LIST (\HasNoChildren) "." Sent`
`* LIST (\HasNoChildren) "." "Sent Mails"`
`* LIST (\HasNoChildren) "." Sent.2020`
`. OK Completed (0.001 secs 4 calls)`

I thought it is new in 3.2, but also my 3.0.13-instance shows this problem.
At least Thunderbird seems to use HasChildren and HasNoChildren.

**Comment by ksmurchison** [comment]
Look at the improved_mboxlist_sort option in imapd.conf(5)
