### ISSUE TITLE
backport deflatepending fix to 3.2

### ISSUE THREAD

**Issue by elliefm** [cyrusimap/cyrus-imapd#3084]
This is from #3061, which is already closed because it has been merged to master, but I don't want to lose track of it in the closed pile.

Looks like, in addition to the commit in the pull request, we will also want to grab b0b1466047 from master.

**Comment by anatoli26** [comment]
@elliefm, did you have an opportunity to backport this fix to 3.2?

**Comment by elliefm** [comment]
Oh, I don't think I did yet, thanks for the reminder

**Comment by elliefm** [comment]
This is now on the 3.2 branch and will be in the next release :)

**Comment by anatoli26** [comment]
Great! Thanks!
