### ISSUE TITLE
sieve-lex.c and sieve.[ch] aren't rebuilt when sieve-lex.l and sieve.y change

### ISSUE THREAD

**Issue by elliefm** [cyrusimap/cyrus-imapd#3093]
something wrong with our Makefile.am rules probably, need to figure out what

**Comment by elliefm** [comment]
Upon closer examination:  the c files are regenerated correctly, but then the build products that depend on those c files are not rebuilt:

```
$ make
[...]
$ touch sieve/sieve-lex.l
$ make
  LEX      sieve/sieve-lex.c
$ touch sieve/sieve.y
$ make
  YACC     sieve/sieve.c
  YACC     sieve/sieve.c
  LEX      sieve/sieve-lex.c
```

(make output judiciously trimmed to reduce noise)

In our `sieve_libcyrus_sieve_lex_la_SOURCES` and `sieve_libcyrus_sieve_la_SOURCES` specifications we include the ".l" and ".y" versions, which I think _should_ be correct (and automake _should_ figure out that the intermediates are important).  But these are both libtool libraries, so maybe there's some disagreement between automake and libtool about what needs to happen when?

It might be as simple as also listing the appropriate generated .c files in these rules, but I'm not sure if that'll introduce new side effects.  Needs experimentation and some documentation reading.

**Comment by elliefm** [comment]
> It might be as simple as also listing the appropriate generated .c files in these rules

automake documentation explicitly says not to do it this way

**Comment by ksmurchison** [comment]
@elliefm   I just discovered that running configure with --enable-maintainer-mode does exactly what I want.  If any *.[yl] is changed they get rebuilt automatically by a subsequent make without having to delete sieve.[ch] and sieve-lex.[ch] first.  We can probably close this task unless you want to keep digging.

**Comment by elliefm** [comment]
Oh, that's interesting

I read somewhere a while ago that supposedly having a separate maintainer mode is going to be deprecated or is no longer fashionable or whatever, and I have vaguely thought about either removing it or making it always on in ours.  But I don't have a good source for that "read somewhere" so I've left it alone, and it's now sounding like it's useful for something, maybe that source was a bit full of it.

Usually I only use maintainer mode when building release tarballs, but I suppose arguably we are all "maintainers" and should use it normally, idk.

Anyway, good to know, and good to have written down for next time we start thinking about this stuff. Thanks!
