### ISSUE TITLE
cyr_info shows archive partitions as unknown keys

### ISSUE THREAD

**Issue by falon** [cyrusimap/cyrus-imapd#3116]
`cyr_info conf-lint` on Cyrus IMAP 3.2.2 lists all archive partitions as unknown config keys:

```
$ cyr_info conf-lint
archivepartition-maildata4: /sysarchivio/example.com/maildata1
[...]
```

I suppose this could be a bug...

**Comment by elliefm** [comment]
That's interesting...

These things are called "overflow strings", as in `config_getoverflowstring()`.  I thought I had added a fix to conf-lint to recognise and not complain about the known ones, but maybe I overlooked archivepartition-*?

**Comment by elliefm** [comment]
Ah, here we go: 46d261fa3940ad5ccf8ef3bb5b1da2a0e6bd73b0.  This was previously #1775 

```
    /* only valid if there's a partition with the same name */
     if (!strncmp(key, "archivepartition-", 17)) {
         if (config_getoverflowstring(key+8, NULL))
             return 1;
     }
```

Do you have a "partition-maildata4:" defined?  If you don't, then it's correct (or at least: expected) that it's complaining.  

If you do, then there's a bug.  That `key+8` looks suspect, now that I look at it again closely?!  I think it's meant to be `key+7`...  Does changing that and recompiling fix it for you?

**Comment by elliefm** [comment]
I've just added a Cassandane test and confirmed that it's buggy and that "7" is the fix.  Looks like this dates back to 3.0; fix coming to affected branches shortly. :)
