### ISSUE TITLE
Building on Apple Silicon (ARM) Mac

### ISSUE THREAD

**Issue by nbrachfogel** [cyrusimap/cyrus-imapd#3118]
There's currently no way to build on the new Apple Silicon (ARM) Macs.

**Comment by elliefm** [comment]
Last time I tried (a few years ago), Cyrus didn't build on Intel Macs either.  Has that changed?

**Comment by nbrachfogel** [comment]
Yes. Cyrus works on Mac OSX.
https://www.cyrusimap.org/sasl/sasl/macosx.html#install-macos

**Comment by elliefm** [comment]
That's Cyrus-SASL, not Cyrus-IMAP.  Which are you asking about?  This is the issue tracker for Cyrus-IMAP, so I am currently assuming you're asking about that.

The tracker for Cyrus-SASL is here: https://github.com/cyrusimap/cyrus-sasl/issues

**Comment by nbrachfogel** [comment]
I'm really sorry, it looks like I made a mistake.
Thanks for your help.
