### ISSUE TITLE
JMAP Support in Distro Package

### ISSUE THREAD

**Issue by sstubbs** [cyrusimap/cyrus-imapd#3170]
Hi,

I'm trying to get jmap working in a distro version of Cyrus Imap. Do any support this? I've tried the following in a dockerfile:
```Dockerfile
FROM ubuntu:20.10

# Install packages
RUN export DEBIAN_FRONTEND=noninteractive \
&& apt-get update \
&& apt-get install \
-y \
--no-install-recommends \
apt-utils \
rsyslog \
logrotate \
libsasl2-2 \
sasl2-bin \
libsasl2-modules \
libpam-pgsql \
cyrus-caldav \
cyrus-imapd \
cyrus-murder \
cyrus-nntpd \
cyrus-pop3d \
cyrus-replication \
&& rm -rf /var/lib/apt/lists/*
```

but I don't see a jmap package and it doesn't look like it's working. Will do some more testing on it though.

Do I still have to compile it if I want jmap support?

**Comment by ksmurchison** [comment]
If you don't have a cyrus httpd binary then you won't have JMAP support.  I'm not familar with Ubuntu packages, but is there a cyrus-httpd package?  What version of Cyrus is currently packaged?

**Comment by sstubbs** [comment]
cyrus imap version is 3.2.3 which is why im using it. I think sasl auth has changed since the compiled version of 3.1.9 which is what I was using before. This issue can be closed and I will add another one for the auth issue.

**Comment by sstubbs** [comment]
Here is the auth issue https://github.com/cyrusimap/cyrus-imapd/issues/3173
