### ISSUE TITLE
Legacy Fastmail sharing

### ISSUE THREAD

**Issue by dilyanpalauzov** [cyrusimap/cyrus-imapd#3205]
http_dav:calcarddav_parse_path() contains:
```c
    /* Check for FastMail legacy sharing URLs and redirect */
    if (httpd_userid && !config_getswitch(IMAPOPT_FASTMAILSHARING) &&
        tgt->flags != TGT_DAV_SHARED &&
        !mboxname_userownsmailbox(httpd_userid, mboxname)) {
        buf_reset(&redirect_buf);
        buf_printf(&redirect_buf, "%s/%s/%s/%s%c%s",
                 tgt->namespace->prefix, USER_COLLECTION_PREFIX,
                 httpd_userid, tgt->userid, SHARED_COLLECTION_DELIM,
                 tgt->collection);
        *resultstr = buf_cstring(&redirect_buf);

        ret = HTTP_MOVED;
        goto done;
    }
```
It handles (legacy) fastmail sharing, when IMAPOPT_FASTMAILSHARING is not set.  Can the code be removed, if fastmail-sharing was never on?  When has that snippet added value?

**Comment by brong** [comment]
Releases were shipped with the fastmailsharing option available, so it's possible that other sites have used it.

**Comment by dilyanpalauzov** [comment]
What will happen, if sites that never used fm-sharing, remove the above snippet?

**Comment by brong** [comment]
Everything would keep working fine - this is just a redirect for clients which have cached those legacy paths.

**Comment by dilyanpalauzov** [comment]
Thanks for your answer.
