### ISSUE TITLE
Reconstruct fails with hash missmatch when upgrading version 10 mailboxes to version 16.

### ISSUE THREAD

**Issue by lastcmaster** [cyrusimap/cyrus-imapd#3230]
A number of mailboxes in an old installation failes with the following error:

```
/var/log/imapd.log:Oct  6 15:00:07 mailboxes reconstruct[17841]: Repacking mailbox user.bcn version 16
/var/log/imapd.log:Oct  6 15:01:29 mailboxes reconstruct[17841]: IOERROR: CRC mismatch on repack commit: user.bcn (953312354 1929973572) (12345678 12345678)
/var/log/imapd.log:Oct  6 15:01:29 mailboxes reconstruct[17841]: mappedfile: longlock /var/spool/imap/user/bcn/cyrus.annotations for 82.3 seconds
/var/log/imapd.log:Oct  6 15:01:29 mailboxes reconstruct[17841]: mailbox: longlock user.bcn for 82.3 seconds
```

These users seems to have excessive problems with Thunderbird and Mac Mail as the mailbox content is not stable in the client view.

**Comment by elliefm** [comment]
Have you run `reconstruct -G` for the affected mailboxes?  I vaguely recall there being a problem in the past where old mailboxes that had previously been upgraded to version 10 may have had uninitialised GUID fields, which can cause a variety of problems later on.  The `-G` option forces re-parsing of the on-disk messages (rather than trusting the caches), so it'll be quite slow, but it should recover from bad records (including those whose GUID is missing).

**Comment by lastcmaster** [comment]
Yes, the full command was
```
sbin/reconstruct -G -R -V max user/bcn
```

I have not dared trying to use 
```
sbin/reconstruct -U -G -R -V max user/bcn
```
Any thoughts?

**Comment by lastcmaster** [comment]
-U do not seems to work:
```
% sbin/reconstruct -U user/abm
user.abm: updating sync_crc 0 => 1802562381
user.abm: updating sync_crc_annot 0 => 12345678
user/abm
% sbin/reconstruct -G -R -V max user/abm
user/abm
FAILED TO REPACK user/abm with new version Mailbox format corruption detected
```

Log:
```
Oct  9 11:25:25 mailboxes reconstruct[40854]: reconstructing user.abm
Oct  9 11:25:25 mailboxes reconstruct[40854]: user.abm: updating sync_crc 0 => 1802562381
Oct  9 11:25:25 mailboxes reconstruct[40854]: user.abm: updating sync_crc_annot 0 => 12345678
Oct  9 11:32:37 mailboxes reconstruct[40868]: Repacking mailbox user.abm version 16
Oct  9 11:32:58 mailboxes reconstruct[40868]: IOERROR: CRC mismatch on repack commit: user.abm (1802562381 1950933372) (12345678 12345678)
Oct  9 11:32:59 mailboxes reconstruct[40868]: mappedfile: longlock /var/spool/imap/user/abm/cyrus.annotations for 22.0 seconds
Oct  9 11:32:59 mailboxes reconstruct[40868]: mailbox: longlock user.abm for 22.0 seconds```

**Comment by elliefm** [comment]
Looking at source for reconstruct, it looks like the other reconstruct actions only happen when the `-V [version]` argument is NOT supplied.  That's surprising, and could probably be better documented!

So I think you might need to reconstruct with whichever of `-G`, `-R` or `-U` it takes to fix the underlying problem, and then once that succeeds, then you'll be able to follow up with `-V max` to actually upgrade it?

**Comment by lastcmaster** [comment]
Run fix for two consecutive times and I get the feeling that nothing is fixed. 
```
sbin/reconstruct -GRU user/bcn
....
user.bcn uid 67530 mismatch: gmtime
user.bcn rewrote cache for 67530 (offset 0 to 93776620, crc 0 to 3049790577/3049790577)
user.bcn: updating sync_crc 1013467875 => 3854461596
user.bcn: updating sync_crc_annot 0 => 12345678
user/bcn

```
sbin/reconstruct -GRU user/bcn
....
user.bcn uid 67530 mismatch: gmtime
user.bcn rewrote cache for 67530 (offset 0 to 93777076, crc 0 to 3049790577/3049790577)
user.bcn uid 67532 mismatch: gmtime
user.bcn rewrote cache for 67532 (offset 0 to 93779592, crc 0 to 1797885393/1797885393)
user.bcn: updating sync_crc 3279990409 => 3232141973
user.bcn: updating sync_crc_annot 0 => 12345678
user/bcn

and new messages are entered with the same error. 

Even if no new messages are entered after the last reconstruct, I get

```
% sbin/reconstruct -V 16  user/bcn
user/bcn
FAILED TO REPACK user/bcn with new version Mailbox format corruption detected

From log after last GRU and the -V

```
Dec 14 14:06:29 mailboxes imaps[465]: Repacking mailbox user.bcn version 10
Dec 14 14:07:54 mailboxes imaps[465]: mailbox: longlock user.bcn for 85.4 seconds
Dec 14 14:09:10 mailboxes reconstruct[1942]: Repacking mailbox user.bcn version 16
Dec 14 14:10:35 mailboxes reconstruct[1942]: IOERROR: CRC mismatch on repack commit: user.bcn (3232141973 3669655955) (12345678 12345678)
Dec 14 14:10:35 mailboxes reconstruct[1942]: mappedfile: longlock /var/spool/imap/user/bcn/cyrus.annotations for 85.3 seconds
Dec 14 14:10:35 mailboxes reconstruct[1942]: mailbox: longlock user.bcn for 85.3 seconds

**Comment by elliefm** [comment]
That's strange, and I'm not sure what's going on.  What happens if you run each of the `-G`, `-R` and `-U` operations separately, rather than doing all three in the same pass?

I'm also wondering what happens if you upgrade the mailbox one step at a time?  I don't think version 11 or 14 really existed, so skip those.  But what happens if you `-V 12`?  And if that succeeds, what about `-V 13`, `-V 15`, `-V 16`?

**Comment by lastcmaster** [comment]
Commands run:
```
% sbin/reconstruct -R user/bcn
user.bcn: updating sync_crc 0 => 1794706821
user.bcn: updating sync_crc_annot 0 => 12345678
user/bcn
% sbin/reconstruct -G user/bcn
user.bcn uid 42689 mismatch: gmtime
user.bcn rewrote cache for 42689 (offset 0 to 46923580, crc 0 to 197269558/197269558)
user.bcn uid 42690 mismatch: gmtime
user.bcn rewrote cache for 42690 (offset 0 to 46925116, crc 0 to 1011146810/1011146810)
user.bcn uid 42691 mismatch: gmtime
user.bcn rewrote cache for 42691 (offset 0 to 46926900, crc 0 to 941059748/941059748)
.........
user.bcn uid 67548 mismatch: gmtime
user.bcn rewrote cache for 67548 (offset 0 to 93839744, crc 0 to 3269292988/3269292988)
user.bcn uid 67551 mismatch: gmtime
user.bcn rewrote cache for 67551 (offset 0 to 93842304, crc 0 to 1335824381/1335824381)
user.bcn uid 67553 mismatch: gmtime
user.bcn rewrote cache for 67553 (offset 0 to 93844696, crc 0 to 874193674/874193674)
user.bcn: updating sync_crc 866172455 => 1499050914
user.bcn: updating sync_crc_annot 0 => 12345678
user/bcn
% sbin/reconstruct -U user/bcn
user.bcn: updating sync_crc 0 => 1499050914
user.bcn: updating sync_crc_annot 0 => 12345678
user/bcn
% sbin/reconstruct -V 12 user/bcn
user/bcn
FAILED TO REPACK user/bcn with new version Mailbox format corruption detected
```
Full log attached.
[imapd-2020-12-16.log](https://github.com/cyrusimap/cyrus-imapd/files/5701044/imapd-2020-12-16.log)

So it just does not work whatever I try.

**Comment by lastcmaster** [comment]
Finally, I got it working by deleting all cyrus.* in the mailboxes that refused to upgrade and recreated the index with a reconstruct on the mailbox. Running reconstruct -V max on the recovered mailbox showed that we had version 16.
