### ISSUE TITLE
Jmap eventSourceUrl authentication error.

### ISSUE THREAD

**Issue by zvasilev** [cyrusimap/cyrus-imapd#3261]
Hello,

I've started implementing JMAP push notifications.
The Fastmail server return "https://jmap.fastmail.com/event/" for eventSourceUrl and that I guess need to use.
But always get HTTP error 401 when making a simple JMAP call.
{"methodCalls":[["PushSubscription/get",{"ids":null},"JBRdog==#6"]],"using":["urn:ietf:params:jmap:core"]}
The returned body has "Incorrect username or password." and a response header ("www-authenticate", "Basic realm=\"jmap.fastmail.com\"").
That basic auth works fine for the other three endpoints(API/upload/download).

Still not running my HTTP service, so could this be the reason for this error?
Or am I doing wrong something else?

Regards,
Zhivko

**Comment by ksmurchison** [comment]
Hi, Cyrus currently doesn't support JMAP push, and we shouldn't be advertising as such.

**Comment by zvasilev** [comment]
Understand, not enough time to set up everything correct :) 

Jmap is like a chicken and egg dilemma, so I'm going to release my JMAP support half-backed.
I really hoped this will work because it is impossible to compete with GMail and MS and this seems like a must-have feature for an email app.
In this case, the only positive is only fast resync of emails state (unread/flags), the rest is slower than IMAP.

Just a bit positive critique. Please update your Jmap endpoint with http2.
In the beginning, I missed the DNS query stuff with /well-known service search. So I tried with Bron's advice from FOSDEM to work with your private JMAP API initially. It is a lot faster than HTTP 1.1.
