### ISSUE TITLE
Sieve date tests cannot use variable in :zone

### ISSUE THREAD

**Issue by futzle** [cyrusimap/cyrus-imapd#3291]
[RFC 5260](https://tools.ietf.org/html/rfc5260) defines tests for `date` and `currentdate`. In these tests, a timezone can be specified:

```
currentdate [":zone" <time-zone: string>]
                        [COMPARATOR] [MATCH-TYPE]
                        <date-part: string>
                        <key-list: string-list>
```

[RFC 5229](https://tools.ietf.org/html/rfc5229) defines how variables are interpolated into strings.

I would like to use a variable as the time zone in a sieve script:
```
require ["date", "relational", "vacation", "variables"];
set "zone" "+1000";
set "start" "2020-11-17T17:00:00";
set "end" "2020-11-24T09:00:00";

if allof(currentdate :zone "${zone}" :value "ge" "iso8601" "${start}${zone}",
  currentdate "${zone}" :value "le" "iso8601" "${end}${zone}")
{ vacation :days 7  "I'm away this week."; }
```

But in Cyrus 3.2 this produces an error: `invalid time-zone ${zone}`.

It looks like the sieve code parses time zones in files at the lexer stage: https://github.com/cyrusimap/cyrus-imapd/blob/da002705f3f30e4f929fff73aaa6af6272e0f161/sieve/sieve-lex.l#L319 which is why it rejects the use of a variable.

I have workarounds, this issue is just here to track what seems to me to be a small nonconformance with the RFC.

**Comment by ksmurchison** [comment]
Yes, this is in fact a bug.  I assume the same can be said for the date-part string.  DO you also have a use case for using a variable for date-part?

**Comment by futzle** [comment]
I don’t have a use case for using a variable in date-part. It’ll always be a string literal for me.

**Comment by ksmurchison** [comment]
Do you have any thoughts on what should happen if the variable specifying :zone is invalid?  Should the test fail?  Should we ignore it and fall back to the local time zone?

**Comment by futzle** [comment]
I’m a big fan of failing hard rather than silently doing something unexpected. The RFC uses MUST:

`The value of time-zone MUST be an offset relative to UTC`

so my feeling is that a badly-formed offset is an error.
