### ISSUE TITLE
cyrus3.0.7 no uniqueid after distant mailbox creation, reconstruct -G is needed

### ISSUE THREAD

**Issue by Isma399** [cyrusimap/cyrus-imapd#3299]
Hello,

I've migrated 8000 mailboxes last month from cyrus2.4 to cyrus3.0.7 (murder setup).
Some users complains to never receive mail from newsletter.
In cyrus logs, I see : 

` dupelim: eliminated duplicate message `
meaning some mailbox have same uid while they are different ones.
So, I want to check in mailboxes.db : 

> cyr_dbtool /var/lib/imap/mailboxes.db twoskip show | grep maupassant
> user.maupassant  %(A %(maupssant lrswipkxtecda cyrus lrswipkxtecda) P splitmeta M 1606310793)

But there's no "I" record in mailboxes.db (the mailbox uid), is it normal?

Running reconstruct -G on this mailbox fix the problem

The only mailboxes that have already "I" record in mailboxes.db is mailboxes have been created in cyrshell : 
`cyradm -u cyrus .." cm user.xxx `

My problem is taht I have created almost all of this mailboxes with a distant Python script, using cyruslib wrapper : 
`imap = cyruslib.CYRUS("imap://backend:143")`
`imap.login("cyrus", "password")`
`imap.cm('user.maupassant')`

cyruslib is a wrapper around Python imaplib, so it's IMAP command CREATE.
https://docs.python.org/3/library/imaplib.html

Is the expected behavior with a distant creation of a mailbox?
For now, running -G is currently running on all mailboxes that don't have a "I" records :

> for uid in $( cyr_dbtool /var/lib/imap/mailboxes.db twoskip show  | egrep '^user\.[0-9]*[-]*[a-z]+\s' | egrep -v '^user\.[0-9]*[-]*[a-z]+\s+.*lrswipkxtecda) I '  | awk '{print $1}'); do reconstruct -G $uid; done

Do I have to have duplicate records after that?
If that is the case, what is the best way to make unique mailboxes ID ?

**Comment by elliefm** [comment]
It sounds like your mailboxes are missing GUID information, which I would expect if you upgraded from an older version that didn't store GUIDs.  `reconstruct -G` is the correct way to recalculate those.

You might also need to `reconstruct -V max`, because very old mailboxes won't even have the header fields to store GUIDs in.

The upgrade notes have a relevant warning that affects 3.0.7, which is fixed by upgrading to 3.0.11.  I assume you're using 3.0.7 because it's what your distribution provides, in which case I suggest checking with the package maintainer whether the fixes from 3.0.11 have been backported.
https://www.cyrusimap.org/3.0/imap/download/upgrade.html#reconstruct-databases-and-cache

**Comment by Isma399** [comment]
Thank you Ellie.
I belived the way I use to migrate will avoid me `reconstruct -V max`, because I create all mailbox on the new cluster and then move data with imapsync.
https://imapsync.lamiral.info/
I will check for an upgrade.

**Comment by Isma399** [comment]
Hello,
I've running this weekend `recontruct -G user.xxx` on all mailboxes missing GUID information.
But there 's still some users complaining about missing mail (due to _dupelim_).

With that script, I can list mailbox with a duplicated GUID : 

> #!/usr/bin/python3
>import subprocess
>import re

>args = ['cyr_dbtool', '/var/lib/imap/mailboxes.db', 'twoskip', 'show']
>p = subprocess.run(args, stdout=subprocess.PIPE)
>with open('/tmp/mailboxes_flat', 'wb') as f:
>        f.write(p.stdout)

>with open('/tmp/mailboxes_flat', 'r') as f:
>    lines = f.readlines()

>result = [line for line in lines if 'DELETED' not in line]

>d = {}
>prog = re.compile('(user.*)\s*%\(A\s+%.+\sI\s([\S]+).+')
>for line in result:
>   res = prog.match(line)
>    if res:
>        mailbox, uid = res.group(1).strip(), res.group(2)
 >       try:
>            d[uid].append (mailbox)
>        except KeyError:
>            d[uid] = []
>            d[uid].append (mailbox)

>e = {}
>for k, v in d.items():
>    if len(v) > 1:
>        v.pop(0)
>        try:
>           e[k.strip()].append(v)
>        except KeyError:
 >           e[k.strip()] = []
 >           e[k.strip()].append(v)

>for k, v in e.items():
>       print(v[0][0])


For instance, this mailboxes have the same GUID : 
`$ cyr_dbtool /var/lib/imap/mailboxes.db twoskip show |grep 2uaialuyxldjz084ehrwhjdl`
`user.maupassant %(A %(maupassant lrswipkxtecda cyrus lrswipkxtecda) I 2uaialuyxldjz084ehrwhjdl P splitmeta V 1603560340 F 3 M 1607349525)`
`user.mauras     %(A %(mauras lrswipkxtecda cyrus lrswipkxtecda) I 2uaialuyxldjz084ehrwhjdl P splitmeta V 1603560340 F 11111 M 1607349441)
`

`mbtool -r` seems to renew GUID following with `reconstruct -G` : 
>$ mbtool -r user.mauras
>Working on user.mauras...
>$ reconstruct -G user.mauras
>user.mauras: update uniqueid from header 2uaialuyxldjz084ehrwhjdl => trvhxxrtp8ieuzxh1jd5pepk
>user.mauras

But the new GUID is not recorded in mailboxes.db : 
>$ cyr_dbtool /var/lib/imap/mailboxes.db twoskip show |grep trvhxxrtp8ieuzxh1jd5pepk
>$
>$ cyr_dbtool /var/lib/imap/mailboxes.db twoskip show |grep 2uaialuyxldjz084ehrwhjdl
>user.maupassant %(A %(maupassant lrswipkxtecda cyrus lrswipkxtecda) I 2uaialuyxldjz084ehrwhjdl P splitmeta V 1603560340 F 3 M 1607349525)
>user.mauras     %(A %(mauras lrswipkxtecda cyrus lrswipkxtecda) I 2uaialuyxldjz084ehrwhjdl P splitmeta V 1603560340 F 11111 M 1607349970)

Log says : 
> Dec  7 15:15:24 store-8-backend-pro cyrus/mbtool[21328]: cannot connect to mupdate server for update of 'user.mauras'

But `mupdatetest` ends succesfully.
I've tried on several mailboxes.
Somtimes it's OK, sometimes not.

I'm quite confused about the way to get rid off this duplicated GUIDs

**Comment by Isma399** [comment]
OK, I have actually to run `mbtool -r user.xxx user.yyy user.zzz` and then `reconstruct -G user.xxx user.yyy user.zzz `
