### ISSUE TITLE
export number of non-idle processes from master

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#337]
From: [Larry Greenfield](leg+cyrus@andrew.cmu.edu)
Bugzilla-Id: 1182
Version: 2.1.x
Owner: [Ken Murchison](murch@andrew.cmu.edu)

**Comment by ksmurchison** [comment]
Probably no longer an issue.  Won't fix

**Comment by elliefm** [comment]
Can confirm we do have an active IMAP connections stat in SNMP these days, cause I wrote a prometheus port of it the other week :)
