### ISSUE TITLE
confidential security contact?

### ISSUE THREAD

**Issue by lambdafu** [cyrusimap/cyrus-imapd#3370]
Hi,
is there a contact for Cyrus that can receive and handle security-related reports confidentially?

Thanks,
Marcus

**Comment by rsto** [comment]
@lambdafu hi Marcus, in case you haven't contacted one from the Fastmail team already, please contact rsto@fastmailteam.com (that's me) and murch@fastmailteam.com . Thanks, Robert

**Comment by lambdafu** [comment]
Thanks!
