### ISSUE TITLE
Invisible subfolders for admins after upgrade from 2.5 to 3.0

### ISSUE THREAD

**Issue by guimard** [cyrusimap/cyrus-imapd#3376]
Hi,

is there a fix for this issue ? Is it fixed in 3.2.x versions ?

From [Debian #924482](https://bugs.debian.org/924482):
> Dear Maintainer,
> 
>   * What led up to the situation?
>        - Package upgrade from 2.5.11 to 3.0.8.
> 
>   * What exactly did you do (or not do) that was effective (or ineffective)?
>        - Just regular apt upgrade
> 
>   * What was the outcome of this action?
>        - One of my users, who is configured as admin in imapd.conf, lost visibility of all his subfolders after the upgrade. Inbox works normally though. This is not a client issue, the subfolders are not visible in ThunderbirdAndroid Gmail client, Alpine and cyradm. Reconstructing does not fix the issue. After removing this user from the admins config option, all subfolders reappear in all clients.
> 
>   * What outcome did you expect instead?
>        - Having a working mailbox including subfolders for all my users, admin or not.

**Comment by dilyanpalauzov** [comment]
The documentation in [imapd.conf](https://www.cyrusimap.org/imap/reference/manpages/configs/imapd.conf.html) for `admins:` says it:
> Note that accounts used by users should not be administrators. Administrative accounts should not receive mail. That is, if user "jbRo" is a user reading mail, he should not also be in the admins line. Some problems may occur otherwise, most notably the ability of administrators to create top-level mailboxes visible to users, but not writable by users.

The text is present there since at leas 2003.

**Comment by guimard** [comment]
Thanks, closing here and in Debian Tracking System
