### ISSUE TITLE
undefined reference if using flock method in 3.2.6 (release)

### ISSUE THREAD

**Issue by rudgab** [cyrusimap/cyrus-imapd#3435]
I'm gettiing a 

imap/.libs/libcyrus_imap.so: undefined reference to `debug_locks_longer_than'
collect2: error: ld returned 1 exit status
make[2]: *** [Makefile:4152: imap/lmtpd] Error 1
imap/.libs/libcyrus_imap.so: undefined reference to `debug_locks_longer_than'

if configure --with-lock=flock 

This locking worked for 3.0.13 (at least) 

Note: debug_locks_longer_than is defined only in lock_fcntl.c and of course it compiles with this locking mechanism.

Regards, Rudi G.

**Comment by dilyanpalauzov** [comment]
This is addressed at https://github.com/cyrusimap/cyrus-imapd/pull/3769.
