### ISSUE TITLE
make dynamic arrays grow harder

### ISSUE THREAD

**Issue by elliefm** [cyrusimap/cyrus-imapd#3439]
Our dynamic array types all* grow by only 16 bytes at a time for some reason:

```
$ack QUANTUM
lib/arrayu64.c
76:#define QUANTUM     16
81:    newalloc = ((newalloc + QUANTUM-1) / QUANTUM) * QUANTUM;

lib/bitvector.c
63:#define QUANTUM         (256)
79:        unsigned int newalloc = ((len + QUANTUM-1) / QUANTUM) * QUANTUM;

lib/bufarray.c
86:#define QUANTUM     16
91:    newalloc = ((newalloc + QUANTUM) / QUANTUM) * QUANTUM;

lib/ptrarray.c
81:#define QUANTUM     16
88:    newalloc = ((newalloc + QUANTUM-1) / QUANTUM) * QUANTUM;

lib/dynarray.c
86:#define QUANTUM     16
94:    newalloc = ((newalloc + QUANTUM-1) / QUANTUM) * QUANTUM;

lib/strarray.c
85:#define QUANTUM     16
90:    newalloc = ((newalloc + QUANTUM) / QUANTUM) * QUANTUM;
```

This results in noticeable memcpy overhead from repeated resizing in hot loops.  It's much more normal to have dynamic arrays grow by a factor of 1.5-2 each time they need to grow, to reduce the amount of times they need to grow.

**Comment by elliefm** [comment]
Most of these modules have thorough unit tests, but there's a few with none at all, so I'll probably flesh those out first...

**Comment by elliefm** [comment]
wip here: https://github.com/cyrusimap/cyrus-imapd/compare/master...elliefm:v35/dynarray-resize

**Comment by hdatma** [comment]
"grow harder"?

**Comment by elliefm** [comment]
faster, more aggressively,

**Comment by elliefm** [comment]
I'm a little bit tempted to leave bitvector alone, since it works with bits rather than objects
