### ISSUE TITLE
Docs: Make sure port information is documented for essential services

### ISSUE THREAD

**Issue by nicolan** [cyrusimap/cyrus-imapd#36]
From a recent thread on the mailing lists:

```
SERVICES {
imaplocal     cmd="imapd -C /etc/imapd-local.conf"  
listen="127.0.0.1:imap" prefork=0
  imaps         cmd="imapd -s" listen="imaps" prefork=1
imapslocal    cmd="imapd -C /etc/imapd-local.conf"  
listen="127.0.0.1:imaps" prefork=0
  sieve         cmd="timsieved" listen="sieve" prefork=0
```

> You did not define an ip address here, so sieve will use 0.0.0.0:sieve

Need to:
-  Amend install guides
-  Amend cyrus.conf man page
-  Amend timsieved/imapd/imaps/ (others?) man page

**Comment by postilion** [comment]
This is addressed in https://github.com/cyrusimap/cyrus-imapd/pull/1789/commits

**Comment by elliefm** [comment]
#1789 has been merged :)
