### ISSUE TITLE
"unknown type of DB: SYNC_CACHE" on upgrade-db

### ISSUE THREAD

**Issue by guimard** [cyrusimap/cyrus-imapd#3659]
From [Debian #994025](https://bugs.debian.org/994025):

> I'm getting this error after upgrading to 3.4.2-1
```
  $ sudo dpkg --configure --pending
  Setting up cyrus-common (3.4.2-1) ...
  Creating/updating cyrus user account...
  The user `cyrus' is already a member of `sasl'.
  /usr/lib/cyrus/bin/upgrade-db: Unknown type of DB: SYNC_CACHE
  dpkg: error processing package cyrus-common (--configure):
   installed cyrus-common package post-installation script subprocess returned error exit status 1
```
> It looks like "SYNC_CACHE" is missing from the case statement in the `upgradealldb()` function in `/usr/lib/cyrus/bin/upgrade-db` which is causing the error I'm seeing. They are listed in `/usr/lib/cyrus/cyrus-db-types.{txt,active}`:
```
  $ grep SYNC_CACHE /usr/lib/cyrus/cyrus-db-types.txt /usr/lib/cyrus/cyrus-db-types.active
  /usr/lib/cyrus/cyrus-db-types.txt:SYNC_CACHE twoskip
  /usr/lib/cyrus/cyrus-db-types.active:SYNC_CACHE twoskip
```

**Comment by elliefm** [comment]
What is `/usr/lib/cyrus/bin/upgrade-db`?  I don't see a file named like that in our sources or documentation, is it a Debian thing?

**Comment by guimard** [comment]
Hi @elliefm, sorry it's a Debian script _([cyrus-upgrade-db](https://salsa.debian.org/debian/cyrus-imapd/-/blob/master/debian/cyrus-upgrade-db))_, wrapper around `cvt_cyrusdb`. I just [added SYNC_CACHE](https://salsa.debian.org/debian/cyrus-imapd/-/commit/485b7959) in known types list _()_
