### ISSUE TITLE
bad acl should get no or be completely ignored

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#368]
From: [Walter Wong](wcw+bugz@cmu.edu)
Bugzilla-Id: 1203
Version: 2.1.x
Owner: [Ken Murchison](murch@andrew.cmu.edu)

**Comment by aaujon** [comment]
RFC4314 states : 

> Note that an unrecognized right MUST cause the command to return the BAD response.  In particular, the server MUST NOT silently ignore unrecognized rights.

**Comment by elliefm** [comment]
Confirmed this still exists(!)

**Comment by elliefm** [comment]
`cyrus_acl_strtomask()` is responsible for turning the rights strings into a bitfield.  It just returns a bitfield assembled from the (recognised) rights in the string.  If the string contains unrecognised rights, those are ignored, and if the string contains _only_ unrecognised rights (e.g. "b"), the bitfield will end up zero, as Walter observes.

"No rights" seems like a useful value to be able to set, so it's not a suitable error indicator.

The obvious alternative, "return -1 on error" will result in all bits set -- which will need careful checking downstream to ensure that a bad rights string doesn't give _more_ rights.

Another possibility is setting a single bit in the mask to indicate that it was bad.  It makes the "check for error return" case marginally more complicated, but won't result in untoward changes in the case where this check is missed.

**Comment by brong** [comment]
Alternative is to make this return r and pass the mask by reference,
like many other functions that can return errors.




On Fri, 27 Jan 2017, at 10:52, elliefm wrote:

> cyrus_acl_strtomask() is responsible for turning the rights strings
> into a bitfield.  It just returns a bitfield assembled from the
> (recognised) rights in the string.  If the string contains
> unrecognised rights, those are ignored, and if the string contains
> *only* unrecognised rights (e.g. "b"), the bitfield will end up zero,
> as Walter observes.
> "No rights" seems like a useful value to be able to set, so it's not a
> suitable error indicator.
> The obvious alternative, "return -1 on error" will result in all bits
> set -- which will need careful checking downstream to ensure that a
> bad rights string doesn't give *more* rights.
> Another possibility is setting a single bit in the mask to indicate
> that it was bad.  It makes the "check for error return" case
> marginally more complicated, but won't result in untoward changes in
> the case where this check is missed.
> — You are receiving this because you authored the thread. Reply to
> this email directly, view it on GitHub[1], or mute the thread[2].
> 



--

  Bron Gondwana

  brong@fastmail.fm




Links:

  1. https://github.com/cyrusimap/cyrus-imapd/issues/368#issuecomment-275551050

**Comment by elliefm** [comment]
Yeah I like that way better, will do it that way

I don't think we have a suitable error code for this yet, will have another look then add one if necessary

**Comment by elliefm** [comment]
Cassandane test here: https://github.com/cyrusimap/cassandane/commit/680ac0f0e965ae6d35c2e9d21f66a363b9a43fb4

**Comment by elliefm** [comment]
Probably should backport this to 2.5 too
