### ISSUE TITLE
reservefile: log errno when file ops fail

### ISSUE THREAD

**Issue by robn** [cyrusimap/cyrus-imapd#3784]
I ran into a sync problem, which turned out to be a filesystem issue, such that the `fopen` call in `reservefile` (`dlist.c`) failed. `errno` was `ENOSPC`, and it would have helped me a lot if that had been logged!

**Comment by elliefm** [comment]
Ah, looks like this is one of the files where I haven't yet gotten around to converting our IOERRORs to use xsyslog (which, among other things, would log errno automatically if it's nonzero) instead of syslog.
