### ISSUE TITLE
Sieve vacation does not support UTF-8 in :subject

### ISSUE THREAD

**Issue by alecpl** [cyrusimap/cyrus-imapd#38]
As mentioned in https://tools.ietf.org/html/rfc5230#section-4.3 in "subject" UTF-8 characters are allowed. The implementation must encode subject strings according to https://tools.ietf.org/html/rfc2047.

So, if you do:

```
if address :matches "from" "*@example.com"
{
     vacation :subject "ä,ö,ü"
            "Having lots of fun! Back in a day or two!";
}
```

Subject of the reply will be malformed.
Tested with cyrus 2.5.8.

**Comment by elliefm** [comment]
Fixed in 0338a62
