### ISSUE TITLE
Add an ENABLE command for sync_client to turn on "spool to archive partition"

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#3830]
When syncing up a new server, you can easily blow out the non-archive space when copying in a big user, before cyr_expire can move all the records.  With this flag, we could force messages to write to the correct place without needing "this came from archive" magic in the wire protocol.

**Comment by elliefm** [comment]
Hmm... might be able to also hit #3785 with the same stone?

**Comment by Davis-A** [comment]
Bump!  This would be really nice to have for us ... ahh soon,
