### ISSUE TITLE
rename user loses sieve bytecode when mailbox_legacy_dirs = yes

### ISSUE THREAD

**Issue by elliefm** [cyrusimap/cyrus-imapd#3835]
To reproduce:

* add `mailbox_legacy_dirs = yes` to the `[config]` section of cassandane.ini
* run the `Rename.rename_user_sieve` test

The test will fail like this:

```
1) Rename.rename_user_sieve
 /dev/shm/cass/0230330101/conf/sieve/n/newuser/test1.bc: file not found at /usr/share/perl5/Test/Unit/Exception.pm line 13.
	Test::Unit::Exception::throw_new(Test::Unit::Failure=HASH(0x55deaab1f7f0), "-package", "Cassandane::Cyrus::TestCase", "-file", "Cassandane/Cyrus/TestCase.pm", "-line", 1389, "-object", ...) called at /usr/share/perl5/Test/Unit/Assert.pm line 85
	Test::Unit::Assert::do_assertion(Cassandane::Cyrus::Rename=HASH(0x55deaaab5078), Test::Unit::Assertion::Boolean=SCALAR(0x55deaab04130), "Cassandane::Cyrus::TestCase", "Cassandane/Cyrus/TestCase.pm", 1389, "/dev/shm/cass/0230330101/conf/sieve/n/newuser/test1.bc: file "...) called at /usr/share/perl5/Test/Unit/Assert.pm line 19
	Test::Unit::Assert::assert(Cassandane::Cyrus::Rename=HASH(0x55deaaab5078), undef, "/dev/shm/cass/0230330101/conf/sieve/n/newuser/test1.bc: file "...) called at Cassandane/Cyrus/TestCase.pm line 1389
	Cassandane::Cyrus::TestCase::assert_sieve_exists(Cassandane::Cyrus::Rename=HASH(0x55deaaab5078), Cassandane::Instance=HASH(0x55deaaac3450), "newuser", "test1", 1) called at Cassandane/Cyrus/Rename.pm line 658
	Cassandane::Cyrus::Rename::test_rename_user_sieve(Cassandane::Cyrus::Rename=HASH(0x55deaaab5078)) called at /usr/share/perl5/Test/Unit/TestCase.pm line 75
	[...framework calls elided...]
```

which is coming from here:
https://github.com/cyrusimap/cyrus-imapd/blob/522d3786d94cd61af5209a5b5d4c13c7acf63d0d/cassandane/Cassandane/Cyrus/Rename.pm#L658

The `rename` command has succeeded:

```
C: 4 rename user.cassandane user.newuser
S: * OK rename user.cassandane user.newuser
S: * OK rename user.cassandane.#sieve user.newuser.#sieve
S: 4 OK Completed
```

And we expect that there is no longer a "test1.bc" for the cassandane user, and there now is one for the newuser user.  The test fails because the "newuser" user doesn't have a test1.bc file.

Looking on disk, we see:

```
cyrus@debian:/dev/shm/cass/0230330101$ find data/
data/
data/stage.
data/user
data/user/newuser
data/user/newuser/#sieve
data/user/newuser/#sieve/cyrus.header
data/user/newuser/#sieve/1.
data/user/newuser/#sieve/cyrus.cache
data/user/newuser/#sieve/cyrus.annotations
data/user/newuser/#sieve/cyrus.index
data/user/newuser/cyrus.header
data/user/newuser/cyrus.annotations
data/user/newuser/cyrus.index

cyrus@debian:/dev/shm/cass/0230330101$ find conf/sieve/
conf/sieve/
conf/sieve/c
conf/sieve/c/cassandane
conf/sieve/c/cassandane/test1.bc
conf/sieve/c/cassandane/defaultbc
```

So it looks like the script file has come across ok (message 1 in the #sieve mailbox).  The bytecode file still exists for the cassandane user, and does not exist for the newuser user, but we expect the opposite at this point.

The test wants to check replication too, but it doesn't get that far because it's already failing here.

I guess it's fine for UUID mailboxes because nothing actually changes on disk, but for legacy mailboxes the compiled sieve needs to be moved around (or at least: the old files removed, and the scripts recompiled as newuser) and it's not happening

It might want to go in here somewhere, where we handle quota and ACL:

https://github.com/cyrusimap/cyrus-imapd/blob/522d3786d94cd61af5209a5b5d4c13c7acf63d0d/imap/imapd.c#L7511-L7516

I see that there is a `user_renamesieve()` in user.c but it's inside an `#if 0` section.

**Comment by ksmurchison** [comment]
Should be fixed by #3837
