### ISSUE TITLE
MOVE does not fail when source mailbox is readonly

### ISSUE THREAD

**Issue by alecpl** [cyrusimap/cyrus-imapd#39]
Consider User1 on backend1 and User2 on backend2. Now, User2 will try to move a message from User1's mailbox, which is readonly (according to ACL it is 'lrs') for him, to his own mailbox.
```
C: A0005 UID MOVE 1 Trash
S: A0005 OK [COPYUID 1474531118 1] Completed
```
Expected is:
```
C: A0005 UID MOVE 1 Trash
S: A0005 NO Permission denied
```
Note also, invalid COPYUID response format above.
Cyrus 2.5.8 with murder setup.

**Comment by elliefm** [comment]
I also think this is the same thing as #51 (as you observed), I wonder if issues can be merged...

**Comment by elliefm** [comment]
... nope :(

Closing this one, because the more detailed commentary is already in the other
