### ISSUE TITLE
Sieve enotify (RFC 5435) implementation bugs

### ISSUE THREAD

**Issue by MartySvec** [cyrusimap/cyrus-imapd#3917]
Hello,

I think there're several bugs in sieve "enotify" extension implementation which cause this feature to be **completely broken**. Consider these two rules, one using old "notify" draft and the second one new "enotify" extension:

`if allof (header :contains "subject" "notifytest")
{
        notify :method "mailto" :options ["recipient@somedomain.com"] :message "Notification body";
}`

`if allof (header :contains "subject" "notifytest")
{
        notify :importance "2" :from "notifysender@somedomain.com" :message "Notification body" "mailto:recipient@somedomain.com";
}`

According to `strace`, notification requests based on these rules are submitted to `notifyd` process as follows:

`recvfrom(0, "mailto\0SIEVE\0normal\0mailboxid@somedomain.com\0\0001\0recipient@somedomain.com\0Notification body\0/var/spool/imap44/stage./4400-1644860274-0\0"...`

`recvfrom(0, "mailto:recipient@somedomain.com\0SIEVE\0normal\0mailboxid@somedomain.com\0\0000\0Notification body\0/var/spool/imap44/stage./20883-1644913849-0\0" ...`

Clearly, the second request sends "method" in the form of `method:address` which is not a valid method recognized by `notifyd` and no notification email is sent. Also, the `:from` address seems to be ignored at all.

I looked into the history and guess that these bugs date back to commit [adb4819b3e8c4e51be40741fc523f26bf3e6f095](https://github.com/cyrusimap/cyrus-imapd/commit/adb4819b3e8c4e51be40741fc523f26bf3e6f095):

1. This commit ignores the fact that enotify method string contains recipient email address and saves it to `c->u.n.method` without stripping `:recipient@somedomain.com`.
2. Notifyd code expects recipient address in `options[0]` but `build_notify()` does not handle it in `B_ENOTIFY` branch.
3. Notifyd code doesn't support `:from` address at all. This address is probably ignored somewhere in the call chain before notifyd daemon is called.

IMO sieve "enotify" support should either correctly populate data structures as expected by the old "notify" draft implementation, or the whole notify callchain including notifyd daemon should be rewritten according to the new "enotify" extension standard.

I noticed these issues in 3.4.3 code but master branch seems to be affected to.

Best regards,
Martin

**Comment by MartySvec** [comment]
Nobody cares?

**Comment by elliefm** [comment]
This should be fixed on master now.  I intend to backport the fix to some of the older branches, so I'm reopening until I have done so.

**Comment by elliefm** [comment]
The fix for this has been backported to 3.4 and 3.2, and will be included in future releases from these series.

**Comment by wtip** [comment]
Can someone confirm that the `:from` address should not be ignored with this fix?
