### ISSUE TITLE
cyrusimap-3.4.2 sieve delivery to inbox as well as fileinto subfolder

### ISSUE THREAD

**Issue by dekeonus** [cyrusimap/cyrus-imapd#3941]
During delivery / sieve processing lmtpunix is delivering to INBOX _as well as_ folder set by fileinto

```
Mar  1 07:38:18 MAILHOST cyrus_imap/lmtpunix[23570]: Delivered: <E1nOmk0-0007qO-U7@smtp-06-tuk1.steampowered.com> to mailbox: user.MYUSER
Mar  1 07:38:18 MAILHOST cyrus_imap/lmtpunix[23570]: Delivered: <E1nOmk0-0007qO-U7@smtp-06-tuk1.steampowered.com> to mailbox: user.MYUSER.email-accts.gmail
Mar  1 07:38:18 MAILHOST cyrus_imap/lmtpunix[23570]: USAGE MYUSER user: 0.497246 sys: 2.105787
```

This is definitely the same messsage, as when I then log into the imap server using my mail client and move the erroneous message from INBOX to email-accts.gmal I get the following

`Mar  1 07:39:07 MAILHOST cyrus_imap/imap[23586]: user.MYUSER.email-accts.gmail: same message appears twice 4898 4899`

Note: it **Always** delivers to INBOX first then the subfolder second (or at the very least, that's always the logged order)
I'm not sure how to get more verbose logging for the sieve filter processing and final delivery action choice.

The active/default sieve script for user:
```
# Sieve Filter: default

##only 'include' as this should just pull in other scripts
require ["include"];

## include fails silently if script does not exist
# Global Amavis filters
include :global "amavisd";

# Webmail generated rules
include :personal "webmail";
```
The global script included above
```
# Sieve Filter: amavisd

require ["fileinto", "regex"];

## only enabled (in amavisd) for select(special) accounts
# File virii into folder Virii
if header :comparator "i;ascii-casemap" :matches "X-Amavis-Alert" "INFECTED*"  {
    fileinto "INBOX/Virii";
    stop;
}

# File spam into folder Junk
if header :comparator "i;ascii-casemap" :matches "X-Spam-Status" "YES*"  {
    fileinto "INBOX/Junk";
    stop;
}
```
The included personal (actual) filter script
```
# Sieve Filter: Personal Rules
# Generated by Ingo (http://www.horde.org/ingo/)
# hand edited by MYUSER

require ["fileinto", "regex"];

# <.. snip ..> # mail sorting into folders, all rules end with a fileinto "INBOX/foo"; stop; (as seen below)

## fall through fetchmail sorting

# <.. snip ..> #other fetchmail accounts (same format as the following)

# fetched-gmail
if header :comparator "i;ascii-casemap" :regex "Received" ".*fetchmail.*polling gmail account MYGMAILUSER"  {
    fileinto "INBOX/email-accts/gmail";
    stop;
}

# <.. snip ..> #other fetchmail accounts
```
config vars: (which might be relavent)
```
altnamespace: no
conversations: yes
duplicatesuppression: yes
improved_mboxlist_sort: yes
lmtp_catchall_mailbox:
search_engine: squat
sieve_utf8fileinto: yes
sievedir: /home/.imap/sieve
anysievefolder: yes
singleinstancestore: no
syslog_prefix: cyrus_imap
virtdomains: off
```

OS: Gentoo
Gentoo Arch: x86
CHOST: i686-pc-linux-gnu

software Versions:
cyrus-imapd-3.4.2
gcc-11.2.0
cyrus-sasl-2.1.27
libpcre-8.45

cyrus configured with
./configure --prefix=/usr --build=i686-pc-linux-gnu --host=i686-pc-linux-gnu --mandir=/usr/share/man \
--infodir=/usr/share/info --datadir=/usr/share --sysconfdir=/etc --localstatedir=/var/lib \
--disable-dependency-tracking --disable-silent-rules --docdir=/usr/share/doc/cyrus-imapd-3.4.2-r1 \
--htmldir=/usr/share/doc/cyrus-imapd-3.4.2-r1/html --with-sysroot=/ --libdir=/usr/lib --enable-murder \
--enable-idled --enable-autocreate --enable-pcre --with-com_err --with-cyrus-user=cyrus --with-sasl \
--with-sphinx-build=no --without-krb --without-krbdes --enable-squat --with-zlib --disable-afs \
--disable-krb5afspts --disable-backup --enable-calalarmd --with-libcap --with-clamav --disable-nntp \
--enable-http --with-nghttp2 --disable-replication --enable-gssapi --with-ldap --with-mysql \
--without-pgsql --with-perl --with-sqlite --with-openssl --enable-server --enable-sieve \
--disable-static --without-libwrap --disable-xapian --disable-unit-tests

CFLAGS: -O2 -march=prescott -msse2 -mfpmath=sse -pipe -g -fno-toplevel-reorder

OF NOTE, the issues discussed in #3562 and #3588 were occurring here:
thunderbird / roundcube had no trouble accessing the messages
k9mail could not see any messages in any folder
gnubiff would cause imapd to segfault.

the disable optimisation flag _-fno-toplevel-reorder_ suggested by @Devstellar in https://github.com/cyrusimap/cyrus-imapd/issues/3562#issuecomment-891349401_ did allow k9mail and gnubiff to operate successfully.
I do wonder if this optimisation issue is causing effects in lmtp delivery / sieve processing.

**Comment by slangenhorst** [comment]
Same problem here. Problem seems to be the Include 

Looks like each sievescript ist run indepently.
If Script A puts the mail in Folder A and Script B does nothing you end up with duplicate deliverys...

**Comment by slangenhorst** [comment]
Took another look at it and i think i found it.

bc_eval.c:1648 sieve_eval_bc keeps a local implicit_keep
in bc_eval.c:2482 an implicit triggers do_keep if the sieve script didn't match anything

If you use an include-statement bc_eval.c:2253 calls sieve_eval_bc recursively. 
So each script where no rules match results in a implicit instant do_keep, even when the complete run isn't even over yet. 
do_keep results in a fileinto("") at message.c:303. There is also mentioned, that copies are OK..

This way either each script has to have an action, or it generates a delivery. It's no problem if no script matches, as the duplicate get noticed and suppressed.

As i see this should do the trick:
bc_eval.c:2479
-    if (!res && implicit_keep) {
+    if (!res && implicit_keep && !is_incl) {

This ensures, that a include (is_incl set) won't do an implicit_keep, but the main-script does.
In my tests this results in exacty the behaviour i want to have an i had in cyrus 3.2


[0099-sieve.patch.txt](https://github.com/cyrusimap/cyrus-imapd/files/8314326/0099-sieve.patch.txt)
