### ISSUE TITLE
The comment "used for internationalization" is aspirational?

### ISSUE THREAD

**Issue by HenkPoley** [cyrusimap/cyrus-imapd#3997]
In particular I was looking for the message templates of the quotawarn/quotawarnmsg, which ended me up at IMAP_NO_CLOSEQUOTA ("Mailbox is at %d%% of quota").

Which has a nearby comment: https://github.com/cyrusimap/cyrus-imapd/blob/cyrus-imapd-2.4.17/imap/imap_err.et#L192

> \# Following used for internationalization of untagged OK/NO responses

But I can't seem to find any kind of _translations of these strings_. _Does it exist?_ (In particular a custom / translated quota warning)

---
The function error_message() itself doesn't appear to do external (translated, language setting based) lookups. But doesn't mean these are not loaded somewhere else: https://github.com/cyrusimap/cyrus-imapd/blob/cyrus-imapd-2.4.17/com_err/et/error_message.c#L67

**Comment by elliefm** [comment]
No, we don't provide translations for these messages.

If you wanted error messages in non-English (or just wanted to change the English text of them for some reason), the .et files are the correct files to update -- as opposed to having to hunt around for strings in all the C sources.  I think this is what that comment was trying to communicate.

There is no mechanism that switches error messages dynamically for the language of the person receiving them.

**Comment by HenkPoley** [comment]
Thanks. I would just need one changed message/one language. Changes to the .et files then need a recompile of the executable, isn't it?

**Comment by elliefm** [comment]
Yes, you will need to recompile after changing them.  You should expect pretty much all of Cyrus IMAP to need to be recompiled -- these files are processed very early cause nearly everything else depends on them, or depends on something that does.

**Comment by HenkPoley** [comment]
Thanks, it seemed like the right place add in a custom 'inbox full' message. But having to keep making custom packages is a bit out of the question for us a the moment. And we're using one of those very stable distros, so even if I would add the feature in the code, and it got merged, it would be few years until that trickled down 😅
