### ISSUE TITLE
CardDAV issue - 403 Forbidden

### ISSUE THREAD

**Issue by spatnynick** [cyrusimap/cyrus-imapd#4]
Dear Cyrus team,
I have a Cyrus instance working, an account created, accessing CardDav via KDE's KAddressBook (I am using this app successfully also with Baïkal's CardDav) and I face following issue:

- when I try to create a new contact manually, one by one, contacts are created
https[11907]: nas [192.168.xxx.xxx] as "bogo" with "Mozilla/5.0 (X11; Linux x86_64) KHTML/4.14.20 (like Gecko) Konqueror/4.14"; "PUT /dav/addressbooks/user/bogo/Default/1467532147.R131.vcf HTTP/1.1" => "201 Created"

- when I try to do more creations in short time, via selecting users of my Baïkal's CardDav account in KAddressBook and performing rightclick->Copy contacts to -> my Cyrrus account, only a few of these contacts are created successfully, most of them are forbidden
https[11907]: nas [192.168.xxx.xxx] as "bogo" with "Mozilla/5.0 (X11; Linux x86_64) KHTML/4.14.20 (like Gecko) Konqueror/4.14"; "PUT /dav/addressbooks/user/bogo/Default/1467532038.R692.vcf HTTP/1.1" => "403 Forbidden"

When I repeat it, the problem occurs randomly - the same contact is sometime created, sometime forbidden

I am using the latest GitHub ver 3 beta 3, but tried also 2.5.8 with the same problem
Please help...

Kind regards
Bohuslav

**Comment by brong** [comment]
Can you get a telemetry dump of the commands that are being used?
  
  
On Sun, Jul 3, 2016, at 18:00, spatnynick wrote: 
> Dear Cyrus team,
>  I have a Cyrus instance working, an account created, accessing
>  CardDav via KDE's KAddressBook (I am using this app successfully also
>  with Baïkal's CardDav) and I face following issue:   >  * when I try
>  to create a new contact manually, one by a one, all is OK, contact is
>  created >  https[11907]: nas [192.168.xxx.xxx] as "bogo" with
>  "Mozilla/5.0 (X11; Linux x86_64) KHTML/4.14.20 (like Gecko)
>  Konqueror/4.14"; "PUT
>  /dav/addressbooks/user/bogo/Default/1467532147.R131.vcf HTTP/1.1" =>
>  "201 Created"   >  * when I try to do more creations in short time,
>  via selecting users of my Baïkal's CardDav account in KAddressBook
>  and performing rightlickc->Copy contacts to -> my Cyrrus account,
>  only a few of these contacts are created successfully, most of them
>  is forbidden >  https[11907]: nas [192.168.xxx.xxx] as "bogo" with
>  "Mozilla/5.0 (X11; Linux x86_64) KHTML/4.14.20 (like Gecko)
>  Konqueror/4.14"; "PUT
>  /dav/addressbooks/user/bogo/Default/1467532038.R692.vcf HTTP/1.1" =>
>  "403 Forbidden"
> When I repeat it, the problem occurs randomly - the same contact is
> sometime created, sometime forbidden
> Please help...
> Kind regards
>  Bohuslav
> — > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].
>
  
--
  Bron Gondwana
  brong@fastmail.fm
 

Links:

  1. https://github.com/cyrusimap/cyrus-imapd/issues/4
  2. https://github.com/notifications/unsubscribe/AABE7aGC0x4buwuyabNB6dEeNG6KPkdKks5qR2wFgaJpZM4JD0vq

**Comment by spatnynick** [comment]
Hi
I have made a WireShark trace, see attachment

Br
Bohuslav

2016-07-03 10:30 GMT+02:00 Bron Gondwana <notifications@github.com>:

**Comment by spatnynick** [comment]
[cyrus-carddav-trace.pcapng.gz](https://github.com/cyrusimap/cyrus-imapd/files/344952/cyrus-carddav-trace.pcapng.gz)

**Comment by brong** [comment]
BEGIN:VCARD   
VERSION:3.0   
N:;Barton....ek;;;   
ORG:Foto doln.. ..jezd   
TEL;TYPE=WORK:+420603753359
UID:1d03ac06-1de6-4c32-a56e-7936f18b900a   
END:VCARD   
   
HTTP/1.1 403 Forbidden
Keep-Alive: timeout=300   
Connection: Keep-Alive   
Date: Sun, 03 Jul 2016 09:22:34 GMT   
Cache-Control: no-cache   
Vary: Accept-Encoding   
Content-Type: application/xml; charset=utf-8   
Content-Length: 138   
   
<?xml version="1.0" encoding="utf-8"?>
<D:error xmlns:D="DAV:" xmlns:C="urn:ietf:params:xml:ns:carddav"><C:valid-address-
data/></D:error>
  
That would be the lack of an 'FN' field.
  
https://en.wikipedia.org/wiki/VCard#Properties 
  FN S R R The formatted name string associated with the vCard object.
  FN:Dr. John Doe
  
The second "R" there is "required in VERSION:3.0".
  
You should file a bug against KAddressBook for failing to follow
the standard.
  
Regards,
  
Bron.
  
On Sun, Jul 3, 2016, at 19:29, spatnynick wrote: 
> cyrus-carddav-trace.pcapng.gz[1]
> — > You are receiving this because you commented. > Reply to this
> email directly, view it on GitHub[2], or mute the thread[3].
>
  
--
  Bron Gondwana
  brong@fastmail.fm
  
 

Links:

  1. https://github.com/cyrusimap/cyrus-imapd/files/344952/cyrus-carddav-trace.pcapng.gz
  2. https://github.com/cyrusimap/cyrus-imapd/issues/4#issuecomment-230144217
  3. https://github.com/notifications/unsubscribe/AABE7dZc03kdsXwECEdPWJFHrnqGL--_ks5qR4DjgaJpZM4JD0vq

**Comment by spatnynick** [comment]
Looks you are right. When I export this contact to vcf, import throws forbidden; if I fill in FN field in text editor, it's then loaded successfully

Thanks!

**Comment by ksmurchison** [comment]
Should this be closed since its a client issue?

**Comment by elliefm** [comment]
IMO yes, let's not clutter this up with dead ends like bugzilla/phabricator if we can help it

We can always reopen it if it becomes a Cyrus problem
