### ISSUE TITLE
installing.html talks about /etc/mail/sendmail.mc and sendmailconfig but no such files are installed

### ISSUE THREAD

**Issue by yurivict** [cyrusimap/cyrus-imapd#4003]
[Here](https://www.cyrusimap.org/imap/installing.html#install-sendmail) the documentation talks about ```/etc/mail/sendmail.mc``` and ```sendmailconfig``` but no such files exist in the system.

OS: FreeBSD 13

**Comment by elliefm** [comment]
This documentation is just using sendmail as one example of a common MTA you could use.  But you could use any other MTA instead, you don't have to use sendmail specifically.  You would need to refer to your MTA's documentation to find out how to configure it.  You should do the same for sendmail, if you choose to use it; this example is a sketch of how it might look, but the specifics will depend on your needs.

If you don't already have and know how to use sendmail, I would suggest using something else.  Probably find out what FreeBSD prefers, and use that... you might even have Postfix or Exim already installed (but I don't know, I'm guessing).

**Comment by yurivict** [comment]
@elliefm 

I meant that I do have sendmail installed and the file that the documentation talks about isn't present.

FreeBSD installs sendmail as part of base so this is what they recommend.

**Comment by dilyanpalauzov** [comment]
The reader is supposed to be familiar with configuring sendmail.  Writing utterly precise instructions for sendmail integration for every platform is out of scope for the manual.

https://www.cyrusimap.org/dev/imap/installing.html#integration-with-sendmail contains updated instructions, compared to https://www.cyrusimap.org/imap/installing.html#install-sendmail .  “Updated” means, that it suggests a setup, where sendmail does not forward all emails to Cyrus, which sends bounces to all non-existent mailboxes.

https://github.com/cyrusimap/cyrus-imapd/pull/3863/ goes into even more details.

**Comment by dilyanpalauzov** [comment]
Can this be closed?
