### ISSUE TITLE
imapd.conf example should have 'unixhierarchysep: yes' by default

### ISSUE THREAD

**Issue by yurivict** [cyrusimap/cyrus-imapd#4013]
I just installed Cyrus IMAPD and Thunderbird doesn't seem to understand mailbox names in the format "user.{username}". But "user/{username}" works.

You should probably uncomment the line 'unixhierarchysep: yes' in the sample imapd.conf to reduce potential user confusion from this issue.

**Comment by elliefm** [comment]
Which sample imapd.conf are you referring to?

**Comment by yurivict** [comment]
Sorry, my mistake. The ```imapd.conf``` file is supplied by the FreeBSD port, not by the project.

I'll address the problem there.
