### ISSUE TITLE
relocate_by_id command line niceties

### ISSUE THREAD

**Issue by elliefm** [cyrusimap/cyrus-imapd#4014]
From reports on info-cyrus:

* It doesn't seem to complain when it doesn't find any work to do.  If you spell the mailbox name incorrectly, and it finds no matches, then it successfully does nothing.  It should instead complain that the mailbox does not exist.
* I think it might be expecting mailbox names on the command line to be in the internal namespace.  But our other tools expect them to be in the admin namespace, so it's confusing to admins when the format they're used to typing doesn't work (and moreso when coupled with the previous point).  We've dealt with this sort of thing before in e.g. #1699

Our tests only invoke it with the `-u userid` invocation, which seems to work fine.  But we ought to test both invocations.

Also, the man page only provides a `-u` example.

**Comment by elliefm** [comment]
@ksmurchison do you wanna tackle this, or shall I?

**Comment by ksmurchison** [comment]
@elliefm Feel free to give it a shot as I have more urgent stuff on my plate.  I'll circle back when my load lightens to see where we are with this.

**Comment by elliefm** [comment]
I think I'm going to tackle this and #4005 together, since I'm doing both anyway, and it'll save merge conflicts.

WIP will be here: https://github.com/cyrusimap/cyrus-imapd/compare/master...elliefm:v37/relocate-fixes
