### ISSUE TITLE
ctl_cyrusdb -r crash on first start after upgrade to 3.6 betas

### ISSUE THREAD

**Issue by elliefm** [cyrusimap/cyrus-imapd#4035]
From the list: https://cyrus.topicbox.com/groups/info/T3e85440ddbb44ec6-Maf769decd0dd45d4572145b8

There is a Debian bug report for this already: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1007965

We're not sure precisely where the crash is happening, because so far nobody who has reported it has had core dumps enabled.  Anecdotally, it appears to be from the mboxlist_upgrade (which upgrades mailboxes.db to support both legacy-storage and uuid-storage of mailboxes).  It also appears that any mailboxes that haven't already been converted yet at the time the crash occurs are left out of the new mailboxes.db, and thus appear to have been "lost".

If the admin has the presence of mind to `reconstruct -f ...`, then the missing mailboxes will come back fine.  If they instead start tinkering on the file system, they can create themselves a mess...

[One user on the Debian bug report](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1007965#25) suggests that it seems to occur for very old mailboxes that do not have a uniqueid.  It's not clear whether this is a guess, or they managed to get a core dump and find the source.  They've provided a patch that creates a uniqueid during the process if there isn't one.

**Comment by elliefm** [comment]
The same user also suggests that if the upgrade process left the original mailboxes.db file in place, and do the conversion into a mailboxes.db.NEW, and finally rename on success, then this wouldn't be a problem.  But instead we rename the original mailboxes.db to mailboxes.db.OLD, and convert into a new mailboxes.db, so after the failure we're left with the half-converted/half-empty version instead of the original file.

**Comment by elliefm** [comment]
@ksmurchison can you have a look at this please, particularly the linked comment on the Debian bug?

I'm not sure whether it's correct to just generate a uniqueid if one is missing, or if the fact it's missing could be indicative of other problems.  Perhaps if the uniqueid is missing, we should bail out (cleanly!) rather than just smoothing it over?  I'm not sure, what do you think?

I think the suggestion about doing the conversion into a mailboxes.db.NEW is a good one, and we should definitely do that if we can.  But I'm not sure if we can, maybe there's a good reason it is the way it is.  What do you think?

**Comment by ksmurchison** [comment]
I'm curious if records without uniqueids was a glitch or they were never added to older entries over time.  I guiess if we find an entry without a uniqueid, we would have to open the cyrus.header for that mailbox and read it from there.

**Comment by elliefm** [comment]
Yeah wow, I think they've just never been added to old entries over time...

`makeuuid()` is called directly in a bunch of places, but only `mailbox_create()` seems to be using it for the mailbox uniqueid.  So newly created mailboxes get one...

`mailbox_make_uniqueid()` looks to be the API way of doing it, but the things that call this are:
* `mailbox_reconstruct_create()` (`reconstruct -f`) -- this only generates a uniqueid if the header file could not be read.  If the header file is pre-dlist, then the old parser will complain about a missing uniqueid, causing a new one to be generated.  But if the header file is dlist, and has no uniqueid, it'll just carry on without a uniqueid.
* `mbtool -r` -- specifically for generating new uniqueids
* `do_reconstruct()` -- but only if there was already a uniqueid, but it didn't match.  If there was no uniqueid, it just shrugs and lets it slide through

So if I'm reading this right, we can only expect to have uniqueids for:
* mailboxes that were created with one in the first place
* mailboxes that have been `reconstruct -f`'d back together specifically from old, pre-uniqueid data
* mailboxes for which the admin has run `mbtool -r`

Notably, none of the other reconstruct paths seem to create a uniqueid if it's missing (not even `reconstruct -V`!)

I guess the fundamental problem is that the dlist paths through `mailbox_read_header()` and `mailbox_write_header()` never do any validation that any fields are actually present.  The old-format read path _did_ do this validation, and I guess everything has continued to assume that `mailbox_read_header()` would complain about missing fields on load, except it mostly doesn't anymore except for ancient header files.  And `mailbox_commit_header()` happily writes a file with a NIL "I" field.

We have lots of code lying around that checks for uniqueid being NULL to prevent itself from crashing if the mailbox is missing one... but I guess all this code assumes actually creating one is someone else's problem, and just works around it being missing.  And any new code that forgets to check, crashes.

So **something needs to create these if they're missing**, and the question is, _which something_??

I think:
* `reconstruct` definitely needs to create one if there isn't one, no question there.  It should never produce junk.
* `ctl_cyrusdb -r` probably does too, though this is complicated by the `mboxlist_upgrade()` call happening _before_ `fixmbox`, so it wouldn't prevent this crash.  (So maybe the upgrade path needs to do it as well.)
* What about `mboxlist_read_header()` and `mboxlist_commit_header()`?  I think they should both complain if it's missing, but I'm not sure if they can safely just create it instead, they don't have a broad enough view.

**Comment by ksmurchison** [comment]
Every mailbox DOES have a uniqueid, whether or not its contained in the mailboxes.db record.  Seen state has always been tracked by mailbox uniqueid (originally just a hash of mailbox name) so it stays consistent across renames.
So, mailboxlist_upgrade() should fetch the uniqueid from cyrus.header if its not in the db record.

**Comment by elliefm** [comment]
What I'm saying is, it's possible for cyrus.header to NOT contain a uniqueid.  As far as I can tell nothing currently enforces that it exists, nothing automatically creates it for existing mailboxes if it's missing, and if the mailbox was old enough to have been created without one, and then someone upgraded to a Cyrus version where cyrus.header was a dlist file, the only way it could have got one is if the admin manually `mbtool -r`'d one in.

This probably doesn't affect us at all, because we do frequent small upgrades rather than infrequent big ones, and so we get all the intemediate states smoothing things over.  But most not-us deployments tend towards the latter, and may have missed state changes we take for granted as having occurred.

> So, mailboxlist_upgrade() should fetch the uniqueid from cyrus.header if its not in the db record.

Yeah, that's fine, but what if it does that and _it's not there either_?

* We could choke out and fail to start, with an error like "mailbox has no uniqueid, please run mbtool -r"
* We could just create one -- this seems easy enough, but I don't feel like I fully understand the ramifications, so there may be a complicating factor that I haven't considered

What do you think?

**Comment by ksmurchison** [comment]
Creating one on the fly makes sense, but I don't understand how a mailbox can't have a uniqueid.  If it doesn't, then we have no way of tracking \Seen state in seen.db

**Comment by elliefm** [comment]
I'll have a go at patching the mailbox upgrade to look up and use the header uniqueid if the mbentry doesn't have one, and generate a new one if the header doesn't have it either.

While I'm in there, I'll also have a go at patching reconstruct so that it also creates one if neither source has one, so that if the problem exists in the wild a reconstruct can fix it.

Though it sounds like, if the situation I think can happen is happening, it will be presenting as \Seen state problems.  So I'll keep that in mind if people turn up reporting \Seen problems, but not worry about it for now otherwise.  Thanks :)

**Comment by elliefm** [comment]
I've got a precarious local setup where I'm able to reproduce the crash on master, and therefore am able to test my "fixed" branch...

And I'm running into an annoying complication.  I can't open the mailbox to check the header uniqueid, because one of the first things `mailbox_open_advanced(name,...)` does is `mboxlist_lookup_allow_all(name, ...)` -- which of course can't find it, because it's expecting it to have a new-style key, but the upgrade hasn't happened yet.  So mailbox_open_advanced returns IMAP_MAILBOX_NONEXISTENT, and the upgrade still fails (but doesn't crash).

So I'm left at an impasse -- can't continue the upgrade without a uniqueid, can't find the uniqueid until the upgrade finishes.  Any ideas?

My WIP is here: https://github.com/cyrusimap/cyrus-imapd/compare/master...elliefm:v37/4035-missing-uniqueid-crash

**Comment by elliefm** [comment]
I believe this is now fixed on the master and 3.6 branches.  The fixes will be in 3.6.0-beta3

**Comment by xkl** [comment]
Hi all,

today I upgraded our familiy+friends email server system from bullseye to bookworm including the cyrus-imapd upgrade to v3.6.1-4.

Unfortunately, all mails of all users disappeared and new inboxes were autocreated when users logged in:

------syslog-----------------
Jun 11 12:27:15 xxx cyrus/imaps[1730301]: autocreateinbox: User xxxxx, INBOX was successfully created
-----------------------------

The emails were still in the non-uuid directory of the cyrus spool dir. I did not figure out how this happened, but I solved it by

1. extracting a list of all sub-mailboxes of all users from the filesystem structure,
2. re-creating the same sub-mailboxes with the cm command of cyradm,
3. and hard-linking all directory content to the new uuid dirs (with the help of mbpath)

The issue is now solved for me, but I can provide additional system information and logs if needed.

(same report goes to https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1007965)

-Kai

**Comment by elliefm** [comment]
> The emails were still in the non-uuid directory of the cyrus spool dir

That's normal behaviour.  The upgrade to 3.6 does not mess around with your existing mailbox storage, other than upgrading the mailboxes.db to identify that those mailboxes are using the legacy storage location.  By default, only newly-created top level mailboxes use the new uuid storage.  To move your existing mailboxes to the uuid location (later, when you're ready) you would use the `relocate_by_id` tool.

> autocreateinbox: User xxxxx, INBOX was successfully created

Ahh, so you're using autocreate.  My gut feel says this is the real culprit.  I bet the autocreate checks don't recognise legacy mailboxes correctly, and helpfully create new ones, masking what was already there.  Autocreate isn't particularly well-tested or well-maintained -- it's not used by any of the regular contributors -- so it being broken like this isn't particularly surprising.  

> The issue is now solved for me

Great!  I've created #4532 for the suspected autocreate bug

**Comment by GijsHillenius** [comment]
My primary mail server is hit by the same bug following a full-upgrade too Debian Bookworm.

I just checked : "/usr/lib/cyrus/bin/relocate_by_id -n -u" returns " user already relocated" for *all* users.

But the legacy mailboxes are unavailable.  Is there anything else we can configure to restore access (other than attempt the steps Kai (and Phil) have documented? What about adding 'mailbox_legacy_dirs: true' to /etc/imapd.conf ?

**Comment by elliefm** [comment]
What version of Cyrus were you running before you upgraded to Debian Bookworm?

Our [upgrade documentation](https://www.cyrusimap.org/3.6/imap/download/upgrade.html#versions-to-upgrade-from) is as clear as it can be that you should be running 3.2.10 (or later) or 3.4.4 (or later) before upgrading to 3.6.  Though this doesn't help you much after the fact.

If you took a full-system backup before upgrading, you should probably just restore to that.  Once you're up and running again, you can approach the upgrade again more carefully.  But since you're here asking about cobbling together a repair, I'll assume you don't have a full system backup to restore to, or can't restore to it for whatever reason.

I expect the situation that you're currently in is that all your mailboxes are still on disk, but Cyrus can't see them because your mailboxes.db is empty or broken.  **Iff** that is the case, then what you're trying to do is recreate the missing mailboxes.db records to point to the existing mailboxes on disk.  This is what `reconstruct -P <path>` does.

The `path` argument is the path to a "cyrus.header" file, or a directory containing one (each mailbox has its own "cyrus.header" file).  So you could search your system for "cyrus.header" files, and then pass each one of these to `reconstruct -P`.  You may need to be careful about ordering, I don't know what will happen if you try to recreate a child mailbox before its parent.  You also can't use any other options with `-P`.  I'd suggest doing these reconstructs one mailbox at a time until you're sure it's working, but it doesn't seem like it would be hard to automate the rest once you're confident.

**Comment by GijsHillenius** [comment]
Thank you

My server was running Debian Bullseye's Cyrus version 3.2.6-2 and got Bookworm's Cyrus version 3.6.1-4.

The script maintained by Phil helped me regain access, but I will investigate the reconstruct -P. 

I have at least one user who is still not able to see email, even though it's all there. Might be something on the client.
