### ISSUE TITLE
cmd_xapplepushservice() ignores the return value of `buf_release()`

### ISSUE THREAD

**Issue by dilyanpalauzov** [cyrusimap/cyrus-imapd#4061]
My understanding is that ignoring the return value of `buf_release()` leads to memory leaks.

[cmd_xapplepushservice()](https://github.com/cyrusimap/cyrus-imapd/blob/master/imap/imapd.c#L14783) does 3× ignore the return value of `buf_release()`.

**Comment by elliefm** [comment]
Good find, I think these should be `buf_free()` instead.
