### ISSUE TITLE
Should depend on libical >= 3.0.10

### ISSUE THREAD

**Issue by robn** [cyrusimap/cyrus-imapd#4071]
Compiling master today:

```
imap/itip_support.c: In function ‘deliver_merge_add’:
imap/itip_support.c:958:9: error: ‘ICALTIMETYPE_INITIALIZER’ undeclared (first use in this function)
  958 |         ICALTIMETYPE_INITIALIZER,
      |         ^~~~~~~~~~~~~~~~~~~~~~~~
imap/itip_support.c:958:9: note: each undeclared identifier is reported only once for each function it appears in
imap/itip_support.c:959:9: error: ‘ICALPERIODTYPE_INITIALIZER’ undeclared (first use in this function)
```

I have libical 3.0.9, but the initializer constants in libical didn't appear until 3.0.10 (libical/libical@45ad8c0a).

configure should do a version check for libical.

**Comment by elliefm** [comment]
https://github.com/cyrusimap/cyrus-imapd/blob/d3eb596bccbc834fc24aa3073506669a8354dda0/configure.ac#L1635-L1640

We have such a check, but it thinks 3.0.0 is adequate.  Looks like the most recent release was 3.0.14.  @ksmurchison shall we bump this to 3.0.10, or straight to 3.0.14?  Probably better check what version the cyruslibs fork thinks it is...

The cyrus-imapd commit that starts using `ICALTIMETYPE_INITIALIZER` (c287d863c7) isn't on the 3.6 branch, so we don't need to worry about 3.6 here, just master.

**Comment by ksmurchison** [comment]
If 3.0.10 is the minimum requires, I'd got with that

**Comment by philfry** [comment]
Hi all,
since cyrus-imapd 3.8.0 uses `icalproperty_get_datetime_with_component()` which came with libical-3.0.5, the minimum requirement should be raised accordingly.

**Comment by elliefm** [comment]
Thanks, will update

**Comment by dilyanpalauzov** [comment]
master brach requires libical 3.0.10 since 96ea872427aeba1289f12a93.  3.8 branch requires libical 3.0.10 since bedb08b1f8eb2c2 .

Can this be closed?

**Comment by elliefm** [comment]
Yeah I think so, though the 3.8 change hasn't been released yet.  Guess I should put together a 3.8.1 soon
