### ISSUE TITLE
JMAP: `Identity/get` incorrectly returns `null` for `notFound`

### ISSUE THREAD

**Issue by elizagamedev** [cyrusimap/cyrus-imapd#4122]
I'm encountering the following behavior live on Fastmail's servers, including the erroneous behavior in #2671 which I see has been since solved, so I apologize if this has already been fixed in the latest revision of Cyrus.

According to the JMAP spec, `notFound` as a response to a `/get` method can be an empty list, but not `null`. Cyrus returns `null` here when `Identity/get` is called with a `null` value for `ids`.

**Comment by rsto** [comment]
The Cyrus server is fine, but the values get mangled on our Fastmail API endpoints. We already work on fixing this.

I am not sure if you expect Cyrus to return an empty list if the `ids` argument is `null`. That would violate the spec, too! It needs to return the complete list of objects of this type. See the definition of the `ids` argument at https://jmap.io/spec-core.html#get 
I updated our tests to make sure that Cyrus implements this (https://github.com/cyrusimap/cyrus-imapd/pull/4124).

**Comment by rsto** [comment]
Since this is not an issue with Cyrus, we should close this issue. If however you would like to keep it open so that I can contact you when the Fastmail API endpoint has been updated, we can do that, too.

**Comment by elizagamedev** [comment]
> I am not sure if you expect Cyrus to return an empty list if the `ids` argument is `null`. That would violate the spec, too! It needs to return the complete list of objects of this type.

No, I expected that `ids` would contain all of the objects. It was specifically `notFound` being set to `null` instead of an empty list that was surprising/non-conforming behavior. I apologize if I was not clear.

If Cyrus does in fact behave correctly and it's the middleware that's causing the issue, I can just work around it. I appreciate the offer, but it's okay to close the issue.

**Comment by robn** [comment]
@elizagamedev fyi, Fastmail middleware fix for this just landed. Holler if it still doesn't look right!
