### ISSUE TITLE
ctl_mboxlist -v needs to be able to report broken uuid mailboxes

### ISSUE THREAD

**Issue by elliefm** [cyrusimap/cyrus-imapd#4187]
This thing looks at everything in the mailboxes.db and everything on the spool, and reports things that are missing from one or the other.

Ken observes that it doesn't currently seem able to deal with uuid mailboxes.

**Comment by a-tze** [comment]
I'm currently setting up a fresh 3.6 murder and found this behaviour yesterday. I'd like to help. Does it make sense to work on this or has there already been some progress somewhere?

**Comment by a-tze** [comment]
@elliefm Any chance to also get this into 3.6 branch? Otherwise at least Debian-based installations will probably not get this fix for a very long time.

**Comment by elliefm** [comment]
Sure. I've added the backport-to-3.6 label to the PR, and I'll take care of it next time I do a batch of backports for that branch, and thereafter it'll be in the following release.
