### ISSUE TITLE
configure should detect need for -ldoor with staticsasl

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#423]
From: [Rob Siemborski](rjs3@andrew.cmu.edu)
Bugzilla-Id: 1262
Version: 2.1.x
Owner: [Ken Murchison](murch@andrew.cmu.edu)

**Comment by elliefm** [comment]
I wonder if the .pc files distributed with cyrus-sasl have since taken care of this...

**Comment by elliefm** [comment]
```
$./configure --with-ipctype=doors --enable-static --disable-shared

[...]

$cat libsasl2.pc
prefix=/usr/local
exec_prefix=${prefix}
libdir=${exec_prefix}/lib
includedir=${prefix}/include

Name: Cyrus SASL
Description: Cyrus SASL implementation
URL: http://www.cyrussasl.org/
Version: 2.1.27
Cflags: -I${includedir}
Libs: -L${libdir} -lsasl2
Libs.private: -ldoor -ldl -lresolv  
```

cyrus-sasl seems to put the right stuff into libsasl2.pc when configured to use doors.  But doors are a Solaris only feature, so I can't do a test build to see what cyrus-imapd does with it.
