### ISSUE TITLE
imap/cyr_cd.sh is not a valid sh script

### ISSUE THREAD

**Issue by guimard** [cyrusimap/cyrus-imapd#4293]
Hi,

currently [imap/cyr_cd.sh](imap/cyr_cd.sh#L47) is not a valid shell script:
```shell
$ sh -n imap/cyr_cd.sh
imap/cyr_cd.sh: 47: Syntax error: "(" unexpected
```
but a valid bash script. Then I think shebang should be changed:
```diff
--- a/imap/cyr_cd.sh
+++ b/imap/cyr_cd.sh
@@ -1,4 +1,4 @@
-#!/bin/sh
+#!/bin/bash
 #
 # cyr_cd -- Shell script to change directory within a mailbox spool
 #
```

**Comment by elliefm** [comment]
Good catch, thanks

**Comment by elliefm** [comment]
That said, this script won't do anything when run, so the shebang is kind of meaningless anyway.

Like the comment says, you `source` it in your shell (or in your .bashrc), and it installs a `cyr_cd` bash function, which is what you actually run
