### ISSUE TITLE
[2.5.17] SEGV on carddav

### ISSUE THREAD

**Issue by MASHtm** [cyrusimap/cyrus-imapd#4386]
Not sure if you still want fixes for 2.5 tree... 

If a client like TB 102 tries to upload a Version 4 VCARD httpd segfaults. And there are other cases as well...

This comes from an incomplete resource leak fix in d9dc8fdfb7eedfac8eb24b9aa43f5369b02b29ee.

IMO
```
--- cyrus-imapd-2.5.17/imap/http_carddav.c.orig 2023-01-24 13:37:25.345223155 +0100
+++ cyrus-imapd-2.5.17/imap/http_carddav.c      2023-01-24 13:37:58.225717934 +0100
@@ -963,7 +963,7 @@
 {
     int ret = HTTP_CREATED, r;
     struct vparse_entry *ventry;
-    struct carddav_data *cdata;
+    struct carddav_data *cdata = NULL;
     FILE *f = NULL;
     struct index_record oldrecord;
     struct stagemsg *stage;
```
is missing. This leads to a SEGV in store_resource() if the version, uid or fn checks fail and bail out to "done" where carddav_data_fini(cdata) is called. cdata is not initialized until after that point when carddav_lookup_uid() is called.

**Comment by elliefm** [comment]
Looks like 2.5 was the only branch that ever got the "mostly fix leak" patch, so it's the only branch affected by this crash.

3.0 and later have 55252e2569c8, which looks like it might address the original leak of the carddav_data emails/member_uids fields differently.

**Comment by elliefm** [comment]
This is on the 2.5 branch now as d4aa084a98.  Thanks!
