### ISSUE TITLE
[2.5.9] SIGSEGV cyrus-httpd frontend backend_starttls

### ISSUE THREAD

**Issue by MASHtm** [cyrusimap/cyrus-imapd#44]
my backends require tls and the frontend cyrus-httpd proxies try to call

```
#0  backend_starttls (s=0x7fa6b09cd0c0, tls_cmd=0x0, c_cert_file=<value optimized out>, c_key_file=0x0) at imap/backend.c:536
```

at imap/http_proxy.c:253

this has to break badly since backend_starttls calls

```
    ask_capability(s, /*dobanner*/1, tls_cmd->auto_capa);
```

unconditionally while tls_cmd == NULL at imap/backend.c:536

**Comment by MASHtm** [comment]
testing with this one now...
```
--- cyrus-imapd-2.5.9/imap/backend.c.orig	2016-10-04 14:48:56.589436078 +0200
+++ cyrus-imapd-2.5.9/imap/backend.c	2016-10-04 14:49:54.550798074 +0200
@@ -533,7 +533,8 @@
     prot_settls(s->in,  s->tlsconn);
     prot_settls(s->out, s->tlsconn);
 
-    ask_capability(s, /*dobanner*/1, tls_cmd->auto_capa);
+    if (tls_cmd)
+        ask_capability(s, /*dobanner*/1, tls_cmd->auto_capa);
 
     return 0;
 #endif /* HAVE_SSL */
```

**Comment by MASHtm** [comment]
this one works for me... http frontend->backend with TLS upgrade works and requests get proxied correctly afterwards.

**Comment by MASHtm** [comment]
Any reason why this patch is not accepted? Still works perfectly here.

**Comment by elliefm** [comment]
No particular reason -- it looks okay to me, I'll try and get it merged today. Thanks, and thanks for the bump :)

**Comment by elliefm** [comment]
Actually, I think there was a "better" fix on master already (still calls `ask_capability`, but does so without crashing): a3ef161d

Not sure what the practical difference is?

**Comment by MASHtm** [comment]
in case of HTTP(S) maybe there is none, but maybe for other/future protocols?

**Comment by elliefm** [comment]
I've reverted your patch (sorry!) and cherry-picked the one from master, so this will be fixed in the next release :)
