### ISSUE TITLE
cyradm listmailbox use of an uninitialized value in 3.4.5

### ISSUE THREAD

**Issue by yaonos** [cyrusimap/cyrus-imapd#4440]
# Description

Cyrus IMAP 3.4.5's cyradm issues a uninitialized value warning with the listmailbox command.

Here is an illustration of this issue :

```
localhost> lm user.tst
Use of uninitialized value $w in numeric gt (>) at /usr/lib64/perl5/vendor_perl/Cyrus/IMAP/Shell.pm line 676.
user.tst (\HasChildren)  
```

This issue has been observed on an RHEL 8.7 system.

# Resolution

A patch that resolves this issue is attached to this report.

[cyrus-imapd_listmailbox_uninitialized.patch](https://github.com/cyrusimap/cyrus-imapd/files/10996702/cyrus-imapd_listmailbox_uninitialized.patch)

**Comment by elliefm** [comment]
Thanks!  The patch looks good, do you want to submit it as a pull request?  I'm happy to just apply the patch myself, but if you submit it as a PR then the commit will have your name on it.  Whichever you prefer, let me know.

If you do submit it as a PR, please submit it against the master branch.  I'll take care of backporting it to the earlier releases. :)
