### ISSUE TITLE
core dump while checking config with cyr_info

### ISSUE THREAD

**Issue by pieska** [cyrusimap/cyrus-imapd#4650]
cyr_info 3.8.1 aborts while checking config.

cyr_info conf-lint -C <path to imapd.conf> -M <path to cyrus.conf> works, but conf-default / conf_all aborts with core dump:

# cyr_info conf-default -C /etc/imapd.conf -M /etc/cyrus.conf
acl_admin_implies_write: no
..
archive_after: 7d
Aborted (core dumped)

either -C or -M or both specified, conf-default/conf-all aborts always on my system.

**Comment by pieska** [comment]
the abort is triggered in cyr_info.c:222:do_conf() and cyr_info.c:278 do_defconf()
```
            default:
                abort();
```

because OPT_BYTESIZE is not handled:
```
Breakpoint 2, do_defconf (want_since=0, since=0) at imap/cyr_info.c:240
240	        switch (imapopts[i].t) {
(gdb) p imapopts[i].t
$32 = OPT_BYTESIZE
(gdb) c
Continuing.

Program received signal SIGABRT, Aborted.
```

**Comment by elliefm** [comment]
Good catch, thanks
