### ISSUE TITLE
3.4.6: can't find pcre in /usr/include/pcre

### ISSUE THREAD

**Issue by asy972** [cyrusimap/cyrus-imapd#4711]
I attempt to build cyrus-imap 3.4.6 with pcre but configure script can;t find it.

$ pkg-config --cflags libpcre
-I/usr/include/pcre

OS: Linux

**Comment by elliefm** [comment]
What version of PCRE?  Maybe you have PCRE2, which Cyrus doesn't support yet.

The configure check looks for `pcreposix.h`, and then checks whether that header defines `REG_UTF8`.  These two checks don't use pkg-config.  If you don't have `pcreposix.h`, or it doesn't define `REG_UTF8`, Cyrus won't find it.  I believe PCRE2 provides `pcre2posix.h`, not `pcreposix.h`, so Cyrus can't find it.

There's an open PR that replaces the PCRE1 support with PCRE2 support: #4545.  That patch might get you going for now.

I have on my to-do list to add PCRE2 support properly (i.e. detecting and supporting either version, unlike #4545 which just replaces the older with the newer), but I haven't gotten to it yet.

I'm not certain of this, but I think the main reason we support PCRE is for UTF8 regular expressions.  If you don't specifically need UTF8 regular expressions, then perhaps you don't need PCRE at all.  Cyrus builds fine and passes all our tests without it (using the glibc versions of the POSIX regex functions) -- at least, it works for me, on Debian Bookworm, which has PCRE2 (that Cyrus configure can't find).

**Comment by asy972** [comment]
> What version of PCRE? Maybe you have PCRE2, which Cyrus doesn't support yet.

I known, I use PCRE. The problem in PATH to headers. Library used if I create symlinks to headers in /usr/include.

**Comment by elliefm** [comment]
Ahh, I see what you mean:  the headers are under `/usr/include/pcre/` but your C compiler doesn't look in the subdirectory.

If you run configure like:

```
./configure CFLAGS=`pkg-config --cflags libpcre` [...]
```

This would:
a) use pkg-config to find the correct directory, which you've shown works
b) add the appropriate `-Ipath` argument to CFLAGS
c) tell configure to preserve these CFLAGS values across the entire build

(Note that this is different from `CFLAGS=... ./configure`, which would set CFLAGS in the environment while configure runs, but would not tell configure to preserve that value)

**Comment by asy972** [comment]
> ./configure CFLAGS=`pkg-config --cflags libpcre` 

It usually works, but not now: CFLAGS is not used everywhere. additionally, this change is required:
`sed "s|@SSL_CPPFLAGS@|@SSL_CPPFLAGS@ -I%_includedir/pcre|" -i perl/imap/Makefile.PL.in`

**Comment by elliefm** [comment]
Yeah that does seem like a nuisance.  When I update it for both PCRE and PCRE2 support, I'll see about using pkg-config for it too

**Comment by elliefm** [comment]
I've updated configure.ac to use pkg-config to find pcre/pcre2 in #4736.  Are you able to apply those patches locally and confirm whether it finds your pcre in `/usr/include/pcre/`?

I think the patches should apply to 3.4 okay, but if you run into trouble, please let me know and I'll produce a version for 3.4.

**Comment by asy972** [comment]
> I think the patches should apply to 3.4 okay

Do I need to apply the whole set of patches or is b9002dba94e enough ? b9002dba94e is not applied separately.

**Comment by elliefm** [comment]
You can download a whole PR as a single patch by adding ".patch" to the end of the URL, like this: https://github.com/cyrusimap/cyrus-imapd/pull/4736.patch

e.g. if you grab that with something like `curl -OL https://github.com/cyrusimap/cyrus-imapd/pull/4736.patch` then you'd be able to apply it with something like `patch -p1 < 4736.patch`

But in writing this, I tested it, and found that the patch doesn't apply cleanly to 3.4 sources.  Bear with me, and I'll put up a version that does for you.

**Comment by elliefm** [comment]
@asy972 I've backported it for 3.4 and put it up as #4738, so you should be able to fetch a patch from https://github.com/cyrusimap/cyrus-imapd/pull/4738.patch and apply that to your local sources.
