### ISSUE TITLE
#sieve folder appears in GETMETADATA response

### ISSUE THREAD

**Issue by alecpl** [cyrusimap/cyrus-imapd#4732]
Cyrus 3.6.1 (murder).

```
C: A0006 GETMETADATA "*" (/private/vendor/kolab/activesync)
S: * METADATA INBOX ("/private/vendor/kolab/activesync" {1225}
...
S: * METADATA #sieve ("/private/vendor/kolab/activesync" NIL)
...
```
I assume `#sieve` is some kind of a hidden special folder. It for sure does not appear on the `LIST` response. So, I think it should not appear in `GETMETADATA` response either.

**Comment by elliefm** [comment]
Thanks for the report.  Looks like all the special JMAP folders are exposed by `GETMETADATA` like this, which is surprising to me, but I don't know if it's intentional.  Will find out...
