### ISSUE TITLE
3.8: unused files under cassandane/tiny-tests/Sieve 

### ISSUE THREAD

**Issue by dilyanpalauzov** [cyrusimap/cyrus-imapd#5004]
On the master branch, 1e7e5b75ffa44906129f added in cassandane/Cassandane/Cyrus/Sieve.pm the line `use Cassandane::Tiny::Loader 'tiny-tests/Sieve';` and created the files cassandane/tiny-tests/Sieve/implicit-keep-target-bad and cassandane/tiny-tests/Sieve/implicit-keep-target-mailboxid.

On the 3.8 branch for the directories under cassandane/tiny-tests: Caldav/ and Sieve/ there are nowhere corresponding lines `use Cassandane::Tiny::Loader 'tiny-tests/Sieve';` and `use Cassandane::Tiny::Loader 'tiny-tests/Caldav';`.  So I guess on the 3.8 branch the files under cassandane/tiny-tests/Caldav and cassandane/tiny-tests/Sieve do nothing.

**Comment by elliefm** [comment]
Good catch, I must've missed that detail when backporting something.  I'll get it cleaned up

**Comment by elliefm** [comment]
I think this is fixed for Caldav in 2ecb73487 (3.10) and 753e8cc85 (3.8).  I couldn't find any tiny-tests under Sieve on 3.8, and on 3.10 the Sieve tiny-tests are actually used.

I checked 3.6 and 3.4 too, and there's no tiny-tests directory on those branches at all.
