### ISSUE TITLE
sieve 'test' should be able to check text script

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#519]
From: [Ken Murchison](ken@oceana.com)
Bugzilla-Id: 1894
Version: 2.2.x
Owner: [Ken Murchison](murch@andrew.cmu.edu)

**Comment by ksmurchison** [comment]
Fixed with https://github.com/cyrusimap/cyrus-imapd/commit/73df00f43270c27b11a1ac2ca01c25ec62da5fa4
