### ISSUE TITLE
"(null)" partitions in ctl_mboxlist

### ISSUE THREAD

**Issue by elliefm** [cyrusimap/cyrus-imapd#53]
On one of my test servers (master, albeit a stale build) I get the following:

ctl_mboxlist -d | grep null:

```
user.anne.Trash.a folder that will be deleted soon  16 (null) 
user.anne.Trash.delete me okay  16 (null) 
user.anne.Trash.kill this folder soon   16 (null) 
[snip]
```

ctl_mboxlist -v:

```
'user.anne.Trash.a folder that will be deleted soon' has a DB entry but no directory on partition '(null)'
'user.anne.Trash.delete me okay' has a DB entry but no directory on partition '(null)'
'user.anne.Trash.kill this folder soon' has a DB entry but no directory on partition '(null)'
[snip]
```

I think this is not the same as #52 but might be vaguely related.  These are all folders in some state of having been deleted.

Those "(null)"s look a lot like printf output when given a NULL argument to %s -- which means on platforms other than linux, it'll probably segfault here instead.

I think this is something to do with deleted mailbox records no longer having a partition associated with them (because they no longer exist on a partition), but ctl_mboxlist not handling that case properly.

**Comment by elliefm** [comment]
cyr_dbtool ... show | grep 'Trash[.]':
```
user.anne.Trash.a folder that will be deleted soon	%(I 7e717cdd-5f4d-435e-a880-6fa530cd6101 T d V 1452550922 F 4 M 1452550943)
user.anne.Trash.delete me okay	%(I d121901c-6e18-4cef-bb0a-b51be33a1129 T d V 1452476728 F 3 M 1452476833)
user.anne.Trash.kill this folder soon	%(I d3a879dc-a400-4380-a7bc-194a5bf9f176 T d V 1450740366 F 6 M 1450744525)
```

**Comment by elliefm** [comment]
Actually I think the "(null)" in the -d output is the ACL column, not the partition partition.  The column partition is empty (note adjacent whitespace before the 16 (mbtype).

**Comment by elliefm** [comment]
These are mailbox tombstones (16 = MBTYPE_DELETED).  Should `ctl_mboxlist` list these by default, optionally, or not at all?  See also #2265 for documentation on mailbox tombstones.

If these are to be listed by `ctl_mboxlist`, presumably the ACL column for these (and other entries with no ACL) should be empty, not "(null)"?

**Comment by slauffer** [comment]
btw... same issue in  #2193
We still have these tons of entries in cyrus-imapd 3.0.4.
Could we add a patch to remove them from the mailboxlist?

**Comment by elliefm** [comment]
Are you running cyr_expire regularly?  If so, with what invocation(s)?  These records are tombstones for deleted mailboxes, and I believe they should be automatically cleaned up after a while, if you're running cyr_expire regularly.

**Comment by slauffer** [comment]
ok... we are using this delprune record in the EVENTS{...} section:
delprune      cmd="cyr_expire -E 1 -D 12h -X 12h -a" at=0400

**Comment by elliefm** [comment]
Hmm, ok.

They're cleaned up here once they reach 7 days old, as long as you're not using the `-x` option (which you're not):
https://github.com/cyrusimap/cyrus-imapd/blob/98eca6b9c8421f122aecd543c100c95632bd3625/imap/cyr_expire.c#L278-L287

So it seems like they ought to be cleaned up regularly... the question is, are they?

If you run something like `ctl_mboxlist -d | grep -c '16 (null)$'` it should give you a count of how many such mailboxes there are.  I would expect this number to stay roughly stable over time (depending on how frequently your users delete mailboxes, or how frequently your admins delete whole users).  But if they're not being cleaned up properly, then I'd expect the number to keep going up indefinitely, week after week...

**Comment by slauffer** [comment]
We have loggs about the date of deleted mailboxes. So I have taken a list of deleted boxes from august and checked if there are "(null)" entries in the mailbox db. And yes, they are all there and none was removed. So we have a increasing list of entries. :-/

**Comment by elliefm** [comment]
To be clear, are they all `16 (null)` entries, or is the number some other value?

**Comment by slauffer** [comment]
Yes.
To become a  feeling about the dimension...
~ # echo "lm user.%" | cyradm --user cyrus localhost -w XXXXXX | grep -c '^user.'
3495
~ # /usr/lib/cyrus/bin/ctl_mboxlist -d | grep -c '16 (null)'
23708
System running since about 3 years. And yes, of course, all the checked and deleted user mailboxes from august (485) are now '16 (null)'. On other backends similar counts.

**Comment by elliefm** [comment]
I guess you also never see "Removing stale tombstone for [mailbox name]" in your syslogs?  Look like cyr_expire in 3.0 just never cleans them up, because when it searches for things to expire, it doesn't ask for them to be included in the search!

I think this patch should fix cyr_expire so that the tombstones are correctly cleaned up after 7 days as intended, instead of hanging around forever:

https://github.com/cyrusimap/cyrus-imapd/compare/cyrus-imapd-3.0...elliefm:v30/53-expire-tombstones

Same again as a downloadable .patch file: https://github.com/cyrusimap/cyrus-imapd/compare/cyrus-imapd-3.0...elliefm:v30/53-expire-tombstones.patch

If you apply this patch, then the next time cyr_expire runs it might take quite a bit longer than usual, because it's got 23k old entries to tidy up.  I expect your mailboxes.db will get a lot smaller afterward too.  Please let me know how it goes if you try it, so I can include it in any future 3.0 release.

Seems like it's only 3.0 that's affected, so if you end up upgrading to 3.2 instead, the problem should go away on its own.

**Comment by slauffer** [comment]
sorry for the delayed reply, a lot of work here. Your patch works (partly because of the file size?). On one of our backends tonight...:
 # grep tombstone  /var/log/messages | wc -l
24144
But the file size is still ~14MB ( Cyrus twoskip DB). Dont't know if this twoskip should become smaller...?

**Comment by elliefm** [comment]
Great, thanks for reporting back.

I guess the database file size won't decrease until it gets repacked or something.  It might happen at a "checkpoint" (`ctl_cyrusdb -c`), which you might have scheduled in EVENTS?

**Comment by slauffer** [comment]
hm... we have this job in events:
   checkpoint    cmd="ctl_cyrusdb -c" period=30
So this means this isn't working, too?

**Comment by elliefm** [comment]
I think it more likely means that that is not the thing that repacks databases.  I don't know much about administering Cyrus servers; I'll ask around about what to expect.

Does `ctl_mboxlist -d` still show tens of thousands of entries, or is it more reasonable now?

**Comment by slauffer** [comment]
no, the null partitions are fixed. I saw the "Removing stale tombstone..." loggs, too. Just the size seems to be to large. Or in other words: It does not shrink.

**Comment by elliefm** [comment]
Hmm, interesting.  Ah, checkpoint doesn't actually repack!  Looks like you might want `cyr_dbtool repack`?

**Comment by slauffer** [comment]
fine, yes a 
 .../cyr_dbtool ..../mailboxes.db twoskip repack
is working! :)
