### ISSUE TITLE
Fix empty manpage entries

### ISSUE THREAD

**Issue by nicolan** [cyrusimap/cyrus-imapd#54]
There are a number of placeholder files under docsrc/imap/reference/manpages/

They generate warnings under certain sphinx themes (fair enough). 

Need to decide whether to delete or document:
- [ ] compile_st.pl.rst
- [ ] cvt_cyrusdb_all.rst
- [ ] cyr_systemd_helper.rst
- [ ] cyr_userseen.rst
- [ ] dohash.rst
- [ ] fixsearchpath.pl.rst
- [ ] migrate-metadata.rst
- [ ] mupdate-loadgen.pl.rst
- [ ] rehash.rst
- [ ] undohash.rst
- [ ] upgradesieve.rst

**Comment by postilion** [comment]
* compile_st.pl.rst:
  * This is a tool for building string tables, for developers not users or admins.  
  * I say we delete.
* cvt_cyrusdb_all.rst
  * There is no program, script, tool for this.  I suspect this is a distro-specific add-on.
  * I say we delete.
* cyr_systemd_helper.rst
  * There's no matching tool or script.  Wishful thinking?
  * I say we delete.
* cyr_userseen.rst
  * Aha!  Something that actually exists.
  * I'll write this up.
* dohash.rst
  * I'll write this up
* fixsearchpath.pl.rst
* migrate-metadata.rst
* mupdate-loadgen.pl.rst
* rehash.rst
* undohash.rst
* upgradesieve.rst

**Comment by nicolan** [comment]
This got all fixed as part of #2007
