### ISSUE TITLE
FR: expunged messages shold not be counted in quotas

### ISSUE THREAD

**Issue by asy972** [cyrusimap/cyrus-imapd#56]
Since 2.5 default expunge_mode is "delayed". It cause the problem for users with quotas: users can't quickly cleanups overquoted mailboxes. Thus E-Mail is not accepted until cyr_expire will not ran. It would be nice not to count expunged messages in the quota when expunge_mode is "delayed". Probably relevant option should be added to imapd.conf. Similarly for folders.

**Comment by brong** [comment]
Are you talking about filesystem quotas, or cyrus quotas?  EXPUNGED
messages don't count for Cyrus quotas.

Bron.


On Wed, 12 Oct 2016, at 18:23, asy972 wrote:
> Since 2.5 default expunge_mode is "delayed". It cause the problem for
> users with quotas: users can't quickly cleanups overquoted mailboxes.
> Thus E-Mail is not accepted until cyr_expire will not ran. It would be
> nice not to count expunged messages in the quota when expunge_mode is
> "delayed". Probably relevant option should be added to imapd.conf.
> Similarly for folders.
> — You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub[1], or mute the
> thread[2].
>

--
  Bron Gondwana
  brong@fastmail.fm



Links:

  1. https://github.com/cyrusimap/cyrus-imapd/issues/56

**Comment by asy972** [comment]
Hm. Apparently, I was sloppy when checking. I talking about cyrus quotas and it seemed to me that these messages arecounted. Sorry.
