### ISSUE TITLE
/etc/krb.equiv bad choice of filename

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#561]
From: [Rob Siemborski](rjs3@andrew.cmu.edu)
Bugzilla-Id: 2070
Version: 2.2.x
Owner: [Ken Murchison](murch@andrew.cmu.edu)

**Comment by rsto** [comment]
@nicolan Would you like to take over this documentation issue?

Background: the Kerberos support libraries in Cyrus (lib/auth_krb.c, ptclient/afskrb.c) expect a file named "krb.equiv" to exist in the Cyrus config directory. But there's a name clash with the Cyrus manual page for this config file (the config file itself is just fine as it is).

So I'm not sure if we should just rename the man page, or merge its contents into one of the other man pages for Cyrus.

**Comment by nicolan** [comment]
Couldn't find any evidence that Heimdal still uses krb.equiv.5
It looks like they have krb5.conf now, so I think our clash is resolved without us needing to do anything.
