### ISSUE TITLE
sample cyrus.conf files need attention

### ISSUE THREAD

**Issue by elliefm** [cyrusimap/cyrus-imapd#59]
These live in the `master/conf/` directory.
- most have both "delprune" and "deleteprune" EVENTs that look like they do the same thing
- some reference `ctl_deliver -E` instead of `cyr_expire -E` -- despite the fact that `ctl_deliver -E`'s only function is to whinge about being deprecated and then invoke `cyr_expire -E` itself

Looks like the world has slowly moved forward but these files haven't been consistently updated to match

**Comment by postilion** [comment]
@elliefm actually, in looking at these samples, the delprune event is used to prune (using the 'ctl_deliver' command) the deliver DB, while the deleteprune is used to delete (using the 'ctl_expire' command) messages meeting some expiration or age criteria.  Similar names, but entirely different functionality.  Perhaps change "delprune" to "deliverprune"?

**Comment by elliefm** [comment]
All the examples that are using `ctl_deliver` are using the `-E` argument, which is just a passthrough to `cyr_expire -E`.  See: https://github.com/cyrusimap/cyrus-imapd/blob/master/imap/ctl_deliver.c#L112-L129

As best as I can interpret, something like this has slowly happened over time:

* ctl_deliver -E [days]  is the correct way to prune stuff, examples are created
* cyr_expire is created with -E functionality, `ctl_deliver -E` is deprecated
* some (not all) examples are updated
* it becomes usual to also use  -D [days] when pruning, `cyr_expire` examples are updated, `ctl_deliver` examples are not
* someone notices there's no -D examples in some files, adds new event containing them
* current chaos

**Comment by postilion** [comment]
Aha!  Okay, I get it now.  What you're saying wasn't clear to me from earlier comments.  Will get to this shortly.  Apologies for denseness.

**Comment by nicolan** [comment]
@postilion I think we can close this task now? Please confirm!

**Comment by postilion** [comment]
At this point all of the references to ctl_deliver have been changed in the sample files, with the exception of cmu-backend.conf.  I intentionally didn't touch any of the cmu* examples, and these are not referenced anywhere else in the documentation.  My assumption was that these are historical artefacts.

#59 should be closed.
