### ISSUE TITLE
Add an implicit_admin_rights option

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#608]
From: [Ken Murchison](ken@oceana.com)
Bugzilla-Id: 2185
Version: 2.2.x
Owner: [Ken Murchison](murch@andrew.cmu.edu)

**Comment by ksmurchison** [comment]
Since this has sat around for 14 years without resolution, I'm guessing any need that I or anyone else may have had has dissipated.  Feel free to close this issue.

**Comment by ajaysusarla** [comment]
Thanks you very much @ksmurchison.  Closing this issue now.
