### ISSUE TITLE
Portability issue about default ai_flags in imap/backend.c

### ISSUE THREAD

**Issue by obache** [cyrusimap/cyrus-imapd#62]
In imap/backend.c:

``` c
hints.ai_flags = AI_V4MAPPED | AI_ADDRCONFIG
```

But on some systems, such AI_\* macro may not be defined, or invalid even if defined.

For example on *BSD, AI_V4MAPPED is not defined on NetBSD and OpenBSD yet even on CVS head.
It is defined on FreeBSD 10 but invalid, then latest 11 release should support it.
Then it is impossible to build on NetBSD and OpenBSD, and probably it does not works as expected on FreeBSD 10.

I don't no about situation of other OSes, but on *BSD, you can validate on build time
with "it is defined" and "it is in AI_MASK", say:

```
#if defined(AI_V4MAPPED) && (AI_MASK & AI_v4MAPPED)
```

**Comment by elliefm** [comment]
This probably also affects platforms which don't provide getaddrinfo(), because the fallback implementation (`lib/gai.h`, `lib/getaddrinfo.c`) doesn't define AI_V4MAPPED or AI_ADDRCONFIG either.  The fallback implementation doesn't define AI_MASK, either.
