### ISSUE TITLE
GCC compile options in Makefile.am

### ISSUE THREAD

**Issue by surfermarty** [cyrusimap/cyrus-imapd#65]
Line 1450 of Makefile.am in the 2.5.10 release has a GCC compile option hardcoded, which breaks compilation on the Solaris Studio compilers. This flag should only be used if GCC is the compiler.

**Comment by elliefm** [comment]
I think this is fixed (on both 2.5 and master) by the commits referenced above, but I don't have Solaris Studio to verify with.  If you're able to verify that it would be helpful.

**Comment by surfermarty** [comment]
Yes - this commit resolves the issue on Solaris with the Studio Compilers - thanks.

**Comment by elliefm** [comment]
Cool, thanks for verifying that :)
