### ISSUE TITLE
Squatter Dies On Any Error => Prevents full system indexing

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#690]
From: [Lee Hoffman](lee@disinfo.com)
Bugzilla-Id: 2589
Version: 2.2.x
Owner: [Ken Murchison](murch@andrew.cmu.edu)

**Comment by ksmurchison** [comment]
This bug was filed against 2.2.  I'm assuming that this is no longer an issue.  Reopen the bug if the problem exists in 2.5+
