### ISSUE TITLE
Can't access mailbox using GSSAPI and virtdomains set to off

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#698]
From: [Aleksandar Milivojevic](alex@milivojevic.org)
Bugzilla-Id: 2610
Version: 2.2.x
Owner: [Ken Murchison](murch@andrew.cmu.edu)

**Comment by elliefm** [comment]
Closing this report cause it's ancient and domain handling has changed a bunch.  If it's still a problem someone can report it again with a recent version
