### ISSUE TITLE
docs: recent sphinx-build warns about 'rfc' role being overridden

### ISSUE THREAD

**Issue by elliefm** [cyrusimap/cyrus-imapd#7]
When building our docs with sphinx-build 1.4.5:

```
WARNING: while setting up extension ?: role 'rfc' is already registered, it will be overridden
```

Our `rfc` is defined in docsrc/conf.py:

```
        'rfc':('http://tools.ietf.org/html/rfc%s', 'RFC '),
```

The thing is, sphinx already has such a thing built in.  And looks like it has had it built in pretty much forever: https://github.com/sphinx-doc/sphinx/commit/d60ca8d49d1654968886612883a2affa9dccfaa8

The difference with the newer version of sphinx-build appears to be that it now warns about us overriding built-in functionality, instead of just quietly doing it.  We should be able to shut up this warning just by no longer defining our own rfc role.  The built-in one does basically the same thing anyway (except that it uses a https link to the same destination -- good!).

We need to support at least back to version 1.3.6, because that's what the website rebuild uses, but I can't easily test that version now that I've upgraded.

**Comment by nicolan** [comment]
I'm running sphinx 1.3.6

I yanked the rfc entry in conf.py and everything built beautifully.

**Comment by nicolan** [comment]
I can't seem to assign it to me or mark it fixed.

commit 3a004c1

**Comment by elliefm** [comment]
@nicolan Awesome, thanks, #10 has been merged.  I've sent you an invite to the cyrusimap group, once you accept it I think you'll be able to assign/close issues.

I'll leave this one hanging open for now so you can try it out

**Comment by nicolan** [comment]
Pull request merged. Closing issue.
And confirming permissions work!
