### ISSUE TITLE
search_xapian.c: use language detection to use non-English stemmers

### ISSUE THREAD

**Issue by rsto** [cyrusimap/cyrus-imapd#72]
Currently, the Xapian search backend stems all documents using an English stemmer, both during indexing and search.

To improve search results for non-English text we'd like to stem search terms according to their natural language.

**What has been done already**
The experimental branch at https://github.com/rsto/cyrus-imapd/commits/xapian_stem_language contains code that builds on either Google's CLD2 or libtextcat to detect a text's language. It also introduces non-English stopwords to omit from indexing and search. CLD2 turned out to provide better results than libtextcat. However, both language detectors failed at identifying the natural language of a search query, due to search texts being way too short for robust language detection.

**Proposed solution candidate**
For each message of a users mailbox, we'd like to detect its language and keep track of how many messages contain each language in a user-scoped database. During indexing a message, we use both the identified stemmers as well as the default Cyrus stemmer. During search we use the stemmers of any identified language of the search terms, of any dominant languages across a user's mailbox and the Cyrus stemmer.

_Note:_ Using the Cyrus stemmer eliminates the risk of false negatives but does nothing to reduce false positives. We might need to weigh search results and/or run stemmers separately to weed out false positives.

**Comment by dilyanpalauzov** [comment]
Is this now implemented, e.g. by the search_index_language option?

**Comment by rsto** [comment]
Yes, it is. Thanks for mentioning it, @dilyanpalauzov .
