### ISSUE TITLE
Segmentation fault on destroying Cyrus::IMAP

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#735]
From: [Sava Chankov](sava@blueboard.biz)
Bugzilla-Id: 2714
Version: 2.2.x
Owner: [Ken Murchison](murch@andrew.cmu.edu)

**Comment by rsto** [comment]
Can't reproduce and most probably fixed with #1584.

Without more details I wouldn't even know where to begin with debugging this.
