### ISSUE TITLE
glob.c: glob_test() function returns wrong matches in some cases

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#743]
From: [Alexander Drozdov](dzal_mail@mtu-net.ru)
Bugzilla-Id: 2746
Version: 2.2.x
Owner: [Ken Murchison](murch@andrew.cmu.edu)

**Comment by elliefm** [comment]
Looks like lib/glob.c has been rewritten to use the POSIX regex functions, so this patch is no longer useful
