### ISSUE TITLE
altnamespace shows mailboxes twice

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#744]
From: [Joseph Brennan](brennan@columbia.edu)
Bugzilla-Id: 2643
Version: 2.3.x
Owner: [Ken Murchison](murch@andrew.cmu.edu)

**Comment by elliefm** [comment]
The list code has changed so much since the last person so much as glanced sideways at this issue that I'm going to suppose that it's no longer relevant or cared about
