### ISSUE TITLE
LIST and LSUB commands don't return "INBOX" and subfolders correctly

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#795]
From: [Alexander Drozdov](dzal_mail@mtu-net.ru)
Bugzilla-Id: 2747
Version: 2.2.x
Owner: [Ken Murchison](murch@andrew.cmu.edu)

**Comment by dilyanpalauzov** [comment]
This looks very similar to https://github.com/cyrusimap/cyrus-imapd/issues/797 .

Is the complaint still valid for the current code?

**Comment by elliefm** [comment]
Same OP, same day, but I think slightly different issue -- this one is talking about unixhs, the other was about altns.

Same answer though: this was all refactored extensively in 2.5 and 3.0, and all of these name translations are now handled through the mbname API.  I don't think this is relevant anymore.
