### ISSUE TITLE
Treating "^" as "." in user's input in some cases

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#796]
From: [Alexander Drozdov](dzal_mail@mtu-net.ru)
Bugzilla-Id: 2748
Version: 2.2.x
Owner: [Ken Murchison](murch@andrew.cmu.edu)

**Comment by brong** [comment]
Closing: was RESOLVED in import

**Comment by elliefm** [comment]
"Bugzilla 3777" was imported here as #1641... just mentioning so github re-links the issues for the next spelunker
