### ISSUE TITLE
Wrong result of LIST and LSUB commands in some cases

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#797]
From: [Alexander Drozdov](dzal_mail@mtu-net.ru)
Bugzilla-Id: 2749
Version: 2.2.x
Owner: [Ken Murchison](murch@andrew.cmu.edu)

**Comment by dilyanpalauzov** [comment]
Is the complaint still valid for the current code?

**Comment by elliefm** [comment]
I think LIST et al were significantly refactored in 2.5 and/or 3.0, and we have a lot of tests for them.  I'm not precisely sure what the complaint here is, but since it was against 2.2.x it's probably long since ceased to be relevant.
