### ISSUE TITLE
JMAP: setMailboxes does not do (topological) sort of creations

### ISSUE THREAD

**Issue by rjbs** [cyrusimap/cyrus-imapd#83]
I issue creates to setMailboxes like this:

```
{ x: { name: "foo" }, y: { name: "bar", parentId: "#x" } }
```

...and I get inconsistent results.  I feel fairly certain that this is an ordering issue.  If it tries to create `y` first, it fails because `#x` can't be resolved.

**Comment by brong** [comment]
Fixed for setMailboxes particularly
