### ISSUE TITLE
need more charset tests

### ISSUE THREAD

**Issue by elliefm** [cyrusimap/cyrus-imapd#86]
These are based on problems that have come up in fastmail's internal job tracker.  We think these have been fixed, but it would be good to confirm them with tests.  Will add each as a comment here.

@rsto - do you want to look at these after your holidays?

**Comment by elliefm** [comment]
BTS-2294 Chinese word boundary issues

(This might be fixed by xapian/icu.)

> As described in IRIS-2306, it is technically challenging to automatically split written Chinese into words.  Basically the problem is that historically Chinese had a simple rule of 1 word = 1 logogram, which led to whitespace for word separation not being necessary.  But then folks started using compound words written with multiple logograms, still without whitespace.
> 
> One technique for dealing with this is to index N-grams, i.e. all 1, 2 and 3 character rolling combinations of a text.  Using an English example, given the text ABCDEF we would add to the index the "words" A B C D E F AB BC CD DE EF ABC BCD CDE DEF.
> 
> Sphinx supports N-grams.  Well, kinda.  First of all it needs to be told per-index in the configuration which Unicode codepoints to handle using N-grams, despite this really being a property of the scripts and not the index.  Secondly, it only works for N=1, which is plainly inadequate.  So if we are to use a N-gram approach we will need to fix both of those behaviours in Sphinx.
> 
> Another possible approach is a dictionary-based approach, which would presumably work by finding the longest initial subset of characters which had a valid dictionary entry.  That seems to be a reasonable approximation of the algorithm that human readers use, and it would also be a lot more space efficient in the index.
> 
> The International Components for Unicode library claims to have such a thing implemented.  We should consider modifying Sphinx to use that library.

**Comment by elliefm** [comment]
BTS-2295 Indonesian stemming algorithm

> As described in IRIS-2306 we will need a stemming algorithm for the Bahasa Indonesia language (ISO code 'id').
> 
> The Snowball project which has the stemmers that we use in Sphinx, does not have an Indonesian stemmer.  The Lucene project has one in Java which we could transcode.  Or we could implement the algorithm directly.

**Comment by elliefm** [comment]
BTS-2296 Polish stemming algorithm

> As described in IRIS-2306 we will need a stemming algorithm for the Polish language (ISO code 'pl').
> 
> There is an Open Source stemmer available which seems to be widely used, the Stempel stemmer.  Unfortunately it's in Java.  We could transcode it for the Snowball project.

**Comment by elliefm** [comment]
BTS-2435 Snippets: the Sovetskoi problem

> Basically, snippets don't work if the match term contains letters which are changed
> during Cyrus' Unicode normalisation phase.  Examples include
> 
> советской -> советскои
> 
> diĝir -> digir
> 
> This is because the text follows different paths through the indexing and snippets algorithms.
> 
> With indexing, Cyrus normalises the text, and then gives it to Xapian which lowercases it and
> indexes it.  So Xapian sees "DIGIR" and adds a term "digir".   With snippets, the generation
> of HTML snippets is actually done in Xapian, and thus to avoid presenting case-folded text to
> the user, Cyrus skips the normalisation phase.  So Xapian sees "diĝir" and fails to find a match
> for it because that's a different set of bits to "digir".
> 
> There are several possible solutions, it's not clear which one is best.  None of
> these options will help with Sphinx, but who cares.  All are unobvious and tricky
> to get right.
> 
> 1.  Pull the snippet generating algorithm out of Xapian and up into Cyrus, and use the Xapian API to get posting lists of match terms based on the normalised text, and match up offsets between the normalised and unnormalised texts.
> 2.  Change Xapian to implement the table-driven Unicode normalisation the way Cyrus does.  Xapian currently just lowercases the text.  It should be noted that Cyrus' normalisation is actually not quite what the Unicode standard defines: the standard says the normal form is lowercase but Cyrus uses uppercase according to the IMAP standard, and Unicode requires diacritics to be preserved but Cyrus strips them.  This might make the patch unnacceptable to the Xapian community.
> 3.  Change Cyrus not to normalise text when feeding it to Xapian.  This immediately solves the snippets problem, but it means the indexed term is now "diĝir" which can no longer be found when searching for "digir".  This makes the search feature significantly less useful for English (and German) speaking customers.
> 4.  Change Cyrus not to normalise text when feeding it to Xapian, and make the Xapian stemmers do diacritic stripping.  This has the advantage that the diacritic stripping is done per-language, so Xapian would strip diacritics and expand ligatures the way speakers of the languages expect.
> 
> The last solution is the closest to logically correct, because it allows for language
> differences in expected behaviour.  For example:
> 
> -  a German speaker would expect to be able to match the term "gären" by typing either "gären" or "gaeren" and not "garen" which is a different word with a different meaning.
> -  an English speaker would expect to be able to match the term "naïve" by typing either "naïve" or "naive".
> -  a French speaker would expect to be able to match the term "léger" by typing only "léger" and not "leger" which is a different word with a different meaning.

With a comment:

> What Xapian does more closely matches the "normalisation" and "case folding" algorithms described in the Unicode standard.  It's Cyrus that is doing things wrong where "wrong" means "not standard":
> 
> -  Unicode defines case folding as giving a lowercase result, Cyrus uses uppercase for backwards compatibility with old IMAP guff.
> -  Unicode defines normalisation in a way that preserves diacritic information but ensures that the multiple ways of representing the same logical glyph as Unicode codepoints are replaced with one canonical set of bytes, so that logically identical strings can be compared bitwise.
> 
> Unfortunately the standard doesn't really address the human, fuzzy examples I listed above, and neither does the Xapian code.  It's a non-trivial change too, since it would mean that at least one part of the term pipeline in Xapian would need to handle generating multiple output terms from a single input, e.g. "naïve" -> "naive", "naïve".  To do this properly, it would need to be language-specific and the only language-specific code now is the Stemmer.  Changing that to return multiple results would be a public API change.

**Comment by elliefm** [comment]
BTS-2293 Bengali Unicode normalisation issues

> As mentioned in IRIS-2306, the Bengali script is an abugida, which is like an alphabet except that the main symbols are consonants and vowels are indicated using diacritic marks visually attached to the preceeding consonant.  The Arabic and Hebrew scripts are other examples of abugidas.  This may cause some difficulties during Unicode normalisation; I haven't looked into the details yet.  This bug is for tracking any such issues.

**Comment by rsto** [comment]
My take on these issues. TL;DR: they should all be closed :)

- **BTS-2294 Chinese word boundary issues**: Fixed in our Xapian fork in commit https://github.com/cyrusimap/xapian/commit/1c4d429b9b1f7d42e8a6b466c0e6c6f4c2ec8458
- **BTS-2295 Indonesian stemming algorithm** and **BTS-2296 Polish stemming algorithm**: We had an experimental feature for language detection, but it turned out to be unstable during search (https://github.com/cyrusimap/cyrus-imapd/issues/72). Let's close these two, if https://github.com/cyrusimap/cyrus-imapd/issues/72 ever gets implemented, we'll get these two languages for free if the classifier and Xapian supports them.
- **BTS-2435 Snippets: the Sovetskoi problem**: fixed, e.g. see test https://github.com/cyrusimap/cassandane/commit/3a0cc7bdb2383473a616eeeef9df18bf8c03cf7e
- **BTS-2293 Bengali Unicode normalisation issues**: Do we have concrete examples where this is broken? If not I'd say to close this issue.

**Comment by elliefm** [comment]
Works for me :)
