### ISSUE TITLE
NIL as a flag to messages

### ISSUE THREAD

**Issue by brong** [cyrusimap/cyrus-imapd#947]
From: tv@beamnet.de
Bugzilla-Id: 2969
Version: 2.3.x
Owner: [Ken Murchison](murch@andrew.cmu.edu)

**Comment by rsto** [comment]
Agreed, this very much looks as if some client had set a flag named NIL on the message. Can reproduce with:

    C: 13 store 1 +flags (NIL)
    S: * FLAGS (\Answered \Flagged \Draft \Deleted \Seen NIL)
    S: * OK [PERMANENTFLAGS (\Answered \Flagged \Draft \Deleted \Seen NIL \*)] Ok
    S: * 1 FETCH (FLAGS (NIL))
    S: 13 OK Completed

    C: 15 select "inbox"
    S: * 2 EXISTS
    S: * 0 RECENT
    S: * FLAGS (\Answered \Flagged \Draft \Deleted \Seen NIL)
    S: * OK [PERMANENTFLAGS (\Answered \Flagged \Draft \Deleted \Seen NIL \*)] Ok

Since a RFC 3501 flag is an [atom](https://tools.ietf.org/html/rfc3501#section-9) we can't reject NIL as a flag name.

Nofix.
